<?php
/**
 * NAMI CMS — Home page
 *
 * Requires the "NAMI CMS — Core engine" snippet. Adds a "Home" menu to the
 * WordPress sidebar with one sub-menu per section of the home page.
 *
 * Field keys must match src/lib/cms/pages/home/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['home'] = array(
			'title'    => 'Home',
			'icon'     => 'dashicons-admin-home',
			'position' => 3,
			'path'     => '/',
			'sections' => array(

				'hero'          => array(
					'title'       => 'Hero',
					'anchor'      => 'hero',
					'description' => 'The first thing visitors see: label, headline, intro text, the two buttons and the image slideshow.',
					'fields'      => array(
						'eyebrow'      => array( 'type' => 'text', 'label' => 'Small label above headline' ),
						'headline'     => array( 'type' => 'text', 'label' => 'Headline', 'help' => 'A comma followed by a space splits the headline onto two lines.' ),
						'standfirst'   => array( 'type' => 'textarea', 'label' => 'Intro text' ),
						'primaryCta'   => array( 'type' => 'link', 'label' => 'Main button' ),
						'secondaryCta' => array( 'type' => 'link', 'label' => 'Second button' ),
						'slides'       => array(
							'type'        => 'repeater',
							'label'       => 'Slideshow images',
							'item_label'  => 'Slide',
							'title_field' => 'image',
							'fields'      => array(
								'image' => $image( 'Image', 'Wide landscape photos work best (about 1500 × 1000 px).' ),
							),
						),
					),
				),

				'marquee'       => array(
					'title'       => 'Programme Ticker',
					'anchor'      => 'programmes',
					'description' => 'The two scrolling bands under the hero.',
					'fields'      => array(
						'items'          => array(
							'type'        => 'repeater',
							'label'       => 'Top band (programmes)',
							'item_label'  => 'Item',
							'title_field' => 'text',
							'fields'      => array(
								'text'    => array( 'type' => 'text', 'label' => 'Text' ),
								'isLevel' => array( 'type' => 'toggle', 'label' => 'Style', 'toggle_label' => 'Highlight as a level heading (accent colour, bold)' ),
							),
						),
						'awardingBodies' => array( 'type' => 'lines', 'label' => 'Bottom band (awarding bodies)', 'help' => 'One name per line.' ),
					),
				),

				'about'         => array(
					'title'       => 'About',
					'anchor'      => 'about',
					'description' => 'Introduction with the video on the left and text on the right.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label (line above title)' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'paragraphs'  => array( 'type' => 'paragraphs', 'label' => 'Text' ),
						'videoSrc'    => array( 'type' => 'video', 'label' => 'Video (MP4)', 'help' => 'Upload an MP4 or paste a link to one.' ),
						'videoPoster' => $image( 'Video cover image', 'Shown before the video plays.' ),
						'button'      => array( 'type' => 'link', 'label' => 'Button' ),
					),
				),

				'institutions'  => array(
					'title'       => 'Institutions',
					'anchor'      => 'institutions',
					'description' => 'The blue section with one card per NAMI institution.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description (optional)' ),
						'cards'       => array(
							'type'        => 'repeater',
							'label'       => 'Cards',
							'item_label'  => 'Card',
							'title_field' => 'name',
							'fields'      => array(
								'name'        => array( 'type' => 'text', 'label' => 'Name' ),
								'badge'       => array( 'type' => 'text', 'label' => 'Badge on image', 'help' => 'e.g. "Estd. 2019". Leave empty to hide.' ),
								'stage'       => array( 'type' => 'text', 'label' => 'Short description' ),
								'highlights'  => array( 'type' => 'lines', 'label' => 'Highlights', 'help' => 'One per line. The first 3 are shown.' ),
								'image'       => $image( 'Image' ),
								'imageFit'    => array(
									'type'    => 'select',
									'label'   => 'Image style',
									'options' => array(
										'cover'   => 'Photo — fills the whole card top',
										'contain' => 'Logo — shown whole on a light background',
									),
								),
								'href'        => array( 'type' => 'url', 'label' => 'Card link' ),
								'footerLabel' => array( 'type' => 'text', 'label' => 'Bottom link text', 'default' => 'Explore Details' ),
							),
						),
					),
				),

				'accreditation' => array(
					'title'       => 'Accreditation',
					'anchor'      => 'affiliations',
					'description' => 'Scrolling row of university and exam-board logos.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title (optional)' ),
						'logos' => array(
							'type'        => 'repeater',
							'label'       => 'Logos',
							'item_label'  => 'Logo',
							'title_field' => 'name',
							'fields'      => array(
								'name' => array( 'type' => 'text', 'label' => 'Organisation name' ),
								'logo' => $image( 'Logo', 'Transparent PNG or SVG works best.' ),
							),
						),
					),
				),

				'ceo'           => array(
					'title'       => 'CEO Message',
					'anchor'      => 'ceo-message',
					'description' => 'The message with the portrait card on the right.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Message', 'rows' => 16 ),
						'name'       => array( 'type' => 'text', 'label' => 'Name' ),
						'title'      => array( 'type' => 'text', 'label' => 'Job title' ),
						'portrait'   => $image( 'Portrait' ),
					),
				),

				'stats'         => array(
					'title'       => 'Numbers',
					'anchor'      => 'stats',
					'description' => 'Animated counters with the campus video beside them.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Counters',
							'item_label'  => 'Counter',
							'title_field' => 'label',
							'fields'      => array(
								'value'  => array( 'type' => 'number', 'label' => 'Number' ),
								'suffix' => array( 'type' => 'text', 'label' => 'After the number', 'help' => 'e.g. "+" or "%". Optional.' ),
								'label'  => array( 'type' => 'text', 'label' => 'Caption' ),
							),
						),
						'poster'      => $image( 'Video cover image', 'Shown while the video loads. Remove it to hide the video panel.' ),
						'youtubeId'   => array( 'type' => 'text', 'label' => 'YouTube video', 'help' => 'Paste a YouTube link or video ID. Plays muted on loop.' ),
					),
				),

				'testimonials'  => array(
					'title'       => 'Testimonials',
					'anchor'      => 'stakeholders',
					'description' => 'Carousel of quotes from partners, teachers and families.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'items'      => array(
							'type'        => 'repeater',
							'label'       => 'Testimonials',
							'item_label'  => 'Testimonial',
							'title_field' => 'name',
							'fields'      => array(
								'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
								'name'     => array( 'type' => 'text', 'label' => 'Name' ),
								'role'     => array( 'type' => 'text', 'label' => 'Role / organisation' ),
								'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
							),
						),
						'emptyState' => array( 'type' => 'text', 'label' => 'Text shown when there are no testimonials' ),
					),
				),

				'notices'       => array(
					'title'       => 'Notices',
					'anchor'      => 'updates',
					'description' => 'Heading and button above the latest three notices. The notices themselves are managed on the Notices page.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'button'     => array( 'type' => 'link', 'label' => 'Button' ),
						'emptyState' => array( 'type' => 'text', 'label' => 'Text shown when there are no notices' ),
					),
				),

				'popup'         => array(
					'title'       => 'Popup',
					'description' => 'The announcement image that pops up when someone opens the home page.',
					'fields'      => array(
						'enabled' => array( 'type' => 'toggle', 'label' => 'Show popup', 'toggle_label' => 'Show the popup on the home page' ),
						'image'   => $image( 'Popup image' ),
						'href'    => array( 'type' => 'url', 'label' => 'Link when clicked', 'help' => 'Leave empty for no link.' ),
						'title'   => array( 'type' => 'text', 'label' => 'Announcement title', 'help' => 'Read out by screen readers.' ),
					),
				),
			),
			'defaults' => json_decode(
				<<<'NAMI_JSON'
{
  "hero": {
    "eyebrow": "Naaya Aayam Multi-Disciplinary Institute",
    "headline": "Transform Yourself to Lead the World",
    "standfirst": "At NAMI, we provide a comprehensive academic pathway from Grade 1 to Master's degrees, empowering learners through world-class education, holistic development and leadership to transform themselves and lead the world.",
    "primaryCta": {
      "label": "Start an Application",
      "href": "/admissions"
    },
    "secondaryCta": {
      "label": "Our Story",
      "href": "/about"
    },
    "slides": [
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM-watermarked.jpg",
          "alt": "NAMI campus life and academic excellence.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (12)-watermarked.jpg",
          "alt": "NAMI student activities and learning spaces.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (13)-watermarked.jpg",
          "alt": "NAMI campus community and student experiences.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (15)-watermarked.jpg",
          "alt": "NAMI faculty and practical academic workshops.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (18)-watermarked.jpg",
          "alt": "NAMI library and collaborative study areas.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (19)-watermarked.jpg",
          "alt": "NAMI events, conferences, and seminars.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (20)-watermarked.jpg",
          "alt": "NAMI laboratories and scientific research.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (21)-watermarked.jpg",
          "alt": "NAMI auditorium presentations and student achievements.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (22)-watermarked.jpg",
          "alt": "NAMI sports, courts, and extracurricular engagement.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (23)-watermarked.jpg",
          "alt": "NAMI modern classrooms and campus infrastructure.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (24)-watermarked.jpg",
          "alt": "NAMI campus grounds and student collaboration.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.22 AM (25)-watermarked.jpg",
          "alt": "NAMI student leadership and academic community.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.23 AM (6)-watermarked.jpg",
          "alt": "NAMI cultural celebrations and academic events.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/WhatsApp Image 2026-09-27 at 10.42.23 AM (23)-watermarked.jpg",
          "alt": "NAMI holistic education and student development.",
          "width": 1500,
          "height": 1000
        }
      }
    ]
  },
  "marquee": {
    "items": [
      {
        "text": "10+2 (NEB)",
        "isLevel": true
      },
      {
        "text": "Science",
        "isLevel": false
      },
      {
        "text": "Management",
        "isLevel": false
      },
      {
        "text": "Cambridge A-Level",
        "isLevel": true
      },
      {
        "text": "Science",
        "isLevel": false
      },
      {
        "text": "Non-Science",
        "isLevel": false
      },
      {
        "text": "Bachelor's Degrees",
        "isLevel": true
      },
      {
        "text": "BSc. (Hons) Computer Science",
        "isLevel": false
      },
      {
        "text": "BSc. (Hons) Software Engineering",
        "isLevel": false
      },
      {
        "text": "BSc. (Hons) Networking Engineering",
        "isLevel": false
      },
      {
        "text": "BSc. (Hons) Environmental Science",
        "isLevel": false
      },
      {
        "text": "BBA (Hons) Business Administration",
        "isLevel": false
      },
      {
        "text": "BSc. Environmental Studies",
        "isLevel": false
      },
      {
        "text": "Master's Degree",
        "isLevel": true
      },
      {
        "text": "MSc Computer Science",
        "isLevel": false
      },
      {
        "text": "School",
        "isLevel": true
      },
      {
        "text": "Grades I through VII",
        "isLevel": false
      }
    ],
    "awardingBodies": [
      "The University of Northampton, UK",
      "Kathmandu University",
      "Cambridge Assessment International Education",
      "National Examination Board, Government of Nepal"
    ]
  },
  "about": {
    "label": "A Nepali entity committed to delivering education of global standards.",
    "title": "NAMI since 2012",
    "paragraphs": [
      "Naaya Aayam Multi-Disciplinary Institute (NAMI) is an educational entity with the aim of contributing meaningfully to Nepal's social and economic development through the delivery of quality education. Established in 2012, NAMI is dedicated to providing world-class education in Nepal.",
      "The institution places strong emphasis on holistic development, integrating rigorous academic learning with extracurricular activities, leadership development and community engagement. By fostering an inclusive and supportive learning environment, NAMI prepares students not only for academic success but also for meaningful contributions to society and the global workforce. Its dedicated faculty, modern facilities and collaborative partnerships further enhance the educational experience, making NAMI a preferred choice for students seeking quality education in Nepal."
    ],
    "videoSrc": "/videos/Final%20First%20Video.mp4",
    "videoPoster": {
      "src": "/videos/Homepage video thumbnails.png",
      "alt": "NAMI College",
      "width": 1280,
      "height": 720
    },
    "button": {
      "label": "Read the Full Story",
      "href": "/about"
    }
  },
  "institutions": {
    "label": "NAMI Entities",
    "title": "One Name, Independently Accredited Educational Institutions",
    "description": "",
    "cards": [
      {
        "name": "NAMI International School",
        "badge": "Estd. 2019",
        "stage": "From Grades I through VII and +2 in Science and Management",
        "highlights": [
          "National Curriculum, Government of Nepal (Grades I–VII)",
          "NEB +2 in Science and Management",
          "Mandarin Chinese and Sanskrit Language Learning"
        ],
        "image": {
          "src": "/hero/home/hero-1.jpg",
          "alt": "NAMI International School campus and activities",
          "width": 1178,
          "height": 667
        },
        "imageFit": "cover",
        "href": "/institutions/school",
        "footerLabel": "Explore Details"
      },
      {
        "name": "NAMI College",
        "badge": "Estd. 2013",
        "stage": "Cambridge A Level, entry from SEE, GCSE, CBSE or equivalent",
        "highlights": [
          "Independent CAIE examination centre since 2024",
          "Science and non-science subject combinations",
          "Entry from SEE, GCSE, CBSE or equivalent"
        ],
        "image": {
          "src": "/hero/home/hero-2.jpg",
          "alt": "NAMI College students on campus",
          "width": 1600,
          "height": 1066
        },
        "imageFit": "cover",
        "href": "/institutions/a-levels",
        "footerLabel": "Explore Details"
      },
      {
        "name": "Naaya Aayam Multi-Disciplinary Institute",
        "badge": "Estd. 2012",
        "stage": "Bachelor's and Master's degrees",
        "highlights": [
          "British degrees taught in Kathmandu since 2012",
          "MSc Computer Science",
          "Bachelors in Environmental Studies (BES) with Kathmandu University"
        ],
        "image": {
          "src": "/hero/home/hero-3.jpg",
          "alt": "Naaya Aayam Multi-Disciplinary Institute facilities and campus",
          "width": 1600,
          "height": 1066
        },
        "imageFit": "cover",
        "href": "/institutions/bachelors",
        "footerLabel": "Explore Details"
      },
      {
        "name": "Vocational & Technical Training",
        "badge": "Approved 2026",
        "stage": "CTEVT Approved Short-Term Vocational Programmes",
        "highlights": [
          "Council for Technical Education & Vocational Training",
          "Skill-based practical & industry-aligned training",
          "Employment & entrepreneurship-oriented pathways"
        ],
        "image": {
          "src": "/logos/brand/ctevt-logo-removebg-preview.png",
          "alt": "CTEVT — Council for Technical Education and Vocational Training",
          "width": 180,
          "height": 144
        },
        "imageFit": "contain",
        "href": "/institutions/ctevt",
        "footerLabel": "Vocational & Technical"
      }
    ]
  },
  "accreditation": {
    "label": "Accredited for Excellence",
    "title": "",
    "logos": [
      {
        "name": "The University of Northampton, UK",
        "logo": {
          "src": "/logos/universities/northampton.png",
          "alt": "The University of Northampton, UK",
          "width": 384,
          "height": 192
        }
      },
      {
        "name": "Cambridge Assessment International Education",
        "logo": {
          "src": "/logos/universities/cambridge.png",
          "alt": "Cambridge Assessment International Education",
          "width": 384,
          "height": 192
        }
      },
      {
        "name": "National Examination Board, Government of Nepal",
        "logo": {
          "src": "/logos/universities/neb.png",
          "alt": "National Examination Board, Government of Nepal",
          "width": 384,
          "height": 192
        }
      },
      {
        "name": "Kathmandu University",
        "logo": {
          "src": "/logos/universities/Kathmandu_University_Logo.webp",
          "alt": "Kathmandu University",
          "width": 384,
          "height": 192
        }
      },
      {
        "name": "University of Hertfordshire",
        "logo": {
          "src": "/logos/brand/uni of hertforshire.png",
          "alt": "University of Hertfordshire",
          "width": 384,
          "height": 192
        }
      }
    ]
  },
  "ceo": {
    "label": "Message from the CEO",
    "paragraphs": [
      "Welcome to NAMI. Since our inception in 2012, our foundational mission has been to provide world-class, globally accredited education right here in Nepal. We believe that true academic excellence begins with an environment that fosters curiosity, integrity, and ambition, supported by state-of-the-art infrastructure and faculty who are deeply dedicated to student success.",
      "In an increasingly interconnected and rapidly evolving world, education must go beyond conventional classroom boundaries. Through strategic academic partnerships with premier international universities and dynamic collaborations with industry leaders, NAMI bridges rigorous academic theory with real-world competence. We emphasize critical thinking, computational capability, research orientation, and an entrepreneurial mindset across all our programs.",
      "Our holistic educational ecosystem is purposefully designed to nurture well-rounded individuals. Alongside academic depth, we place strong value on leadership development, community engagement, ethical values, and extracurricular enrichment. By empowering our students with both knowledge and character, we ensure they are prepared to excel in competitive global arenas and make meaningful contributions to their professions.",
      "As we look ahead, NAMI remains steadfast in its dedication to transformative education and institutional excellence. We invite our students, parents, alumni, and community partners to join hands with us as we continue to inspire innovation, shape impactful careers, and cultivate the next generation of visionary leaders for Nepal and the world."
    ],
    "name": "Mr. Pranil Pandey, FCCA",
    "title": "Chief Executive Officer, NAMI Group of Companies",
    "portrait": {
      "src": "/leadership/pranil.jpeg",
      "alt": "Studio portrait of Mr. Pranil Pandey, Chief Executive Officer of NAMI, hands clasped in a blue suit and blue tie against a mottled blue-grey backdrop.",
      "width": 1173,
      "height": 1600
    }
  },
  "stats": {
    "label": "Our Milestones",
    "title": "NAMI, by the Numbers",
    "description": "Over a decade of academic excellence, shaped across four learning tiers and a thriving community of thousands.",
    "items": [
      {
        "value": 8000,
        "suffix": "+",
        "label": "alumni across all programmes"
      },
      {
        "value": 176,
        "suffix": "",
        "label": "students in Grades I–VII"
      },
      {
        "value": 350,
        "suffix": "",
        "label": "students in Grade 11"
      },
      {
        "value": 454,
        "suffix": "",
        "label": "students in Grade 12"
      },
      {
        "value": 71,
        "suffix": "",
        "label": "Cambridge A Level students"
      },
      {
        "value": 239,
        "suffix": "",
        "label": "undergraduate students"
      }
    ],
    "poster": {
      "src": "/sections/nami/campus-service-camp.jpg",
      "alt": "Pupils in red uniforms seated around a hilltop school ground in Sindhupalchowk, facing stacks of red relief bags laid out on benches at a NAMI service camp.",
      "width": 1190,
      "height": 793
    },
    "youtubeId": "XW2vMPwdPg8"
  },
  "testimonials": {
    "label": "",
    "title": "Stakeholder Voice",
    "emptyState": "Stakeholder stories are being collected — this space is reserved for them.",
    "items": [
      {
        "quote": "The team at NAMI International School has been fantastic to work with. The teachers help us deliver our UnMath District program with ease, including building a Math Museum at the school. In a short time, we have delivered 100+ interactive experiences for Grade 1–7 students. We are thrilled to continue this meaningful partnership.",
        "name": "Mr. Divesh Bhatija",
        "role": "Math Storyteller & Co-Founder, UnMath School",
        "portrait": {
          "src": "/testimonials/stakeholders/Divesh Bhatija.png",
          "alt": "Mr. Divesh Bhatija",
          "width": 1323,
          "height": 1189
        }
      },
      {
        "quote": "Being part of NAMI International School has been a joyful journey. The supportive colleagues, curious students, and warm community make every day rewarding. Teaching Chinese here has enriched my life and deepened my appreciation for Nepal’s culture. I am proud to be part of NAMI.",
        "name": "Ren Yuanyuan",
        "role": "Chinese Facilitator",
        "portrait": {
          "src": "/testimonials/teachers/Ren Yuanyuan.png",
          "alt": "Ren Yuanyuan",
          "width": 1103,
          "height": 1426
        }
      },
      {
        "quote": "When I first entered NAMI International School, I immediately felt its peaceful and welcoming environment. It feels like a place where children are encouraged to learn and grow. The teachers are caring, supportive, and easy to connect with. The enthusiastic students bring energy to every lesson, making teaching here truly enjoyable.",
        "name": "Miss Chandrika Limbu",
        "role": "3Di Facilitator",
        "portrait": {
          "src": "/testimonials/stakeholders/Chandrika Limbu.png",
          "alt": "Miss Chandrika Limbu",
          "width": 1254,
          "height": 1254
        }
      },
      {
        "quote": "यस विद्यालयमा छुट्टै ऊर्जा महसुस हुन्छ। सहयोगी वातावरण, सहकार्यको भावना, विद्यार्थीहरूको अनुशासन र जिज्ञासु स्वभावले यहाँ पढाउँदा आत्मीय आनन्द मिल्छ । यस विद्यालयको एक सदस्यका रूपमा मेरो अनुभव अत्यन्तै सुखद र आत्मीय रहेको छ ।",
        "name": "RamKrishna Koirala",
        "role": "Sanskrit Facilitator",
        "portrait": {
          "src": "/testimonials/teachers/Ramkrishna Koirala.png",
          "alt": "RamKrishna Koirala",
          "width": 1141,
          "height": 1379
        }
      },
      {
        "quote": "As a PE Trainer representing Play Nepal at NAMI for nearly three years, the supportive environment, friendly staff, wonderful colleagues, enthusiastic students, and caring parents have made my journey truly memorable. I’m grateful to be part of the NAMI family.",
        "name": "Rajesh Tumbapo",
        "role": "Team Play Nepal",
        "portrait": {
          "src": "/testimonials/stakeholders/Rajesh Thumbapo.png",
          "alt": "Rajesh Tumbapo",
          "width": 1254,
          "height": 1254
        }
      },
      {
        "quote": "Stepping into NAMI feels like stepping into a balanced space filled with positive energy. The admin and faculty work in true harmony, creating a calm, supportive environment where students and teachers share a natural, effortless growth.",
        "name": "Miss Indu Poudel",
        "role": "Yoga Instructor",
        "portrait": {
          "src": "/testimonials/teachers/Indu.png",
          "alt": "Miss Indu Poudel",
          "width": 1107,
          "height": 1421
        }
      },
      {
        "quote": "NAMI International School को एक शिक्षकका रूपमा यस गौरवशाली शैक्षिक परिवारको हिस्सा बन्न पाउनु मेरो लागि अत्यन्तै गर्व र आत्मीयताको अनुभूति हो। यहाँको प्रेरणादायी वातावरण, समर्पित नेतृत्व र सहकार्यपूर्ण संस्कृतिले विद्यार्थीको ज्ञान, सीप, सिर्जनशीलता र चरित्र विकासलाई सार्थक दिशा दिन्छ।",
        "name": "प्रतिभा फुयाल",
        "role": "सामाजिक शिक्षक",
        "portrait": {
          "src": "/testimonials/teachers/Pratibha Phuyal.png",
          "alt": "प्रतिभा फुयाल",
          "width": 1155,
          "height": 1362
        }
      },
      {
        "quote": "My journey with NAMI International School has come full circle in a truly beautiful way. From being a student who once learned within these walls to now serving as a school librarian, I feel a deep sense of gratitude and belonging. It is meaningful to give back to the school that shaped me and inspire young learners.",
        "name": "Prishita Rokaya",
        "role": "School Librarian",
        "portrait": {
          "src": "/testimonials/teachers/Prishita Rokaya.png",
          "alt": "Prishita Rokaya",
          "width": 1269,
          "height": 1240
        }
      }
    ]
  },
  "notices": {
    "label": "",
    "title": "Notices",
    "button": {
      "label": "View All Notices",
      "href": "/notices"
    },
    "emptyState": "No current notices."
  },
  "popup": {
    "enabled": true,
    "image": {
      "src": "/sections/misc/popup ad 2.jpeg",
      "alt": "NAMI College - Admission Open",
      "width": 1200,
      "height": 1200
    },
    "href": "/admissions",
    "title": "NAMI College Admission Open Announcement"
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
