<?php
/**
 * NAMI CMS — About page
 *
 * Requires the "NAMI CMS — Core engine" snippet. Adds an "About" menu to the
 * WordPress sidebar with one sub-menu per section of the /about page.
 *
 * Field keys must match src/lib/cms/pages/about/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['about'] = array(
			'title'    => 'About',
			'icon'     => 'dashicons-info-outline',
			'position' => 3.1,
			'path'     => '/about',
			'sections' => array(

				'hero'         => array(
					'title'       => 'Hero',
					'anchor'      => 'about',
					'description' => 'Page title, intro, button and the wide image(s) at the top.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Page title' ),
						'standfirst' => array( 'type' => 'textarea', 'label' => 'Intro text' ),
						'button'     => array( 'type' => 'link', 'label' => 'Button' ),
						'images'     => array(
							'type'        => 'repeater',
							'label'       => 'Images',
							'item_label'  => 'Image',
							'title_field' => 'image',
							'help'        => 'One image shows as a wide banner; two or more show side by side (three per row).',
							'fields'      => array(
								'image' => $image( 'Image' ),
							),
						),
					),
				),

				'overview'     => array(
					'title'       => 'Overview',
					'anchor'      => 'overview',
					'description' => 'Heading with text on the left and a photo on the right.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Heading' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Text' ),
						'image'      => $image( 'Photo' ),
					),
				),

				'leadership'   => array(
					'title'       => 'Leadership Messages',
					'anchor'      => 'leadership-messages',
					'description' => 'Message cards from the Chairperson, CEO and other leaders. The first two paragraphs show until "Read Full Message" is clicked.',
					'fields'      => array(
						'label'    => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'    => array( 'type' => 'text', 'label' => 'Title' ),
						'messages' => array(
							'type'        => 'repeater',
							'label'       => 'Messages',
							'item_label'  => 'Message',
							'title_field' => 'name',
							'fields'      => array(
								'badge'       => array( 'type' => 'text', 'label' => 'Badge', 'help' => 'e.g. "Message from the Chairperson".' ),
								'name'        => array( 'type' => 'text', 'label' => 'Name' ),
								'title'       => array( 'type' => 'text', 'label' => 'Job title' ),
								'credentials' => array( 'type' => 'text', 'label' => 'Credentials line' ),
								'portrait'    => $image( 'Portrait', 'Portrait orientation (4:5) works best.' ),
								'quote'       => array( 'type' => 'textarea', 'label' => 'Highlighted quote', 'rows' => 3 ),
								'paragraphs'  => array( 'type' => 'paragraphs', 'label' => 'Message' ),
							),
						),
					),
				),

				'history'      => array(
					'title'       => 'History',
					'anchor'      => 'history',
					'description' => 'Introduction and the milestone timeline.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Heading' ),
						'intro'      => array( 'type' => 'textarea', 'label' => 'Introduction', 'rows' => 6 ),
						'milestones' => array(
							'type'        => 'repeater',
							'label'       => 'Milestones (in order)',
							'item_label'  => 'Milestone',
							'title_field' => 'title',
							'fields'      => array(
								'year'        => array( 'type' => 'text', 'label' => 'Year', 'help' => 'e.g. "2024" or "2025–2026".' ),
								'era'         => array( 'type' => 'text', 'label' => 'Tag', 'help' => 'Short label next to the year, e.g. "The Foundation".' ),
								'title'       => array( 'type' => 'text', 'label' => 'Title' ),
								'partner'     => array( 'type' => 'text', 'label' => 'Partner name' ),
								'logo'        => $image( 'Partner logo' ),
								'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
							),
						),
					),
				),

				'emblem'       => array(
					'title'       => 'Emblem & Values',
					'anchor'      => 'emblem',
					'description' => 'The red lotus story and the five core values shown under "Read More".',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'image'       => $image( 'Emblem image' ),
						'paragraphs'  => array( 'type' => 'paragraphs', 'label' => 'Story', 'help' => 'The first paragraph is shown larger. Leave an empty line between paragraphs.' ),
						'valuesTitle' => array( 'type' => 'text', 'label' => 'Values heading' ),
						'values'      => array(
							'type'        => 'repeater',
							'label'       => 'Values (petals)',
							'item_label'  => 'Value',
							'title_field' => 'name',
							'fields'      => array(
								'name'    => array( 'type' => 'text', 'label' => 'Name' ),
								'meaning' => array( 'type' => 'textarea', 'label' => 'Meaning', 'rows' => 2 ),
							),
						),
					),
				),

				'creed'        => array(
					'title'       => 'Mission & Vision',
					'anchor'      => 'creed',
					'description' => 'The two side-by-side cards.',
					'fields'      => array(
						'label'        => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'        => array( 'type' => 'text', 'label' => 'Title' ),
						'missionLabel' => array( 'type' => 'text', 'label' => 'First card heading' ),
						'mission'      => array( 'type' => 'paragraphs', 'label' => 'First card text', 'rows' => 5 ),
						'visionLabel'  => array( 'type' => 'text', 'label' => 'Second card heading' ),
						'vision'       => array( 'type' => 'paragraphs', 'label' => 'Second card text', 'rows' => 5 ),
					),
				),

				'mascot'       => array(
					'title'       => 'Mascot',
					'anchor'      => 'mascot',
					'description' => 'The swan mascot story and image.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Text' ),
						'image'      => $image( 'Mascot image' ),
					),
				),

				'awards'       => array(
					'title'       => 'Awards',
					'anchor'      => 'awards',
					'description' => 'The newest award is featured large; the rest are listed beside it, newest first.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Awards',
							'item_label'  => 'Award',
							'title_field' => 'title',
							'fields'      => array(
								'year'         => array( 'type' => 'number', 'label' => 'Year' ),
								'title'        => array( 'type' => 'text', 'label' => 'Award' ),
								'awardingBody' => array( 'type' => 'text', 'label' => 'Awarded by' ),
								'citation'     => array( 'type' => 'textarea', 'label' => 'Citation (optional)', 'rows' => 2 ),
							),
						),
						'emptyState'  => array( 'type' => 'text', 'label' => 'Text shown when there are no awards' ),
					),
				),

				'testimonials' => array(
					'title'       => 'Testimonials',
					'anchor'      => 'stakeholders',
					'description' => 'Carousel of quotes at the bottom of the About page (separate from the Home page list).',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'items'      => array(
							'type'        => 'repeater',
							'label'       => 'Testimonials',
							'item_label'  => 'Testimonial',
							'title_field' => 'name',
							'fields'      => array(
								'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
								'name'     => array( 'type' => 'text', 'label' => 'Name' ),
								'role'     => array( 'type' => 'text', 'label' => 'Role / organisation' ),
								'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
							),
						),
						'emptyState' => array( 'type' => 'text', 'label' => 'Text shown when there are no testimonials' ),
					),
				),

				'seo'          => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the About page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults' => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "About NAMI",
    "description": "The institution behind NAMI in Kathmandu — its story and scale, mission and vision, the people who govern and teach it, and the five values carried in the petals of the red lotus."
  },
  "hero": {
    "title": "Institutions under NAMI",
    "standfirst": "One entity, three institutions, and the five values carried in the petals of the red lotus.",
    "button": {
      "label": "Meet the People Behind NAMI",
      "href": "/faculty"
    },
    "images": [
      {
        "image": {
          "src": "/sections/general/download.png",
          "alt": "NAMI campus facilities, learning spaces, and academic environments",
          "width": 1200,
          "height": 399
        }
      }
    ]
  },
  "overview": {
    "title": "NAMI since 2012",
    "paragraphs": [
      "Naaya Aayam Multi-Disciplinary Institute (NAMI) is an educational entity with the aim of contributing meaningfully to Nepal's social and economic development through the delivery of quality education. Established in 2012, NAMI is dedicated to providing world-class education in Nepal.",
      "The institution places strong emphasis on holistic development, integrating rigorous academic learning with extracurricular activities, leadership development and community engagement. By fostering an inclusive and supportive learning environment, NAMI prepares students not only for academic success but also for meaningful contributions to society and the global workforce. Its dedicated faculty, modern facilities and collaborative partnerships further enhance the educational experience, making NAMI a preferred choice for students seeking quality education in Nepal."
    ],
    "image": {
      "src": "/sections/general/7.jpg",
      "alt": "NAMI students and faculty on campus",
      "width": 1600,
      "height": 1062
    }
  },
  "leadership": {
    "label": "Executive Leadership",
    "title": "Messages from the Chairperson & Chief Executive Officer",
    "messages": [
      {
        "badge": "Message from the Chairperson",
        "name": "Capt. Rameshwar Thapa",
        "title": "Chairperson, NAMI Group of Companies",
        "credentials": "Founder Chairman · Aviator & Strategic Entrepreneur",
        "portrait": {
          "src": "/leadership/rameshwar-thapa.webp",
          "alt": "Capt. Rameshwar Thapa",
          "width": 800,
          "height": 1000
        },
        "quote": "Our founding conviction remains steadfast: to offer access to world-class education within Nepal and nurture leaders who transform communities locally and globally.",
        "paragraphs": [
          "When we established Naaya Aayam Multi-Disciplinary Institute (NAMI) in 2012, our guiding principle was both ambitious and clear: to create an educational ecosystem that eliminates the necessity for talented Nepali youth to seek abroad what could be delivered with uncompromised excellence right here in Nepal.",
          "Over the past decade, NAMI has grown from a singular pioneering tertiary institute into a comprehensive educational group spanning NAMI International School, Cambridge GCE A-Levels, NEB +2, and multidisciplinary Bachelor's and Master's degree programmes in collaboration with world-renowned institutions like the University of Northampton, University of Hertfordshire, and Kathmandu University.",
          "Our institutions are built on strong governance, cutting-edge infrastructure, and holistic character formation symbolised by the five petals of our red lotus emblem — enlightenment, knowledge, purity of heart and mind, self-awareness, and wisdom. We do not simply impart academic curricula; we instill the discipline, empathy, and ethical leadership necessary for our graduates to excel in an interconnected global economy.",
          "As we look ahead, NAMI remains committed to sustainable innovation, state-of-the-art STEM and humanities research, and empowering generations of students to lead with conviction, purpose, and integrity."
        ]
      },
      {
        "badge": "Message from the Chief Executive Officer",
        "name": "Mr. Pranil Pandey, FCCA",
        "title": "Chief Executive Officer, NAMI Group of Companies",
        "credentials": "FCCA (UK) · Master's in Management",
        "portrait": {
          "src": "/leadership/pranil.jpeg",
          "alt": "Mr. Pranil Pandey, FCCA",
          "width": 800,
          "height": 1000
        },
        "quote": "At NAMI, we align world-class academic frameworks with experiential learning, cultivating future-ready professionals and compassionate global citizens.",
        "paragraphs": [
          "Education in the 21st century demands more than conventional classroom instruction; it requires dynamic adaptability, analytical rigor, hands-on technological literacy, and deeply ingrained social responsibility. At NAMI, every academic programme is meticulously structured to meet these imperatives.",
          "Having been part of NAMI's journey since 2015, I take immense pride in our evolution into an institution recognized for academic excellence, innovative pedagogy, and strong industry-academia linkages. From our Primary and Middle School divisions to our Cambridge A-Levels, CTEVT skill-based vocational programmes, and international undergraduate degrees, we foster an environment where students actively discover their intellectual and creative potential.",
          "We continue to invest extensively in modern learning technologies, advanced science and computing laboratories, Pearson VUE testing facilities, and comprehensive career counseling. Our dedicated faculty members bring international best practices into every classroom, mentoring students to turn curiosity into meaningful scholarship.",
          "We warmly invite students and parents to experience the NAMI difference — where global opportunities and grounded values converge to build extraordinary futures."
        ]
      }
    ]
  },
  "history": {
    "title": "NAMI History",
    "intro": "Established in 2012, Naaya Aayam Multi-Disciplinary Institute (NAMI) was founded with a visionary commitment to deliver transformative, world-class education in Nepal. Over more than a decade of academic excellence and institutional growth, NAMI has evolved from pioneering UK-accredited international degree pathways to establishing premier Cambridge A-Levels, national school divisions (+2 NEB & Primary), vocational CTEVT courses, and strategic partnerships with Kathmandu University—shaping generations of leaders equipped to make a lasting global impact.",
    "milestones": [
      {
        "year": "2012",
        "era": "The Foundation",
        "title": "Establishment of NAMI & UK Degree Programmes",
        "partner": "University of Northampton (UK)",
        "logo": {
          "src": "/logos/universities/northampton.png",
          "alt": "University of Northampton (UK)",
          "width": 288,
          "height": 96
        },
        "description": "Established in Kathmandu in direct academic partnership with the University of Northampton, UK, offering accredited Bachelor's and Master's degrees."
      },
      {
        "year": "2013",
        "era": "Campus Scaling",
        "title": "NAMI College Incorporation & Expansion",
        "partner": "NAMI College",
        "logo": {
          "src": "/logos/brand/nami-college.png",
          "alt": "NAMI College",
          "width": 288,
          "height": 96
        },
        "description": "Formally incorporated with dedicated multi-storey academic wings, advanced science laboratories, and campus resource centers."
      },
      {
        "year": "2014",
        "era": "Cambridge A-Levels",
        "title": "Launch of Cambridge International GCE A-Levels",
        "partner": "Cambridge Assessment International",
        "logo": {
          "src": "/logos/universities/cambridge.png",
          "alt": "Cambridge Assessment International",
          "width": 288,
          "height": 96
        },
        "description": "Accredited to offer gold-standard Cambridge GCE A-Levels in Science and Non-Science streams with global university placement guidance."
      },
      {
        "year": "2019",
        "era": "National Board",
        "title": "Launch of NAMI International School & NEB +2",
        "partner": "National Examinations Board (NEB)",
        "logo": {
          "src": "/logos/universities/neb.png",
          "alt": "National Examinations Board (NEB)",
          "width": 288,
          "height": 96
        },
        "description": "Expanded into the national curriculum with NAMI International School, offering NEB-affiliated 10+2 Science and Management programmes."
      },
      {
        "year": "2024",
        "era": "Comprehensive K-12",
        "title": "Primary Wing Launch & CAIE Home Centre Status",
        "partner": "NAMI International School",
        "logo": {
          "src": "/logos/brand/International School-ai.png",
          "alt": "NAMI International School",
          "width": 288,
          "height": 96
        },
        "description": "Opened Primary School (Grades 1–7) and earned independent Cambridge International Home Examination Centre status in Nepal."
      },
      {
        "year": "2024",
        "era": "Global Testing",
        "title": "Pearson VUE-Authorized Test Center Collaboration",
        "partner": "Pearson VUE",
        "logo": {
          "src": "/sections/misc/pearson-vue.jpg",
          "alt": "Pearson VUE",
          "width": 288,
          "height": 96
        },
        "description": "Officially authorized as a Pearson VUE testing center, enabling on-campus computer-based international IT certifications, academic tests, and global licensure exams."
      },
      {
        "year": "2025–2026",
        "era": "Future Frontiers",
        "title": "Kathmandu University Partnership & CTEVT Programmes",
        "partner": "Kathmandu University & CTEVT",
        "logo": {
          "src": "/logos/universities/Kathmandu_University_Logo.webp",
          "alt": "Kathmandu University & CTEVT",
          "width": 288,
          "height": 96
        },
        "description": "MoU with Kathmandu University for BSc. Environmental Studies, University of Hertfordshire collaboration, and CTEVT vocational programmes."
      }
    ]
  },
  "emblem": {
    "label": "The Red Lotus.",
    "title": "The Emblem",
    "image": {
      "src": "/sections/misc/lotus.png",
      "alt": "NAMI Emblem - Red Lotus",
      "width": 612,
      "height": 408
    },
    "paragraphs": [
      "The lotus flower, a representation of rebirth, blossoms in the dark and becomes a lovely plant in the NAMI logo. NAMI's core values are represented by each of the lotus's five petals.",
      "The heart, or \"Hridaya\", is symbolised by the red lotus in Sanskrit as love, passion, kindness and compassion. A fully blossomed red lotus represents the compassion and warmth of the human spirit. As our graduates enter the real world, we aim for NAMIANS to embody the spirit reflected in our logo."
    ],
    "valuesTitle": "The Five Petals & Core Values",
    "values": [
      {
        "name": "Enlightenment",
        "meaning": "Ensures a complete and holistic development."
      },
      {
        "name": "Knowledge",
        "meaning": "The skills and awareness acquired through experience with situations and facts."
      },
      {
        "name": "Purity of Heart and Mind",
        "meaning": "Removes impurities from thoughts and thinking, promoting ethics and values for creating a compassionate society."
      },
      {
        "name": "Self-Awareness",
        "meaning": "Enhances the ability to recognise and understand one's own ideas, feelings and behaviours."
      },
      {
        "name": "Wisdom",
        "meaning": "The ability to reason logically and to behave wisely."
      }
    ]
  },
  "creed": {
    "label": "What NAMI stands for.",
    "title": "Mission & Vision",
    "missionLabel": "Mission",
    "mission": [
      "To empower individuals with fundamental academic knowledge, life skills and values that foster a genuine love for learning, and prepare them to impact their own lives and the lives of others positively."
    ],
    "visionLabel": "Vision",
    "vision": [
      "To offer access to world-class education within Nepal, fostering human capital development among the youth and empowering them to become responsible individuals contributing to society, both locally and globally."
    ]
  },
  "mascot": {
    "label": "The swan carries the same five values.",
    "title": "The Mascot",
    "paragraphs": [
      "NAMI's mascot is a graceful swan, representing the spirit and values of NAMI. With its snow-white feathers and elegant posture, the swan symbolizes purity, resilience, transformation, and excellence. Its warm and friendly expression reflects NAMI's welcoming community. Surrounded by a vibrant lotus flower inspired by the NAMI logo, the mascot embodies growth, knowledge, and nurturing. The lotus petals gently cradle the swan, symbolizing the supportive and interconnected nature of the NAMI family.",
      "With its wings slightly spread, the swan signifies NAMI students' readiness to soar toward new opportunities. The wings carry the same core values as the petals of the lotus above. The mascot was designed by a NAMI student, showcasing the creativity and spirit of the NAMI community."
    ],
    "image": {
      "src": "/mascot/Mascot final.png",
      "alt": "NAMI College Mascot - The Swan",
      "width": 800,
      "height": 800
    }
  },
  "awards": {
    "label": "",
    "title": "Awards & Honours",
    "description": "Distinctions the institution and its students have carried home, and the bodies that conferred them.",
    "emptyState": "NAMI is compiling its awards record — this space is reserved for it.",
    "items": [
      {
        "year": 2024,
        "title": "Excellence in Teaching and Learning",
        "awardingBody": "National education awards panel",
        "citation": ""
      },
      {
        "year": 2022,
        "title": "Best Emerging Institution",
        "awardingBody": "Regional schools association",
        "citation": ""
      },
      {
        "year": 2020,
        "title": "Outstanding Student Achievement",
        "awardingBody": "Inter-college academic council",
        "citation": ""
      },
      {
        "year": 2018,
        "title": "College Sustainability Commendation",
        "awardingBody": "City sustainability forum",
        "citation": ""
      }
    ]
  },
  "testimonials": {
    "label": "",
    "title": "Stakeholder Voice",
    "emptyState": "Stakeholder stories are being collected — this space is reserved for them.",
    "items": [
      {
        "quote": "The team at NAMI International School has been fantastic to work with. The teachers help us deliver our UnMath District program with ease, including building a Math Museum at the school. In a short time, we have delivered 100+ interactive experiences for Grade 1–7 students. We are thrilled to continue this meaningful partnership.",
        "name": "Mr. Divesh Bhatija",
        "role": "Math Storyteller & Co-Founder, UnMath School",
        "portrait": {
          "src": "/testimonials/stakeholders/Divesh Bhatija.png",
          "alt": "Mr. Divesh Bhatija",
          "width": 1323,
          "height": 1189
        }
      },
      {
        "quote": "Being part of NAMI International School has been a joyful journey. The supportive colleagues, curious students, and warm community make every day rewarding. Teaching Chinese here has enriched my life and deepened my appreciation for Nepal’s culture. I am proud to be part of NAMI.",
        "name": "Ren Yuanyuan",
        "role": "Chinese Facilitator",
        "portrait": {
          "src": "/testimonials/teachers/Ren Yuanyuan.png",
          "alt": "Ren Yuanyuan",
          "width": 1103,
          "height": 1426
        }
      },
      {
        "quote": "When I first entered NAMI International School, I immediately felt its peaceful and welcoming environment. It feels like a place where children are encouraged to learn and grow. The teachers are caring, supportive, and easy to connect with. The enthusiastic students bring energy to every lesson, making teaching here truly enjoyable.",
        "name": "Miss Chandrika Limbu",
        "role": "3Di Facilitator",
        "portrait": {
          "src": "/testimonials/stakeholders/Chandrika Limbu.png",
          "alt": "Miss Chandrika Limbu",
          "width": 1254,
          "height": 1254
        }
      },
      {
        "quote": "यस विद्यालयमा छुट्टै ऊर्जा महसुस हुन्छ। सहयोगी वातावरण, सहकार्यको भावना, विद्यार्थीहरूको अनुशासन र जिज्ञासु स्वभावले यहाँ पढाउँदा आत्मीय आनन्द मिल्छ । यस विद्यालयको एक सदस्यका रूपमा मेरो अनुभव अत्यन्तै सुखद र आत्मीय रहेको छ ।",
        "name": "RamKrishna Koirala",
        "role": "Sanskrit Facilitator",
        "portrait": {
          "src": "/testimonials/teachers/Ramkrishna Koirala.png",
          "alt": "RamKrishna Koirala",
          "width": 1141,
          "height": 1379
        }
      },
      {
        "quote": "As a PE Trainer representing Play Nepal at NAMI for nearly three years, the supportive environment, friendly staff, wonderful colleagues, enthusiastic students, and caring parents have made my journey truly memorable. I’m grateful to be part of the NAMI family.",
        "name": "Rajesh Tumbapo",
        "role": "Team Play Nepal",
        "portrait": {
          "src": "/testimonials/stakeholders/Rajesh Thumbapo.png",
          "alt": "Rajesh Tumbapo",
          "width": 1254,
          "height": 1254
        }
      },
      {
        "quote": "Stepping into NAMI feels like stepping into a balanced space filled with positive energy. The admin and faculty work in true harmony, creating a calm, supportive environment where students and teachers share a natural, effortless growth.",
        "name": "Miss Indu Poudel",
        "role": "Yoga Instructor",
        "portrait": {
          "src": "/testimonials/teachers/Indu.png",
          "alt": "Miss Indu Poudel",
          "width": 1107,
          "height": 1421
        }
      },
      {
        "quote": "NAMI International School को एक शिक्षकका रूपमा यस गौरवशाली शैक्षिक परिवारको हिस्सा बन्न पाउनु मेरो लागि अत्यन्तै गर्व र आत्मीयताको अनुभूति हो। यहाँको प्रेरणादायी वातावरण, समर्पित नेतृत्व र सहकार्यपूर्ण संस्कृतिले विद्यार्थीको ज्ञान, सीप, सिर्जनशीलता र चरित्र विकासलाई सार्थक दिशा दिन्छ।",
        "name": "प्रतिभा फुयाल",
        "role": "सामाजिक शिक्षक",
        "portrait": {
          "src": "/testimonials/teachers/Pratibha Phuyal.png",
          "alt": "प्रतिभा फुयाल",
          "width": 1155,
          "height": 1362
        }
      },
      {
        "quote": "My journey with NAMI International School has come full circle in a truly beautiful way. From being a student who once learned within these walls to now serving as a school librarian, I feel a deep sense of gratitude and belonging. It is meaningful to give back to the school that shaped me and inspire young learners.",
        "name": "Prishita Rokaya",
        "role": "School Librarian",
        "portrait": {
          "src": "/testimonials/teachers/Prishita Rokaya.png",
          "alt": "Prishita Rokaya",
          "width": 1269,
          "height": 1240
        }
      }
    ]
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
