<?php
/**
 * NAMI CMS — Faculty & Leadership page
 *
 * Requires the "NAMI CMS — Core engine" snippet. Adds a "Faculty & Leadership"
 * menu to the WordPress sidebar with one sub-menu per group on the /faculty page.
 *
 * Field keys must match src/lib/cms/pages/faculty/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$group = function ( $title, $description ) {
			return array(
				'title'       => $title,
				'description' => $description,
				'fields'      => array(
					'title'  => array( 'type' => 'text', 'label' => 'Group heading' ),
					'people' => array(
						'type'        => 'repeater',
						'label'       => 'People (in display order)',
						'item_label'  => 'Person',
						'title_field' => 'name',
						'fields'      => array(
							'name'     => array( 'type' => 'text', 'label' => 'Name' ),
							'title'    => array( 'type' => 'text', 'label' => 'Job title' ),
							'portrait' => array( 'type' => 'image', 'label' => 'Portrait', 'help' => 'Portrait orientation (4:5) works best; the top of the photo is kept.' ),
							'brief'    => array( 'type' => 'textarea', 'label' => 'Short summary (on the card)', 'rows' => 3, 'help' => 'About 3 lines are shown on the card.' ),
							'bio'      => array( 'type' => 'textarea', 'label' => 'Full bio (in the popup)', 'rows' => 14, 'help' => 'Leave an empty line between paragraphs. Start lines with • or - for a bullet list. Leave empty to show the short summary.' ),
						),
					),
				),
			);
		};

		$pages['faculty'] = array(
			'title'      => 'Faculty & Leadership',
			'menu_title' => 'Faculty',
			'icon'       => 'dashicons-groups',
			'position'   => 3.2,
			'path'       => '/faculty',
			'sections'   => array(
				'board'      => $group( 'Board of Directors', 'The first group on the page. With exactly 7 people it shows as a row of 4 and a row of 3.' ),
				'management' => $group( 'Management Team', 'With more than 4 people the cards scroll sideways.' ),
				'academics'  => $group( 'Academic Heads', 'With more than 4 people the cards scroll sideways.' ),
				'seo'        => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Faculty & Leadership",
    "description": "Meet the board of directors, academic heads, and management team who shape the future of NAMI."
  },
  "board": {
    "title": "Board of Directors",
    "people": [
      {
        "name": "Capt. Rameshwar Thapa",
        "title": "Chairperson, NAMI Group of Companies",
        "brief": "Founder Chairman of Annapurna Ventures, comprising 30+ ventures across Nepal's economy. A first-generation entrepreneur, strategic investor, and pioneering MI-17 Commander with over two decades of aviation leadership.",
        "bio": "Capt. Rameshwar Thapa is the Founder Chairman of Annapurna Ventures, a diversified entrepreneurship platform comprising more than 30 ventures across multiple sectors of Nepal’s economy. A first-generation entrepreneur and strategic investor, he has established and nurtured institutions in aviation, media, hydropower, healthcare, education, manufacturing, trading and distribution, real estate, construction, hospitality, ropeway infrastructure, and strategic investment.\n\nHis leadership approach is founded on disciplined capital allocation, long-term value creation, strong governance, and responsible enterprise development. Under his guidance, Annapurna Ventures has evolved into a multi-sector business ecosystem employing more than 1,200 professionals and creating sustainable platforms for economic growth and institutional resilience.\n\nCapt. Thapa’s professional journey is deeply rooted in aviation. With over two decades of operational flying experience and more than 10,000 flight hours across various helicopter platforms, he combines aviation expertise, operational discipline, and strategic vision. He holds the distinction of being Nepal’s first MI-17 Commander for commercial operations and one of the pioneering Instructor Pilots on the MI-17 platform, contributing significantly to the advancement of helicopter aviation standards, safety practices, and operational excellence in Nepal.\n\nHe currently serves as Chairman of Simrik Air Pvt. Ltd., one of Nepal’s leading helicopter operators, and Executive Chairman and Principal Owner of Annapurna Media Network, publisher of Annapurna Post and operator of Radio Annapurna. Through these institutions, he continues to contribute to national connectivity, entrepreneurship, education, and public discourse.\n\nLeadership and Institutional Roles:\n• Chairman, Annapurna Ventures Pvt. Ltd.\n• Chairman, Annapurna Media Network Pvt. Ltd.\n• Chairman, Annapurna Education Initiatives Pvt. Ltd.\n• Chairman, NAMI College Pvt. Ltd.\n• Chairman, NAMI International School Pvt. Ltd.\n• Chairman, Simrik Air Pvt. Ltd.\n• Chairman, Hydro Village Pvt. Ltd.\n• Chairman, Jurimba Hydropower Company Pvt. Ltd.\n\nIndustry Leadership Roles:\n• Past President, Airlines Operators Association of Nepal\n• President, Helicopter Society of Nepal\n\nProfessional Credentials:\n• Airline Transport Pilot License (Helicopter) – ATPL(H), License No. 015\n• Commercial Pilot License – USSR\n• Airline Transport Pilot License – United States\n• Instructor Pilot Certification – United States\n\nAircraft Experience:\nCommand and instructional experience across Bell 407GXP, AS 350 B3, BK 117 B2, MI-17 series, MI-8 series, MI-2, Bell 47, and Cessna 152 aircraft platforms.\n\nNational Honors and Decorations:\nCapt. Thapa has received several national decorations and recognitions from the Government of Nepal and national security institutions in acknowledgement of his distinguished service, aviation leadership, disaster response contributions, and commitment to national development:\n• Prabal Gorkha Dakshin Bahu, Fourth Class (2003)\n• Prakhyat Trishakti Patta, Fourth Class (2005)\n• Sukirtimaya Rastradeep (2021)\n• Rastrasewa Padak (2002)\n• Nepal Police Medal (2002)\n• Daivik Prakop Padak (2001)\n• Public Service Award, Fourth Class (2011)\n• Bravery Awards from Nepal Police (2010 and 2013)\n\nOther Professional Recognitions:\n• National Personality Award (2003)\n• Best Pilot of the Year (2003)\n• Man of the Year (2004)\n\nLegacy, Vision and Leadership Philosophy:\nCapt. Thapa’s career represents a distinctive combination of aviation excellence, entrepreneurial vision, and institution-building leadership. His contributions across diverse sectors reflect his commitment to creating sustainable enterprises that generate economic value while supporting Nepal’s broader development goals. Through Annapurna Ventures and its affiliated institutions, he continues to promote innovation, responsible governance, and sustainable growth.",
        "portrait": {
          "src": "/leadership/rameshwar-thapa.webp",
          "alt": "Studio portrait of Capt. Rameshwar Thapa, Chairperson of NAMI, arms folded in a pale blue mandarin-collar shirt against a mottled blue-grey backdrop.",
          "width": 1173,
          "height": 1600
        }
      },
      {
        "name": "Mr. Suresh Raj Ghimire",
        "title": "Director, NAMI Group of Companies",
        "brief": "Engineering management specialist and international business expert with extensive experience in manufacturing operations, lean systems, global trading, and technical consultancy. Holds an MSc from Brunel University London, UK.",
        "bio": "Mr. Suresh Raj Ghimire is an accomplished engineering management professional and international business expert with over two decades of experience in manufacturing operations management, trading, and consultancy services. He currently serves as Director at Naaya Aayam Multi-Disciplinary Institute (NAMI), contributing to the institute's vision of delivering high quality education that blends technical knowledge with managerial expertise.\n\nMr. Ghimire holds a Master's in Engineering Management (MSc) from Brunel University, London, UK, specializing in Technical Management of Manufacturing Industries, and a Bachelor's in Electrical and Electronics Engineering from Karnataka University, India. His academic background and professional experience position him as a strategic leader in engineering operations, project management, and technical consultancy.\n\nProfessionally, he has led international trading and consulting ventures while offering specialized expertise in lean manufacturing, production optimization, and technical management. His career includes key leadership roles both in Nepal and abroad, such as founding and operating KRYSS International Pvt. Ltd., a prominent trading house dealing in IT-based equipment for security forces and high-tech consumer goods.\n\nIn London, he worked with Three Star Consulting Inc., offering global consulting in lean manufacturing systems, and served as Assistant Manager for International Sales and Services at TSK Company Ltd (Toyota International Wing). He also consulted for Nepal Hydro and Electric Co. Ltd., improving manufacturing and production systems. As part-time faculty at the London College of Engineering and Management, he contributed to curriculum design and taught technical management. In Nepal, he led Re-Join Quality Foods Pvt. Ltd., the country's only meat processing and export facility, and Nara Himalayan Natural Spring Water Co. Pvt. Ltd., the first export-quality spring water project.\n\nAt NAMI, he applies his global expertise and entrepreneurial vision to strengthen academic programs, promote industry-oriented learning, and mentor future professionals in engineering and management disciplines. He actively collaborates with faculty and industry experts to design curricula that address real-world challenges, fosters innovation through interdisciplinary initiatives, and supports student-led projects that build technical and leadership competencies.",
        "portrait": {
          "src": "/leadership/suresh-raj-ghimire.webp",
          "alt": "Studio portrait of Mr. Suresh Raj Ghimire, Director at NAMI, arms folded in a light grey suit and patterned tie against a mottled blue-grey backdrop.",
          "width": 1158,
          "height": 1600
        }
      },
      {
        "name": "Ms. Soni Joshi",
        "title": "Director, NAMI Group of Companies",
        "brief": "Development practitioner, educator, and gender rights advocate with extensive experience in social development, women's empowerment, project management, and leadership with UN Women's Organization and Zonta International.",
        "bio": "Ms. Soni Joshi is a development practitioner, educator, and gender rights advocate with extensive experience in social development, education, and project management. She holds a Master’s degree in Rural Development and Gender Studies (M.SC. R.D.G.S) from the South Asian Institute of Technology (SAIT) and a Post Graduate Diploma in Women’s Studies from Padma Kanya College, Tribhuvan University. Her academic background reflects her strong interest in gender equality, education, and community development. Over the years, she has built her career around supporting women’s empowerment and improving opportunities for marginalized communities in Nepal.\n\nThroughout her professional journey, Ms. Joshi has worked in research, project development, communication, and training programs. She has been involved in many initiatives focused on women’s empowerment, social awareness, and community development. She has organized, facilitated, and participated in several national and international workshops and programs with organizations such as Friedrich Ebert Stiftung (FES), Inter Press Service (IPS), and the International Geographic Union (IGU).\n\nMs. Joshi has held significant leadership and advisory roles across various national and international organizations. She has served as President of the Centre for Health, Education, Training & National Advocacy (CHETANA). Her international involvement includes serving as the former Chair for Social Welfare, Environment Member, and Editorial Board Member of The Mirror Magazine under the United Nations Women's Organization (UNWO). She has also led the Association of St. Mary's Alumni (ASMAN) as President, contributing to numerous academic and community initiatives. Additionally, she served as the first Nepali President of Active Women of Nepal (AWON).\n\nShe is a Founder Member of Zonta Club Kathmandu which is under the umbrella of Zonta International and has served as the Chair of different committees as Advocacy, Leadership, Service and UN. Currently she is the District Chair of the UN Committee which comprises Nepal, India, Bangladesh and Sri Lanka. She was also an Executive Member and Co-coordinator for International Affairs at the Ganesh Man Singh Academy (GMSA).\n\nAt present she is also the Country Patron for the World Women Leadership Congress and has been awarded with:\n• Women Leadership Achievement Award by the World Women Leadership Congress Awards (February 2015)\n• Women Super Achiever Award by the World Women Leadership Congress Awards (February 2017)\n• Social Innovation Leadership Award by Nepal Social Innovation Leadership Awards (December 2017)\n\nAt NAMI, she plays an active role in institutional planning, supporting students, improving academic programs, and creating awareness about social responsibility. Through her work, she continues to encourage positive change in education and society.",
        "portrait": {
          "src": "/leadership/soni-joshi.webp",
          "alt": "Studio portrait of Ms. Soni Joshi, Director at NAMI, hands clasped in a green and blue floral sari against a mottled blue-grey backdrop.",
          "width": 1158,
          "height": 1600
        }
      },
      {
        "name": "Mr. Yog Raj Kandel Sharma",
        "title": "Director, NAMI Group of Companies",
        "brief": "Aviation and business management professional with over two decades of leadership spanning aviation management, corporate governance, renewable energy, and community development. Holds an MBA Executive and FAA certification.",
        "bio": "Mr. Yog Raj Kandel Sharma brings to Naaya Aayam Multi-Disciplinary Institute (NAMI) a wealth of leadership experience spanning aviation management, corporate governance, and community development. Holding an MBA Executive from Purbanchal University and a professional qualification as an Aircraft Dispatcher from the U.S. Federal Aviation Administration (FAA), Mr. Sharma's expertise bridges business management and technical aviation operations.\n\nAs the former Chief Executive Officer of NAMI (2012–2017), he directed strategic operations and governance, aligning institutional goals with quality education delivery. His extensive leadership in Nepal's aviation sector includes senior roles at Simrik Air Pvt. Ltd., a leading helicopter service provider, where he managed operations, administration, and business development over 15 years.\n\nMr. Sharma's corporate influence extends across multiple sectors through board memberships at prominent organizations such as Simrik Air Pvt. Ltd., KRYSS International Pvt. Ltd., and Manakamana Development Bank Ltd. His entrepreneurial vision is also demonstrated through promotion of renewable energy projects like the Aankhu Khola Jalbidhyut Company Ltd.\n\nDeeply committed to social development, Mr. Sharma has played vital roles in numerous nonprofit and community organizations, including founding youth clubs and leading the Nepal German Friendship Association. His dedication to social upliftment is matched by his active participation in training and coordinating educational and leadership programs throughout Nepal.\n\nDuring his four-year tenure as Chief Executive Officer (CEO) of NAMI from 2012 to 2017, Mr. Sharma led the institution through a period of exponential growth. Under his leadership, NAMI saw significant improvements in institutional branding, student admissions, and overall visibility in the education sector. He was instrumental in establishing core operational systems and frameworks that continue to support the institute's academic and administrative functions today.",
        "portrait": {
          "src": "/leadership/yog-raj-kandel-sharma.webp",
          "alt": "Studio portrait of Mr. Yog Raj Kandel Sharma, Director at NAMI, arms folded in a navy suit and blue tie against a mottled blue-grey backdrop.",
          "width": 1217,
          "height": 1600
        }
      },
      {
        "name": "Mr. Robin Rana",
        "title": "Director, NAMI Group of Companies",
        "brief": "Business leader and strategic advisor with over three decades of professional experience across banking, aviation, telecommunications, energy, carbon markets, and environmental sustainability in Nepal. Holds a BBA in Finance from SUNY Albany, USA.",
        "bio": "Mr. Robin Rana is an experienced business leader and strategic advisor with over three decades of professional experience across banking, aviation, telecommunications, energy, consultancy, and environmental sustainability sectors in Nepal. With a strong foundation in finance and business management, he has built expertise in strategic planning, business development, corporate advisory, financial operations, and stakeholder engagement.\n\nThroughout his career, Mr. Rana has contributed to the growth and transformation of organisations by combining financial acumen with entrepreneurial vision and cross-sector industry knowledge. His leadership journey reflects extensive experience in building partnerships, managing business operations, identifying growth opportunities, and supporting organisations in navigating evolving market environments.\n\nCurrently, Mr. Rana serves as the Director of Himalayan Carbon, where he provides strategic leadership in advancing initiatives related to carbon markets, renewable energy, climate finance, and environmental sustainability. He is actively involved in developing opportunities around International Renewable Energy Certificates (I-RECs), green investments, carbon trading, and corporate sustainability commitments, contributing towards Nepal’s transition to a low-carbon economy.\n\nAs the Chief Executive Officer of a business consultancy firm, Mr. Rana provides strategic advisory services to national and international clients, supporting organisations in areas including business expansion, operational improvement, market development, and corporate strategy. His sector expertise spans aviation, energy, and telecommunications, enabling him to deliver practical and result-oriented business solutions.\n\nMr. Rana also serves as Director of Hansa International, where he brings significant experience from Nepal’s aviation and travel industry. During his association with the sector, he played a key role in airline representation, corporate partnerships, and market coordination, including serving as the General Sales Agent (GSA) for Jet Airways in Nepal.\n\nPrior to his entrepreneurial and advisory roles, Mr. Rana served as Executive Manager at Himalayan Bank Limited, where he established and managed the Credit Card Centre for Visa and Mastercard services. His contribution supported the expansion of retail banking services and the development of Nepal’s digital payment ecosystem.\n\nMr. Rana holds a Bachelor of Business Administration (BBA) in Finance from State University of Albany, New York, USA. Beyond his professional pursuits, he has demonstrated excellence in sports and personal development, including achievements as a National Swimming Silver Medalist and National Shooting Silver Medalist in the Veteran Category. He is also an avid golfer.",
        "portrait": {
          "src": "/leadership/robin-rana.webp",
          "alt": "Studio portrait of Mr. Robin Rana, Director at NAMI, arms folded in a slate blue suit and striped grey tie against a mottled blue-grey backdrop.",
          "width": 1205,
          "height": 1600
        }
      },
      {
        "name": "Ms. Samjhana Phuyal",
        "title": "Director, NAMI Group of Companies",
        "brief": "Human rights advocate, legal professional, and social development leader with nearly two decades of experience in gender equality, women's rights, and community empowerment. Holds an LLB and Master's in Anthropology from Tribhuvan University.",
        "bio": "Ms. Samjhana Phuyal is a Nepalese human rights advocate, legal professional, and social development leader with nearly two decades of experience in gender equality, women's rights, and community empowerment. She holds a Master's degree in Anthropology, a Postgraduate Diploma in Women's Studies, and an LLB from Tribhuvan University.\n\nShe is widely recognized for advancing women's rights and public safety initiatives in Nepal. In collaboration with Safe City India, she helped launch the Pink Bus Project, aimed at addressing sexual harassment in public transportation. She is also the founder of SEEW (Social Education and Empowerment of Women), which supports survivors of domestic violence and promotes gender equality. Through her work with the Safe Motherhood Network Federation (SMNF), she contributed to integrating Respectful Maternity Care (RMC) into Nepal's maternal health framework.\n\nMs. Phuyal represented Nepal at the United Nations General Assembly (UNGA) in 2012 as a Youth Leader for Maternal Health and has engaged with international platforms including Vital Voices, the White Ribbon Alliance, the World Forestry Institute, and Bioneers. Following the 2015 Nepal earthquake, she played an active role in relief and recovery efforts, including shelter support, school reconstruction, and community-based public health initiatives.\n\nHer advocacy has been featured on international platforms, including The Guardian, and she has contributed testimony on child marriage to parliamentary discussions in the United Kingdom. She is a recipient of the Tewa Excellent Fundraising Award (2009) and the Innovation & Entrepreneurship Prize (2015) awarded by the National Youth Entrepreneurship Forum (NYEF) in collaboration with the U.S. Embassy in Nepal.\n\nCurrently serving in a leadership role at NAMI International School, she contributes to institutional development, inclusive education, and youth mentorship, fostering leadership, empathy, and social responsibility among students.",
        "portrait": {
          "src": "/leadership/samjhana-phuyal.webp",
          "alt": "Studio portrait of Ms. Samjhana Phuyal, Director at NAMI, hands clasped in a cream embroidered sari over a red blouse against a mottled blue-grey backdrop.",
          "width": 1158,
          "height": 1600
        }
      },
      {
        "name": "Mr. Ramesh Prasad Tiwari",
        "title": "Director, NAMI Group of Companies",
        "brief": "Distinguished entrepreneur, educationist, and governance professional with extensive experience in business leadership, corporate governance, and institutional development. Pursuing a PhD in Conflict and Peace Development.",
        "bio": "Mr. Ramesh Prasad Tiwari is a distinguished entrepreneur, educationist, and governance professional with extensive experience in business leadership, corporate governance, and institutional development. As a Board Member of NAMI, he contributes to the strategic governance and long-term vision of the institution, supporting its commitment to academic excellence, innovation, and sustainable growth.\n\nAcademically, Mr. Tiwari holds a Master's degree in Sociology and Political Science and is currently pursuing a PhD in Conflict and Peace Development at Tribhuvan University. His academic interests in governance, conflict resolution, and peacebuilding complement his professional expertise, enabling him to contribute meaningfully to both the education sector and broader social development initiatives.\n\nMr. Tiwari also serves as a Board Director of Stoxkarts Securities Limited and Kantipur Campus, where he provides strategic oversight in corporate governance, policy formulation, organisational development, and stakeholder engagement. As a Founder Member of Kantipur Academy, he has played a pivotal role in establishing and strengthening an institution dedicated to delivering quality education and holistic student development.\n\nAn accomplished businessman, Mr. Tiwari has successfully led and managed diverse business ventures with a focus on strategic planning and sustainable growth. His leadership is characterised by a strong commitment to ethical governance, institutional excellence, and long-term value creation.",
        "portrait": {
          "src": "/leadership/ramesh-prasad-tiwari.webp",
          "alt": "Studio portrait of Mr. Ramesh Prasad Tiwari, Director at NAMI, arms folded in a dark checked suit and red tie against a mottled blue-grey backdrop.",
          "width": 1233,
          "height": 1600
        }
      }
    ]
  },
  "management": {
    "title": "Management Team",
    "people": [
      {
        "name": "Mr. Pranil Pandey, FCCA",
        "title": "Chief Executive Officer, NAMI Group of Companies",
        "brief": "Chief Executive Officer of NAMI since 2024. Brings dynamic financial leadership, global partnerships, and educational strategy, having previously served 9 years as Chief Financial Officer. Fellow Chartered Certified Accountant (FCCA, UK) and Master's in Management.",
        "bio": "Mr. Pranil Pandey, FCCA, is the Chief Executive Officer of NAMI since 2024. With his dynamic financial leadership, global partnerships, and education strategy, he has played a key role in shaping NAMI's vision and growth. Joining NAMI in 2015, he initially served as Chief Financial Officer (CFO) for nine years, where he played a pivotal role in strengthening financial governance and operational systems.\n\nBefore his tenure at NAMI, Mr. Pandey established a solid foundation in finance and auditing through his work with leading chartered accountancy firms, including J Santosh & Co. CA, K.K. Budhathoki & Associates, and JK & SS CA. These experiences equipped him with practical knowledge in auditing, taxation, financial advisory, and corporate compliance, which he later applied to streamline operations and strengthen governance at NAMI.\n\nAt NAMI, Mr. Pandey leads key strategic initiatives, including institutional expansion, financial governance, and the development of globally aligned academic programs. He has strengthened operational systems, advanced industry-relevant curricula, and fostered innovation and international collaboration, positioning NAMI as a progressive, future-ready institution committed to academic excellence and global standards. He also promotes leadership development and interdisciplinary learning, reinforcing NAMI’s mission to produce globally competent, socially responsible, and career-ready graduates.\n\nA Fellow Chartered Certified Accountant (FCCA, UK), Mr. Pandey holds a Master’s degree in Management. He also earned a Bachelor of Business Administration (BBA) from IEC University and completed his GCE ‘A’ and ‘O’ Levels under the University of Cambridge curriculum. His academic background combines strong financial expertise with an international perspective, enabling him to effectively bridge finance and education. This diverse qualification base supports his strategic leadership in a global context and reflects his commitment to continuous learning and global best practices.",
        "portrait": {
          "src": "/leadership/pranil.jpeg",
          "alt": "Studio portrait of Mr. Pranil Pandey, Chief Executive Officer of NAMI, hands clasped in a blue suit and blue tie against a mottled blue-grey backdrop.",
          "width": 1173,
          "height": 1600
        }
      },
      {
        "name": "Mr. Karun Regmi",
        "title": "Head, Business Development and Marketing & Branding",
        "brief": "Head of Business Development and Marketing & Branding at NAMI, bringing multidisciplinary expertise in marketing strategy, brand communications, banking operations, and media content development. Holds an MBS from Tribhuvan University.",
        "bio": "Mr. Karun Regmi is an experienced professional currently serving as the Head of Marketing and Branding at Naaya Aayam Multi-Disciplinary Institute (NAMI). He has professional experience spanning marketing and branding, communication, content development, banking, credit management, branch operations and customer relations. Mr. Regmi holds strong leadership, communication, analytical and problem-solving skills.\n\nAt NAMI, Mr. Regmi is responsible for supporting the institution's marketing, branding, communication and promotional activities. His role involves contributing to institutional visibility, policy making, developing communication and promotional content, coordinating marketing initiatives and supporting the organization's overall branding and outreach efforts.\n\nPrior to joining NAMI, he gained extensive experience in the banking and financial services sector. He worked as an Assistant at Muktinath Bikas Bank Ltd. for two years, handling retail and SME credit-related activities, credit file preparation and legal documentation reporting. He subsequently worked as an Assistant at Garima Bikas Bank Ltd. for two years, where he was involved in retail and SME credit functions, documentation, customer service and credit file management.\n\nHe also worked for two years at Kamana Sewa Bikas Bank Ltd. as a Branch Manager/Supervisor, where he was responsible for branch operations, deposit-related activities, customer service, staff coordination and communication with the Head Office.\n\nIn the field of communication and media, Karun worked as a Content Writing Expert at Shilalekha Multimedia Pvt. Ltd., Banke and Montage Media Pvt. Ltd., Surkhet, gaining experience in content development and communication. He also served as an Officer/Content Writing Expert at the Trade and Export Promotion Centre, Pulchowk, Lalitpur, where he was involved in content development, communication, documentation and information dissemination.\n\nMr. Regmi holds a Master of Business Studies (MBS) from Baneshwor Multiple Campus, Tribhuvan University. He has completed professional training in Advanced Office Package, General Banking Knowledge and Basic Credit Management. He possesses practical skills in MS Office, communication, content development, documentation, marketing coordination and stakeholder engagement.",
        "portrait": {
          "src": "/leadership/karun-regmi.webp",
          "alt": "Studio portrait of Mr. Karun Regmi, Head of Business Development and Marketing & Branding at NAMI, arms folded in a black suit, red tie and glasses against a mottled blue-grey backdrop.",
          "width": 1086,
          "height": 1449
        }
      }
    ]
  },
  "academics": {
    "title": "Academic Heads",
    "people": [
      {
        "name": "Mr. Nischal Khadka",
        "title": "Academic Head, Naaya Aayam Multi-Disciplinary Institute",
        "brief": "Academic Head at Naaya Aayam Multi-Disciplinary Institute and NILE Champion. Dual Gold Medalist in BCA and MCA from Sikkim Manipal University, full-stack developer, and IT consultant in .NET Core, Angular, microservices, and ISO 27001.",
        "bio": "Mr. Nischal Khadka is a distinguished academician and IT professional, currently serving as the Academic Head at Naaya Aayam Multi-Disciplinary Institute (NAMI). With dual gold medals in both Bachelor and Master of Computer Applications from Sikkim Manipal University, he has demonstrated consistent academic excellence and a passion for advancing technology driven education.\n\nMr. Khadka brings a strong combination of academic leadership, software development expertise, and IT consultancy experience. His career at NAMI has evolved from lecturing to key leadership roles such as Module Leader, Assistant Program Leader, Program Leader, and now Academic Head demonstrating a clear trajectory of professional growth and dedication to educational excellence. As the NILE (Northampton Integrated Learning Environment) Champion, he spearheads digital learning initiatives and leads efforts in academic quality assurance, ensuring that teaching practices and program delivery meet international standards.\n\nAdditionally, he plays a pivotal role in curriculum development, faculty mentoring, and the integration of technology to enhance learning outcomes. In parallel with his academic leadership, Mr. Khadka works as a full-stack developer and IT consultant, specializing in .NET Core, Angular, microservice architecture, and ISO 27001 consultancy. His industry work includes developing ERP solutions, e-commerce platforms, and workflow systems. His expertise strengthens NAMI’s IT programs, promoting innovation and student excellence. A leader in academia and technology, Mr. Khadka drives innovation at NAMI by integrating education with industry practice.",
        "portrait": {
          "src": "/leadership/nischal-khadka.webp",
          "alt": "Studio portrait of Mr. Nischal Khadka, Academic Head at NAMI, arms folded in a dark navy suit and patterned blue tie against a mottled blue-grey backdrop.",
          "width": 1086,
          "height": 1449
        }
      },
      {
        "name": "Ms. Anisha Panday Joshi",
        "title": "Principal, NAMI International School",
        "brief": "Principal of NAMI International School with over 15 years of experience in education leadership, curriculum development, and administration. Holds a Master's in Education (NOCN, UK) and an MBA from Kathmandu University.",
        "bio": "Ms. Anisha Panday Joshi is the Principal of NAMI International School, with more than 15 years of experience in education, school leadership, administration, and organizational management. She holds a Master’s in Business Administration in Marketing from Kathmandu University and a Master’s in University of Applied Research & Development from the National Open College Network (NOCN), United Kingdom.\n\nThroughout her career, Ms. Panday has worked in curriculum development, teacher development, school operations, student support, and academic leadership. Before joining NAMI, she served as a Secondary School Coordinator and English Language Teacher at Sanskriti International School and worked as an educational consultant at Shushrusha Serves. Her earlier experience in corporate marketing has also contributed to her strengths in communication, planning, teamwork, and organizational development.\n\nAs Principal, she provides leadership across the Primary and Secondary School, working closely with students, teachers, parents, and the wider NAMI community. She oversees academic planning and development, curriculum and assessment, teacher development, student wellbeing, school operations, and contributes to policy planning, review, and implementation. She also works closely with staff and families to strengthen communication, build a positive school culture, and ensure that students receive the guidance and support they need to grow with confidence. In 2024, she became the Founding Principal of NAMI International School’s Primary Wing, which has since grown into the Primary and Middle School, playing a significant role in establishing its academic and operational foundations and shaping its culture from the outset.\n\nAt the heart of her educational philosophy is the belief that schools should prepare students not only for academic success, but also to become thoughtful, responsible, confident, and compassionate individuals. She values open communication, collaboration, and shared responsibility, and believes that students make progress when they feel a genuine sense of belonging and are encouraged to take ownership of their choices and actions.\n\nFor Ms. Panday, leading a school is not simply about managing an institution; it is about creating a place where young people feel that they belong, where teachers feel that their work matters, and where what students learn and experience at school stays with them long after they leave the classroom.",
        "portrait": {
          "src": "/leadership/anisha-panday-joshi.webp",
          "alt": "Studio portrait of Ms. Anisha Panday Joshi, Principal of NAMI International School, hands clasped in an olive and red patterned sari over a red blouse against a mottled blue-grey backdrop.",
          "width": 1154,
          "height": 1600
        }
      },
      {
        "name": "Mr. Philip Badikar Hilario",
        "title": "A Level Principal, NAMI College",
        "brief": "A Level Principal at NAMI College with over 21 years of expertise in business and accounting education. Leads academic coordination, Cambridge curriculum implementation, and student development.",
        "bio": "Mr. Philip Badikar Hilario is an experienced educator and academic administrator with over 21 years of expertise in business and accounting education. As A Level Principal at NAMI College, he leads academic coordination, curriculum implementation, and student development, ensuring high academic standards and promoting a culture of excellence.\n\nMr. Hilario has taught Business and Accounting at A Level across several reputed institutions in Nepal, consistently demonstrating strong leadership, subject expertise, and a passion for student-centred learning. His dedication to academic excellence and institutional growth is reflected in his ability to build effective teaching teams, introduce best practices in pedagogy, and mentor students toward both academic and professional success.\n\nHe holds international qualifications, including an LCCI Level 3 certification in Advanced Business Calculations, and is currently pursuing the ACCA (UK), a globally recognized credential in accounting and finance. These qualifications enhance his analytical and leadership capabilities, enabling evidence-based decision-making and aligning academic delivery with global best practices.",
        "portrait": {
          "src": "/leadership/philip-badikar-hilario.webp",
          "alt": "Studio portrait of Mr. Philip Badikar Hilario, A Level Principal at NAMI College, arms folded in a charcoal suit and black tie against a mottled blue-grey backdrop.",
          "width": 1084,
          "height": 1451
        }
      }
    ]
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
