<?php
/**
 * NAMI CMS — NAMI International School page
 *
 * Requires the "NAMI CMS — Core engine" snippet (version with nested lists).
 * Adds a "School" menu to the WordPress sidebar with one sub-menu per section
 * of the /institutions/school page.
 *
 * Field keys must match src/lib/cms/pages/school/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$testimonials = function ( $title, $description ) use ( $image ) {
			return array(
				'title'       => $title,
				'description' => $description,
				'fields'      => array(
					'label'      => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
					'title'      => array( 'type' => 'text', 'label' => 'Title' ),
					'items'      => array(
						'type'        => 'repeater',
						'label'       => 'Testimonials',
						'item_label'  => 'Testimonial',
						'title_field' => 'name',
						'fields'      => array(
							'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
							'name'     => array( 'type' => 'text', 'label' => 'Name' ),
							'role'     => array( 'type' => 'text', 'label' => 'Role / class', 'help' => 'e.g. "Grade 5" or "Parent of …".' ),
							'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
						),
					),
					'emptyState' => array( 'type' => 'text', 'label' => 'Text shown when there are no testimonials' ),
				),
			);
		};

		$band = function ( $title, $description ) use ( $image ) {
			return array(
				'title'       => $title,
				'description' => $description,
				'fields'      => array(
					'tabLabel' => array( 'type' => 'text', 'label' => 'Tab label' ),
					'body'     => array( 'type' => 'textarea', 'label' => 'Introduction', 'rows' => 5 ),
					'notes'    => array( 'type' => 'lines', 'label' => 'Highlights (ticked list)', 'rows' => 8, 'help' => 'One highlight per line.' ),
					'streams'  => array(
						'type'        => 'repeater',
						'label'       => 'Cards (grade groups / streams)',
						'item_label'  => 'Card',
						'title_field' => 'name',
						'fields'      => array(
							'name'          => array( 'type' => 'text', 'label' => 'Title' ),
							'note'          => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
							'photo'         => $image( 'Photo' ),
							'subjects'      => array( 'type' => 'lines', 'label' => 'Subjects (shown as tags)', 'help' => 'One subject per line. Used only when the card has no subject combinations below.' ),
							'subjectGroups' => array(
								'type'        => 'repeater',
								'label'       => 'Subject combinations (optional)',
								'item_label'  => 'Combination',
								'title_field' => 'title',
								'help'        => 'Shown as Track A, Track B, … columns. Leave empty to show the subject tags instead.',
								'fields'      => array(
									'title'    => array( 'type' => 'text', 'label' => 'Combination name' ),
									'subjects' => array( 'type' => 'lines', 'label' => 'Subjects', 'help' => 'One subject per line.' ),
								),
							),
						),
					),
				),
			);
		};

		$pages['school'] = array(
			'title'      => 'NAMI International School',
			'menu_title' => 'School',
			'icon'       => 'dashicons-welcome-learn-more',
			'position'   => 3.3,
			'path'       => '/institutions/school',
			'sections'   => array(

				'hero'          => array(
					'title'       => 'Hero',
					'description' => 'Title, intro text, button and the slideshow at the top of the page.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'standfirst' => array( 'type' => 'textarea', 'label' => 'Intro text' ),
						'button'     => array( 'type' => 'link', 'label' => 'Button' ),
						'slides'     => array(
							'type'        => 'repeater',
							'label'       => 'Slideshow images',
							'item_label'  => 'Slide',
							'title_field' => 'image',
							'fields'      => array(
								'image' => $image( 'Image', 'Wide landscape photos work best (about 1500 × 1000 px).' ),
							),
						),
					),
				),

				'why'           => array(
					'title'       => 'Why Study at NAMI',
					'anchor'      => 'why-school',
					'description' => 'The introduction with a "Read More" toggle.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'intro' => array( 'type' => 'textarea', 'label' => 'First paragraph (always shown)', 'rows' => 6 ),
						'more'  => array( 'type' => 'textarea', 'label' => 'Second paragraph (shown on "Read More")', 'rows' => 6, 'help' => 'Leave empty to hide the Read More button.' ),
					),
				),

				'principal'     => array(
					'title'       => 'Principal\'s Message',
					'anchor'      => 'principal',
					'description' => 'The message with the portrait card on the right.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Message', 'rows' => 16 ),
						'name'       => array( 'type' => 'text', 'label' => 'Name' ),
						'title'      => array( 'type' => 'text', 'label' => 'Job title' ),
						'portrait'   => $image( 'Portrait' ),
					),
				),

				'approach'      => array(
					'title'       => 'Approach & Values',
					'anchor'      => 'approach-values',
					'description' => 'The educational approach cards and the school values.',
					'fields'      => array(
						'title'             => array( 'type' => 'text', 'label' => 'Approach title' ),
						'description'       => array( 'type' => 'textarea', 'label' => 'Approach description' ),
						'items'             => array(
							'type'        => 'repeater',
							'label'       => 'Approach cards',
							'item_label'  => 'Card',
							'title_field' => 'title',
							'fields'      => array(
								'title'       => array( 'type' => 'text', 'label' => 'Title' ),
								'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
							),
						),
						'valuesLabel'       => array( 'type' => 'text', 'label' => 'Values small label' ),
						'valuesTitle'       => array( 'type' => 'text', 'label' => 'Values title' ),
						'valuesDescription' => array( 'type' => 'textarea', 'label' => 'Values description' ),
						'values'            => array(
							'type'        => 'repeater',
							'label'       => 'Values',
							'item_label'  => 'Value',
							'title_field' => 'name',
							'help'        => 'Each value gets the next colour in the school palette.',
							'fields'      => array(
								'name'    => array( 'type' => 'text', 'label' => 'Name' ),
								'meaning' => array( 'type' => 'textarea', 'label' => 'Meaning', 'rows' => 2 ),
							),
						),
					),
				),

				'admission'     => array(
					'title'       => 'Admission Process',
					'anchor'      => 'admissions',
					'description' => 'The numbered admission steps (shown as diamonds on desktop). Seven steps fit best.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'steps'       => array(
							'type'        => 'repeater',
							'label'       => 'Steps (in order)',
							'item_label'  => 'Step',
							'title_field' => 'title',
							'fields'      => array(
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2, 'help' => 'Keep it short — about 10 words fit inside the diamond.' ),
							),
						),
					),
				),

				'academics'     => array(
					'title'       => 'Academics — Intro',
					'anchor'      => 'academics',
					'description' => 'Heading above the two tabs. The tab contents are under "Grades I–VII" and "+2 Programme".',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label (optional)' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
					),
				),

				'primaryBand'   => $band( 'Grades I–VII', 'The first tab. The Learning Collaborators and FAQs below it belong to this tab.' ),
				'plusTwoBand'   => $band( '+2 Programme', 'The second tab. The Clubs section shows below it.' ),

				'collaborators' => array(
					'title'       => 'Learning Collaborators',
					'anchor'      => 'collaborators',
					'description' => 'Partner carousel shown under the Grades I–VII tab.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Partners',
							'item_label'  => 'Partner',
							'title_field' => 'name',
							'fields'      => array(
								'name'             => array( 'type' => 'text', 'label' => 'Name' ),
								'tagline'          => array( 'type' => 'text', 'label' => 'Tagline' ),
								'logo'             => $image( 'Logo', 'Transparent PNG works best.' ),
								'shortDescription' => array( 'type' => 'textarea', 'label' => 'Short description (on the card)', 'rows' => 2 ),
								'description'      => array( 'type' => 'textarea', 'label' => 'Full description (in the popup)', 'rows' => 4 ),
							),
						),
					),
				),

				'faq'           => array(
					'title'       => 'FAQs',
					'anchor'      => 'faqs',
					'description' => 'Questions and answers shown under the Grades I–VII tab.',
					'fields'      => array(
						'titleLead'   => array( 'type' => 'text', 'label' => 'Title — first part', 'help' => 'The title is shown as three parts: normal, red, green.' ),
						'titleAccent' => array( 'type' => 'text', 'label' => 'Title — red part' ),
						'titleTail'   => array( 'type' => 'text', 'label' => 'Title — green part' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'highlights'  => array(
							'type'        => 'repeater',
							'label'       => 'Highlight cards',
							'item_label'  => 'Highlight',
							'title_field' => 'title',
							'fields'      => array(
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 2 ),
							),
						),
						'helpTitle'   => array( 'type' => 'text', 'label' => 'Help box title' ),
						'helpText'    => array( 'type' => 'text', 'label' => 'Help box text' ),
						'phoneLabel'  => array( 'type' => 'text', 'label' => 'Call button text' ),
						'phoneNumber' => array( 'type' => 'text', 'label' => 'Phone number to call', 'help' => 'e.g. +977014917441' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Questions',
							'item_label'  => 'Question',
							'title_field' => 'question',
							'fields'      => array(
								'question' => array( 'type' => 'text', 'label' => 'Question' ),
								'answer'   => array( 'type' => 'textarea', 'label' => 'Answer', 'rows' => 4 ),
							),
						),
					),
				),

				'facilities'    => array(
					'title'       => 'Facilities',
					'anchor'      => 'day',
					'description' => 'The green section listing facilities; each one opens to show its text.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Facilities',
							'item_label'  => 'Facility',
							'title_field' => 'title',
							'fields'      => array(
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
								'photo' => $image( 'Photo' ),
							),
						),
					),
				),

				'parentVoices'  => $testimonials( 'Parent & Student Voices', 'Testimonials shown while the Grades I–VII tab is selected.' ),
				'plusTwoVoices' => $testimonials( '+2 Graduate Voices', 'Testimonials shown while the +2 tab is selected.' ),

				'notices'       => array(
					'title'       => 'Notices',
					'anchor'      => 'notices',
					'description' => 'Heading above the school notices. The notices themselves are managed on the Notices page.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text' ),
						'emptyState'  => array( 'type' => 'textarea', 'label' => 'Text shown when there are no notices', 'rows' => 2 ),
					),
				),

				'seo'           => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "NAMI International School | Grades I–VII & +2 Science and Management",
    "description": "NAMI International School offers progressive education for Grades I–VII under the Nepal Government's National Curriculum and NEB +2 in Science and Management at Gokarneshwor-7, Kathmandu."
  },
  "hero": {
    "title": "NAMI International School",
    "standfirst": "Nurturing Minds, Shaping Tomorrow Together! From Grades I through VII and +2 in Science and Management.",
    "button": {
      "label": "Apply for Admission",
      "href": "/admissions"
    },
    "slides": [
      {
        "image": {
          "src": "/hero/contact/contact-hero.jpg",
          "alt": "NAMI International School campus and student life.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/gallery/gallery-hero.jpg",
          "alt": "NAMI International School learning environment and activities.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/notices/notices-hero.jpg",
          "alt": "NAMI International School classroom and academic sessions.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/documents/documents-hero.jpg",
          "alt": "NAMI International School student activities and sports.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/faculty/faculty-hero.jpg",
          "alt": "NAMI International School events and community.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/32.jpg",
          "alt": "NAMI International School facilities and grounds.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/33.jpg",
          "alt": "NAMI International School cultural and creative programmes.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/34.jpg",
          "alt": "NAMI International School academic excellence and practical sessions.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/35.jpg",
          "alt": "NAMI International School student leadership and collaboration.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/36.jpg",
          "alt": "NAMI International School holistic education and celebration.",
          "width": 1500,
          "height": 1000
        }
      }
    ]
  },
  "why": {
    "label": "NAMI International School",
    "title": "Why Study at NAMI?",
    "intro": "At NAMI International School, we believe education is about more than acquiring knowledge. It is about helping students understand the world, discover their strengths, build meaningful relationships, and grow into confident, responsible individuals. We create an environment where students are encouraged to ask questions, explore ideas, work with others, think critically, and connect what they learn with real-life experiences.",
    "more": "Our educational approach is grounded in progressive education, with an emphasis on meaningful learning, student participation, inclusion, values, creativity, and personal growth. Through classroom learning, practical activities, creative pursuits, sports, community engagement, modern science and computer laboratories, and student well-being support, we help learners develop the confidence and competencies to succeed in higher education and life."
  },
  "principal": {
    "label": "From the Principal",
    "paragraphs": [
      "My personal and professional commitment at NAMI International School is to guide the growth of students and ensure a nurturing environment for all.",
      "At NAMI International School, we hold a deep conviction that education should be a catalyst for bringing out the best in every child. We work towards enhancing knowledge, skill, ability, and the overall potential of individuals to become successful and ready for a world that never ceases to change.",
      "As my understanding of the world deepens, so does my conviction that we need to raise a generation of empathetic/compassionate individuals.",
      "Therefore, it is crucial to instil a culture of care from an early age, both within the household and the school environment. This entails acknowledging parents as essential partners in moulding the educational path of the child.",
      "Keeping the above in mind, our school curriculum is crafted through extensive research and is designed to address various facets of development—cognitive, social-emotional, physical, and creative. We aim to instill a genuine love for learning in our students and therefore embrace each child as an individual with unique talent and potential.",
      "Academics at NAMI International School are not just about grades; Our focus is on creating an inclusive and caring community where every child feels seen, heard, and supported in all manner of ways.",
      "Together with my team, we are dedicated to creating a centre of excellence in education, empowering students to become resilient lifelong learners and positive agents of change. As someone deeply passionate about enhancing the learning experiences of young minds and transforming children's lives through the power of education, I carry this devotion into my role as the Principal at NAMI International School."
    ],
    "name": "Ms. Anisha Panday Joshi",
    "title": "Principal, NAMI International School",
    "portrait": {
      "src": "/leadership/anisha-panday-joshi.webp",
      "alt": "Studio portrait of Ms. Anisha Panday Joshi, Principal of NAMI International School, hands clasped in an olive and red patterned sari over a red blouse against a mottled blue-grey backdrop.",
      "width": 1154,
      "height": 1600
    }
  },
  "approach": {
    "title": "Our Educational Approach to Learning",
    "description": "At NAMI International School, students are active participants in their learning. Teachers guide, support, and challenge students while creating opportunities to explore ideas, develop understanding, collaborate, and make meaningful connections.",
    "items": [
      {
        "title": "Learning Through Exploration",
        "description": "Students learn by asking questions, investigating ideas, researching, experimenting, and discovering connections."
      },
      {
        "title": "Learning Through Collaboration",
        "description": "Students work with peers, teachers, parents, and the wider community to develop communication, teamwork, and interpersonal skills."
      },
      {
        "title": "Learning Through Application",
        "description": "Learning is connected to practical experiences and real-life situations so that students can understand how knowledge can be used beyond the classroom."
      },
      {
        "title": "Developing Critical Thinkers",
        "description": "Students are encouraged to analyse, reason, question, solve problems, and make thoughtful decisions."
      },
      {
        "title": "Encouraging Creativity",
        "description": "Students are given opportunities to express ideas, experiment, create, and explore different ways of approaching challenges."
      },
      {
        "title": "Building Confidence",
        "description": "Students are encouraged to share their ideas, participate actively, learn from mistakes, and take increasing responsibility for their learning."
      },
      {
        "title": "Inclusion and Belonging",
        "description": "We recognise that every student is different. We strive to create a caring environment where students with different interests, learning needs, backgrounds, and abilities feel valued and included."
      },
      {
        "title": "Intrinsic Motivation",
        "description": "Nurturing internal motivation for learning."
      }
    ],
    "valuesLabel": "Guiding Principles",
    "valuesTitle": "Our Values",
    "valuesDescription": "Our school community is guided by core values that shape everyday learning, character formation, and meaningful relationships.",
    "values": [
      {
        "name": "Respect",
        "meaning": "We respect ourselves, others, different perspectives, and our shared environment."
      },
      {
        "name": "Kindness",
        "meaning": "We encourage students to treat others with care and consideration."
      },
      {
        "name": "Honesty",
        "meaning": "We value integrity and encourage students to be truthful and responsible."
      },
      {
        "name": "Responsibility",
        "meaning": "We help students understand that their choices and actions matter."
      },
      {
        "name": "Inclusion",
        "meaning": "We celebrate differences and work to ensure that every student feels valued and included."
      },
      {
        "name": "Curiosity",
        "meaning": "We encourage students to question, explore, and keep learning."
      }
    ]
  },
  "admission": {
    "label": "",
    "title": "Admission Process",
    "description": "The step-by-step admissions procedure from registration to final enrolment.",
    "steps": [
      {
        "title": "Registration",
        "body": "Register your child's name at reception or through our online portal."
      },
      {
        "title": "Orientation",
        "body": "Attend the Principal's academic briefing and a guided school tour."
      },
      {
        "title": "Application",
        "body": "Obtain the official application form from admissions or online."
      },
      {
        "title": "Application Submission",
        "body": "Submit forms to schedule placement assessment and family interview."
      },
      {
        "title": "Notification",
        "body": "Receive your child's admission decision by phone or email."
      },
      {
        "title": "Admission Confirmation",
        "body": "Confirm your seat upon acceptance letter and deposit submission."
      },
      {
        "title": "Open House",
        "body": "Attend the Open House to receive student handbooks and essentials."
      }
    ]
  },
  "academics": {
    "label": "",
    "title": "Academics",
    "description": "A progressive education approach grounded in meaningful learning, student participation, inclusion, values, creativity, and personal growth."
  },
  "primaryBand": {
    "tabLabel": "Grades I–VII",
    "body": "NAMI International School offers education from Grades I to VII, following the Nepal Government's National Curriculum through a progressive approach to teaching and learning. Our Grades I to VII programme provides students with strong academic foundations while giving them opportunities to explore, create, collaborate, communicate, and apply what they learn.",
    "notes": [
      "Curriculum across Languages, Mathematics, Science & Tech, Serophero, Samajik Shikshya, Mero Gokarneshwor, Positive Living, HPE & Creative Arts",
      "English is the primary language of instruction with a strong emphasis on Nepali, plus Mandarin Chinese and Sanskrit language learning",
      "Active learning through morning circles, exploration, research, projects, experiments, problem-solving, reflection, and real-world application",
      "Continuous assessment through classwork, assignments, projects, practical activities, and interactive engagement",
      "Learning collaborations with 3Di School (Design & Tech), Play Nepal (Movement & Wellness), UnMath (Joyful Math), Mero Coding (Coding & Computational Thinking), and Samatva Wellness",
      "Co-curricular activities in Art & Craft, Music, Dance, Public Speaking, Football, Basketball, Karate, Cricksal, Swimming, Table Tennis & Badminton",
      "Curriculum-related educational trips (2 per term in Kathmandu Valley) plus optional national and international experiential learning trips",
      "Strong parent partnership with parent representative roles, guest speaking, classroom support, and regular communication"
    ],
    "streams": [
      {
        "name": "Grades I - III",
        "note": "Foundational academic programme developing early literacy, numeracy, positive living, local knowledge, and foreign languages.",
        "photo": {
          "src": "/sections/general/9.jpg",
          "alt": "Primary students exploring books and interactive materials in the school library.",
          "width": 1600,
          "height": 1200
        },
        "subjects": [
          "English Language Arts",
          "Nepali Language Arts",
          "Mathematics",
          "Serophero",
          "Mero Gokarneshwor",
          "Positive Living",
          "Mandarin Chinese",
          "Sanskrit"
        ],
        "subjectGroups": []
      },
      {
        "name": "Grades IV - VII",
        "note": "Comprehensive progressive curriculum integrating core academics, scientific inquiry, social studies, creative arts, and continuous assessment.",
        "photo": {
          "src": "/sections/general/10.jpg",
          "alt": "Middle school students learning collaboratively in interactive digital classrooms.",
          "width": 1600,
          "height": 1066
        },
        "subjects": [
          "English Language Arts",
          "Nepali Language Arts",
          "Mathematics",
          "Science and Technology",
          "Samajik Shikshya",
          "Mero Gokarneshwor",
          "Positive Living",
          "Health, Physical Education & Creative Arts",
          "Mandarin Chinese",
          "Sanskrit"
        ],
        "subjectGroups": []
      }
    ]
  },
  "plusTwoBand": {
    "tabLabel": "Grades XI and XII (+2)",
    "body": "NAMI's Secondary School offers Grades XI and XII (+2) programmes in Management and Science under the National Examination Board (NEB). The programme combines academic learning with practical experiences, career guidance, internships, competitions, educational visits, and national and international exposure.",
    "notes": [
      "In-house well-equipped Biology, Chemistry, and Physics laboratories with skilled laboratory technicians",
      "Career counselling and guidance helping students explore pathways and prepare for higher education",
      "Internship opportunities, hotel visits, biology excursions, industry visits, and educational tours",
      "Student clubs: Sports Club, Art and Literature Club, Event Management Club, Social Service Club, and Science & Technology Club",
      "Sports competitions in futsal, basketball, table tennis, chess, carrom, shot put, tug of war, and annual Sports Meet",
      "National and international exposure trips fostering independence, adaptability, and cultural understanding",
      "Modern facilities: Air-conditioned classrooms, 250+ seat auditorium, computer labs, library, infirmary, and school canteen"
    ],
    "streams": [
      {
        "name": "Science Stream",
        "note": "Offers Biology Group (A), Biology Group (B), and Physical Group (Computer Science) with well-equipped in-house laboratories and skilled technicians applying theory to practice.",
        "photo": {
          "src": "/sections/general/16.jpg",
          "alt": "NAMI Science Stream laboratory with chemistry workstations and apparatus.",
          "width": 1280,
          "height": 853
        },
        "subjects": [],
        "subjectGroups": [
          {
            "title": "Biology Group (A)",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Mathematics",
              "Physics",
              "Chemistry",
              "Biology"
            ]
          },
          {
            "title": "Biology Group (B)",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Social Studies",
              "Physics",
              "Chemistry",
              "Biology"
            ]
          },
          {
            "title": "Physical Group (Computer)",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Mathematics",
              "Physics",
              "Chemistry",
              "Computer Science"
            ]
          }
        ]
      },
      {
        "name": "Management Stream",
        "note": "Offers Business Studies, Computer Science, and Hotel Management groups providing a solid foundational understanding of management facts and principles.",
        "photo": {
          "src": "/sections/general/15.jpg",
          "alt": "NAMI Management stream classroom and facilities.",
          "width": 1280,
          "height": 853
        },
        "subjects": [],
        "subjectGroups": [
          {
            "title": "Business Studies",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Social Studies",
              "Accounting",
              "Economics",
              "Business Studies"
            ]
          },
          {
            "title": "Computer Science",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Social Studies / Mathematics",
              "Accounting",
              "Economics",
              "Computer Science"
            ]
          },
          {
            "title": "Hotel Management",
            "subjects": [
              "Comp. Nepali",
              "Comp. English",
              "Social Studies",
              "Accounting",
              "Economics",
              "Hotel Management"
            ]
          }
        ]
      }
    ]
  },
  "collaborators": {
    "label": "Partners in Learning",
    "title": "Our Learning Collaborators",
    "description": "We collaborate with premier specialized learning partners to complement classroom education and enrich student discovery.",
    "items": [
      {
        "name": "3Di School",
        "tagline": "Design, Software & Emerging Tech",
        "shortDescription": "Hands-on design and technology platform exploring creativity and software through practical projects.",
        "description": "3Di School provides a hands-on design and technology platform where students explore creativity, software, and emerging technologies through practical projects.",
        "logo": {
          "src": "/logos/collaborators/3di.png",
          "alt": "3Di School logo",
          "width": 180,
          "height": 64
        }
      },
      {
        "name": "Play Nepal",
        "tagline": "Movement, Focus & Physical Confidence",
        "shortDescription": "Structured physical movement and team habits promoting active fitness and emotional well-being.",
        "description": "Play Nepal helps students develop focus, physical confidence, teamwork, and active habits through joyful and structured movement. Their sessions also support students' emotional well-being and confidence.",
        "logo": {
          "src": "/logos/collaborators/play-nepal.png",
          "alt": "Play Nepal logo",
          "width": 180,
          "height": 64
        }
      },
      {
        "name": "UnMath",
        "tagline": "Creative & Experiential Mathematics",
        "shortDescription": "Joyful experiential math education connecting core concepts to creativity and real-world situations.",
        "description": "The UnMath Programme helps students experience mathematics with greater joy and confidence by connecting mathematical concepts to creativity and real-life situations. It supports engaging and meaningful math learning.",
        "logo": {
          "src": "/logos/collaborators/unmath.png",
          "alt": "UnMath logo",
          "width": 180,
          "height": 64
        }
      },
      {
        "name": "Mero Coding",
        "tagline": "Coding & Computational Thinking",
        "shortDescription": "Foundational coding and problem-solving skills empowering students to build interactive tech projects.",
        "description": "Mero Coding introduces students to the fundamentals of coding and computational thinking. It helps students develop problem-solving, logical thinking, and creativity through coding activities. Students learn to create simple projects while building confidence with technology.",
        "logo": {
          "src": "/logos/collaborators/mero-coding.png",
          "alt": "Mero Coding logo",
          "width": 180,
          "height": 64
        }
      },
      {
        "name": "Samatva Wellness",
        "tagline": "Mindfulness & Holistic Well-Being",
        "shortDescription": "Holistic wellness and mindfulness sessions nurturing mental and emotional balance.",
        "description": "NAMI International School collaborates with Samatva Wellness to support student well-being through regular wellness classes and workshops.",
        "logo": {
          "src": "/logos/collaborators/samatva-wellness.png",
          "alt": "Samatva Wellness logo",
          "width": 180,
          "height": 64
        }
      }
    ]
  },
  "faq": {
    "titleLead": "Answers to",
    "titleAccent": "your most",
    "titleTail": "common questions",
    "description": "Everything you need to know about our progressive educational philosophy, curriculum, daily routines, healthy meals, and student well-being at NAMI International School.",
    "highlights": [
      {
        "title": "Stress-Free Foundation",
        "body": "Continuous formative assessment without high-stakes exam pressure through Grade V."
      },
      {
        "title": "100% In-House Vegetarian Meals",
        "body": "Nutritionally balanced, freshly prepared hot meals and wholesome snacks daily."
      }
    ],
    "helpTitle": "Still have questions?",
    "helpText": "Our admissions team is here to help.",
    "phoneLabel": "Call Admissions: +977-01-4917441/42/43/44",
    "phoneNumber": "+977014917441",
    "items": [
      {
        "question": "What is the philosophy of the school?",
        "answer": "The school follows a progressive education approach, emphasizing holistic development for each individual."
      },
      {
        "question": "What will the role of parents at NAMI International School be?",
        "answer": "Parents are encouraged to take on roles such as class representatives and guest speakers, and occasionally accompany students on trips and picnics."
      },
      {
        "question": "Which curriculum do Grades I-VII follow?",
        "answer": "NAMI International School has adopted the Nepal Government's curriculum to align with progressive education principles. The school implements this curriculum using the progressive pedagogical approach, emphasising creative thinking and inquiry-based learning."
      },
      {
        "question": "Does NAMI International School have a uniform?",
        "answer": "We celebrate diversity and acknowledge each student's individuality, we therefore do not have a uniform, instead, we have a dress code in place to ensure a sense of decorum. However, the school does have a track suit and jersey for students that is optional to wear on regular days but is mandatory on days they have field trips."
      },
      {
        "question": "Why doesn't NAMI International School have assessments until grade V?",
        "answer": "Our approach to education is centered on preparing children for life, not just examinations. We believe in empowering students to take ownership of their learning and construct knowledge actively. Continuous assessments in the form of assignments, projects, and interactive engagements are used to evaluate their understanding and application of concepts in real-life situations."
      },
      {
        "question": "Does NAMI International School provide meals to the students?",
        "answer": "Yes, we provide 3 vegetarian meals (breakfast, lunch and snack). We have a canteen for Grade 11 and 12 students."
      },
      {
        "question": "Why is NAMI International School’s cafeteria vegetarian?",
        "answer": "We prioritize healthy eating and avoid the challenges associated with managing a large-scale meat supply, which poses hygiene risks. Our commitment to the nutritional well-being of children is uncompromising."
      },
      {
        "question": "What are the sports facilities at NAMI International School?",
        "answer": "We offer physical education classes, along with activities like table tennis, basketball, badminton, cricksal and football. Additionally, students get the opportunity to attend futsal and swimming lessons at a nearby public club."
      },
      {
        "question": "Does NAMI International School provide transportation?",
        "answer": "We have transport facilities in various areas."
      }
    ]
  },
  "facilities": {
    "label": "School & Learning Environment",
    "title": "Facilities & Student Experience",
    "description": "NAMI International School provides facilities designed to support learning, creativity, technology, physical development, and student well-being.",
    "items": [
      {
        "title": "School Library",
        "body": "A well-resourced school library for study, research, and leisure reading, with dedicated classroom libraries in the primary grades.",
        "photo": {
          "src": "/sections/general/8.jpg",
          "alt": "A well-resourced school library for study, research, and leisure reading.",
          "width": 1280,
          "height": 960
        }
      },
      {
        "title": "Science Laboratories",
        "body": "In-house, well-equipped Biology, Chemistry, and Physics laboratories staffed with skilled technicians to apply scientific theories to practical experiments.",
        "photo": {
          "src": "/sections/nami/nami-school-science-lab.jpg",
          "alt": "Students in white lab coats and safety goggles running a titration into a conical flask at a laboratory bench, reagent bottles ranked on the shelves behind them.",
          "width": 1000,
          "height": 666
        }
      },
      {
        "title": "Computer Laboratories",
        "body": "Modern computer laboratories in both junior and senior wings, each furnished with computer workstations on high-speed internet.",
        "photo": {
          "src": "/sections/general/14.jpg",
          "alt": "Modern computer laboratories equipped with high-speed workstations for interactive learning.",
          "width": 1280,
          "height": 960
        }
      },
      {
        "title": "Digital Classrooms & Interactive Boards",
        "body": "Interactive smart boards in every classroom used as an everyday active teaching tool, with air-conditioned spaces for comfortable learning year-round.",
        "photo": {
          "src": "/sections/nami/nami-school-digital-classroom.jpeg",
          "alt": "A teacher mid-lesson at a wall-mounted interactive board, presenting a red quadrilateral she has drawn on its touchscreen.",
          "width": 1125,
          "height": 1066
        }
      },
      {
        "title": "250+ Seat Auditorium",
        "body": "A fully equipped auditorium with a 250+ seat capacity and quality acoustic sound system for school assemblies, cultural fests, presentations, and events.",
        "photo": {
          "src": "/sections/general/12.jpg",
          "alt": "A fully equipped 250+ seat auditorium with acoustic sound system for assemblies, cultural fests, and events.",
          "width": 1600,
          "height": 811
        }
      },
      {
        "title": "Sports Facilities & Courts",
        "body": "Indoor spaces for table tennis and badminton, outdoor facilities for mini-football, basketball, and cricksal, plus swimming and futsal coaching.",
        "photo": {
          "src": "/sections/general/11.jpg",
          "alt": "Indoor and outdoor sports facilities, courts, and athletic coaching at NAMI.",
          "width": 1600,
          "height": 1066
        }
      },
      {
        "title": "Cafeteria",
        "body": "Three nutritious, hygienic vegetarian meals (breakfast, lunch, and snack) provided for primary students, with a dedicated canteen for Grades 11 and 12.",
        "photo": {
          "src": "/sections/nami/nami-school-cafeteria.jpg",
          "alt": "The school cafeteria, wooden tables and chairs ranked across a polished floor beside a glazed partition, with a stainless steel serving counter and a water dispenser against the orange wall.",
          "width": 1000,
          "height": 1333
        }
      },
      {
        "title": "Infirmary & Nursing Support",
        "body": "A fully equipped school infirmary with qualified nursing staff on duty throughout school hours to ensure student health and well-being.",
        "photo": {
          "src": "/sections/nami/nami-school-infirmity.jpg",
          "alt": "The school infirmary, two single beds made up with pale blue linen and folded blankets beneath a wall fan and a curtained window.",
          "width": 1000,
          "height": 1333
        }
      },
      {
        "title": "Counselling Services",
        "body": "Dedicated psycho-social counselling and career guidance to ensure every child feels safe, respected, heard, and supported in their personal and academic growth.",
        "photo": {
          "src": "/sections/nami/nami-school-cafeteria.jpg",
          "alt": "Students and teachers collaborating in a welcoming campus environment.",
          "width": 1000,
          "height": 1333
        }
      },
      {
        "title": "School Transportation",
        "body": "Safe and reliable bus service covering extensive pickup and drop-off routes across Kathmandu Valley.",
        "photo": {
          "src": "/sections/general/13.jpg",
          "alt": "Safe and reliable NAMI International School transportation fleet covering extensive routes across Kathmandu.",
          "width": 1280,
          "height": 483
        }
      }
    ]
  },
  "parentVoices": {
    "label": "",
    "title": "Parent & Student Voices",
    "emptyState": "Stories and experiences from our students and families appear here as they are shared.",
    "items": [
      {
        "quote": "We are truly happy with our child’s experience at school. The teachers are so warm, caring, and approachable, and he genuinely looks forward to going to school each day. It has brought out his confidence and helped him grow in so many ways. He says the food is yummy, and the ECAs are wonderful too!",
        "name": "Dayana Shakya, PhD",
        "role": "Parent of Adhyant Bhatta (Grade 2) • Associate Professor, Kathmandu Medical College",
        "portrait": {
          "src": "/testimonials/parents/Dayana Shakya.jpeg",
          "alt": "Dayana Shakya, PhD",
          "width": 334,
          "height": 363
        }
      },
      {
        "quote": "We learn from our own mistakes. Our teachers help us understand our mistakes with kindness, so we can do better next time.",
        "name": "Evana Khanal",
        "role": "Grade 4",
        "portrait": {
          "src": "/testimonials/school/evana khanal.png",
          "alt": "Evana Khanal",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "Associating with NAMI has been a great experience. I have noticed remarkable growth in my child’s confidence, communication, and essential life skills beyond regular academics.",
        "name": "Arun Poudyal",
        "role": "Arushi Poudyal’s Parent",
        "portrait": {
          "src": "/testimonials/parents/Arun Poudyal.jpeg",
          "alt": "Arun Poudyal",
          "width": 344,
          "height": 351
        }
      },
      {
        "quote": "At NAMI, we learn through fun activities. In Science, we played football to understand force, which was my best learning experience.",
        "name": "Hriden Jung Karki",
        "role": "Grade 5",
        "portrait": {
          "src": "/testimonials/school/Hriden Jung Karki.png",
          "alt": "Hriden Jung Karki",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "Being part of the NAMI community has been truly rewarding. We value the supportive teachers, welcoming environment, and strong partnership fostering our child’s growth and well-being.",
        "name": "Mr. Milan Phuyal",
        "role": "Parent of Sanvika Phuyal",
        "portrait": {
          "src": "/testimonials/parents/Milan Phuyal.jpeg",
          "alt": "Mr. Milan Phuyal",
          "width": 257,
          "height": 292
        }
      },
      {
        "quote": "At NAMI, I learned to adapt to new challenges and become much more confident through public speaking and teamwork.",
        "name": "Himanshu Raya",
        "role": "Grade 5",
        "portrait": {
          "src": "/testimonials/school/Himanshu Raya.png",
          "alt": "Himanshu Raya",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "Enrolling our kids at NAMI has proved to be our best decision. The kids love interacting with their teachers in academics and ECA activities, and have become noticeably confident and vocal.",
        "name": "Pooja Shrestha",
        "role": "Mother of Satwik Ghimire, Grade 7 and Saarvi Ghimire, Grade 3",
        "portrait": {
          "src": "/testimonials/parents/Pooja Shrestha.jpeg",
          "alt": "Pooja Shrestha",
          "width": 189,
          "height": 255
        }
      },
      {
        "quote": "I will never forget visiting Namgyal School during Environment Week, where I learned to segregate, reuse, and recycle different types of waste.",
        "name": "Aarushi Poudyal",
        "role": "Grade 5",
        "portrait": {
          "src": "/testimonials/school/Aarushi Poudyal.png",
          "alt": "Aarushi Poudyal",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "It gives us immense pride to see Yuvan thriving at NAMI. In a short time, we have witnessed remarkable growth in his confidence, curiosity, and overall learning environment.",
        "name": "Enu Shrestha (Yuvan Krien Shrestha)",
        "role": "Parent, Grade 1",
        "portrait": {
          "src": "/testimonials/parents/Enu shrestha.jpeg",
          "alt": "Enu Shrestha (Yuvan Krien Shrestha)",
          "width": 219,
          "height": 214
        }
      }
    ]
  },
  "plusTwoVoices": {
    "label": "",
    "title": "From Our +2 Graduates",
    "emptyState": "Testimonials and experiences from our +2 students and graduates appear here as they are shared.",
    "items": [
      {
        "quote": "My journey at NAMI has been a meaningful and memorable part of my academic life. The supportive environment, teacher guidance, friendships, and experiences helped me grow in confidence, knowledge, and skills. I am proud to be part of the NAMI family.",
        "name": "Nirakar Bhandari",
        "role": "Batch of 2026",
        "portrait": {
          "src": "/testimonials/plus-two/Nirakar Bhandari.jpeg",
          "alt": "Nirakar Bhandari",
          "width": 301,
          "height": 334
        }
      },
      {
        "quote": "My two years at NAMI were filled with learning, friendships, and unforgettable memories. From lab classes and Holi celebrations to leading the Arts and Literature Club, every experience helped me grow in confidence and gratitude.",
        "name": "Avni Adhikari",
        "role": "Batch of 2026",
        "portrait": {
          "src": "/testimonials/plus-two/Avni Adhikari.png",
          "alt": "Avni Adhikari",
          "width": 1175,
          "height": 1338
        }
      },
      {
        "quote": "My journey at NAMI has been a truly wonderful and memorable experience. The faculty members were very supportive, friendly, and understanding, always there whenever I needed guidance. The peaceful, green campus and the wonderful friends I made created memories that I will always cherish.",
        "name": "Yunisha Basnet",
        "role": "Management Stream (Class of 2026)",
        "portrait": {
          "src": "/testimonials/plus-two/Yunisha Shrestha.jpeg",
          "alt": "Yunisha Basnet",
          "width": 273,
          "height": 349
        }
      }
    ]
  },
  "notices": {
    "title": "Notice Board",
    "description": "Admission windows, examination dates, holidays and the standing notices that parents need in front of them.",
    "buttonLabel": "All School Notices",
    "emptyState": "There is no school notice standing right now. Everything the school publishes appears here and on the notice board."
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
