<?php
/**
 * NAMI CMS — NAMI College (A-Levels) page
 *
 * Requires the "NAMI CMS — Core engine" snippet (version with nested lists).
 * Adds an "A-Levels" menu to the WordPress sidebar with one sub-menu per
 * section of the /institutions/a-levels page.
 *
 * Field keys must match src/lib/cms/pages/a-levels/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['a-levels'] = array(
			'title'      => 'NAMI College (A-Levels)',
			'menu_title' => 'A-Levels',
			'icon'       => 'dashicons-awards',
			'position'   => 3.4,
			'path'       => '/institutions/a-levels',
			'sections'   => array(

				'hero'       => array(
					'title'       => 'Hero',
					'description' => 'Title, intro text, button and the slideshow at the top of the page.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'standfirst' => array( 'type' => 'textarea', 'label' => 'Intro text' ),
						'button'     => array( 'type' => 'link', 'label' => 'Button' ),
						'slides'     => array(
							'type'        => 'repeater',
							'label'       => 'Slideshow images',
							'item_label'  => 'Slide',
							'title_field' => 'image',
							'fields'      => array(
								'image' => $image( 'Image', 'Wide landscape photos work best (about 1500 × 1000 px).' ),
							),
						),
					),
				),

				'why'        => array(
					'title'       => 'Why A Levels',
					'anchor'      => 'why-a-levels',
					'description' => 'The introduction with a "Read More" toggle.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'intro' => array( 'type' => 'textarea', 'label' => 'First paragraph (always shown)', 'rows' => 6 ),
						'more'  => array( 'type' => 'textarea', 'label' => 'Second paragraph (shown on "Read More")', 'rows' => 6, 'help' => 'Leave empty to hide the Read More button.' ),
					),
				),

				'principal'  => array(
					'title'       => 'Principal\'s Message',
					'anchor'      => 'principal',
					'description' => 'The message with the portrait card on the right.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Message', 'rows' => 16 ),
						'name'       => array( 'type' => 'text', 'label' => 'Name' ),
						'title'      => array( 'type' => 'text', 'label' => 'Job title' ),
						'portrait'   => $image( 'Portrait' ),
					),
				),

				'cambridge'  => array(
					'title'       => 'The Qualification',
					'anchor'      => 'cambridge',
					'description' => 'The olive-green section with numbered cards that stack as you scroll.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'badge'       => array( 'type' => 'text', 'label' => 'Badge on each card', 'help' => 'Leave empty to hide.' ),
						'cards'       => array(
							'type'        => 'repeater',
							'label'       => 'Cards',
							'item_label'  => 'Card',
							'title_field' => 'title',
							'fields'      => array(
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 3 ),
							),
						),
					),
				),

				'subjects'   => array(
					'title'       => 'Subjects',
					'anchor'      => 'subjects',
					'description' => 'Streams (Science, Non-Science) and the pathway cards inside each.',
					'fields'      => array(
						'label'           => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'           => array( 'type' => 'text', 'label' => 'Title' ),
						'description'     => array( 'type' => 'textarea', 'label' => 'Description' ),
						'compulsoryLabel' => array( 'type' => 'text', 'label' => 'Tag next to compulsory subjects' ),
						'electivesLabel'  => array( 'type' => 'text', 'label' => 'Heading above electives' ),
						'streams'         => array(
							'type'        => 'repeater',
							'label'       => 'Streams',
							'item_label'  => 'Stream',
							'title_field' => 'label',
							'fields'      => array(
								'label'       => array( 'type' => 'text', 'label' => 'Stream name' ),
								'requirement' => array( 'type' => 'textarea', 'label' => 'Requirement note (bottom of each card)', 'rows' => 2 ),
								'pathways'    => array(
									'type'        => 'repeater',
									'label'       => 'Pathway cards',
									'item_label'  => 'Pathway',
									'title_field' => 'title',
									'fields'      => array(
										'title'      => array( 'type' => 'text', 'label' => 'Pathway name' ),
										'compulsory' => array( 'type' => 'lines', 'label' => 'Compulsory subjects', 'rows' => 2, 'help' => 'One per line.' ),
										'electives'  => array( 'type' => 'lines', 'label' => 'Elective subjects', 'rows' => 7, 'help' => 'One per line.' ),
									),
								),
							),
						),
					),
				),

				'milestones' => array(
					'title'       => 'Milestones',
					'anchor'      => 'milestones',
					'description' => 'Year cards with a logo at the top.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'items' => array(
							'type'        => 'repeater',
							'label'       => 'Milestones',
							'item_label'  => 'Milestone',
							'title_field' => 'title',
							'fields'      => array(
								'year'  => array( 'type' => 'number', 'label' => 'Year' ),
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
								'logo'  => $image( 'Logo (optional)' ),
							),
						),
					),
				),

				'clubs'      => array(
					'title'       => 'ECA & Clubs',
					'anchor'      => 'eca-clubs',
					'description' => 'Heading above the club cards. The clubs themselves (and their detail pages) are not edited here yet.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
					),
				),

				'alumni'     => array(
					'title'       => 'Alumni',
					'anchor'      => 'alumni',
					'description' => 'Carousel of A Level alumni testimonials.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Testimonials',
							'item_label'  => 'Testimonial',
							'title_field' => 'name',
							'fields'      => array(
								'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
								'name'     => array( 'type' => 'text', 'label' => 'Name' ),
								'role'     => array( 'type' => 'text', 'label' => 'Programme / where they are now' ),
								'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
							),
						),
						'emptyState'  => array( 'type' => 'text', 'label' => 'Text shown when there are no testimonials' ),
					),
				),

				'entry'      => array(
					'title'       => 'Entry & Support',
					'anchor'      => 'entry',
					'description' => 'Eligibility, scholarships and the application button.',
					'fields'      => array(
						'label'  => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'  => array( 'type' => 'text', 'label' => 'Title' ),
						'button' => array( 'type' => 'link', 'label' => 'Button' ),
						'blocks' => array(
							'type'        => 'repeater',
							'label'       => 'Blocks',
							'item_label'  => 'Block',
							'title_field' => 'title',
							'fields'      => array(
								'title' => array( 'type' => 'text', 'label' => 'Title' ),
								'body'  => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 4 ),
							),
						),
					),
				),

				'notices'    => array(
					'title'       => 'Notices',
					'anchor'      => 'notices',
					'description' => 'Heading above the college notices. The notices themselves are managed on the Notices page.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text' ),
						'emptyState'  => array( 'type' => 'textarea', 'label' => 'Text shown when there are no notices', 'rows' => 2 ),
					),
				),

				'seo'        => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "NAMI College",
    "description": "NAMI College teaches the Cambridge International A Level at Gokarneshwor-7, Kathmandu — an independent CAIE examination centre and, since June 2024, an accredited Cambridge International Home Centre in Nepal."
  },
  "hero": {
    "title": "NAMI College",
    "standfirst": "An independent Cambridge Assessment International Education examination centre, and an accredited Cambridge International Home Centre in Nepal since June 2024.",
    "button": {
      "label": "Apply to NAMI College",
      "href": "https://college.nami.edu.np/"
    },
    "slides": [
      {
        "image": {
          "src": "/sections/general/17.jpg",
          "alt": "NAMI College practical laboratory and science equipment.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/sections/general/18.jpg",
          "alt": "NAMI College campus facilities and learning environment.",
          "width": 1280,
          "height": 853
        }
      },
      {
        "image": {
          "src": "/sections/general/19.jpg",
          "alt": "NAMI College campus grounds and facilities.",
          "width": 1500,
          "height": 1000
        }
      }
    ]
  },
  "why": {
    "label": "Cambridge A Levels",
    "title": "Why A Levels at NAMI?",
    "intro": "NAMI College offers the internationally recognised Cambridge A Level programme, providing students with a rigorous academic pathway that is valued for university admissions both in Nepal and internationally. The programme emphasises academic excellence, critical thinking and independent learning, helping students develop the ability to analyse, question and learn beyond the classroom.",
    "more": "With a wide range of subjects and flexible subject combinations, students can build an academic pathway suited to their future ambitions, whether in Science, Medicine, Engineering, Business, Humanities or Liberal Arts. As an independent Cambridge Assessment International Education examination centre since 2024, NAMI provides students with an internationally oriented academic environment supported by experienced academic leadership and student-focused learning."
  },
  "principal": {
    "label": "From the Principal",
    "paragraphs": [
      "Dear Parents and Well-Wishers,",
      "We are delighted and proud to share an important milestone in the journey of our institution. Since June 2024, NAMI College has been officially accredited as a Cambridge International Home Centre in Nepal. This recognition from Cambridge International reflects our continued commitment to quality education, strong academic standards, and creating an environment where students can learn, grow, and achieve their full potential.",
      "This achievement is also being reflected in the performance of our students. We are especially proud that our students have begun to achieve Nepal Topper positions in various subjects under the Cambridge GCE A Level examinations. These results are a reflection of the students' hard work and dedication, as well as the continuous guidance and support of our teachers and the encouragement of their parents.",
      "At NAMI College, our aim goes beyond academic results. We focus on developing students’ critical thinking, confidence, creativity, analytical skills, and independent learning abilities, while preparing them for higher education and future opportunities in a changing global environment.",
      "We sincerely thank our parents, students, teachers, staff, and well-wishers for their continued trust, support, and contribution to our journey. These achievements are the result of a shared commitment and collective effort.",
      "As we move forward, we remain committed to providing our students with meaningful learning experiences and opportunities to achieve even greater success.",
      "Together, let us continue to inspire, support, and empower our students to reach their full potential."
    ],
    "name": "Mr. Philip Badikar Hilario",
    "title": "A Level Principal, NAMI College",
    "portrait": {
      "src": "/leadership/philip-badikar-hilario.webp",
      "alt": "Studio portrait of Mr. Philip Badikar Hilario, A Level Principal at NAMI College, arms folded in a charcoal suit and black tie against a mottled blue-grey backdrop.",
      "width": 1538,
      "height": 2000
    }
  },
  "cambridge": {
    "label": "An international benchmark, taught in small classes.",
    "title": "The Qualification",
    "description": "The A Level is administered by Cambridge Assessment International Education, University of Cambridge, United Kingdom.",
    "badge": "Cambridge A-Levels",
    "cards": [
      {
        "title": "Science and non-science streams",
        "body": "Students take both science and non-science combinations, so management and humanities sit alongside the sciences."
      },
      {
        "title": "Project-based learning",
        "body": "Learning runs through projects across subjects. Students explore, experiment, challenge ideas and take leadership roles, with the emphasis on creativity and critical thinking."
      },
      {
        "title": "Seasoned faculty, small classes",
        "body": "NAMI teaches the programme with seasoned faculty, small class sizes and a friendly, caring approach. The college is fully co-educational."
      },
      {
        "title": "Recognised preparation",
        "body": "Cambridge qualifications are an international benchmark, and a recognised preparation for university study and for employment."
      }
    ]
  },
  "subjects": {
    "label": "Two streams, and the subjects in each.",
    "title": "Subjects",
    "description": "A wide range of subject combinations preparing students for university study in science, medicine, engineering, and business.",
    "compulsoryLabel": "Compulsory",
    "electivesLabel": "Electives",
    "streams": [
      {
        "label": "Science",
        "requirement": "English General Paper (AS) is compulsory, along with any 3 or more additional subjects of your choice to complete your A Levels.",
        "pathways": [
          {
            "title": "Medicine & Biological Sciences",
            "compulsory": [
              "English General Paper (AS)"
            ],
            "electives": [
              "Physics",
              "Chemistry",
              "Biology",
              "Mathematics",
              "Further Mathematics",
              "Psychology"
            ]
          },
          {
            "title": "Engineering, Computer Science & Architecture",
            "compulsory": [
              "English General Paper (AS)"
            ],
            "electives": [
              "Physics",
              "Chemistry",
              "Mathematics",
              "Further Mathematics",
              "Computer Science"
            ]
          }
        ]
      },
      {
        "label": "Non-Science",
        "requirement": "English General Paper (AS) is compulsory, along with any 3 or more additional subjects of your choice to complete your A Levels.",
        "pathways": [
          {
            "title": "Business, Economics & Finance",
            "compulsory": [
              "English General Paper (AS)"
            ],
            "electives": [
              "Business",
              "Economics",
              "Accounting",
              "Computer Science",
              "Mathematics"
            ]
          },
          {
            "title": "Humanities & Social Sciences",
            "compulsory": [
              "English General Paper (AS)"
            ],
            "electives": [
              "Business",
              "Sociology",
              "Psychology",
              "Art and Design"
            ]
          }
        ]
      }
    ]
  },
  "milestones": {
    "label": "The Cambridge programme, year by year.",
    "title": "Milestones and Accreditations",
    "items": [
      {
        "year": 2014,
        "title": "The Cambridge A Level begins",
        "body": "NAMI College starts teaching the Cambridge International A Level, administered by Cambridge Assessment International Education, University of Cambridge, United Kingdom.",
        "logo": {
          "src": "/logos/universities/cambridge.png",
          "alt": "Cambridge Assessment International Education",
          "width": 352,
          "height": 112
        }
      },
      {
        "year": 2024,
        "title": "Independent Examination Centre",
        "body": "In June 2024 NAMI College is accredited as a Cambridge International Home Centre in Nepal, and holds independent Cambridge Assessment International Education examination centre status.",
        "logo": {
          "src": "/logos/universities/cambridge.png",
          "alt": "Cambridge Assessment International Education",
          "width": 352,
          "height": 112
        }
      }
    ]
  },
  "clubs": {
    "label": "Extracurricular & Co-Curricular",
    "title": "ECA & Clubs",
    "description": "Student-led clubs fostering community engagement, competitive sports, and artistic creativity."
  },
  "alumni": {
    "label": "What the programme is worth, from the people who finished it.",
    "title": "Alumni",
    "description": "A Level alumni on the teaching, the workload and what the qualification carried them into.",
    "emptyState": "A Level alumni stories will appear here as graduates share them.",
    "items": [
      {
        "quote": "One thing I learned at NAMI that I’ll never forget is that there are endless possibilities beyond what I had imagined. Before coming here, I thought college life was just about studying, but NAMI showed me that it’s so much more. I have had the chance to explore new experiences and explore what I am interested in.",
        "name": "Rufash K.C.",
        "role": "AS Level — Batch 2026",
        "portrait": {
          "src": "/testimonials/a-levels/Rufash.png",
          "alt": "Rufash K.C.",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "One thing I learned at NAMI is that freedom to make decisions is the best way a student can learn, grow and build a strong self-confidence.",
        "name": "Adarsh Karna",
        "role": "A Level — Batch 2025",
        "portrait": {
          "src": "/testimonials/a-levels/Adarsh Karna.png",
          "alt": "Adarsh Karna",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "One thing I will never forget about NAMI College is the friendships and enjoyable moments which made school memorable. But education should always remain a priority because it shapes my future opportunities. Guidance and encouragement of my teachers also taught me to enjoy student life while staying focused on my studies. NAMI College taught me the value of balance as while we create happy memories, our responsibility as a student should be consistent to a bright and successful future.",
        "name": "Angel Gurung",
        "role": "A Level — Batch 2025",
        "portrait": {
          "src": "/testimonials/a-levels/Angel.png",
          "alt": "Angel Gurung",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "One thing about NAMI that will forever stay with me is the fun I had studying here. Two years in this college passed so quickly I wish I could go back in time and live all those moments once again. Awkward orientation in Chitwan to that emotional farewell in Kurintar. One of the best moments in my life.",
        "name": "Shreeyash Dhungana",
        "role": "A Level — Batch 2022",
        "portrait": {
          "src": "/testimonials/a-levels/Shreeyash.png",
          "alt": "Shreeyash Dhungana",
          "width": 400,
          "height": 400
        }
      }
    ]
  },
  "entry": {
    "label": "Entry and Support",
    "title": "Who it is for, and how it is supported.",
    "button": {
      "label": "Start an Application",
      "href": "https://college.nami.edu.np/"
    },
    "blocks": [
      {
        "title": "Eligibility",
        "body": "Students who have completed SEE, GCSE, CBSE or an equivalent qualification at the time of admission. What the programme asks for is the academic ability to meet its demands."
      },
      {
        "title": "Scholarships",
        "body": "Scholarships are offered to highly meritorious students who are financially weak, and further scholarships are available to other deserving candidates."
      }
    ]
  },
  "notices": {
    "title": "Notice Board",
    "description": "Registration windows, examination dates and standing notices for A Level students and their families.",
    "buttonLabel": "All College Notices",
    "emptyState": "There is no college notice standing right now. Everything the college has published stays on the notice board."
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
