<?php
/**
 * NAMI CMS — Bachelors (NAMI Institute) page and its course pages
 *
 * Requires the "NAMI CMS — Core engine" snippet (version with nested lists).
 * Adds a "Bachelors" menu to the WordPress sidebar with one sub-menu per
 * section of the /institutions/bachelors page. The "Degree Courses" section
 * also feeds every course page (/institutions/bachelors/{web address}).
 *
 * Field keys must match src/lib/cms/pages/bachelors/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['bachelors'] = array(
			'title'      => 'Bachelors (NAMI Institute)',
			'menu_title' => 'Bachelors',
			'icon'       => 'dashicons-welcome-learn-more',
			'position'   => 3.5,
			'path'       => '/institutions/bachelors',
			'sections'   => array(

				'hero'         => array(
					'title'       => 'Hero',
					'description' => 'Title, intro text, button and the slideshow at the top of the page.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Slideshow name', 'help' => 'Not shown on screen; read aloud to visitors using screen readers.' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'standfirst' => array( 'type' => 'textarea', 'label' => 'Intro text' ),
						'button'     => array( 'type' => 'link', 'label' => 'Button' ),
						'slides'     => array(
							'type'        => 'repeater',
							'label'       => 'Slideshow images',
							'item_label'  => 'Slide',
							'title_field' => 'image',
							'fields'      => array(
								'image' => $image( 'Image', 'Wide landscape photos work best (about 1500 × 1000 px).' ),
							),
						),
					),
				),

				'why'          => array(
					'title'       => 'Why Undergraduate',
					'anchor'      => 'why-undergraduate',
					'description' => 'The introduction with a "Read More" toggle.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'intro' => array( 'type' => 'textarea', 'label' => 'First paragraph (always shown)', 'rows' => 6 ),
						'more'  => array( 'type' => 'textarea', 'label' => 'Second paragraph (shown on "Read More")', 'rows' => 6, 'help' => 'Leave empty to hide the Read More button.' ),
					),
				),

				'academicHead' => array(
					'title'       => 'Academic Head\'s Message',
					'anchor'      => 'academic-head',
					'description' => 'The message with the portrait card on the right. The first 4 paragraphs show before "Read More".',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Message', 'rows' => 18, 'help' => 'Leave an empty line between paragraphs. Leave everything empty to hide this section.' ),
						'name'       => array( 'type' => 'text', 'label' => 'Name' ),
						'title'      => array( 'type' => 'text', 'label' => 'Job title' ),
						'portrait'   => $image( 'Portrait', 'Portrait (upright) photos work best.' ),
					),
				),

				'universities' => array(
					'title'       => 'University Partners',
					'anchor'      => 'university-partners',
					'description' => 'The expandable university cards, each with its leader\'s message. The first card starts open.',
					'fields'      => array(
						'label'    => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'    => array( 'type' => 'text', 'label' => 'Title' ),
						'partners' => array(
							'type'        => 'repeater',
							'label'       => 'Universities',
							'item_label'  => 'University',
							'title_field' => 'name',
							'fields'      => array(
								'name'              => array( 'type' => 'text', 'label' => 'University name' ),
								'badge'             => array( 'type' => 'text', 'label' => 'Badge (top left)' ),
								'status'            => array( 'type' => 'text', 'label' => 'Partnership status (next to the badge)' ),
								'location'          => array( 'type' => 'text', 'label' => 'Address' ),
								'logo'              => $image( 'Logo / crest' ),
								'dark'              => array( 'type' => 'toggle', 'label' => 'Card style', 'toggle_label' => 'Dark card (the University of Northampton style)' ),
								'overview'          => array( 'type' => 'paragraphs', 'label' => 'About the university', 'rows' => 8, 'help' => 'Leave an empty line between paragraphs. The first paragraph is shown while the card is closed.' ),
								'note'              => array( 'type' => 'textarea', 'label' => 'Note (optional)', 'rows' => 2, 'help' => 'Shown in a small box under the text. Leave empty to hide.' ),
								'metrics'           => array(
									'type'        => 'repeater',
									'label'       => 'Key partnership metrics',
									'item_label'  => 'Metric',
									'title_field' => 'value',
									'fields'      => array(
										'value' => array( 'type' => 'text', 'label' => 'Value (big text)' ),
										'label' => array( 'type' => 'text', 'label' => 'Label (small text)' ),
									),
								),
								'programmes'        => array(
									'type'        => 'repeater',
									'label'       => 'Affiliated degree programmes',
									'item_label'  => 'Programme',
									'title_field' => 'title',
									'fields'      => array(
										'title' => array( 'type' => 'text', 'label' => 'Programme' ),
										'award' => array( 'type' => 'text', 'label' => 'Awarded by (shown in brackets)' ),
									),
								),
								'leaderRole'        => array( 'type' => 'text', 'label' => 'Message heading', 'placeholder' => 'Message from the Vice-Chancellor' ),
								'leaderName'        => array( 'type' => 'text', 'label' => 'Leader\'s name' ),
								'leaderTitle'       => array( 'type' => 'text', 'label' => 'Leader\'s job title' ),
								'leaderAffiliation' => array( 'type' => 'text', 'label' => 'Leader\'s university / place' ),
								'leaderPhoto'       => $image( 'Leader\'s photo (optional)', 'Portrait (upright) photos work best. Without a photo, the name shows in a small box.' ),
								'leaderQuote'       => array( 'type' => 'textarea', 'label' => 'Highlighted quote', 'rows' => 3 ),
								'leaderMessage'     => array( 'type' => 'paragraphs', 'label' => 'Message', 'rows' => 10 ),
							),
						),
					),
				),

				'courses'      => array(
					'title'       => 'Degree Courses',
					'anchor'      => 'programmes',
					'description' => 'The course cards on this page, and each course\'s own page. Click a course to open it; inside are its details, entry requirements, careers and year-by-year modules.',
					'fields'      => array(
						'label'         => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'         => array( 'type' => 'text', 'label' => 'Title' ),
						'description'   => array( 'type' => 'textarea', 'label' => 'Description (optional)', 'rows' => 2 ),
						'awardedLabel'  => array( 'type' => 'text', 'label' => 'Text before the awarding university on each card', 'placeholder' => 'Awarded by' ),
						'startingLabel' => array( 'type' => 'text', 'label' => 'Text before the start date on each card', 'placeholder' => 'Begins' ),
						'pendingLabel'  => array( 'type' => 'text', 'label' => 'Heading above a course\'s "programme detail" note' ),
						'items'         => array(
							'type'        => 'repeater',
							'label'       => 'Courses',
							'item_label'  => 'Course',
							'title_field' => 'fullTitle',
							'fields'      => array(
								'slug'             => array( 'type' => 'text', 'label' => 'Web address', 'help' => 'The course page lives at /institutions/bachelors/<this>. Lowercase words with hyphens, e.g. computer-science. Changing it breaks old links to the course.' ),
								'qualification'    => array( 'type' => 'text', 'label' => 'Qualification (small text on the card)', 'placeholder' => 'BSc. (Hons)' ),
								'title'            => array( 'type' => 'text', 'label' => 'Short name (on the card)' ),
								'fullTitle'        => array( 'type' => 'text', 'label' => 'Full name (course page title)' ),
								'shortDescription' => array( 'type' => 'textarea', 'label' => 'Card description', 'rows' => 2, 'help' => 'If empty, the card uses the first overview paragraph.' ),
								'image'            => $image( 'Photo', 'Used on the card and at the top of the course page. Landscape, about 1500 × 1000 px. A course without a photo is hidden.' ),
								'awardingBody'     => array( 'type' => 'text', 'label' => 'Awarding university' ),
								'startingFrom'     => array( 'type' => 'text', 'label' => 'Start date (optional)', 'help' => 'Shown on the card as "Begins …". Leave empty to hide.' ),
								'format'           => array( 'type' => 'text', 'label' => 'Duration / format', 'placeholder' => '3 years | 360 credits' ),
								'metaDescription'  => array( 'type' => 'textarea', 'label' => 'Search & sharing description', 'rows' => 3, 'help' => 'How the course page appears in Google and on social media. About 150 characters.' ),
								'keyFacts'         => array(
									'type'        => 'repeater',
									'label'       => 'Key Facts boxes',
									'item_label'  => 'Fact',
									'title_field' => 'label',
									'fields'      => array(
										'label' => array( 'type' => 'text', 'label' => 'Label' ),
										'value' => array( 'type' => 'text', 'label' => 'Value' ),
									),
								),
								'whatYoullStudy'   => array( 'type' => 'textarea', 'label' => '"What you\'ll study" paragraph (optional)', 'rows' => 5 ),
								'summary'          => array( 'type' => 'paragraphs', 'label' => 'Course overview', 'rows' => 12, 'help' => 'Leave an empty line between paragraphs. The first sentence also appears next to the course title.' ),
								'entryLabel'       => array( 'type' => 'text', 'label' => 'Entry requirements heading' ),
								'entry'            => array(
									'type'        => 'repeater',
									'label'       => 'Entry requirements',
									'item_label'  => 'Requirement',
									'title_field' => 'label',
									'fields'      => array(
										'label'       => array( 'type' => 'text', 'label' => 'Qualification' ),
										'requirement' => array( 'type' => 'textarea', 'label' => 'Requirement', 'rows' => 2 ),
									),
								),
								'entryNotes'       => array( 'type' => 'lines', 'label' => 'Important entry notes', 'rows' => 3, 'help' => 'One note per line.' ),
								'careersLabel'     => array( 'type' => 'text', 'label' => 'Careers heading' ),
								'careerSummary'    => array( 'type' => 'textarea', 'label' => 'Careers text', 'rows' => 4 ),
								'careerSectors'    => array( 'type' => 'lines', 'label' => 'Industry sectors & roles', 'rows' => 8, 'help' => 'One per line. Each becomes a tag.' ),
								'pendingNote'      => array( 'type' => 'textarea', 'label' => 'Programme detail note (optional)', 'rows' => 2, 'help' => 'For a course whose details are not final yet. Leave empty to hide.' ),
								'stagesNote'       => array( 'type' => 'textarea', 'label' => 'Text under "Courses offered" (optional)', 'rows' => 2 ),
								'stages'           => array(
									'type'        => 'repeater',
									'label'       => 'Years / stages',
									'item_label'  => 'Year',
									'title_field' => 'label',
									'fields'      => array(
										'label'   => array( 'type' => 'text', 'label' => 'Heading', 'placeholder' => 'Year I' ),
										'note'    => array( 'type' => 'textarea', 'label' => 'Note under the table (optional)', 'rows' => 2 ),
										'modules' => array(
											'type'        => 'repeater',
											'label'       => 'Modules',
											'item_label'  => 'Module',
											'title_field' => 'title',
											'fields'      => array(
												'code'          => array( 'type' => 'text', 'label' => 'Code' ),
												'title'         => array( 'type' => 'text', 'label' => 'Title' ),
												'credits'       => array( 'type' => 'number', 'label' => 'Credits' ),
												'status'        => array(
													'type'    => 'select',
													'label'   => 'Status',
													'options' => array(
														''           => '— None —',
														'Compulsory' => 'Compulsory',
														'Optional'   => 'Optional',
														'Designated' => 'Designated',
													),
												),
												'prerequisites' => array( 'type' => 'text', 'label' => 'Pre-requisites', 'placeholder' => 'None' ),
												'description'   => array( 'type' => 'textarea', 'label' => 'Description (shown when the row is opened)', 'rows' => 3 ),
											),
										),
									),
								),
							),
						),
					),
				),

				'awarding'     => array(
					'title'       => 'Awarding Universities',
					'anchor'      => 'awarding',
					'description' => 'Heading above the awarding university cards. The universities themselves are shared with other pages and not edited here yet.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'sinceLabel'  => array( 'type' => 'text', 'label' => 'Text before the year on each card', 'placeholder' => 'Since' ),
					),
				),

				'pearson'      => array(
					'title'       => 'Pearson VUE Banner',
					'anchor'      => 'pearson-vue',
					'description' => 'The banner with the Pearson VUE logo.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title', 'help' => 'Leave empty to hide the banner.' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'logo'        => $image( 'Logo' ),
					),
				),

				'placement'    => array(
					'title'       => 'Career Placement',
					'anchor'      => 'partners',
					'description' => 'Heading and photo of the career placement section. The partner logos are shared with other pages and not edited here yet.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'image' => $image( 'Photo', 'Remove the photo to hide this section.' ),
					),
				),

				'alumni'       => array(
					'title'       => 'Student Voices',
					'anchor'      => 'alumni',
					'description' => 'Carousel of student testimonials.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Testimonials',
							'item_label'  => 'Testimonial',
							'title_field' => 'name',
							'fields'      => array(
								'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
								'name'     => array( 'type' => 'text', 'label' => 'Name' ),
								'role'     => array( 'type' => 'text', 'label' => 'Programme / where they are now' ),
								'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
							),
						),
						'emptyState'  => array( 'type' => 'text', 'label' => 'Text shown when there are no testimonials' ),
					),
				),

				'mou'          => array(
					'title'       => 'MoU Partners',
					'anchor'      => 'mou-partners',
					'description' => 'Carousel of companies NAMI has signed an MoU with.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'badge'       => array( 'type' => 'text', 'label' => 'Text at the bottom of each card', 'placeholder' => 'Verified MoU Partner' ),
						'partners'    => array(
							'type'        => 'repeater',
							'label'       => 'Partners',
							'item_label'  => 'Partner',
							'title_field' => 'organization',
							'fields'      => array(
								'organization' => array( 'type' => 'text', 'label' => 'Company name' ),
								'domain'       => array( 'type' => 'text', 'label' => 'Sector (red tag)' ),
								'logo'         => $image( 'Logo', 'A logo with a transparent background (PNG) works best.' ),
							),
						),
					),
				),

				'notices'      => array(
					'title'       => 'Notices',
					'anchor'      => 'notices',
					'description' => 'Heading above the institute notices. The notices themselves are managed on the Notices page.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description' ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text' ),
						'emptyState'  => array( 'type' => 'textarea', 'label' => 'Text shown when there are no notices', 'rows' => 2 ),
					),
				),

				'seo'          => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Bachelors page appears in Google results and when shared on social media. Each course has its own description under Degree Courses.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Naaya Aayam Multi-Disciplinary Institute",
    "description": "Naaya Aayam Multi-Disciplinary Institute teaches partner-university degrees at New Baneshwor, Kathmandu — BSc. (Hons) Computer Science, BSc. (Hons) Environmental Science, and Bachelor in Business Administration awarded by the University of Northampton, UK, and BSc. Environmental Studies awarded by Kathmandu University."
  },
  "hero": {
    "label": "NAMI at New Baneshwor",
    "title": "NAAYA AAYAM MULTI-DISCIPLINARY INSTITUTE",
    "standfirst": "British & KU degree programmes in Kathmandu, partnered with the University of Northampton (UK).",
    "button": {
      "label": "Start an Application",
      "href": "/admissions"
    },
    "slides": [
      {
        "image": {
          "src": "/hero/careers/careers-hero.jpg",
          "alt": "NAMI Higher Education student sports tournament and campus life.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/about/about-hero.jpg",
          "alt": "NAMI Higher Education faculty, students, and graduation ceremony.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/a-levels/a-levels-hero.jpg",
          "alt": "NAMI Higher Education campus facilities and learning environment.",
          "width": 1280,
          "height": 853
        }
      },
      {
        "image": {
          "src": "/hero/bachelors/bachelors-hero.jpg",
          "alt": "NAMI Higher Education academic campus and community.",
          "width": 1500,
          "height": 1000
        }
      },
      {
        "image": {
          "src": "/hero/school/school-hero.jpg",
          "alt": "NAMI Higher Education practical laboratories and campus life.",
          "width": 1500,
          "height": 1000
        }
      }
    ]
  },
  "why": {
    "label": "Undergraduate Studies",
    "title": "Why Undergraduate at NAMI?",
    "intro": "NAMI offers internationally oriented undergraduate education through its academic collaboration with the University of Northampton, UK. Students can pursue British degrees across disciplines including Computer Science, Software Engineering, Networking Engineering, Environmental Science and Business Administration, gaining an academic foundation designed to meet the expectations of the global job market.",
    "more": "The undergraduate experience goes beyond academic study. NAMI's industry partnerships provide opportunities for internships, mentorship, job placements and collaborative research, helping students connect classroom learning with real-world requirements. Through its Innovation and Incubation Centre, students can also develop ideas, work with entrepreneurs and industry experts, build prototypes, explore business models and pursue their own ventures."
  },
  "academicHead": {
    "label": "From the Academic Head",
    "paragraphs": [
      "On behalf of the entire NAMI family, it is my great pleasure to warmly welcome all our new and returning students as you begin or continue academic journey with NAMI across our undergraduate and postgraduate programmes.",
      "As you begin or continue your journey at NAMI, we are pleased to welcome you to a community where learning goes beyond the classroom. We want your time at NAMI to be an opportunity to gain knowledge, discover your strengths, explore new ideas and build the confidence to pursue your ambitions. At NAMI, we are committed to creating an environment that encourages students to learn, explore, innovate and achieve their full potential.",
      "Our students are at the heart of everything we do. You will be joining a community of talented, enthusiastic and ambitious individuals who bring diverse perspectives, experiences and ideas to our learning environment. I encourage you to engage with your peers, collaborate with others and make the most of every opportunity to learn and grow together.",
      "At NAMI, education extends beyond the classroom. Alongside your academic studies, you will have opportunities to participate in student clubs and societies, projects, events, leadership activities, industry engagement and a wide range of co-curricular and extracurricular initiatives. These experiences complement your academic learning and help you develop the knowledge, skills, confidence and professional attributes needed to thrive in an ever-changing world.",
      "I encourage you to make the most of your time at NAMI by taking opportunities available to you, both within and beyond the classroom. Stay curious, ask questions, share your ideas, take on new challenges and play an active role in the NAMI community. Each experience will contribute to your personal and academic growth, helping you develop confidence, strengthen your communication and teamwork. It will build the leadership, creativity, critical thinking and problem-solving skills that will serve you well in the future.",
      "Our faculty and staff are committed to supporting you throughout your journey. We are here to provide academic guidance, mentorship and opportunities for personal and professional development. Your success matters to us and we encourage you to seek guidance and support whenever you need it.",
      "I hope your time at NAMI will be rewarding, inspiring and transformative. Embrace every opportunity, learn from every experience and contribute positively to our community. Your time at NAMI is not simply about earning a qualification; it is about developing the knowledge, confidence, values and capabilities to make a meaningful contribution to society and the world of work.",
      "Once again, I warmly welcome you to NAMI. We are pleased to have you as part of our academic community and I look forward to seeing you grow with confidence, pursue your aspirations and make the most of the opportunities ahead.",
      "Warmest wishes for a successful, fulfilling and inspiring academic journey."
    ],
    "name": "Mr. Nischal Khadka",
    "title": "Academic Head, Naaya Aayam Multi-Disciplinary Institute",
    "portrait": {
      "src": "/leadership/nischal-khadka.webp",
      "alt": "Studio portrait of Mr. Nischal Khadka, Academic Head at NAMI, arms folded in a dark navy suit and patterned blue tie against a mottled blue-grey backdrop.",
      "width": 1507,
      "height": 2000
    }
  },
  "universities": {
    "label": "Academic Affiliations & Degree Awarding",
    "title": "Our University Partners",
    "partners": [
      {
        "name": "University of Northampton, UK",
        "badge": "Official UK Degree Awarding Partner",
        "status": "Direct Academic Partnership Since 2012",
        "location": "Waterside Campus, University Drive, Northampton - NN1 5PH",
        "logo": {
          "src": "/logos/universities/northampton.png",
          "alt": "University of Northampton, UK Crest",
          "width": 612,
          "height": 407
        },
        "dark": true,
        "overview": [
          "The University of Northampton is a leading British public university located on its purpose-built £330 million Waterside Campus in England. Globally recognized as the UK's first Ashoka U Changemaker Campus and commended for teaching excellence under the British Teaching Excellence Framework (TEF), the university champions social innovation, enterprise, and high graduate outcomes.",
          "Since 2012, NAMI has operated in direct academic partnership with the University of Northampton to deliver accredited undergraduate and postgraduate degrees in Kathmandu. Programmes follow identical curricula, assessment frameworks, and moderation from external UK examiners, granting graduates authentic British degrees recognized internationally."
        ],
        "note": "",
        "metrics": [
          {
            "value": "12+ Years",
            "label": "Academic Partnership"
          },
          {
            "value": "100% UK Awarded",
            "label": "Direct Equivalence"
          },
          {
            "value": "TEF Rated",
            "label": "Teaching Excellence"
          }
        ],
        "programmes": [
          {
            "title": "BSc. (Hons) Computing",
            "award": "UoN, UK"
          },
          {
            "title": "BSc. (Hons) Software Engineering",
            "award": "UoN, UK"
          },
          {
            "title": "BSc. (Hons) Network Engineering",
            "award": "UoN, UK"
          },
          {
            "title": "BSc. (Hons) Environmental Science",
            "award": "UoN, UK"
          },
          {
            "title": "BBA (Hons) Business Administration",
            "award": "UoN, UK"
          }
        ],
        "leaderRole": "Message from the Vice-Chancellor",
        "leaderName": "Professor Anne-Marie Kilday",
        "leaderTitle": "Vice-Chancellor",
        "leaderAffiliation": "University of Northampton, United Kingdom",
        "leaderPhoto": {
          "src": "/sections/nami/anne-marie-kilday-outside-portrait-683x1024.jpg",
          "alt": "Professor Anne-Marie Kilday",
          "width": 683,
          "height": 1024
        },
        "leaderQuote": "Our partnership with NAMI reflects our shared conviction in widening access to world-class British higher education, equipping students in Nepal with the innovation and global competencies to lead transformative careers.",
        "leaderMessage": [
          "At the University of Northampton, we believe higher education has the transformative power to develop future leaders, ignite innovation, and deliver real social impact. Our long-standing collaboration with Naaya Aayam Multi-Disciplinary Institute (NAMI) in Kathmandu is a testament to this global mission.",
          "Through this partnership, students in Nepal engage in rigorous, career-focused degree programmes in Computing, Software Engineering, Network Engineering, Environmental Science, and Business Administration. These programmes are delivered under our exacting academic standards, incorporating experiential learning and technological literacy.",
          "We take immense pride in the achievements of NAMI graduates who continue to excel across international technology companies, research organizations, and entrepreneurial ventures. We look forward to deepening our academic collaboration and welcoming future cohorts into our global community."
        ]
      },
      {
        "name": "Kathmandu University (KU)",
        "badge": "National University Collaboration",
        "status": "Collaborative Academic Partnership from 2026",
        "location": "Main Campus · Dhulikhel, Kavrepalanchok, Nepal",
        "logo": {
          "src": "/logos/universities/Kathmandu_University_Logo.webp",
          "alt": "Kathmandu University (KU) Crest",
          "width": 1280,
          "height": 1280
        },
        "dark": false,
        "overview": [
          "Established in 1991, Kathmandu University is an autonomous, premier non-government public institution dedicated to academic excellence, scientific research, and professional training in Nepal. Ranked consistently among Nepal's top national universities, KU is celebrated for research integrity, dedicated faculty, and high pedagogical standards.",
          "NAMI has entered into a strategic collaboration with Kathmandu University to offer the Bachelor in Environmental Studies (BES) programme. Combining classroom rigour with field-based ecological assessments, GIS spatial modeling, and sustainability policy analysis, the programme prepares graduates to tackle critical Himalayan and global environmental challenges."
        ],
        "note": "Official Dean message and comprehensive KU academic details will be updated as finalized by Kathmandu University.",
        "metrics": [
          {
            "value": "Autonomous",
            "label": "Premier National University"
          },
          {
            "value": "Himalayan Fieldwork",
            "label": "Applied Ecology Practicums"
          },
          {
            "value": "Session 2026",
            "label": "Commencing Intake"
          }
        ],
        "programmes": [
          {
            "title": "BSc. in Environmental Studies (BES)",
            "award": "KU Collaboration"
          },
          {
            "title": "Himalayan Ecology & Field Practicums",
            "award": "KU Academic Track"
          },
          {
            "title": "Climate Policy & Sustainability Governance",
            "award": "Joint Initiatives"
          }
        ],
        "leaderRole": "Message from the Dean / Academic Leadership",
        "leaderName": "Office of the Dean, School of Science",
        "leaderTitle": "Dean & Academic Leadership Council",
        "leaderAffiliation": "Kathmandu University, Dhulikhel, Nepal",
        "leaderPhoto": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        },
        "leaderQuote": "Collaborating with NAMI allows us to expand multidisciplinary environmental education, nurturing the next generation of environmental researchers, policy advocates, and sustainability leaders in Nepal.",
        "leaderMessage": [
          "Kathmandu University has always led the nation in scientific innovation, environmental stewardship, and academic quality. As global environmental and climate realities evolve, the need for skilled, research-oriented environmental professionals has never been more urgent.",
          "Through our collaborative academic initiatives with NAMI, we bring KU's rich curriculum and pedagogical framework to motivated students in Kathmandu. The Bachelor in Environmental Studies programme is designed to bridge scientific fundamentals with practical fieldwork and community-based sustainability projects.",
          "We welcome aspiring environmental scientists and future changemakers to embark on this collaborative educational journey with Kathmandu University and NAMI."
        ]
      }
    ]
  },
  "courses": {
    "label": "Academics",
    "title": "Degree Programmes",
    "description": "",
    "awardedLabel": "Awarded by",
    "startingLabel": "Begins",
    "pendingLabel": "Programme detail",
    "items": [
      {
        "slug": "computer-science",
        "qualification": "BSc. (Hons)",
        "title": "Computer Science",
        "fullTitle": "BSc. (Hons) Computer Science",
        "shortDescription": "Three-year honours degree with majors in Software Engineering, Computing Systems, and Networks.",
        "image": {
          "src": "/sections/general/degree (1).jpg",
          "alt": "NAMI BSc. (Hons) Computer Science lecture and interactive computing workshop.",
          "width": 1500,
          "height": 1000
        },
        "awardingBody": "The University of Northampton, UK",
        "startingFrom": "",
        "format": "Three-year degree",
        "metaDescription": "BSc. (Hons) Computer Science at NAMI, Kathmandu — a three-year degree awarded by the University of Northampton, UK, with majors in Computing, Software Engineering and Computer Networks Engineering.",
        "keyFacts": [
          {
            "label": "Programme Name",
            "value": "BSc. (Hons) Computer Science"
          },
          {
            "label": "Level",
            "value": "Undergraduate Degree"
          },
          {
            "label": "Duration",
            "value": "3 years"
          },
          {
            "label": "Intake",
            "value": "September / January"
          },
          {
            "label": "Location",
            "value": "New Baneshwor, Kathmandu"
          },
          {
            "label": "Awarding Institution",
            "value": "University of Northampton"
          },
          {
            "label": "Mode",
            "value": "Full Time"
          },
          {
            "label": "Total Credits",
            "value": "360"
          }
        ],
        "whatYoullStudy": "Our BSc. Computer Science degree gives you the opportunity to explore different ideas and develop innovative solutions to current issues in the computing industry. This three-year Computer Science university degree will give you an insight into the computing industry, investigating the wide-reaching influences that computers and computing technology have on the world. Studying this course will also contribute towards helping you find your ideal path for a career in Computing.",
        "summary": [
          "This course is designed to give the students the opportunity to explore different ideas, developing innovative solutions of improvements to current issues in the computing industry. This program covers the fundamental principles that are key to computing technology and its various uses.",
          "Throughout this degree, students will cover software engineering methods, database implementation and system design, with multiple users and multiple platforms in mind. It also includes background theory, practical implications of knowledge-based systems, neural networks and evolutionary algorithms on the development of artificial intelligence systems."
        ],
        "entryLabel": "Entry Requirements:",
        "entry": [
          {
            "label": "+2 (NEB)",
            "requirement": "Minimum of 55% (2.2 GPA) or equivalent."
          },
          {
            "label": "CBSE",
            "requirement": "Minimum of 60%."
          },
          {
            "label": "A Levels",
            "requirement": "280 UCAS tariff points."
          },
          {
            "label": "English",
            "requirement": "Minimum of 60 marks in English at +2 or CBSE, or an IELTS score of 6 with no band less than 5.5."
          }
        ],
        "entryNotes": [
          "Students awaiting results, and students who have completed a foundation or bridge course (Level 3) from a recognised institution, are also encouraged to apply.",
          "All decisions regarding an offer letter are made by the University of Northampton, UK."
        ],
        "careersLabel": "Career prospect",
        "careerSummary": "Graduates join organisational projects directly, without intensive further training, and the research skills built through the dissertation open a second route into research or independent consultancy. Computing is used in every discipline, so the long-term scope of the degree reaches wherever computing reaches.",
        "careerSectors": [
          "Software industries",
          "Internet service providers",
          "Banks",
          "Airlines",
          "Hydropower",
          "Automobile industries",
          "Educational institutions",
          "Research and consultancy"
        ],
        "pendingNote": "",
        "stagesNote": "During the first year all computing students share the same modules. In years two and three they have the flexibility to focus on a specialism from a range of topics.",
        "stages": [
          {
            "label": "Year I",
            "note": "Students must take all modules.",
            "modules": [
              {
                "code": "CSY1062",
                "title": "Computer Communications",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This module develops students' understanding of the principles of communication networks and how to classify the various network devices in the appropriate layer of the protocol stack. Students will learn how to manage IP addresses in a small network and will develop confidence in using network simulation software."
              },
              {
                "code": "CSY1061",
                "title": "Computer Systems",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This module provides knowledge of the hardware and software components that make up a computer system and overview the important concepts in preparation for future study of computer science."
              },
              {
                "code": "CSY1063",
                "title": "Web Development",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This purpose of this module is to give students an understanding of client side web technologies. This module provides students with: the essential knowledge and practical skills to design, develop and implement a Web site to contemporary web standard"
              },
              {
                "code": "CSY1064",
                "title": "Software Engineering Fundamentals",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "The purpose of this module is to develop student’s experience with the multiple stages of software engineering life-cycles from initial need and requirements identification through to the design and implementation of code in order to develop confidence in the use of terminology and techniques for each of the stages."
              },
              {
                "code": "CSY1020",
                "title": "Problem Solving & Programming",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This purpose of this module is to: introduce students to the skills, principles and concepts necessary to solve problems in computing; to develop essential skills to enable the solution of these problems with the construction of appropriate algorithms and a computer program; introduce principles underlying the design of a high level programming language (HLPL); gain experience and confidence in the use of a HLPL to implement algorithms; implement HLPL programs using an appropriate programming language e.g. Java; introduce an object-oriented language initially as a non-object language."
              },
              {
                "code": "CSY1060",
                "title": "Mathematics for Computer Science",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This module introduces a set of mathematical topics, which include binary number system, logic circuits, linear systems, graph theory, probability and statistics, that are widely studied by those learning computing sciences. The module equips students with fundamental mathematical skills which underpin a range of computing disciplines."
              }
            ]
          },
          {
            "label": "Year II",
            "note": "Students must take all compulsory modules.",
            "modules": [
              {
                "code": "CSY2092",
                "title": "Operating Systems",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY1061",
                "description": "The purpose of this module is designed to give an understanding of the theory, application, structure and design principles of operating systems. This module requires a significant practical element delivered as formal laboratory sessions."
              },
              {
                "code": "CSY2087",
                "title": "Data Structures and Algorithms",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This module provides students with a conceptual understanding of common data structures and algorithms used in Computer Science and Software Engineering. It enables students to implement and evaluate a selection of algorithms and abstract data types, including linked lists, stacks, queues, graphs and binary trees using an object-oriented language."
              },
              {
                "code": "CSY2088",
                "title": "Group Project",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY1062 or CSY1063 or CSY1064 or CSY1060",
                "description": "The module is designed to develop higher-order intellectual skills (problem-solving) and appropriate personal qualities including team working. Each group will develop and document effective, robust and high-quality computing systems to a professional standard in response to a supplied specification of requirements."
              },
              {
                "code": "CSY2089",
                "title": "Web Programming",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY1063 and CSY1020",
                "description": "This purpose of this module is to give students an understanding of the concepts and technologies of web based server side technologies; teach students to use up-to-date programming techniques to design and develop coherent server side software for websites with a focus on security, functionality and usability."
              },
              {
                "code": "CSY2080",
                "title": "Relational Databases",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "The purpose of this module is to understand and apply the principles of database integrity to implement and utilise efficient databases. RD is a practical module that employs data modelling and SQL techniques to design, define and manipulate data."
              },
              {
                "code": "CSY2094",
                "title": "Software Systems Design & Development",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY1020 and CSY1062 or CSY1063 or CSY1064",
                "description": "This purpose of this module is to extend and apply system design and development to large scale systems; explore building GUIs so that the idea of specifying general software components and implementing re-usable classes will become familiar; provide tools and skills which the student will require when encountering design projects."
              }
            ]
          },
          {
            "label": "Year III",
            "note": "Students must take all compulsory modules.",
            "modules": [
              {
                "code": "CSY4022",
                "title": "Computing Dissertation",
                "credits": 40,
                "status": "Compulsory",
                "prerequisites": "Students undertaking this module should have successfully completed all level 4 and at least 100 credits at level 5.",
                "description": "This project module provides the opportunity for the student to undertake independent research, development, and self-management of a Computing related project leading to completing a dissertation. An essential outcome for this module is that the student’s project deliverable includes the design and development of a system, or a software application, or a novel functional approach that relates to the main areas of student study, and that can be used, applied or demonstrated in some way. Students on the BSc. Business Computing may engage on a research centered project resulting in a report of analysis of an appropriate topic."
              },
              {
                "code": "CSY3058",
                "title": "Media Technology",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY2089 or CSY2094",
                "description": "Media Technology is an important aspect to Computer Science. This module will introduce a range of technologies relevant to modern multimedia systems. This includes computer graphics, digital image processing, online video streaming, immersive media, and other advanced applications. Student will develop audio-visual systems in a third generation computer language."
              },
              {
                "code": "CSY3062",
                "title": "Cyber Security and Applied Cryptography",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "This module provides students with the necessary practical skills and theoretical understanding of the technologies used to secure communications and protect the privacy of users within an online environment. Concepts introduced, and skills learnt, provide the necessary technical underpinning to enable the student to address the issues of effective Security."
              },
              {
                "code": "CSY3059",
                "title": "Modern Databases",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "CSY2093 or CSY2080",
                "description": "The purpose of this module is to study advanced/latest database topics. The module focuses primarily on NoSQL databases (e.g., graph and document databases), from designing and creating to querying the databases."
              },
              {
                "code": "CSY3060",
                "title": "Advanced AI and Applications",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": "The purpose of this module is to teach students the fundamental theory and practical applications of: knowledge-based systems, artificial neural networks, and deep neural network. The underpinning concepts will be introduced, followed by examples of how intelligent systems are used in engineering, software, or computer science in general. Students will explore core AI techniques including supervised and unsupervised learning, with selected advanced topics introduced to extend their understanding of modern intelligent systems. The course combines conceptual learning with practical implementation, encouraging individual exploration through technical analysis and applied project work."
              }
            ]
          }
        ]
      },
      {
        "slug": "environmental-science",
        "qualification": "BSc. (Hons)",
        "title": "Environmental Science",
        "fullTitle": "BSc. (Hons) Environmental Science",
        "shortDescription": "Three-year honours degree combining ecology, physical science, and practical field and lab research.",
        "image": {
          "src": "/sections/general/degree (2).jpg",
          "alt": "NAMI ClimateAI Launchpad - Environmental Science and AI innovation initiative.",
          "width": 1500,
          "height": 1000
        },
        "awardingBody": "The University of Northampton, UK",
        "startingFrom": "",
        "format": "Three-year degree",
        "metaDescription": "BSc. (Hons) Environmental Science at NAMI, Kathmandu — a three-year degree awarded by the University of Northampton, UK, combining ecology and physical science with field and laboratory work.",
        "keyFacts": [
          {
            "label": "Programme Name",
            "value": "BSc. (Hons) Environmental Science"
          },
          {
            "label": "Level",
            "value": "Undergraduate Degree"
          },
          {
            "label": "Duration",
            "value": "Three-year degree"
          },
          {
            "label": "Location",
            "value": "New Baneshwor, Kathmandu"
          },
          {
            "label": "Awarding Institution",
            "value": "The University of Northampton, UK"
          },
          {
            "label": "Mode",
            "value": "Full Time"
          },
          {
            "label": "Total Credits",
            "value": "360"
          }
        ],
        "whatYoullStudy": "",
        "summary": [
          "A three-year degree combining ecology and physical science to evaluate environmental issues and propose appropriate solutions, and to recognise their relevance to society at national and global levels.",
          "Students undertake a wide variety of activities and encounter new challenges that support the theoretical learning. Accuracy, critical evaluation, the ability to research solutions and apply them in new ways, and the ability to communicate findings to a variety of audiences are all vital skills for an environmental scientist.",
          "Students examine research design and methodology across field and laboratory work — data collection, qualitative analysis and statistical tools — with field and lab activities running through the course so scientific concepts are developed in practice."
        ],
        "entryLabel": "Entry Requirements:",
        "entry": [
          {
            "label": "+2 (NEB)",
            "requirement": "Minimum of 55% (2.2 GPA) or equivalent."
          },
          {
            "label": "CBSE",
            "requirement": "Minimum of 60%."
          },
          {
            "label": "A Levels",
            "requirement": "280 UCAS tariff points."
          },
          {
            "label": "English",
            "requirement": "Minimum of 60 marks in English at +2 or CBSE, or an IELTS score of 6 with no band less than 5.5."
          }
        ],
        "entryNotes": [
          "Students awaiting results, and students who have completed a foundation or bridge course (Level 3) from a recognised institution, are also encouraged to apply.",
          "All decisions regarding an offer letter are made by the University of Northampton, UK."
        ],
        "careersLabel": "Career prospect",
        "careerSummary": "Graduates move into organisational projects directly, without intensive further training, across monitoring, conservation and consultancy work. The same research training supports a career as a researcher or independent consultant, and the sector runs from national monitoring and EIA work to the international agencies operating in Nepal.",
        "careerSectors": [
          "Environmental monitoring",
          "Conservation and wildlife",
          "Natural resource management",
          "Climate change and CDM projects",
          "IEE and EIA consultancy",
          "Environmental inspection (MOEST)",
          "International agencies (UNEP, UNDP, FAO, WWF, WHO, UNICEF, World Bank, ADB)"
        ],
        "pendingNote": "",
        "stagesNote": "",
        "stages": [
          {
            "label": "Year I",
            "note": "Students must take all compulsory modules for their pathway.",
            "modules": [
              {
                "code": "ENV1002",
                "title": "Introduction to Ecology",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV1110",
                "title": "Global Environmental Issues",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "GEO1108",
                "title": "Geohazards",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV1128",
                "title": "Lab and Field Skills",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV1126",
                "title": "Life on Earth",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV1127",
                "title": "Environmental Pollution",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year II",
            "note": "Students must take all compulsory modules for their pathway.",
            "modules": [
              {
                "code": "GEO2038",
                "title": "Research Methods",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV2125",
                "title": "International Environmental Policy & Control",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV2140",
                "title": "Terrestrial and Freshwater Ecosystems",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV2103",
                "title": "Biogeography",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV2124",
                "title": "Field Work Module",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV2142",
                "title": "Impacts of Pollution",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year III",
            "note": "Students must take all compulsory modules.",
            "modules": [
              {
                "code": "ENV4101",
                "title": "Research Project and Dissertation",
                "credits": 40,
                "status": "Compulsory",
                "prerequisites": "GEO2038 or equivalent",
                "description": ""
              },
              {
                "code": "ENV3013",
                "title": "Sustainable Development: Land Use and Planning",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV3143",
                "title": "Sustainable Resources Management",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENV3144",
                "title": "Pollution Monitoring and Control",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "GEO3124",
                "title": "Water Resource Management",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          }
        ]
      },
      {
        "slug": "environmental-studies",
        "qualification": "BES",
        "title": "Environmental Studies",
        "fullTitle": "Bachelors in Environmental Studies",
        "shortDescription": "Four-year bachelor's degree focusing on the social, economic, and ecological dimensions of environmental issues.",
        "image": {
          "src": "/gallery/Bachelors/Events/ClimateAI.jpeg",
          "alt": "NAMI Environmental Studies and ClimateAI innovation cohort.",
          "width": 1280,
          "height": 853
        },
        "awardingBody": "Kathmandu University",
        "startingFrom": "",
        "format": "4 years | 8 semesters",
        "metaDescription": "Bachelors in Environmental Studies (BES) at NAMI, Kathmandu — a four-year undergraduate programme awarded by Kathmandu University, focusing on the social, economic, and ecological dimensions of environmental issues.",
        "keyFacts": [
          {
            "label": "Programme Name",
            "value": "Bachelors in Environmental Studies"
          },
          {
            "label": "Level",
            "value": "Undergraduate Degree"
          },
          {
            "label": "Duration",
            "value": "4 years | 8 semesters"
          },
          {
            "label": "Location",
            "value": "New Baneshwor, Kathmandu"
          },
          {
            "label": "Awarding Institution",
            "value": "Kathmandu University"
          },
          {
            "label": "Mode",
            "value": "Full Time"
          },
          {
            "label": "Total Credits",
            "value": "127"
          }
        ],
        "whatYoullStudy": "",
        "summary": [
          "The Bachelors in Environmental Studies (BES) at NAMI, awarded by Kathmandu University, is a four-year undergraduate programme designed with focus on the social, economic, and ecological dimensions of environmental issues. Through an interdisciplinary curriculum bridging ecological science, socio-economic dynamics, and governance, students gain a holistic understanding of how living and non-living systems interact and develop sustainable solutions.",
          "Understanding Our Environment: Environment is not only the \"surrounding\" — it is the sum total of all the living and non-living entities affecting each other including humans. Environment is the ultimate resource for all living beings, but with human need and greed, the status of the environment is undergoing degradation, requiring multi-disciplinary intervention.",
          "A Multi-Disciplinary Curriculum: The environment has become the focus of many disciplines and discourses, encompassing biology, physics, chemistry, geography, sociology, economics, management, laws, governance and policies, ethics, and philosophy. Because environmental issues are now part of every career path and employment, holistic multi-disciplinary knowledge is essential.",
          "Practical & Field-Based Learning: At NAMI, environmental education is deeply immersive. Students participate in comprehensive field trips, in-house laboratory projects, GIS and remote sensing analysis, Environmental Impact Assessments (IEE/EIA), community-based learning, and internships at leading NGOs, INGOs, and research organisations.",
          "Course Highlights & Specialisations: BES is an eight-semester (four-year) programme. Featured courses include Green Entrepreneurship, Conservation and Protected Areas, Environmental Pollution, Indigenous Traditional Knowledge (ITK) and Practices, Environmental Arts and Design, Nature-Based Solutions and Innovation, Environmental Tourism, and Final Year Projects."
        ],
        "entryLabel": "Entry Requirements:",
        "entry": [
          {
            "label": "+2 / NEB (or Equivalent)",
            "requirement": "Nepali or non-Nepali nationals with 10+2 or equivalent level education of at least 1.60 CGPA or 40% in aggregate."
          },
          {
            "label": "GCE A Level",
            "requirement": "Passed in minimum three subjects in A Level and one General Paper in AS Level with minimum 40% PUM in aggregate."
          }
        ],
        "entryNotes": [
          "Admission is open to interested students from all high school streams including Science, Arts, Law, Management, Computer, etc., with the minimum qualification.",
          "Nepali and non-Nepali nationals are eligible for admission."
        ],
        "careersLabel": "Where Can BES Take You?",
        "careerSummary": "Environmental issues are now part of every career path and employment. The Bachelors in Environmental Studies equips graduates with holistic, multi-disciplinary expertise to pursue diverse career paths across public, private, research, and non-governmental organisations.",
        "careerSectors": [
          "Environmental Inspector",
          "Environmentalist",
          "Environmental Resource Manager",
          "Ecologist",
          "Conservationist",
          "Monitoring and Evaluation Expert (M&E)",
          "Gender Equity and Social Inclusion (GESI) Expert",
          "Sustainable and Climate Finance Expert",
          "IEE / EIA Expert",
          "Environmental Educator",
          "Environmental Analyst",
          "Environmental Researcher",
          "Environmental Consultant",
          "Environmental Reporter"
        ],
        "pendingNote": "",
        "stagesNote": "",
        "stages": [
          {
            "label": "Year 1 — Build Your Foundation in Environmental Science & Systems",
            "note": "Focus: Understand ecological systems and scientific fundamentals. Modules span Semester I & Semester II (32 credits total), covering introductory environmental studies, development practices, ecosystems of the world and Nepal, chemistry, biodiversity, economics, Nepali/English communication, and in-house projects.",
            "modules": [
              {
                "code": "BEST 101",
                "title": "Introduction to Environmental Studies",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 102",
                "title": "Developmental Practices and Environment",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 103",
                "title": "Ecosystem of the World and Nepal",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "NEPL 151",
                "title": "Communication Skills (Nepali)",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 111",
                "title": "Introduction to Economics",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 142",
                "title": "Environmental In-house Project",
                "credits": 1,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 104",
                "title": "Environmental Chemistry and the Major Material Cycle",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 105",
                "title": "Biodiversity and the Living World",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 106",
                "title": "Culture and Environment",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENG 152",
                "title": "Communication Skills (English)",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 128",
                "title": "Statistics I",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 141",
                "title": "Field Trip",
                "credits": 1,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year 2 — Environmental Dynamics & Natural Resource Management",
            "note": "Focus: Deepen scientific analysis and resource governance. Modules span Semester I & Semester II (34 credits total), covering climate dynamics, environmental physics, natural resource management, environmental statistics, sustainable development principles, pollution theory, geology, occupational health, and energy.",
            "modules": [
              {
                "code": "BEST 201",
                "title": "Climate and its Dynamics",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 202",
                "title": "Environmental Physics",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 203",
                "title": "Natural Resource Management",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 251",
                "title": "Environmental Statistics",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "CDEV 214",
                "title": "Sustainable Development: Principles & Practice",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "SOCL 206",
                "title": "Gender, Ethnicity and Social Inclusion",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 204",
                "title": "Environmental Pollution Theory & Practical",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 205",
                "title": "Environmental Geology",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 231",
                "title": "Environmental and Occupational Health",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 251",
                "title": "Energy and Environments",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "CDEV 220",
                "title": "Working with Organisations",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 241",
                "title": "Field Trip",
                "credits": 1,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year 3 — Conservation, Policy & Community Development",
            "note": "Focus: Bridge conservation, social systems, and legal frameworks. Modules span Semester I & Semester II (34 credits total), covering protected areas, indigenous knowledge, pollution control, research methods, disaster management, migration & mobility, environmental arts & design, food security, environmental sociology, conflict resolution, and environmental laws.",
            "modules": [
              {
                "code": "BEST 301",
                "title": "Conservation and Protected Area",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 302",
                "title": "Indigenous Knowledge and Environment",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 303",
                "title": "Pollution Control and Management",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "DEVS 305",
                "title": "Research Methods",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "DEVS 311",
                "title": "Disaster Management",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "CDEV 311",
                "title": "Migration, Mobility and Community Development",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 352",
                "title": "Environmental Arts, Designs and Engineering",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 304",
                "title": "Land & Food Security",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 345",
                "title": "Environmental Sociology",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "DEVS 302",
                "title": "Society and Conflict Resolution",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 351",
                "title": "Environmental Conventions, Policies and Laws",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 341",
                "title": "Field Trip",
                "credits": 1,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year 4 — Applied Assessment, Policy & Capstone Project",
            "note": "Focus: Apply professional assessment and research. Modules span Semester I & Semester II (27 credits total), covering urban planning, GIS and remote sensing, EIA/SIA, environmental economics, watershed management, media & environment, institutional internships, and an independent final year project.",
            "modules": [
              {
                "code": "DEVS 401",
                "title": "Urban Planning and Development",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ENVT 402",
                "title": "Geographic Information System and Remote Sensing",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "CDEV 401",
                "title": "Environmental and Social Impact Assessment",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BECO 413",
                "title": "Environmental Economics",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 443",
                "title": "Integrated Watershed Management",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 442",
                "title": "Mass Media and Environmental Issues",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 442",
                "title": "Internship at NGOs/INGOs/Research Organizations",
                "credits": 3,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BEST 499",
                "title": "Final Year Project",
                "credits": 6,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          }
        ]
      },
      {
        "slug": "business-administration",
        "qualification": "Bachelor",
        "title": "Business Administration",
        "fullTitle": "Bachelor of Business Administration",
        "shortDescription": "Build the knowledge, skills and confidence to succeed in the world of business.",
        "image": {
          "src": "/sections/general/degree (3).jpg",
          "alt": "NAMI Bachelor of Business Administration (BBA) auditorium seminar and conference.",
          "width": 1500,
          "height": 1000
        },
        "awardingBody": "The University of Northampton, UK",
        "startingFrom": "",
        "format": "3 years | 360 credits",
        "metaDescription": "Bachelor of Business Administration (BBA) at NAMI, Kathmandu — a three-year undergraduate programme awarded by the University of Northampton, UK, preparing students for careers in business, management, finance, marketing and entrepreneurship.",
        "keyFacts": [
          {
            "label": "Programme Name",
            "value": "Bachelor of Business Administration"
          },
          {
            "label": "Level",
            "value": "Undergraduate Degree"
          },
          {
            "label": "Duration",
            "value": "3 years | 360 credits"
          },
          {
            "label": "Location",
            "value": "New Baneshwor, Kathmandu"
          },
          {
            "label": "Awarding Institution",
            "value": "The University of Northampton, UK"
          },
          {
            "label": "Mode",
            "value": "Full Time"
          },
          {
            "label": "Total Credits",
            "value": "360"
          }
        ],
        "whatYoullStudy": "",
        "summary": [
          "The BBA at NAMI, awarded by the University of Northampton, UK, is a three-year undergraduate programme designed to prepare students for careers in business, management, finance, marketing, entrepreneurship and a wide range of professional sectors. Through a combination of academic learning, real-world case studies, business projects, presentations, teamwork, industry engagement and practical activities, students develop the knowledge and professional skills needed to navigate today's dynamic business environment.",
          "Why Study BBA at NAMI? Earn a UK University Award from the University of Northampton, giving you an internationally oriented business education. Develop practical business knowledge through case studies, business simulations, projects, presentations, discussions and problem-solving activities. Cultivate entrepreneurial thinking, gain a global business perspective across interconnected markets, and build practical expertise in finance, accounting, and data-informed decision-making.",
          "Learning Beyond the Classroom: At NAMI, business education goes far beyond textbooks and lectures. Students apply their learning through business simulations, case-study competitions, entrepreneurship activities, student-led projects, pitching sessions, industry and guest-speaker sessions, seminars, workshops, business and management events, student clubs and societies, and leadership initiatives.",
          "Skills You Will Develop: Throughout the programme, students build business and management expertise (strategic thinking, business decision-making, financial awareness, marketing knowledge, project management), professional excellence (communication, presentation, teamwork, leadership, negotiation), and future-focused capabilities (critical thinking, problem-solving, creativity, entrepreneurship, digital and analytical skills, and research skills).",
          "Is BBA Right for You? The BBA is ideal for students who are interested in business and management, want to understand how organisations work, are interested in entrepreneurship or starting their own venture, enjoy collaborating in teams, want to develop leadership acumen, or seek a broad business degree before specialising."
        ],
        "entryLabel": "Entry Requirements:",
        "entry": [
          {
            "label": "NEB +2",
            "requirement": "55% / 2.2 GPA or equivalent"
          },
          {
            "label": "CBSE",
            "requirement": "60%"
          },
          {
            "label": "A Levels",
            "requirement": "280 UCAS tariff points"
          },
          {
            "label": "English",
            "requirement": "60 marks in English at +2/CBSE or IELTS 6.0, no band below 5.5"
          }
        ],
        "entryNotes": [
          "Students awaiting results, and students who have completed a foundation or bridge course (Level 3) from a recognised institution, are also encouraged to apply.",
          "All decisions regarding an offer letter are made by the University of Northampton, UK."
        ],
        "careersLabel": "Where Can a BBA Take You?",
        "careerSummary": "A BBA can provide a foundation for careers across a wide range of business functions and sectors. Graduates are prepared for roles such as Business Executive, Marketing Executive, HR Executive, Banking Professional, Business Development Executive, Project Coordinator, Operations Executive, Entrepreneur, Sales Executive, and Management Trainee.",
        "careerSectors": [
          "Business Management",
          "Banking and Financial Services",
          "Marketing and Digital Marketing",
          "Human Resource Management",
          "Sales and Business Development",
          "Operations Management",
          "Project Management",
          "Entrepreneurship",
          "Consulting",
          "Customer Relationship Management",
          "Hospitality and Service Management",
          "Business Analysis",
          "Administration and Management"
        ],
        "pendingNote": "",
        "stagesNote": "",
        "stages": [
          {
            "label": "Year 1 — Build Your Business Foundation",
            "note": "Focus: Understand business. Develop a broad understanding of how businesses operate across marketing, accounting and finance, business environment, business in society, entrepreneurship, and people management.",
            "modules": [
              {
                "code": "MKT1001",
                "title": "Foundation of Marketing",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ACC1003",
                "title": "Introductory Finance and Accounting",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS1001",
                "title": "Business Environment",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS1009",
                "title": "Business in Society",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "MKT1003",
                "title": "Enterprise and Opportunity",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "HRM1004",
                "title": "Managing People",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year 2 — Develop Management Expertise",
            "note": "Focus: Manage and analyse business. Build deeper knowledge and develop practical management capabilities across strategic business analysis, human resources, operations, financial decision-making, project management, and brand management.",
            "modules": [
              {
                "code": "BUS2002",
                "title": "Strategic Business Analysis",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "HRM2003",
                "title": "Managing Human Resources",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BSO2003",
                "title": "Operations Management 1",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "ACC2004",
                "title": "Managing Finance & Financial Decisions",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "ACC1003",
                "description": ""
              },
              {
                "code": "BSO2016",
                "title": "Project Management: Planning and Control",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "MKT2006",
                "title": "Brand Management",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              }
            ]
          },
          {
            "label": "Year 3 — Think Strategically and Professionally",
            "note": "Focus: Lead, innovate and create solutions. Apply your knowledge to contemporary business challenges through innovation and entrepreneurship, strategic management, corporate social responsibility, global business, and an independent business dissertation (BUS4001).",
            "modules": [
              {
                "code": "MKT3026",
                "title": "Opportunity, Innovation and Entrepreneurship",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS3002",
                "title": "Debates in Strategic Management",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS3001",
                "title": "Social Responsibility of Business",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS3003",
                "title": "Global Business Development",
                "credits": 20,
                "status": "Compulsory",
                "prerequisites": "None",
                "description": ""
              },
              {
                "code": "BUS4001",
                "title": "Business Dissertation",
                "credits": 40,
                "status": "Designated",
                "prerequisites": "None",
                "description": ""
              }
            ]
          }
        ]
      }
    ]
  },
  "awarding": {
    "label": "Partner Universities awarding our degrees.",
    "title": "Awarding Universities",
    "description": "Taught at NAMI in Kathmandu, awarded by our accredited university partners.",
    "sinceLabel": "Since"
  },
  "pearson": {
    "label": "OFFICIAL TESTING CENTRE",
    "title": "Pearson VUE-Authorized Test Center",
    "description": "NAMI is an officially authorized Pearson VUE test center, empowering students and professionals across Nepal to take internationally recognized IT certifications, academic assessments, and global professional licensure examinations in a secure, state-of-the-art testing facility.",
    "logo": {
      "src": "/sections/misc/pearson-vue.jpg",
      "alt": "Pearson VUE-Authorized Test Center Logo",
      "width": 367,
      "height": 220
    }
  },
  "placement": {
    "label": "Industry partners and career placements.",
    "title": "Career Placement",
    "image": {
      "src": "/hero/student-life/student-life-hero.jpg",
      "alt": "Industry partner panel discussion and career placement session at NAMI.",
      "width": 1280,
      "height": 853
    }
  },
  "alumni": {
    "label": "In their own words, on what the degree is actually worth.",
    "title": "Student Voices",
    "description": "Hear directly from our students on the British system of learning, practical innovation, and personal growth at NAMI.",
    "emptyState": "Student stories will appear here as they are shared.",
    "items": [
      {
        "quote": "At NAMI, I learned that true family isn't just born the amazing friends I met here became my brothers for life..",
        "name": "Dhirendra Singh Khadka",
        "role": "BSc. Computer Science — Level 5 (Year II)",
        "portrait": {
          "src": "/testimonials/bachelors/dhirendra Singh Khadka.png",
          "alt": "Dhirendra Singh Khadka",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "Beyond academics, NAMI showed me that meaningful success comes from integrity, adaptability, and building genuine connections with people.",
        "name": "Rashmi KC",
        "role": "BBA — Level 4 (Year I)",
        "portrait": {
          "src": "/testimonials/bachelors/rashmi kc.png",
          "alt": "Rashmi KC",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "NAMI taught me to solve problems, collaborate effectively, and keep learning with confidence. These lessons will stay with me forever.",
        "name": "Smrit Chaulagain",
        "role": "BSc. Computer Science — Level 5 (Year II)",
        "portrait": {
          "src": "/testimonials/bachelors/smrit Chaulagai.png",
          "alt": "Smrit Chaulagain",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "NAMI has taught me that meaningful innovation begins with empathy, collaboration, and solving real-world problems to create lasting impact in our communities.",
        "name": "Subham Khadka",
        "role": "BSc. Computer Science — Level 5 (Year II)",
        "portrait": {
          "src": "/testimonials/bachelors/Subham_Khadka.png",
          "alt": "Subham Khadka",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "I learned that every challenge is an opportunity to grow, build confidence, and become a more responsible and resilient individual. .",
        "name": "Anish Babu Pokharel",
        "role": "BSc. Computer Science — Level 5 (Year II)",
        "portrait": {
          "src": "/testimonials/bachelors/anish_babu.png",
          "alt": "Anish Babu Pokharel",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "NAMI taught me to solve problems, collaborate effectively, and keep learning with confidence. These lessons will stay with me forever.",
        "name": "Renasha Dahal",
        "role": "BSc. Computer Science — Level 6 (Year III)",
        "portrait": {
          "src": "/testimonials/bachelors/renasha dahal.png",
          "alt": "Renasha Dahal",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "NAMI’s vibrant tech community and encouraging mentors transformed my learning into a journey of innovation, deep confidence, and lasting career readiness.",
        "name": "Aarya Adhikari",
        "role": "BSc. Computer Science — Level 6 (Year III)",
        "portrait": {
          "src": "/testimonials/bachelors/Aarya_Adhikari.png",
          "alt": "Aarya Adhikari",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "Tackling group projects with my classmates under tight deadlines, where shared stress turned hard work into unforgettable memories and genuine friendships.",
        "name": "Rhythm Manandhar",
        "role": "BSc. Computer Science — Level 6 (Year III)",
        "portrait": {
          "src": "/testimonials/bachelors/Rhythm_Manandhar.png",
          "alt": "Rhythm Manandhar",
          "width": 400,
          "height": 400
        }
      },
      {
        "quote": "The friendships I built, vibrant campus events, and shared laughter are memories I'll always cherish. More importantly, NAMI gave me the confidence to connect and communicate openly with others.",
        "name": "Dipa Chaulagain",
        "role": "BSc. Computer Science — Level 5 (Year II)",
        "portrait": {
          "src": "/testimonials/bachelors/Dipa_Chaulagain.png",
          "alt": "Dipa Chaulagain",
          "width": 400,
          "height": 400
        }
      }
    ]
  },
  "mou": {
    "label": "Strategic Alliances",
    "title": "MoU Signed Partners",
    "description": "Naaya Aayam Multi-Disciplinary Institute establishes institutional MoUs with leading enterprises across technology, hospitality, architecture, and innovation sectors to foster real-world industrial exposure, student internships, and dynamic career pathways.",
    "badge": "Verified MoU Partner",
    "partners": [
      {
        "organization": "Web Surfer The Broad Band Company",
        "domain": "Broadband & Telecommunications",
        "logo": {
          "src": "/logos/mou/websurfer-logo-brighter1920x658-removebg-preview.png",
          "alt": "Web Surfer The Broad Band Company logo",
          "width": 854,
          "height": 292
        }
      },
      {
        "organization": "Machan Wildlife Resort Pvt. Ltd",
        "domain": "Eco-Tourism & Hospitality",
        "logo": {
          "src": "/logos/mou/machian-removebg-preview.png",
          "alt": "Machan Wildlife Resort Pvt. Ltd logo",
          "width": 447,
          "height": 447
        }
      },
      {
        "organization": "Suraj Interior And Designers Pvt. Ltd",
        "domain": "Architecture & Interior Design",
        "logo": {
          "src": "/logos/mou/Suraj-removebg-preview.png",
          "alt": "Suraj Interior And Designers Pvt. Ltd logo",
          "width": 447,
          "height": 559
        }
      },
      {
        "organization": "Cross Web Office Automation Pvt. Ltd",
        "domain": "Office Automation & IT Solutions",
        "logo": {
          "src": "/logos/mou/Cross_web-removebg-preview.png",
          "alt": "Cross Web Office Automation Pvt. Ltd logo",
          "width": 400,
          "height": 400
        }
      },
      {
        "organization": "Startup Discovery Asia",
        "domain": "Incubation & Venture Acceleration",
        "logo": {
          "src": "/logos/mou/Startup_Discovery-removebg-preview.png",
          "alt": "Startup Discovery Asia logo",
          "width": 480,
          "height": 175
        }
      }
    ]
  },
  "notices": {
    "title": "Notice Board",
    "description": "Registration windows, submission deadlines and standing notices for undergraduate and postgraduate students.",
    "buttonLabel": "All Institute Notices",
    "emptyState": "There is no institute notice standing right now. Everything the institute has published stays on the notice board."
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
