<?php
/**
 * NAMI CMS — CTEVT page
 *
 * Requires the "NAMI CMS — Core engine" snippet (version with nested lists).
 * Adds a "CTEVT" menu to the WordPress sidebar with one sub-menu per section of
 * the /institutions/ctevt page (also served at /ctevt).
 *
 * Field keys must match src/lib/cms/pages/ctevt/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};
		$bold  = 'Wrap words in **double asterisks** to make them bold.';

		$pages['ctevt'] = array(
			'title'      => 'CTEVT',
			'menu_title' => 'CTEVT',
			'icon'       => 'dashicons-hammer',
			'position'   => 3.6,
			'path'       => '/institutions/ctevt',
			'sections'   => array(

				'hero'        => array(
					'title'       => 'Header',
					'description' => 'The top of the page with the CTEVT logo box on the right.',
					'fields'      => array(
						'label'          => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'          => array( 'type' => 'text', 'label' => 'Title' ),
						'subtitle'       => array( 'type' => 'text', 'label' => 'Subtitle (red)' ),
						'intro'          => array( 'type' => 'textarea', 'label' => 'Intro text', 'rows' => 3, 'help' => $bold ),
						'logo'           => $image( 'Logo', 'Remove the logo to hide the box.' ),
						'logoCaption'    => array( 'type' => 'text', 'label' => 'Text under the logo' ),
						'logoSubcaption' => array( 'type' => 'text', 'label' => 'Small text under that' ),
					),
				),

				'overview'    => array(
					'title'       => 'Overview Statement',
					'description' => 'The highlighted statement in the pink box.',
					'fields'      => array(
						'text' => array( 'type' => 'textarea', 'label' => 'Statement', 'rows' => 4, 'help' => $bold . ' Leave empty to hide the box.' ),
					),
				),

				'programmes'  => array(
					'title'       => 'Approved Programs',
					'description' => 'The table of CTEVT-approved training programs.',
					'fields'      => array(
						'label'            => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'            => array( 'type' => 'text', 'label' => 'Title' ),
						'description'      => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						'programmeHeading' => array( 'type' => 'text', 'label' => 'Column heading: program' ),
						'sectorHeading'    => array( 'type' => 'text', 'label' => 'Column heading: sector' ),
						'durationHeading'  => array( 'type' => 'text', 'label' => 'Column heading: duration' ),
						'items'            => array(
							'type'        => 'repeater',
							'label'       => 'Programs',
							'item_label'  => 'Program',
							'title_field' => 'title',
							'fields'      => array(
								'title'    => array( 'type' => 'text', 'label' => 'Program name' ),
								'sector'   => array( 'type' => 'text', 'label' => 'Sector & specialization' ),
								'duration' => array( 'type' => 'text', 'label' => 'Duration', 'placeholder' => '390 Hours' ),
							),
						),
					),
				),

				'about'       => array(
					'title'       => 'About CTEVT',
					'description' => 'The left card below the table.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'paragraphs'  => array( 'type' => 'paragraphs', 'label' => 'Text', 'rows' => 8, 'help' => 'Leave an empty line between paragraphs. ' . $bold ),
						'footerLeft'  => array( 'type' => 'text', 'label' => 'Footer text (left)' ),
						'footerRight' => array( 'type' => 'text', 'label' => 'Footer text (right, red)' ),
					),
				),

				'approval'    => array(
					'title'       => 'NAMI\'s Approval',
					'description' => 'The right card with the approval details.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'items'      => array(
							'type'        => 'repeater',
							'label'       => 'Details',
							'item_label'  => 'Detail',
							'title_field' => 'label',
							'fields'      => array(
								'label' => array( 'type' => 'text', 'label' => 'Label' ),
								'value' => array( 'type' => 'textarea', 'label' => 'Value', 'rows' => 2 ),
							),
						),
						'note'       => array( 'type' => 'textarea', 'label' => 'Note (italic, under the details)', 'rows' => 2 ),
						'footerLeft' => array( 'type' => 'text', 'label' => 'Footer text (left)' ),
						'badge'      => array( 'type' => 'text', 'label' => 'Green status badge', 'help' => 'Leave empty to hide.' ),
					),
				),

				'standards'   => array(
					'title'       => 'Training Standards',
					'description' => 'The grid of tick-marked standards.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						'items'       => array( 'type' => 'lines', 'label' => 'Standards', 'rows' => 9, 'help' => 'One per line. Empty list hides this section.' ),
					),
				),

				'skills'      => array(
					'title'       => 'Hospitality Skills',
					'description' => 'The grey box with skill tags at the bottom.',
					'fields'      => array(
						'label'      => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Text', 'rows' => 8, 'help' => 'Leave an empty line between paragraphs. ' . $bold ),
						'tags'       => array( 'type' => 'lines', 'label' => 'Skill tags', 'rows' => 5, 'help' => 'One per line.' ),
					),
				),

				'recognition' => array(
					'title'       => 'Official Recognition',
					'description' => 'The card with the approval letter button.',
					'fields'      => array(
						'label'         => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'         => array( 'type' => 'text', 'label' => 'Title' ),
						'subtitle'      => array( 'type' => 'text', 'label' => 'Subtitle (red)' ),
						'description'   => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'facts'         => array(
							'type'        => 'repeater',
							'label'       => 'Fact chips',
							'item_label'  => 'Fact',
							'title_field' => 'label',
							'fields'      => array(
								'label' => array( 'type' => 'text', 'label' => 'Label' ),
								'value' => array( 'type' => 'text', 'label' => 'Value (bold)' ),
							),
						),
						'letterButton'  => array( 'type' => 'link', 'label' => 'Approval letter button', 'help' => 'Opens in a new tab. To use a new letter, upload it under Media → Add New, copy its "File URL" and paste it as the link. Leave the button text empty to hide the button.' ),
						'contactButton' => array( 'type' => 'link', 'label' => 'Second button' ),
					),
				),

				'commitment'  => array(
					'title'       => 'Our Commitment',
					'description' => 'The red banner at the end of the page.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title', 'help' => 'Leave empty to hide the banner.' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 3 ),
						'button'      => array( 'type' => 'link', 'label' => 'Button' ),
					),
				),

				'seo'         => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "CTEVT Affiliation & Vocational Programmes | NAMI",
    "description": "NAMI is a CTEVT-affiliated institution authorized to conduct approved short-term vocational training programs in the hospitality sector in Kathmandu, Nepal."
  },
  "hero": {
    "label": "Vocational & Technical Education",
    "title": "CTEVT Affiliation",
    "subtitle": "Council for Technical Education and Vocational Training",
    "intro": "**Naaya Aayam Multi-Disciplinary Institute Pvt. Ltd. (NAMI)** is a CTEVT-affiliated institution authorized to conduct approved short-term vocational training programs in the hospitality sector.",
    "logo": {
      "src": "/logos/brand/ctevt-logo-removebg-preview.png",
      "alt": "CTEVT Logo",
      "width": 474,
      "height": 349
    },
    "logoCaption": "Government of Nepal",
    "logoSubcaption": "Apex Body for Technical Training"
  },
  "overview": {
    "text": "The affiliation reflects NAMI's commitment to providing structured, practical and industry-oriented vocational education in accordance with the curriculum and requirements prescribed by the **Council for Technical Education and Vocational Training (CTEVT), Nepal**."
  },
  "programmes": {
    "label": "Approved Courses",
    "title": "CTEVT-Approved Training Programs",
    "description": "NAMI is authorized to conduct 5 specialized short-term vocational training programs tailored for the growing hospitality and service industries.",
    "programmeHeading": "Training Program",
    "sectorHeading": "Sector & Specialization",
    "durationHeading": "Duration",
    "items": [
      {
        "title": "General Cook Commis II",
        "sector": "Culinary & Kitchen Operations",
        "duration": "484 Hours"
      },
      {
        "title": "Hotel Assistant",
        "sector": "Hospitality Management",
        "duration": "390 Hours"
      },
      {
        "title": "Barista",
        "sector": "Beverage & Coffee Art",
        "duration": "390 Hours"
      },
      {
        "title": "Bartender",
        "sector": "Beverage Service & Mixology",
        "duration": "390 Hours"
      },
      {
        "title": "Room Attendant",
        "sector": "Housekeeping Operations",
        "duration": "390 Hours"
      }
    ]
  },
  "about": {
    "label": "National Apex Body",
    "title": "About CTEVT",
    "paragraphs": [
      "The **Council for Technical Education and Vocational Training (CTEVT)** is Nepal's national apex body for technical and vocational education and training. CTEVT is responsible for areas including curriculum development, quality control, skills standards, skills testing and the development of skilled human resources.",
      "Through its affiliation, NAMI conducts approved short-term training programs following the applicable CTEVT curriculum, standards and institutional requirements."
    ],
    "footerLeft": "Accreditation: National Standards",
    "footerRight": "CTEVT Nepal"
  },
  "approval": {
    "label": "Verification & Review",
    "title": "NAMI's CTEVT Approval",
    "items": [
      {
        "label": "Institution",
        "value": "Naaya Aayam Multi-Disciplinary Institute Pvt. Ltd."
      },
      {
        "label": "Address",
        "value": "Jorpati-07, Kathmandu, Nepal"
      },
      {
        "label": "Type of Approval",
        "value": "Short-Term Training Programs"
      },
      {
        "label": "Approval Period",
        "value": "Two years, as specified in the CTEVT approval letter"
      },
      {
        "label": "Approving Authority",
        "value": "Council for Technical Education and Vocational Training (CTEVT), Nepal"
      }
    ],
    "note": "The approval was granted following the required institutional review and inspection process.",
    "footerLeft": "Official Approval Record",
    "badge": "Approved & Active"
  },
  "standards": {
    "label": "Quality Framework",
    "title": "Training Standards",
    "description": "NAMI's approved programs are conducted in strict accordance with the requirements specified by CTEVT:",
    "items": [
      "Delivery of training according to the approved CTEVT curriculum",
      "Maintenance of required physical and educational facilities",
      "Practical and competency-oriented training",
      "Compliance with prescribed trainee admission procedures",
      "Training conducted at the approved institutional location",
      "Compliance with applicable assessment and skill-testing requirements",
      "Certification of eligible trainees in accordance with applicable CTEVT provisions",
      "Submission of required institutional and progress reports to CTEVT"
    ]
  },
  "skills": {
    "label": "Career Readiness",
    "title": "Skills for the Hospitality Industry",
    "paragraphs": [
      "NAMI's CTEVT-approved programs focus on developing practical skills relevant to hospitality and service-sector employment. The programs provide learners with structured training in areas including **culinary operations, hotel services, coffee preparation, beverage service and housekeeping**.",
      "Through practical learning and occupation-specific training, NAMI aims to equip learners with skills that can be applied in professional hospitality environments."
    ],
    "tags": [
      "Culinary Operations",
      "Hotel Services",
      "Coffee Preparation",
      "Beverage Service",
      "Housekeeping"
    ]
  },
  "recognition": {
    "label": "Institutional Certification",
    "title": "Official Recognition",
    "subtitle": "CTEVT Affiliated Institution — Approved Short-Term Training Programs",
    "description": "NAMI's CTEVT affiliation and approved programs are documented through the official approval issued by the Council for Technical Education and Vocational Training.",
    "facts": [
      {
        "label": "Approved Programs",
        "value": "5"
      },
      {
        "label": "Training Duration",
        "value": "390–484 Hours"
      },
      {
        "label": "Approval",
        "value": "CTEVT Short-Term Training Programs"
      }
    ],
    "letterButton": {
      "label": "View CTEVT Approval Letter",
      "href": "/hero/ctevt/ctevt-hero.jpeg"
    },
    "contactButton": {
      "label": "Inquire About Admissions",
      "href": "/contact"
    }
  },
  "commitment": {
    "label": "Our Commitment",
    "title": "Learn. Practice. Build Skills.",
    "description": "NAMI is committed to maintaining the standards and requirements associated with its CTEVT-approved programs and to providing learners with quality vocational education, practical training and industry-relevant skills.",
    "button": {
      "label": "Apply for Vocational Training",
      "href": "/admissions"
    }
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
