<?php
/**
 * NAMI CMS — Site Settings (names, contact details, campuses, footer, header menu,
 * enroll banner, newsletter, contact block labels, floating buttons)
 *
 * Requires the "NAMI CMS — Core engine" snippet.
 * Adds a "Site Settings" menu to the WordPress sidebar. These details are shared
 * by every page: the header, footer, "Contact & Location" blocks, floating
 * buttons and the information Google reads about NAMI.
 *
 * Field keys must match src/lib/cms/pages/site/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$campus = function () {
			return array(
				'locality'      => array( 'type' => 'text', 'label' => 'Area', 'placeholder' => 'Gokarneshwor-7' ),
				'city'          => array( 'type' => 'text', 'label' => 'City' ),
				'streetAddress' => array( 'type' => 'text', 'label' => 'Street address (optional)', 'help' => 'Shown before the area, e.g. "Shantinagar Marg, House No. 27".' ),
				'hosts'         => array( 'type' => 'lines', 'label' => 'What is taught here', 'rows' => 4, 'help' => 'One per line.' ),
				'mapUrl'        => array( 'type' => 'url', 'label' => 'Google Maps link', 'help' => 'The "Get directions" link. In Google Maps: Share → Copy link.' ),
				'embedMapUrl'   => array( 'type' => 'url', 'label' => 'Google Maps embed link', 'help' => 'The map shown on the page. In Google Maps: Share → Embed a map → copy only the address inside src="…". If empty, a map is made from the area and city.' ),
			);
		};

		$office = function ( $who, $name ) {
			return array(
				$who . 'Phones'          => array( 'type' => 'lines', 'label' => $name . ': phone numbers', 'rows' => 3, 'help' => 'One per line. Extensions can be written like +977-01-4917441/42/43.' ),
				$who . 'Email'           => array( 'type' => 'text', 'label' => $name . ': email' ),
				$who . 'AdmissionsEmail' => array( 'type' => 'text', 'label' => $name . ': admissions email (optional)' ),
				$who . 'Facebook'        => array( 'type' => 'url', 'label' => $name . ': Facebook page (optional)', 'help' => 'Replaces the main Facebook link for this institution.' ),
			);
		};

		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$links = function ( $label, $item ) {
			return array(
				'type'        => 'repeater',
				'label'       => $label,
				'item_label'  => $item,
				'title_field' => 'label',
				'fields'      => array(
					'label' => array( 'type' => 'text', 'label' => 'Text' ),
					'href'  => array( 'type' => 'url', 'label' => 'Link' ),
				),
			);
		};

		$pages['site'] = array(
			'title'      => 'Site Settings',
			'menu_title' => 'Site Settings',
			'icon'       => 'dashicons-admin-site-alt3',
			'position'   => 3.05,
			'path'       => '/',
			'sections'   => array(

				'names'        => array(
					'title'       => 'Names & Motto',
					'description' => 'The names used across the whole website (header, footer, page headings, Google).',
					'fields'      => array(
						'instituteName'      => array( 'type' => 'text', 'label' => 'Institute: full name' ),
						'instituteShortName' => array( 'type' => 'text', 'label' => 'Institute: short name' ),
						'instituteYear'      => array( 'type' => 'number', 'label' => 'Institute: year established', 'help' => 'Shown in the footer as "Estd. …". 0 hides it.' ),
						'collegeName'        => array( 'type' => 'text', 'label' => 'College (A Levels): full name' ),
						'collegeShortName'   => array( 'type' => 'text', 'label' => 'College: short name' ),
						'collegeYear'        => array( 'type' => 'number', 'label' => 'College: year established' ),
						'schoolName'         => array( 'type' => 'text', 'label' => 'School: full name' ),
						'schoolShortName'    => array( 'type' => 'text', 'label' => 'School: short name' ),
						'schoolYear'         => array( 'type' => 'number', 'label' => 'School: year established' ),
						'motto'              => array( 'type' => 'text', 'label' => 'Motto' ),
					),
				),

				'contact'      => array(
					'title'       => 'Contact & Social Media',
					'description' => 'The main contact details and social media links used across the website.',
					'fields'      => array(
						'phones'   => array( 'type' => 'lines', 'label' => 'Main phone numbers', 'rows' => 4, 'help' => 'One per line.' ),
						'email'    => array( 'type' => 'text', 'label' => 'Main email' ),
						'whatsapp' => array( 'type' => 'text', 'label' => 'WhatsApp number or username' ),
						'websites' => $links( 'Other websites (shown in the menu)', 'Website' ),
						'socials'  => array(
							'type'        => 'repeater',
							'label'       => 'Social media',
							'item_label'  => 'Account',
							'title_field' => 'platform',
							'fields'      => array(
								'platform' => array(
									'type'    => 'select',
									'label'   => 'Platform',
									'options' => array(
										'facebook'  => 'Facebook',
										'instagram' => 'Instagram',
										'linkedin'  => 'LinkedIn',
										'youtube'   => 'YouTube',
										'tiktok'    => 'TikTok',
										'whatsapp'  => 'WhatsApp (chat link)',
									),
								),
								'href'     => array( 'type' => 'url', 'label' => 'Link' ),
							),
						),
					),
				),

				'offices'      => array(
					'title'       => 'Institution Contacts',
					'description' => 'Each institution\'s own phone numbers and emails, shown in the footer and in the "Contact & Location" block on its pages. Fields are grouped: school first, then college (A Levels), then institute (Bachelors).',
					'fields'      => array_merge(
						$office( 'school', 'School' ),
						$office( 'college', 'College (A Levels)' ),
						$office( 'institute', 'Institute (Bachelors)' )
					),
				),

				'gokarneshwor' => array(
					'title'       => 'Gokarneshwor Campus',
					'description' => 'The School, +2 and A Levels campus. Shown in the "Contact & Location" block on those pages and in the menu.',
					'fields'      => $campus(),
				),

				'newBaneshwor' => array(
					'title'       => 'New Baneshwor Campus',
					'description' => 'The Bachelors campus. Shown in the "Contact & Location" block on the Bachelors pages and in the menu.',
					'fields'      => $campus(),
				),

				'footer'       => array(
					'title'       => 'Footer',
					'description' => 'The red footer at the bottom of every page. Phone numbers and emails come from Institution Contacts; social icons from Contact & Social Media.',
					'fields'      => array(
						'about'            => array( 'type' => 'textarea', 'label' => 'About text (under the logo)', 'rows' => 4 ),
						'quickLinksTitle'  => array( 'type' => 'text', 'label' => 'Quick links heading' ),
						'quickLinks'       => $links( 'Quick links', 'Link' ),
						'contactsTitle'    => array( 'type' => 'text', 'label' => 'Contacts heading' ),
						'schoolTagline'    => array( 'type' => 'text', 'label' => 'Line under the school name' ),
						'collegeTagline'   => array( 'type' => 'text', 'label' => 'Line under the college name' ),
						'instituteTagline' => array( 'type' => 'text', 'label' => 'Line under the institute name' ),
						'bottomLinks'      => $links( 'Links in the bottom bar', 'Link' ),
					),
				),

				'menu'         => array(
					'title'       => 'Header Menu',
					'description' => 'The menu at the top of every page, and the panel that opens with the menu button.',
					'fields'      => array(
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Menu items',
							'item_label'  => 'Menu item',
							'title_field' => 'label',
							'fields'      => array(
								'label'      => array( 'type' => 'text', 'label' => 'Text' ),
								'href'       => array( 'type' => 'url', 'label' => 'Link' ),
								'descriptor' => array( 'type' => 'text', 'label' => 'Short description (optional)' ),
								'children'   => array(
									'type'        => 'repeater',
									'label'       => 'Drop-down links (optional)',
									'item_label'  => 'Sub-link',
									'title_field' => 'label',
									'fields'      => array(
										'label' => array( 'type' => 'text', 'label' => 'Text' ),
										'href'  => array( 'type' => 'url', 'label' => 'Link' ),
									),
								),
							),
						),
						'panelText'   => array( 'type' => 'textarea', 'label' => 'Menu panel: intro text', 'rows' => 3, 'help' => 'Shown under the logo when the menu panel is open on a computer.' ),
						'panelImage'  => $image( 'Menu panel: photo' ),
						'panelButton' => array( 'type' => 'link', 'label' => 'Menu panel: button on the photo' ),
					),
				),

				'enroll'       => array(
					'title'       => 'Enroll Banner',
					'description' => 'The "Ready to Enroll?" banner near the bottom of each institution\'s pages. The phone number in it comes from Institution Contacts.',
					'fields'      => array(
						'helpText'             => array( 'type' => 'text', 'label' => 'Text before the phone number', 'placeholder' => 'Need help? Call Admissions at' ),
						'schoolHeading'        => array( 'type' => 'text', 'label' => 'School: heading' ),
						'schoolDescription'    => array( 'type' => 'textarea', 'label' => 'School: text', 'rows' => 3 ),
						'schoolApply'          => array( 'type' => 'link', 'label' => 'School: main button' ),
						'schoolBrochure'       => array( 'type' => 'link', 'label' => 'School: second button' ),
						'collegeHeading'       => array( 'type' => 'text', 'label' => 'College (A Levels): heading' ),
						'collegeDescription'   => array( 'type' => 'textarea', 'label' => 'College: text', 'rows' => 3 ),
						'collegeApply'         => array( 'type' => 'link', 'label' => 'College: main button' ),
						'collegeBrochure'      => array( 'type' => 'link', 'label' => 'College: second button' ),
						'instituteHeading'     => array( 'type' => 'text', 'label' => 'Institute (Bachelors): heading' ),
						'instituteDescription' => array( 'type' => 'textarea', 'label' => 'Institute: text', 'rows' => 3 ),
						'instituteApply'       => array( 'type' => 'link', 'label' => 'Institute: main button' ),
						'instituteBrochure'    => array( 'type' => 'link', 'label' => 'Institute: second button' ),
					),
				),

				'newsletter'   => array(
					'title'       => 'Newsletter',
					'description' => 'The dark "Subscribe to our Newsletter" band with the QR code (above the footer, and on institution pages). The line under the heading is the page\'s institution name.',
					'fields'      => array(
						'heading'          => array( 'type' => 'text', 'label' => 'Heading' ),
						'qr'               => $image( 'QR code', 'Remove it to hide the QR code.' ),
						'namePlaceholder'  => array( 'type' => 'text', 'label' => 'Hint in the name box' ),
						'emailPlaceholder' => array( 'type' => 'text', 'label' => 'Hint in the email box' ),
						'buttonLabel'      => array( 'type' => 'text', 'label' => 'Button text' ),
					),
				),

				'contactBlock' => array(
					'title'       => 'Contact Block Labels',
					'description' => 'The headings in the "Contact & Location" block at the end of each institution\'s page. The details themselves come from Institution Contacts and the campus sections.',
					'fields'      => array(
						'label'        => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'        => array( 'type' => 'text', 'label' => 'Title' ),
						'addressLabel' => array( 'type' => 'text', 'label' => 'Address label' ),
						'phoneLabel'   => array( 'type' => 'text', 'label' => 'Phone label' ),
						'emailLabel'   => array( 'type' => 'text', 'label' => 'Email label' ),
						'followLabel'  => array( 'type' => 'text', 'label' => 'Text before the institution name above the social icons', 'placeholder' => 'Follow' ),
					),
				),

				'floating'     => array(
					'title'       => 'Floating Buttons',
					'description' => 'The red buttons fixed to the right edge of the screen on computers: downloads and WhatsApp. The WhatsApp number comes from Contact & Social Media. PDF links open in a new tab and download.',
					'fields'      => array(
						'downloadLabel'   => array( 'type' => 'text', 'label' => 'Download button name (read by screen readers)' ),
						'formsLabel'      => array( 'type' => 'text', 'label' => 'First list: name' ),
						'forms'           => $links( 'First list: links', 'Link' ),
						'brochuresLabel'  => array( 'type' => 'text', 'label' => 'Second list: name' ),
						'brochures'       => $links( 'Second list: links', 'Link' ),
						'whatsappLabel'   => array( 'type' => 'text', 'label' => 'WhatsApp button tooltip' ),
						'whatsappMessage' => array( 'type' => 'textarea', 'label' => 'Message pre-filled in WhatsApp', 'rows' => 2 ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "names": {
    "instituteName": "Naaya Aayam Multi-Disciplinary Institute",
    "instituteShortName": "NAMI",
    "instituteYear": 2012,
    "collegeName": "NAMI College",
    "collegeShortName": "NAMI",
    "collegeYear": 2013,
    "schoolName": "NAMI International School",
    "schoolShortName": "NAMI International School",
    "schoolYear": 2019,
    "motto": "Transform Yourself to Lead the World"
  },
  "contact": {
    "phones": [
      "+977-01-4917441/42/43/44",
      "+977-01-4913353",
      "+977-01-5920335/36"
    ],
    "email": "info@nami.edu.np",
    "whatsapp": "namicollege",
    "websites": [
      {
        "label": "school.nami.edu.np",
        "href": "https://school.nami.edu.np"
      },
      {
        "label": "college.nami.edu.np",
        "href": "https://college.nami.edu.np/"
      }
    ],
    "socials": [
      {
        "platform": "whatsapp",
        "href": "https://wa.me/namicollege?text=Hello%20NAMI%2C%20I%20would%20like%20to%20enquire%20about%20admissions%20and%20programmes."
      },
      {
        "platform": "facebook",
        "href": "https://www.facebook.com/share/1CS5HvZ6xf/?mibextid=wwXIfr"
      },
      {
        "platform": "instagram",
        "href": "https://www.instagram.com/nami.college"
      },
      {
        "platform": "linkedin",
        "href": "https://www.linkedin.com/company/13186439/"
      },
      {
        "platform": "youtube",
        "href": "https://www.youtube.com/@naminepal"
      },
      {
        "platform": "tiktok",
        "href": "https://www.tiktok.com/@nami.college?_r=1&_t=ZS-99xxwcx4jFE"
      }
    ]
  },
  "offices": {
    "schoolPhones": [
      "+977-01-4917441/42/43/44",
      "+977-01-4913353"
    ],
    "schoolEmail": "info@nami.edu.np",
    "schoolAdmissionsEmail": "admissions@nami.edu.np",
    "schoolFacebook": "https://www.facebook.com/share/1DpZc6ubM8/?mibextid=wwXIfr",
    "collegePhones": [
      "+977-01-4917441/42/43/44",
      "+977-01-4913353"
    ],
    "collegeEmail": "info@nami.edu.np",
    "collegeAdmissionsEmail": "admissions@nami.edu.np",
    "collegeFacebook": "https://www.facebook.com/share/1513mfhP69m/?mibextid=wwXIfr",
    "institutePhones": [
      "+977-01-5920335/36"
    ],
    "instituteEmail": "info@nami.edu.np",
    "instituteAdmissionsEmail": "admissions@nami.edu.np",
    "instituteFacebook": "https://www.facebook.com/share/1CS5HvZ6xf/?mibextid=wwXIfr"
  },
  "gokarneshwor": {
    "locality": "Gokarneshwor-7",
    "city": "Kathmandu",
    "streetAddress": "",
    "hosts": [
      "School, Grade I–VII",
      "+2 NEB, Science and Management",
      "Cambridge A Level"
    ],
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=NAMI+College%2C+Jorpati%2C+Gokarneshwor%2C+Kathmandu",
    "embedMapUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d882.9749868182432!2d85.38358969999999!3d27.720375300000008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1bbf46821009%3A0xb8e1a147cb4dc56c!2sNaya%20Aayam%20Multi-Disciplinary%20Institute!5e0!3m2!1sen!2sin!4v1791065660030!5m2!1sen!2sin"
  },
  "newBaneshwor": {
    "locality": "New Baneshwor",
    "city": "Kathmandu",
    "streetAddress": "Shantinagar Marg, House No. 27",
    "hosts": [
      "Undergraduate programmes",
      "Postgraduate programmes"
    ],
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=NAMI+College%2C+New+Baneshwor%2C+Kathmandu",
    "embedMapUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28263.043992494844!2d85.30609671562503!3d27.690088099999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb19cc4a60df7d%3A0xa3d62c8a38b7e837!2sNAMI%20COLLEGE%20bachelors%20block!5e0!3m2!1sen!2sin!4v1791065743872!5m2!1sen!2sin"
  },
  "footer": {
    "about": "Naaya Aayam Multi-Disciplinary Institute (NAMI) is an educational entity established in 2012, committed to advancing human capital through world-class education, global standards and holistic development while empowering individuals with the knowledge, skills and leadership capabilities to create meaningful impact locally and globally.",
    "quickLinksTitle": "Quick Links",
    "quickLinks": [
      {
        "label": "Home",
        "href": "/"
      },
      {
        "label": "About Us",
        "href": "/about"
      },
      {
        "label": "Admissions",
        "href": "/admissions"
      },
      {
        "label": "Documents & Downloads",
        "href": "/documents"
      },
      {
        "label": "Student Life",
        "href": "/student-life"
      },
      {
        "label": "Photo Gallery",
        "href": "/gallery"
      },
      {
        "label": "Alumni",
        "href": "/alumni"
      },
      {
        "label": "Notices & Events",
        "href": "/notices"
      }
    ],
    "contactsTitle": "Institutions & Contacts",
    "schoolTagline": "School & +2 NEB",
    "collegeTagline": "Cambridge Assessment GCE A Levels",
    "instituteTagline": "Undergraduate & Postgraduate Programmes",
    "bottomLinks": [
      {
        "label": "Official Documents",
        "href": "/documents"
      },
      {
        "label": "Privacy Policy",
        "href": "/privacy"
      },
      {
        "label": "Terms & Conditions",
        "href": "/terms"
      }
    ]
  },
  "menu": {
    "items": [
      {
        "label": "Home",
        "href": "/",
        "descriptor": "Start your journey here.",
        "children": []
      },
      {
        "label": "About Us",
        "href": "/about",
        "descriptor": "Discover our mission, vision, and values.",
        "children": [
          {
            "label": "Our Story",
            "href": "/about"
          },
          {
            "label": "Messages from Leadership",
            "href": "/about#leadership-messages"
          },
          {
            "label": "History of NAMI",
            "href": "/about#history"
          },
          {
            "label": "Faculty & Leadership",
            "href": "/faculty"
          }
        ]
      },
      {
        "label": "Institutions",
        "href": "/institutions/a-levels",
        "descriptor": "Explore our institutions, each separately accredited.",
        "children": [
          {
            "label": "NAMI International School",
            "href": "/institutions/school"
          },
          {
            "label": "NAMI A-Levels",
            "href": "/institutions/a-levels"
          },
          {
            "label": "Naaya Aayam Multi-Disciplinary Institute",
            "href": "/institutions/bachelors"
          },
          {
            "label": "CTEVT Vocational Programmes",
            "href": "/institutions/ctevt"
          }
        ]
      },
      {
        "label": "Admissions",
        "href": "/admissions",
        "descriptor": "Join our diverse community.",
        "children": []
      },
      {
        "label": "Gallery",
        "href": "/gallery",
        "descriptor": "View our photo gallery.",
        "children": []
      },
      {
        "label": "Alumni",
        "href": "/alumni",
        "descriptor": "Our global alumni network, stories, and impact.",
        "children": []
      }
    ],
    "panelText": "NAMI provides world-class education with state-of-the-art facilities, empowering students to become future leaders and innovators.",
    "panelImage": {
      "src": "/sections/nami/campus-library.jpg",
      "alt": "College Library",
      "width": 1280,
      "height": 853
    },
    "panelButton": {
      "label": "Apply Now",
      "href": "/admissions"
    }
  },
  "enroll": {
    "helpText": "Need help? Call Admissions at",
    "schoolHeading": "Ready to Enroll?",
    "schoolDescription": "We are here to guide you through every step of the admissions process. If you have any questions or need assistance, our admissions team is ready to help.",
    "schoolApply": {
      "label": "Apply Now",
      "href": "/admissions"
    },
    "schoolBrochure": {
      "label": "Brochure",
      "href": "/admissions"
    },
    "collegeHeading": "Ready to Enroll?",
    "collegeDescription": "We are here to guide you through every step of the Cambridge A-Level admissions process. If you have any questions, our admissions desk is here to support you.",
    "collegeApply": {
      "label": "Apply Now",
      "href": "/admissions"
    },
    "collegeBrochure": {
      "label": "Prospectus",
      "href": "/admissions"
    },
    "instituteHeading": "Ready to Enroll?",
    "instituteDescription": "We are here to guide you through every step of university admissions. If you have any questions about Northampton UK degree programmes, our advisors are ready to assist.",
    "instituteApply": {
      "label": "Apply Now",
      "href": "/admissions"
    },
    "instituteBrochure": {
      "label": "Prospectus",
      "href": "/admissions"
    }
  },
  "newsletter": {
    "heading": "Subscribe to our Newsletter",
    "qr": {
      "src": "/sections/misc/newsletter-qr.png",
      "alt": "Scan to subscribe to NAMI Newsletter",
      "width": 710,
      "height": 710
    },
    "namePlaceholder": "Your name",
    "emailPlaceholder": "you@example.com",
    "buttonLabel": "Subscribe"
  },
  "contactBlock": {
    "label": "Get in Touch with NAMI",
    "title": "Contact & Location",
    "addressLabel": "Campus Address",
    "phoneLabel": "Phone Numbers",
    "emailLabel": "Email Inquiries",
    "followLabel": "Follow"
  },
  "floating": {
    "downloadLabel": "Download Forms & Brochures",
    "formsLabel": "Application Forms",
    "forms": [
      {
        "label": "Primary School",
        "href": "/documents/Nami International School (Primary) Admission form.pdf"
      },
      {
        "label": "+2 NEB",
        "href": "/documents/Application_form_nami_international_school_plus_2.pdf"
      },
      {
        "label": "A-Levels",
        "href": "/documents/NAMI_College_A_Level_Application_Form.pdf"
      },
      {
        "label": "Bachelors",
        "href": "/documents/Nami_applicationform_bachelors.pdf"
      }
    ],
    "brochuresLabel": "Brochures",
    "brochures": [
      {
        "label": "Primary School",
        "href": "/institutions/school"
      },
      {
        "label": "+2 NEB",
        "href": "/institutions/school"
      },
      {
        "label": "A-Levels",
        "href": "/institutions/a-levels"
      },
      {
        "label": "Bachelors",
        "href": "/documents/Nami book.pdf"
      }
    ],
    "whatsappLabel": "Chat on WhatsApp",
    "whatsappMessage": "Hello NAMI, I would like to enquire about admissions, programmes, and campus visits."
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
