<?php
/**
 * NAMI CMS — Clubs (School and A-Levels clubs and their pages)
 *
 * Requires the "NAMI CMS — Core engine" snippet (version with nested lists).
 * Adds a "Clubs" menu to the WordPress sidebar with one sub-menu for the
 * School clubs and one for the A-Levels clubs. Each club feeds its card on the
 * School / A-Levels page and its own page at
 * /institutions/{school|a-levels}/clubs/{web address}.
 *
 * Field keys must match src/lib/cms/pages/clubs/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$clubs = function ( $base ) use ( $image ) {
			return array(
				'type'        => 'repeater',
				'label'       => 'Clubs',
				'item_label'  => 'Club',
				'title_field' => 'title',
				'fields'      => array(
					'slug'            => array( 'type' => 'text', 'label' => 'Web address', 'help' => 'The club page lives at ' . $base . '/<this>. Lowercase words with hyphens, e.g. sports-club. Changing it breaks old links to the club.' ),
					'title'           => array( 'type' => 'text', 'label' => 'Club name' ),
					'category'        => array( 'type' => 'text', 'label' => 'Category', 'placeholder' => 'Athletics & Physical Fitness' ),
					'tagline'         => array( 'type' => 'textarea', 'label' => 'Short description (on the card)', 'rows' => 2 ),
					'coverImage'      => $image( 'Cover photo', 'Used on the card and at the top of the club page. A club without a cover photo is hidden.' ),
					'metaDescription' => array( 'type' => 'textarea', 'label' => 'Search & sharing description', 'rows' => 2, 'help' => 'How the club page appears in Google and on social media. About 150 characters.' ),
					'overview'        => array( 'type' => 'paragraphs', 'label' => 'About the club', 'rows' => 8 ),
					'quoteText'       => array( 'type' => 'textarea', 'label' => 'Highlighted quote', 'rows' => 2 ),
					'quoteAuthor'     => array( 'type' => 'text', 'label' => 'Quote by' ),
					'objectives'      => array( 'type' => 'lines', 'label' => 'Objectives', 'rows' => 5, 'help' => 'One per line.' ),
					'activities'      => array(
						'type'        => 'repeater',
						'label'       => 'Key activities',
						'item_label'  => 'Activity',
						'title_field' => 'title',
						'fields'      => array(
							'title'       => array( 'type' => 'text', 'label' => 'Title' ),
							'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
							'tag'         => array( 'type' => 'text', 'label' => 'Tag', 'placeholder' => 'Annual Flagship' ),
						),
					),
					'skills'          => array(
						'type'        => 'repeater',
						'label'       => 'Skills developed',
						'item_label'  => 'Skill',
						'title_field' => 'title',
						'fields'      => array(
							'title'       => array( 'type' => 'text', 'label' => 'Skill' ),
							'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						),
					),
					'gallery'         => array(
						'type'        => 'repeater',
						'label'       => 'Photo gallery',
						'item_label'  => 'Photo',
						'title_field' => 'caption',
						'fields'      => array(
							'image'   => $image( 'Photo' ),
							'caption' => array( 'type' => 'text', 'label' => 'Caption (optional)' ),
						),
					),
					'meetingSchedule' => array( 'type' => 'text', 'label' => 'Meeting schedule' ),
					'eligibility'     => array( 'type' => 'text', 'label' => 'Who can join' ),
					'facultyMentor'   => array( 'type' => 'text', 'label' => 'Faculty mentor / department' ),
				),
			);
		};

		$pages['clubs'] = array(
			'title'      => 'Clubs',
			'menu_title' => 'Clubs',
			'icon'       => 'dashicons-groups',
			'position'   => 3.65,
			'sections'   => array(

				'school'  => array(
					'title'       => 'School Clubs',
					'description' => 'The club cards on the School page (in the +2 section) and each club\'s own page. Click a club to open it.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label above the cards' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title above the cards' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description above the cards', 'rows' => 2 ),
						'items'       => $clubs( '/institutions/school/clubs' ),
					),
				),

				'aLevels' => array(
					'title'       => 'A-Levels Clubs',
					'description' => 'The club cards on the A-Levels page and each club\'s own page. The heading above the cards is edited under A-Levels → ECA & Clubs. Click a club to open it.',
					'fields'      => array(
						'items' => $clubs( '/institutions/a-levels/clubs' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "school": {
    "label": "Extracurricular & Co-Curricular",
    "title": "ECA & Clubs",
    "description": "Five vibrant student-led clubs nurturing physical vitality, creative expression, leadership, social empathy, and scientific inquiry.",
    "items": [
      {
        "slug": "sports-club",
        "title": "Sports Club",
        "category": "Athletics & Physical Fitness",
        "tagline": "Fostering athleticism, discipline, teamwork, and sportsmanship through competitive and recreational sports.",
        "metaDescription": "NAMI International School Sports Club promotes fitness, inter-house leagues, basketball tournaments, and football championships for all student grades.",
        "coverImage": {
          "src": "/gallery/Sports Club/Annual Sports Meet/Basketball-upright.jpg",
          "alt": "NAMI International School students engaged in competitive sports and basketball tournaments.",
          "width": 2400,
          "height": 3200
        },
        "overview": [
          "The NAMI Sports Club is dedicated to building strong physical health, stamina, and camaraderie among students. We believe sports teach values that extend far beyond the pitch — resilience under pressure, strategic thinking, mutual trust, and humble victory.",
          "With access to an NBA-standard basketball court, a mini-football field, table tennis arenas, and athletic running tracks, members participate in weekly training sessions, intra-school house leagues, and regional inter-school championships under the guidance of certified sports coaches."
        ],
        "quoteText": "Sports do not merely build character — they reveal it on the court and shape lifelong leaders.",
        "quoteAuthor": "Sports Club Coordinator",
        "objectives": [
          "Develop athletic prowess, cardiovascular fitness, and fundamental movement skills.",
          "Promote the values of sportsmanship, fairness, and perseverance.",
          "Provide regular opportunities for competitive and friendly sporting fixtures.",
          "Identify and nurture student athletic talent for national and regional tournaments."
        ],
        "activities": [
          {
            "title": "Annual Sports Meet & Athletic Championship",
            "description": "The flagship school-wide athletic event featuring track & field races, relay sprints, long jump, and house championships.",
            "tag": "Annual Flagship"
          },
          {
            "title": "Inter-House Football & Futsal League",
            "description": "Seasonal tournaments across junior and senior divisions on the school's mini-football ground.",
            "tag": "Tournament"
          },
          {
            "title": "SEE & +2 3x3 Basketball Cup",
            "description": "High-energy 3x3 basketball invitational tournament hosting teams across Kathmandu valley.",
            "tag": "Invitational"
          },
          {
            "title": "Weekly Fitness & Conditioning Clinics",
            "description": "Regular training sessions covering endurance building, agility drills, and yoga/stretching routines.",
            "tag": "Weekly Routine"
          }
        ],
        "skills": [
          {
            "title": "Teamwork & Synergy",
            "description": "Understanding individual roles within a team to achieve shared collective victory."
          },
          {
            "title": "Resilience & Mental Toughness",
            "description": "Bouncing back from setbacks and maintaining composure during high-stakes moments."
          },
          {
            "title": "Tactical Acumen",
            "description": "Quick decision-making, spatial awareness, and strategic planning in real time."
          },
          {
            "title": "Physical Wellness",
            "description": "Establishing lifelong habits of cardiovascular fitness and bodily health."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Sports Club/Annual Sports Meet/Basketball-upright.jpg",
              "alt": "Inter-house basketball championship fixture",
              "width": 2400,
              "height": 3200
            },
            "caption": "Inter-house basketball championship match"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Intra Futsal/4fe72723-53bd-4408-a417-776bb9af9ce1.jfif",
              "alt": "Intra-school futsal tournament on the green turf ground",
              "width": 1280,
              "height": 960
            },
            "caption": "Intra-school green turf futsal league"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Annual Sports Meet/Carrom.JPG",
              "alt": "Indoor carrom championship round",
              "width": 6000,
              "height": 4000
            },
            "caption": "Indoor precision carrom contest"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Inter School Basketball/46dcb38e-ac84-4ac8-b0ea-a11f6cb8f43b.jfif",
              "alt": "Valley-wide inter-school basketball playoffs",
              "width": 1280,
              "height": 960
            },
            "caption": "Inter-school basketball invitational cup"
          }
        ],
        "meetingSchedule": "Tuesdays & Thursdays (3:30 PM – 5:00 PM)",
        "eligibility": "Open to students from Grade 1 to Grade 12 (+2)",
        "facultyMentor": "Department of Physical Education & Sports"
      },
      {
        "slug": "art-and-literature-club",
        "title": "Art and Literature Club",
        "category": "Creative Expression & Humanities",
        "tagline": "Igniting imagination, storytelling, poetic expression, visual arts, and literary appreciation.",
        "metaDescription": "Explore creative writing, fine arts, drama, poetry, and publishing with the NAMI International School Art and Literature Club.",
        "coverImage": {
          "src": "/gallery/Art and literature/Art Competition/20251224_101654.jpg",
          "alt": "Students showcasing artistic creativity and live painting during the school art competition.",
          "width": 4000,
          "height": 3000
        },
        "overview": [
          "The Art and Literature Club serves as the creative heartbeat of NAMI International School. It is an open studio and salon where young authors, poets, painters, illustrators, and theatrical performers converge to celebrate the beauty of human expression.",
          "From writing short fiction and reciting poetry to acrylic canvas painting, clay sculpting, and staging dramatic plays, students are encouraged to find their unique voice and express bold perspectives."
        ],
        "quoteText": "Art gives form to our deepest feelings, and words give wings to our wildest imaginations.",
        "quoteAuthor": "Literary Faculty Advisor",
        "objectives": [
          "Cultivate refined creative writing, storytelling, and poetic composition skills in English and Nepali.",
          "Foster artistic techniques in sketching, acrylic painting, sculpture, and mixed media.",
          "Encourage public speaking, theatrical performance, and debate among students.",
          "Publish the annual student-curated school literary magazine and art anthology."
        ],
        "activities": [
          {
            "title": "Annual School Art & Sculpture Exhibition",
            "description": "A curated public gallery showcasing paintings, clay models, and craftwork created by students across all grades.",
            "tag": "Exhibition"
          },
          {
            "title": "Poetry Slam & Creative Writing Fest",
            "description": "Spoken-word sessions and flash-fiction competitions celebrating diverse literary voices.",
            "tag": "Festival"
          },
          {
            "title": "Theatrical Drama & Monologue Showcase",
            "description": "Full-stage plays and Shakespearean/Nepali drama staged inside the 250+ seat school auditorium.",
            "tag": "Performance"
          },
          {
            "title": "The Lotus Quill — School Magazine Publishing",
            "description": "Student-led editorial board producing the school's periodic literary journal and gazette.",
            "tag": "Publishing"
          }
        ],
        "skills": [
          {
            "title": "Creative Artistry",
            "description": "Mastery of visual composition, color theory, brushwork, and conceptual crafting."
          },
          {
            "title": "Articulate Storytelling",
            "description": "Expressing complex human emotions and structured narratives with eloquence."
          },
          {
            "title": "Critical Thinking",
            "description": "Analyzing classic and contemporary literature to develop nuanced philosophical worldviews."
          },
          {
            "title": "Stage Presence",
            "description": "Confidence in public speaking, declamation, and theatrical expression."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Art and literature/Art Competition/20251224_101654.jpg",
              "alt": "Pupils immersed in live watercolor and sketching contest",
              "width": 4000,
              "height": 3000
            },
            "caption": "Live sketching & acrylic painting competition"
          },
          {
            "image": {
              "src": "/gallery/Art and literature/Art Competition/20251224_110720.jpg",
              "alt": "Creative artwork and visual illustrations in classroom",
              "width": 4000,
              "height": 2252
            },
            "caption": "Classroom mixed-media art studio"
          },
          {
            "image": {
              "src": "/gallery/Art and literature/PPts/IMG-42c20df59da55331efb1eb2055eddc72-V.jpg",
              "alt": "Digital storytelling and literature presentation slide deck",
              "width": 1191,
              "height": 717
            },
            "caption": "Digital storytelling & prose presentation"
          },
          {
            "image": {
              "src": "/gallery/Art and literature/PPts/IMG-b5bc243a81739f47f9b8eb0ea6f3de35-V.jpg",
              "alt": "Poetic analysis and creative writing review",
              "width": 973,
              "height": 709
            },
            "caption": "Poetry critique & literary analysis"
          }
        ],
        "meetingSchedule": "Wednesdays & Fridays (3:30 PM – 4:45 PM)",
        "eligibility": "Open to students from Grade 1 to Grade 12 (+2)",
        "facultyMentor": "Department of Languages & Fine Arts"
      },
      {
        "slug": "event-management-club",
        "title": "Event Management Club",
        "category": "Leadership & Stage Operations",
        "tagline": "Orchestrating memorable school functions, cultural galas, assemblies, and stage productions.",
        "metaDescription": "Learn public relations, stage lighting, sound engineering, logistics, and executive event coordination with NAMI Event Management Club.",
        "coverImage": {
          "src": "/gallery/Event Management/Award & Cultural/DSC08026.JPG",
          "alt": "NAMI International School auditorium stage and cultural performance prepared for a grand student production.",
          "width": 4734,
          "height": 4000
        },
        "overview": [
          "The Event Management Club is the powerhouse behind every major event, assembly, cultural festival, and ceremony at NAMI International School. Students learn the intricate arts of event design, timeline planning, sound engineering, backstage coordination, and hospitality management.",
          "Members collaborate with faculty and student council to plan budgets, design invitations, manage stage lighting, anchor ceremonies, and ensure that every school celebration runs with seamless precision."
        ],
        "quoteText": "Behind every great show is an invisible team whose precision and passion make magic look effortless.",
        "quoteAuthor": "Event Club President",
        "objectives": [
          "Master end-to-end event planning, budgeting, hospitality, and scheduling.",
          "Operate professional audio-visual, acoustic, and lighting equipment in the auditorium.",
          "Develop executive leadership, crisis management, and diplomatic communication skills.",
          "Host memorable assemblies, guest lectures, cultural festivals, and graduation galas."
        ],
        "activities": [
          {
            "title": "Annual Day & Cultural Extravaganza",
            "description": "End-to-end management of the school's signature annual showcase, coordinating 500+ performers and guests.",
            "tag": "Mega Production"
          },
          {
            "title": "Teachers' Day & Children's Day Galas",
            "description": "Student-curated celebrations with stage surprises, awards, and entertainment programs.",
            "tag": "Celebration"
          },
          {
            "title": "Guest Speaker & Leadership Series",
            "description": "Hosting diplomats, entrepreneurs, and thought leaders for auditorium panel discussions.",
            "tag": "Symposium"
          },
          {
            "title": "Backstage & AV Technical Workshops",
            "description": "Hands-on training in stage acoustics, digital mixers, spotlighting, and broadcast live-streaming.",
            "tag": "Technical Training"
          }
        ],
        "skills": [
          {
            "title": "Executive Leadership",
            "description": "Leading cross-functional teams and assigning responsibilities under time constraints."
          },
          {
            "title": "Crisis Resolution",
            "description": "Thinking on your feet to resolve unexpected technical or logistical issues calmly."
          },
          {
            "title": "Public Emceeing & PR",
            "description": "Polished stage presence, professional announcing, and audience engagement."
          },
          {
            "title": "AV Production & Tech",
            "description": "Operating modern digital soundboards, acoustic consoles, and multimedia projectors."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Event Management/Award & Cultural/DSC08026.JPG",
              "alt": "Cultural dance performance and stage lighting in auditorium",
              "width": 4734,
              "height": 4000
            },
            "caption": "Auditorium stage lighting & cultural performance"
          },
          {
            "image": {
              "src": "/gallery/Event Management/Award & Cultural/3.jpg",
              "alt": "Annual awards ceremony and student honors",
              "width": 2231,
              "height": 2149
            },
            "caption": "Annual awards & ceremony protocol"
          },
          {
            "image": {
              "src": "/gallery/Event Management/Orientation Program/_GN_1060.jpg",
              "alt": "Orientation assembly in the main auditorium",
              "width": 6641,
              "height": 4427
            },
            "caption": "Auditorium orientation assembly"
          },
          {
            "image": {
              "src": "/gallery/Event Management/Welcome Program/IMG_9595.JPG",
              "alt": "Stage lighting and technical coordination",
              "width": 5282,
              "height": 3521
            },
            "caption": "Stage lighting & audio-visual management"
          }
        ],
        "meetingSchedule": "Mondays & Thursdays (3:30 PM – 5:00 PM)",
        "eligibility": "Open to students from Grade 6 to Grade 12 (+2)",
        "facultyMentor": "Student Affairs & Cultural Committee"
      },
      {
        "slug": "social-service-club",
        "title": "Social Service Club",
        "category": "Community Outreach & Sustainability",
        "tagline": "Cultivating empathy, humanitarian outreach, environmental stewardship, and civic responsibility.",
        "metaDescription": "Engage in community service camps, environmental tree plantation, disaster relief drives, and social welfare with NAMI Social Service Club.",
        "coverImage": {
          "src": "/gallery/Social Service Club/Donation Camp/4-upright.jpg",
          "alt": "NAMI International School students distributing relief materials during a community service outreach camp.",
          "width": 1800,
          "height": 2400
        },
        "overview": [
          "Rooted in the NAMI philosophy that education must contribute meaningfully to society, the Social Service Club instills deep civic consciousness and active compassion in every member. We believe that true education is measured by how effectively we uplift those around us.",
          "The club organizes community service camps in rural districts, environmental cleanups along local river corridors, textbook donation drives, and sustainability campaigns to protect Nepal's natural ecology."
        ],
        "quoteText": "The smallest act of kindness is worth more than the grandest intention. We serve because we care.",
        "quoteAuthor": "Service Learning Coordinator",
        "objectives": [
          "Instill empathy, social consciousness, and altruism as core personal virtues.",
          "Organize recurring relief drives, health awareness camps, and educational support programs.",
          "Champion environmental sustainability through tree plantations and zero-waste campus drives.",
          "Partner with verified non-profits and community organizations across Nepal."
        ],
        "activities": [
          {
            "title": "Rural Outreach & Relief Camp (Sindhupalchowk)",
            "description": "Annual field expedition delivering educational supplies, warm winter clothes, and health aid to mountain community schools.",
            "tag": "Outreach Camp"
          },
          {
            "title": "World Environment Day Tree Plantation",
            "description": "Afforestation drives planting indigenous saplings across Gokarneshwor and surrounding community forests.",
            "tag": "Ecology"
          },
          {
            "title": "Book & Warm Clothes Donation Drive",
            "description": "Student-led collection and distribution campaigns assisting underprivileged children and elderly care homes.",
            "tag": "Charity Drive"
          },
          {
            "title": "Clean Campus & Zero-Waste Campaign",
            "description": "Workshops on waste segregation, organic composting, and reducing single-use plastics.",
            "tag": "Sustainability"
          }
        ],
        "skills": [
          {
            "title": "Empathetic Citizenship",
            "description": "Gaining deep perspective on social disparities and active ways to contribute to national well-being."
          },
          {
            "title": "Community Mobilization",
            "description": "Rallying peers, parents, and community stakeholders for impactful charitable causes."
          },
          {
            "title": "Environmental Stewardship",
            "description": "Understanding ecological systems and practical carbon-reduction strategies."
          },
          {
            "title": "Ethical Leadership",
            "description": "Leading initiatives with integrity, transparency, and genuine respect for diverse communities."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Social Service Club/Donation Camp/4-upright.jpg",
              "alt": "Student volunteers packaging community relief kits",
              "width": 1800,
              "height": 2400
            },
            "caption": "Relief kit sorting & charity packaging"
          },
          {
            "image": {
              "src": "/gallery/Social Service Club/Donation Camp/5.jpg",
              "alt": "Distributing warm clothing to community families",
              "width": 960,
              "height": 1280
            },
            "caption": "Winter relief & clothing distribution"
          },
          {
            "image": {
              "src": "/gallery/Social Service Club/Blood Donation/Blood Donation..jpg",
              "alt": "Campus blood donation camp banner",
              "width": 986,
              "height": 1339
            },
            "caption": "Campus voluntary blood donation drive"
          },
          {
            "image": {
              "src": "/gallery/Social Service Club/Blood Donation/IMG-c96541748440d49ea99a6c662ccc1edd-V.jpg",
              "alt": "Youth volunteers supporting medical donors",
              "width": 913,
              "height": 1438
            },
            "caption": "Youth medical volunteer support"
          }
        ],
        "meetingSchedule": "Fridays (3:30 PM – 5:00 PM) + Weekend Field Trips",
        "eligibility": "Open to students from Grade 1 to Grade 12 (+2)",
        "facultyMentor": "Social Sciences & Community Outreach Cell"
      },
      {
        "slug": "science-and-technology-club",
        "title": "Science and Technology Club",
        "category": "STEM, Robotics & Innovation",
        "tagline": "Exploring scientific frontiers, robotics, software coding, and experimental discovery.",
        "metaDescription": "Build robots, code software, conduct laboratory experiments, and innovate at the NAMI International School Science and Technology Club.",
        "coverImage": {
          "src": "/gallery/Science & Tech/bio Excursion/IMG-4c57ac4b6ca59fd28fd1d147218f6fe3-V.jpg",
          "alt": "Students conducting biological field research and science experiments in the advanced NAMI science laboratory.",
          "width": 1600,
          "height": 900
        },
        "overview": [
          "The Science and Technology Club is a dynamic incubator for young inventors, coders, aspiring engineers, and curious researchers. From building autonomous micro-robots and writing Python algorithms to conducting chemical titration experiments, members explore how STEM transforms our world.",
          "Leveraging modern science laboratories, high-speed computer labs, and interactive hardware toolkits, students translate classroom theory into hands-on inventions that solve real-world challenges."
        ],
        "quoteText": "Science is not just a subject — it is a way of questioning, experimenting, and innovating for the future.",
        "quoteAuthor": "STEM Club Mentor",
        "objectives": [
          "Foster rigorous scientific methodology, inquiry-based thinking, and hypothesis testing.",
          "Teach practical software programming, web development, and robotics hardware interfacing.",
          "Conduct engaging laboratory experiments across Physics, Chemistry, and Biological sciences.",
          "Prepare student teams for national STEM fairs, hackathons, and science olympiads."
        ],
        "activities": [
          {
            "title": "Annual STEM & Science Innovation Fair",
            "description": "Student teams present working prototypes, automated robots, and scientific research posters to expert judges.",
            "tag": "Innovation Fair"
          },
          {
            "title": "Robotics & Microcontroller Workshop",
            "description": "Hands-on building of line-following bots, obstacle sensors, and automated smart-home circuits.",
            "tag": "Robotics"
          },
          {
            "title": "Coding Hackathon & App Challenge",
            "description": "A 24-hour collaborative coding sprint designing software solutions for educational and everyday problems.",
            "tag": "Hackathon"
          },
          {
            "title": "Practical Laboratory Masterclasses",
            "description": "Advanced titration, molecular biology extraction, and physics optics experiments beyond standard textbooks.",
            "tag": "Lab Masterclass"
          }
        ],
        "skills": [
          {
            "title": "Algorithmic & Computational Thinking",
            "description": "Decomposing complex problems into logical, code-driven step-by-step algorithms."
          },
          {
            "title": "Hardware Engineering",
            "description": "Working with microcontrollers, breadboards, sensors, servos, and electronic circuits."
          },
          {
            "title": "Empirical Research",
            "description": "Designing rigorous experiments, recording accurate data, and drawing evidence-backed conclusions."
          },
          {
            "title": "Innovation Mindset",
            "description": "Transforming abstract theoretical concepts into functional physical and digital prototypes."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Science & Tech/bio Excursion/IMG-4c57ac4b6ca59fd28fd1d147218f6fe3-V.jpg",
              "alt": "Students exploring botanical species during outdoor field excursion",
              "width": 1600,
              "height": 900
            },
            "caption": "Outdoor biology field excursion & research"
          },
          {
            "image": {
              "src": "/gallery/Science & Tech/bio Excursion/IMG-f46f1eb2db148ca96464c442f1ba0e6c-V.jpg",
              "alt": "Botanical taxonomy and field observation",
              "width": 1600,
              "height": 900
            },
            "caption": "Botanical taxonomy & nature study"
          },
          {
            "image": {
              "src": "/sections/nami/nami-school-science-lab.jpg",
              "alt": "Junior science laboratory practical demonstration",
              "width": 1000,
              "height": 750
            },
            "caption": "Hands-on laboratory apparatus & experiments"
          },
          {
            "image": {
              "src": "/sections/nami/nami-school-computer-lab.jpg",
              "alt": "Digital ICT and coding workstations",
              "width": 1000,
              "height": 750
            },
            "caption": "ICT coding & digital literacy workshops"
          }
        ],
        "meetingSchedule": "Tuesdays & Wednesdays (3:30 PM – 5:00 PM)",
        "eligibility": "Open to students from Grade 3 to Grade 12 (+2)",
        "facultyMentor": "Department of Science & Computer Studies"
      }
    ]
  },
  "aLevels": {
    "items": [
      {
        "slug": "social-services",
        "title": "Social Services",
        "category": "Community Outreach & Humanitarian Aid",
        "tagline": "Driving impactful social initiatives, community outreach camps, disaster relief drives, and social welfare projects.",
        "metaDescription": "NAMI College A-Levels Social Services Club engages students in community relief camps, blood donation drives, and public welfare campaigns.",
        "coverImage": {
          "src": "/sections/nami/campus-service-camp.jpg",
          "alt": "NAMI College A-Levels students organizing community service materials during an outreach camp.",
          "width": 1190,
          "height": 793
        },
        "overview": [
          "The Social Services Club at NAMI College embodies the belief that academic brilliance must be matched with social empathy and active civic leadership. The club offers Cambridge A-Level students a structured platform to understand social realities and organize tangible relief for underserved communities across Nepal.",
          "From running annual educational and winter-relief camps in remote hill districts to hosting blood donation drives and partnering with local grassroots shelters, members develop profound empathy, logistical acumen, and ethical leadership."
        ],
        "quoteText": "True leadership begins when we dedicate our knowledge and resources to uplifting the community around us.",
        "quoteAuthor": "Social Services Faculty Mentor",
        "objectives": [
          "Instill active humanitarian empathy, altruism, and civic responsibility among A-Level students.",
          "Organize annual rural community outreach expeditions delivering education and health aid.",
          "Coordinate quarterly campus blood donation drives and emergency relief campaigns.",
          "Partner with verified non-profits and community organizations across Nepal."
        ],
        "activities": [
          {
            "title": "Sindhupalchowk Rural Outreach Camp",
            "description": "Annual expedition delivering school supplies, winter clothing, and hygiene essentials to rural community schools.",
            "tag": "Annual Expedition"
          },
          {
            "title": "Campus Blood Donation & Health Drive",
            "description": "Quarterly blood collection camps organized in partnership with the Nepal Red Cross Society.",
            "tag": "Health & Welfare"
          },
          {
            "title": "Book & Warm Clothes Collection Drive",
            "description": "Student-led mobilization drives collecting and distributing study materials to underprivileged youth.",
            "tag": "Community Drive"
          },
          {
            "title": "Community Tutoring & Literacy Program",
            "description": "Weekly volunteer tutoring sessions conducted by A-Level students for local municipal school children.",
            "tag": "Weekly Volunteering"
          }
        ],
        "skills": [
          {
            "title": "Empathetic Leadership",
            "description": "Leading high-impact initiatives with compassion, integrity, and cultural humility."
          },
          {
            "title": "Project Management",
            "description": "Managing logistical planning, supply chain coordination, and field budgeting."
          },
          {
            "title": "Community Engagement",
            "description": "Communicating effectively with municipal leaders, non-profit stakeholders, and local families."
          },
          {
            "title": "Crisis Response",
            "description": "Mobilizing rapid volunteer relief and aid campaigns during national contingencies."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Social Service Club/Donation Camp/4-upright.jpg",
              "alt": "Community relief supplies and charity package packing",
              "width": 1800,
              "height": 2400
            },
            "caption": "Relief supplies packaging & distribution"
          },
          {
            "image": {
              "src": "/gallery/Social Service Club/Donation Camp/5.jpg",
              "alt": "Distributing warm clothing to families",
              "width": 960,
              "height": 1280
            },
            "caption": "Winter relief & community donation drive"
          },
          {
            "image": {
              "src": "/gallery/Social Service Club/Blood Donation/Blood Donation..jpg",
              "alt": "Campus blood donation campaign",
              "width": 986,
              "height": 1339
            },
            "caption": "Quarterly campus blood donation drive"
          },
          {
            "image": {
              "src": "/sections/nami/campus-service-camp.jpg",
              "alt": "A-Levels student volunteers on rural outreach expedition",
              "width": 1190,
              "height": 793
            },
            "caption": "Sindhupalchowk rural outreach expedition"
          }
        ],
        "meetingSchedule": "Fridays (3:30 PM – 5:00 PM) + Weekend Field Drives",
        "eligibility": "Open to all Cambridge A-Level students (AS and A2)",
        "facultyMentor": "Department of Social Sciences & Student Affairs"
      },
      {
        "slug": "sports",
        "title": "Sports",
        "category": "Athletics & Competitive Tournaments",
        "tagline": "Fostering athletic excellence, tactical discipline, stamina, and team spirit through competitive and recreational sports.",
        "metaDescription": "NAMI College A-Levels Sports Club offers competitive training, 3x3 basketball tournaments, futsal championships, and athletics.",
        "coverImage": {
          "src": "/sections/nami/campus-basketball-award.jpg",
          "alt": "NAMI College A-Levels basketball championship awards ceremony in the campus auditorium.",
          "width": 1500,
          "height": 1000
        },
        "overview": [
          "The Sports Club at NAMI College is dedicated to cultivating physical fitness, mental toughness, and athletic sportsmanship among A-Level students. Balancing rigorous Cambridge academics with energetic physical play, the club provides an outlet for students to excel on courts, fields, and tracks.",
          "With access to an NBA-standard basketball court, mini-football turf, table tennis facilities, and athletic running tracks, members participate in structured coaching clinics, intra-college house leagues, and prominent valley-wide inter-college tournaments."
        ],
        "quoteText": "Sports instill a winning mindset — discipline in practice, humility in victory, and resilience in defeat.",
        "quoteAuthor": "College Athletic Director",
        "objectives": [
          "Develop cardiovascular fitness, athletic skill, and bodily wellness alongside academic study.",
          "Promote team camaraderie, mutual accountability, and healthy competitive sportsmanship.",
          "Host signature inter-college invitationals in basketball, futsal, and table tennis.",
          "Prepare student-athletes for national and regional Cambridge sports meets."
        ],
        "activities": [
          {
            "title": "NAMI SEE & +2 3x3 Basketball Cup",
            "description": "Flagship valley-wide 3x3 basketball invitational tournament hosted on the college outdoor court.",
            "tag": "Flagship Invitational"
          },
          {
            "title": "Inter-House Futsal & Football League",
            "description": "Seasonal intra-college league running across AS and A2 cohorts on the mini-football turf.",
            "tag": "League Tournament"
          },
          {
            "title": "Annual Sports Day & Track Meet",
            "description": "Comprehensive athletic championship featuring sprints, relays, shot put, long jump, and tug-of-war.",
            "tag": "Annual Championship"
          },
          {
            "title": "Table Tennis & Badminton Open",
            "description": "Singles and doubles knockout tournament held in the indoor recreation complex.",
            "tag": "Indoor Sports"
          }
        ],
        "skills": [
          {
            "title": "Strategic Teamwork",
            "description": "Executing tactical game plans and supporting teammates under competitive pressure."
          },
          {
            "title": "Physical Conditioning",
            "description": "Building endurance, muscular strength, agility, and overall personal wellness."
          },
          {
            "title": "Resilience & Focus",
            "description": "Maintaining mental composure, concentration, and determination during high-stakes games."
          },
          {
            "title": "Sportsmanship",
            "description": "Treating opponents, referees, and teammates with unwavering respect and fairness."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Sports Club/Annual Sports Meet/Basketball-upright.jpg",
              "alt": "Basketball championship match in progress",
              "width": 2400,
              "height": 3200
            },
            "caption": "NAMI SEE & +2 3x3 Basketball Cup"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Intra Futsal/4fe72723-53bd-4408-a417-776bb9af9ce1.jfif",
              "alt": "Intra-college futsal league action on turf",
              "width": 1280,
              "height": 960
            },
            "caption": "Inter-house futsal league on campus turf"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Annual Sports Meet/Table Tennis.jpg",
              "alt": "Table tennis singles knockout match",
              "width": 891,
              "height": 660
            },
            "caption": "Table tennis & indoor racket tournament"
          },
          {
            "image": {
              "src": "/gallery/Sports Club/Inter School Basketball/46dcb38e-ac84-4ac8-b0ea-a11f6cb8f43b.jfif",
              "alt": "Inter-college basketball match action",
              "width": 1280,
              "height": 960
            },
            "caption": "Valley-wide inter-college tournament finals"
          }
        ],
        "meetingSchedule": "Tuesdays & Thursdays (3:45 PM – 5:15 PM)",
        "eligibility": "Open to all Cambridge A-Level students (AS and A2)",
        "facultyMentor": "Department of Physical Education & Sports"
      },
      {
        "slug": "arts-and-crafts",
        "title": "Arts and crafts",
        "category": "Visual Arts, Craftsmanship & Design",
        "tagline": "Cultivating artistic expression, canvas painting, sculpture, stage installations, and visual craftsmanship.",
        "metaDescription": "NAMI College A-Levels Arts and Crafts Club provides studio spaces for painting, sketching, sculpting, and art exhibitions.",
        "coverImage": {
          "src": "/gallery/Art and literature/Art Competition/20251224_101654.jpg",
          "alt": "NAMI College A-Levels arts and craftsmanship exhibition and creative design installations.",
          "width": 4000,
          "height": 3000
        },
        "overview": [
          "The Arts and Crafts Club at NAMI College provides a vibrant open studio for young artists, sculptors, graphic illustrators, and craftspeople. It celebrates aesthetic creativity as a vital counterpoint to academic rigor, encouraging students to experiment with diverse mediums and techniques.",
          "Members collaborate on fine art exhibitions, theatrical stage set designs, festive campus installations, pottery and clay sculpting, and visual branding for major college festivals."
        ],
        "quoteText": "Art is the voice of imagination. Craft is the disciplined hand that brings vision into tangible reality.",
        "quoteAuthor": "Visual Arts Instructor",
        "objectives": [
          "Develop refined artistic techniques in sketching, oil/acrylic painting, and mixed-media sculpture.",
          "Host annual campus art exhibitions showcasing student portfolios and conceptual projects.",
          "Design creative stage backdrops, props, and festive installations for college celebrations.",
          "Foster a supportive, collaborative studio space for personal artistic development."
        ],
        "activities": [
          {
            "title": "Annual College Art & Design Showcase",
            "description": "A curated campus gallery featuring student paintings, sculptures, and photographic installations.",
            "tag": "Exhibition"
          },
          {
            "title": "Festive Stage & Auditorium Installations",
            "description": "Designing large-scale thematic backdrops and decorative artwork for college galas.",
            "tag": "Stage Design"
          },
          {
            "title": "Pottery & Clay Modelling Workshops",
            "description": "Hands-on studio sessions exploring traditional pottery wheels and ceramic sculpting.",
            "tag": "Craft Workshop"
          },
          {
            "title": "Live Sketching & Plein Air Art Camps",
            "description": "Outdoor sketching expeditions capturing historical architecture and natural landscapes.",
            "tag": "Outdoor Studio"
          }
        ],
        "skills": [
          {
            "title": "Visual Artistry",
            "description": "Mastery of color theory, spatial composition, perspective, and various paint media."
          },
          {
            "title": "Craftsmanship & Fabrication",
            "description": "Working with clay, wood, papier-mâché, textiles, and architectural model materials."
          },
          {
            "title": "Creative Conceptualization",
            "description": "Transforming abstract themes and personal reflections into compelling visual artworks."
          },
          {
            "title": "Exhibition Curation",
            "description": "Mounting, lighting, and curating public gallery exhibitions with professional polish."
          }
        ],
        "gallery": [
          {
            "image": {
              "src": "/gallery/Art and literature/Art Competition/20251224_101654.jpg",
              "alt": "Fine art canvas painting and sketching competition",
              "width": 4000,
              "height": 3000
            },
            "caption": "Live studio painting & fine art showcase"
          },
          {
            "image": {
              "src": "/gallery/Art and literature/Art Competition/20251224_110720.jpg",
              "alt": "Creative mixed media and color sketches",
              "width": 4000,
              "height": 2252
            },
            "caption": "Visual arts & mixed-media illustrations"
          },
          {
            "image": {
              "src": "/mascot/event-mascot.jpg",
              "alt": "Festive stage installation and mascot design",
              "width": 1000,
              "height": 750
            },
            "caption": "Stage mascot & decorative installations"
          },
          {
            "image": {
              "src": "/nami/campus-reading-hall.jpg",
              "alt": "College gallery and art exhibition",
              "width": 1200,
              "height": 800
            },
            "caption": "Annual campus art & craft gallery"
          }
        ],
        "meetingSchedule": "Mondays & Thursdays (3:30 PM – 4:45 PM)",
        "eligibility": "Open to all Cambridge A-Level students (AS and A2)",
        "facultyMentor": "Department of Fine Arts & Design"
      }
    ]
  }
}
NAMI_JSON
				,
				true
			),
		);

		return $pages;
	}
);
