<?php
/**
 * NAMI CMS — News & Notices
 *
 * Requires the "NAMI CMS — Core engine" snippet, version 1.2.0 or later
 * (collections). Adds a "Notices" menu:
 *   - All Notices / Add New: each notice, event, news item or press release.
 *     They appear on the News & Notices page, the home page and each
 *     institution's notice board.
 *   - Page: …: the text of the /notices page itself.
 *
 * Field keys must match src/lib/cms/pages/notices/types.ts in the Next.js project.
 * The JSON blocks at the bottom are generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_collections',
	function ( $collections ) {
		$collections['notice-items'] = array(
			'post_type'   => 'nami_notice',
			'singular'    => 'Notice',
			'plural'      => 'Notices',
			'icon'        => 'dashicons-megaphone',
			'position'    => 3.7,
			'title_label' => 'Notice title',
			'description' => 'Notices appear on the News & Notices page, the home page and the notice board of the institution chosen below.',
			'columns'     => array( 'kind', 'institution', 'category' ),
			'ready'       => false,
			'fields'      => array(
				'kind'        => array(
					'type'    => 'select',
					'label'   => 'Type',
					'options' => array(
						'notice'        => 'Notice',
						'event'         => 'Event',
						'news'          => 'News',
						'press-release' => 'Press Release',
					),
				),
				'category'    => array(
					'type'    => 'select',
					'label'   => 'Category',
					'options' => array(
						'general'      => 'General',
						'admissions'   => 'Admissions',
						'examinations' => 'Examinations',
						'results'      => 'Results',
						'events'       => 'Events',
						'holidays'     => 'Holidays',
					),
				),
				'institution' => array(
					'type'    => 'select',
					'label'   => 'Institution',
					'options' => array(
						''          => 'All of NAMI',
						'school'    => 'NAMI International School',
						'college'   => 'NAMI College (A Levels)',
						'institute' => 'NAMI Institute (Bachelors)',
					),
					'help'    => 'The notice also appears on that institution\'s page.',
				),
				'excerpt'     => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 7, 'help' => 'Line breaks are kept.' ),
				'happensAt'   => array( 'type' => 'date', 'label' => 'Event / exam date (optional)', 'help' => 'For events and deadlines. Until this date the notice is shown as "Upcoming".' ),
				'venue'       => array( 'type' => 'text', 'label' => 'Venue (optional)' ),
				'image'       => array( 'type' => 'image', 'label' => 'Photo (optional)' ),
				'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text (optional)', 'placeholder' => 'Download the notice' ),
				'buttonLink'  => array( 'type' => 'file', 'label' => 'Button link', 'help' => 'Upload a PDF or image of the notice, or paste a link. The button only shows when both the text and the link are filled in.' ),
			),
			'import'      => json_decode(
				<<<'NAMI_IMPORT'
[
  {
    "title": "Dashain Festival Holiday Notice",
    "date": "2026-09-20",
    "fields": {
      "kind": "notice",
      "category": "holidays",
      "institution": "school",
      "excerpt": "Dear Parents/Guardians,\nThis is to kindly inform you that the school will remain closed for the Dashain Festival holiday from 17th October 2026 to 25th October 2026.\nRegular classes will resume from 26th October 2026 (Monday) as per the regular school schedule.\nWe wish all our students and families a joyful and peaceful Dashain.\nRegards,\nNAMI International School",
      "happensAt": "2026-10-17",
      "venue": "",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/level-school.jpg",
        "alt": "A yellow NAMI International School minibus parked in the school yard alongside the rest of the fleet.",
        "width": 465,
        "height": 349
      }
    }
  },
  {
    "title": "CAIE Examinations Schedule & Guidelines",
    "date": "2026-09-20",
    "fields": {
      "kind": "notice",
      "category": "examinations",
      "institution": "college",
      "excerpt": "Dear Students,\nA gentle reminder that the CAIE Examinations will begin on Monday, 28 September 2026.\n• Morning Shift: Examination starts at 10:45 AM; reporting time is 10:15 AM.\n• Afternoon Shift: Examination starts at 2:45 PM; reporting time is 2:15 PM.\nExam Venue: NAMI College, Hall 3.\nPlease ensure that you arrive at the college on time with your SOE and ID card, which are mandatory to sit for the examination.\nThank you.\nNAMI College NP743",
      "happensAt": "2026-09-28",
      "venue": "NAMI College, Hall 3",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/campus-library.jpg",
        "alt": "A NAMI reading hall, long study desks ranked beneath ceiling fans with a projection screen at the far end and a silence notice on the wall.",
        "width": 1280,
        "height": 853
      }
    }
  },
  {
    "title": "Second Session of the most awaited talk program “Motivational Stories by Inspirational Leaders of Change”",
    "date": "2024-07-30",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "institute",
      "excerpt": "We are pleased to announce the Second Session of the most awaited talk program “Motivational Stories by Inspirational Leaders of Change” taking place at Naaya Aayam Multi-Disciplinary Institute, Jorpati, on the 30th of July, 2024. Get ready for an enriching experience!",
      "happensAt": "",
      "venue": "Jorpati",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      }
    }
  },
  {
    "title": "Motivational Stories by Inspirational Leaders of Change",
    "date": "2024-06-30",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "NAMI is proud to launch a new monthly series featuring three motivational speakers from various walks of life. NAMI kicked off our series of motivational speeches featuring the country's best in their respective fields, Ms. Vidushi Rana, Dr. Bishal Dhakal and Mr. Anil Keshary Shah. The stories shared by all three speakers were relatable, motivational, and deeply moving.",
      "happensAt": "",
      "venue": "Jorpati",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      }
    }
  },
  {
    "title": "NAMI SEE 3x3 Basketball Tournament",
    "date": "2024-05-16",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "We are thrilled to announce the successful conclusion of the NAMI SEE 3x3 Basketball Tournament! A huge thank you to all the participants for their dedication and sportsmanship.",
      "happensAt": "",
      "venue": "College Premise",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/campus-basketball-award.jpg",
        "alt": "Prize-giving for the NAMI SEE 3x3 Basketball Tournament on the college auditorium stage, both teams wearing medals and holding certificates behind the winners' trophy and the tournament cheques.",
        "width": 1500,
        "height": 1000
      }
    }
  },
  {
    "title": "Social Camp",
    "date": "2024-01-27",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "NAMI organized a transformative Social Camp at Shree Ganesh Basic School in Sindhupalchowk from January 27th to 28th, aimed at making a positive impact on the local community. The primary focus of the event was to extend assistance to underprivileged children and uplift the overall welfare of the community.",
      "happensAt": "",
      "venue": "Sindhupalchowk",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/campus-service-camp.jpg",
        "alt": "Pupils in red uniforms seated around a hilltop school ground in Sindhupalchowk, facing stacks of red relief bags laid out on benches at a NAMI service camp.",
        "width": 1190,
        "height": 793
      }
    }
  },
  {
    "title": "Christmas Event, NAMI City College",
    "date": "2023-12-24",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "We are delighted to share the tremendous success of the X-Mas Event, a culmination of festive cheer, laughter, and camaraderie, aimed to provide an unforgettable experience for both students and faculty. The venue was transformed into a festive wonderland, adorned with vibrant Christmas decorations, including two beautifully crafted trees made of cardboard boxes and paper.",
      "happensAt": "",
      "venue": "City College",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-christmas-city-campus.png",
        "alt": "A hall hung with red and green balloons, paper snowflakes and fairy lights, the projection screen reading Merry Christmas and Happy New Year above a microphone stand.",
        "width": 826,
        "height": 691
      }
    }
  },
  {
    "title": "NAMI A-Level Students Embrace the Spirit of Giving through Christmas Blood Donation Drive",
    "date": "2023-12-22",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "college",
      "excerpt": "In the spirit of Christmas, A-Level students at NAMI organized a blood donation drive on December 22, 2023, exemplifying the college's commitment to community welfare. The event, marked by festive cheer, saw active participation from students eager to make a meaningful contribution to those in need.",
      "happensAt": "",
      "venue": "College Premise",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      }
    }
  },
  {
    "title": "NAMI A Level Students Tour of Mustang & Muktinath",
    "date": "2023-12-08",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "college",
      "excerpt": "NAMI organized an enriching 3-night, 4-day tour for A Level students to explore the picturesque region of Mustang and visit the sacred Muktinath temple.",
      "happensAt": "",
      "venue": "Mustang & Manang",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      }
    }
  },
  {
    "title": "NAMI A Levels: A Welcoming Spectacle at Kwality Beach Resort",
    "date": "2023-07-29",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "college",
      "excerpt": "NAMI hosted a vibrant welcome programme on July 29, 2023, for its A Level students at Kwality Beach Resort, Mulkot, and the event was nothing short of magical.",
      "happensAt": "",
      "venue": "Mulkot",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      }
    }
  },
  {
    "title": "Eco Club's Environment Day Programme",
    "date": "2023-06-05",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "NAMI Eco Club orchestrated a captivating Environment Day programme that left a lasting impact on approximately 30 participants. The event, dedicated to fostering environmental awareness, featured a thought-provoking photo exhibition and an engaging photo contest centered around the theme of \"Nature.\"",
      "happensAt": "",
      "venue": "College Premise",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-eco-club.jpg",
        "alt": "Three NAMI students posing inside a hand-made World Environment Day photo frame lettered Eco Vision and hung with paper butterflies and origami cranes.",
        "width": 789,
        "height": 732
      }
    }
  },
  {
    "title": "Unleashing Creativity: The Ultimate College Mascot Design Competition",
    "date": "2023-05-03",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "NAMI organized a one-of-a-kind event, the Ultimate Mascot Design Competition from May 03 to May 11, 2023. Students across faculties unleashed their creativity, drawing inspiration from the college logo and Saraswati's swan symbol.",
      "happensAt": "",
      "venue": "College Premise",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/mascot/event-mascot.jpg",
        "alt": "A mascot design entry titled The Swan — a white swan rising from a red lotus, laid out beside the NAMI wordmark on a red and white board.",
        "width": 800,
        "height": 563
      }
    }
  },
  {
    "title": "ELITE 2023",
    "date": "2023-03-31",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "institute",
      "excerpt": "Elite 2023, an inter-college business competition was meticulously organized to showcase undergraduates' skills in finance, marketing, and management.",
      "happensAt": "",
      "venue": "City College",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-elite-2023.jpg",
        "alt": "NAMI undergraduates in formal dress crowded together holding certificates, medals and trophies in front of the ELITE competition screen.",
        "width": 999,
        "height": 843
      }
    }
  },
  {
    "title": "Panel Discussion on \"Climate Change: Impacts and the Global Response\"",
    "date": "2023-03-23",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "We had insightful conversations on the urgent need for action and the collective efforts required to mitigate the devastating effects of climate change.",
      "happensAt": "",
      "venue": "City College, New Baneshwor",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-climate-panel.jpg",
        "alt": "A panel discussion in a wood-panelled conference room, a speaker addressing a seated audience with a microphone while the other panellists listen from the front row.",
        "width": 800,
        "height": 533
      }
    }
  },
  {
    "title": "Welcome Undergraduates Orientation 2022",
    "date": "2022-11-14",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "institute",
      "excerpt": "NAMI welcomes the new batch of BSc. Computing, BSc. Environmental Science, and BBA. The orientation was held at Diamond Hill Resort with a fun-packed orientation session, skillful activities, and a gaming session.",
      "happensAt": "",
      "venue": "Diamond Hill Resort, Panauti",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-orientation-2022.jpg",
        "alt": "Incoming NAMI undergraduates seated at round banquet tables with worksheets, beneath a banner reading Bachelor's Orientation Program 2079.",
        "width": 772,
        "height": 470
      }
    }
  },
  {
    "title": "Triumph and Transition: NAMI's Grand Convocation Day 2022 at Yak & Yeti Hotel",
    "date": "2022-09-17",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "institute",
      "excerpt": "NAMI's Convocation held at the prestigious Yak & Yeti Hotel, was a momentous occasion that celebrated the academic achievements of graduates from diverse disciplines. The grand event drew attention not only for the remarkable accomplishments of the graduating class but also for the presence of distinguished personalities from both NAMI and the esteemed University of Northampton.",
      "happensAt": "",
      "venue": "Yak & Yeti Hotel",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-convocation-2022.jpg",
        "alt": "NAMI graduands in gowns and blue hoods throwing their caps in the air in front of a Convocation Ceremony 2022 backdrop carrying the NAMI and University of Northampton marks.",
        "width": 800,
        "height": 449
      }
    }
  },
  {
    "title": "Plantation Programme on the Occasion of World Environment Day",
    "date": "2022-06-05",
    "fields": {
      "kind": "event",
      "category": "events",
      "institution": "",
      "excerpt": "NAMI organized a Plantation programme along with Nature Art Competition in collaboration with WCN (Wildlife Conservation Nepal) and Gokarneshwor Municipality on 5th June at NAMI premises.",
      "happensAt": "",
      "venue": "College Premise",
      "buttonLabel": "",
      "buttonLink": "",
      "image": {
        "src": "/sections/nami/event-plantation-2022.jpg",
        "alt": "Staff and volunteers crouched on the grass settling a sapling into the ground, one of them wearing a Nepal Prakriti Pathshala shirt from Wildlife Conservation Nepal.",
        "width": 800,
        "height": 753
      }
    }
  }
]
NAMI_IMPORT
				,
				true
			),
		);
		return $collections;
	}
);

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$pages['notices'] = array(
			'title'          => 'News & Notices page',
			'menu_parent'    => 'edit.php?post_type=nami_notice',
			'submenu_prefix' => 'Page: ',
			'path'           => '/notices',
			'sections'       => array(
				'masthead' => array(
					'title'       => 'Heading',
					'description' => 'The heading at the top of the News & Notices page.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
					),
				),
				'empty'    => array(
					'title'       => 'When empty',
					'description' => 'Shown on the page when there are no notices at all.',
					'fields'      => array(
						'text' => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 2 ),
					),
				),
				'seo'      => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the News & Notices page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "News and Notices",
    "description": "Everything NAMI publishes in one place — standing notices, upcoming events and the record of what the school, the college and the institute have hosted in Kathmandu, filterable by institution."
  },
  "masthead": {
    "label": "News & Notices",
    "title": "What NAMI is announcing.",
    "description": "One board for notices, events and news from the school, the college and the institute."
  },
  "empty": {
    "text": "There is nothing to announce right now. Notices, events and news will appear here as the group publishes them."
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);
