<?php
/**
 * NAMI CMS — Careers
 *
 * Requires the "NAMI CMS — Core engine" snippet, version 1.2.0 or later
 * (collections). Adds a "Careers" menu:
 *   - All Vacancies / Add New: each job opening on the Careers page. A vacancy
 *     disappears from the website the day after its closing date.
 *   - Page: …: the rest of the Careers page (heading, how to apply, benefits,
 *     staff voices, first-job stories, placement).
 *
 * Field keys must match src/lib/cms/pages/careers/types.ts in the Next.js project.
 * The JSON block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_collections',
	function ( $collections ) {
		$collections['vacancies'] = array(
			'post_type'   => 'nami_vacancy',
			'singular'    => 'Vacancy',
			'plural'      => 'Vacancies',
			'menu_name'   => 'Careers',
			'icon'        => 'dashicons-businessperson',
			'position'    => 3.75,
			'title_label' => 'Job title',
			'description' => 'Each vacancy shows on the Careers page with an "Apply via Email" button. It disappears the day after its closing date.',
			'columns'     => array( 'department', 'employmentType', 'closesAt' ),
			// The vacancies bundled with the site are invented examples, so the
			// website shows only this list as soon as it is connected.
			'ready'       => true,
			'fields'      => array(
				'department'     => array( 'type' => 'text', 'label' => 'Wing / department', 'placeholder' => 'Naaya Aayam Multi-Disciplinary Institute', 'help' => 'Visitors can filter vacancies by this.' ),
				'employmentType' => array(
					'type'    => 'select',
					'label'   => 'Type',
					'options' => array(
						'full-time'  => 'Full Time',
						'part-time'  => 'Part Time',
						'contract'   => 'Contract',
						'internship' => 'Internship',
					),
				),
				'location'       => array( 'type' => 'text', 'label' => 'Location', 'default' => 'New Baneshwor, Kathmandu' ),
				'summary'        => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 5 ),
				'closesAt'       => array( 'type' => 'date', 'label' => 'Closing date (optional)', 'help' => 'Leave empty for "Open until filled".' ),
				'requirements'   => array( 'type' => 'lines', 'label' => 'Requirements (optional)', 'rows' => 5, 'help' => 'One per line. Shown under "Requirements" instead of the general checklist (Careers → Page: How to Apply).' ),
			),
		);
		return $collections;
	}
);

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['careers'] = array(
			'title'          => 'Careers page',
			'menu_parent'    => 'edit.php?post_type=nami_vacancy',
			'submenu_prefix' => 'Page: ',
			'path'           => '/careers',
			'sections'       => array(

				'masthead'    => array(
					'title'       => 'Heading',
					'description' => 'The top of the Careers page.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text (jumps to the vacancies)' ),
						'image'       => $image( 'Photo' ),
					),
				),

				'vacancies'   => array(
					'title'       => 'Vacancies heading',
					'anchor'      => 'vacancies',
					'description' => 'The heading above the list of vacancies. Add the vacancies themselves under Careers → Add New.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'emptyState'  => array( 'type' => 'textarea', 'label' => 'Text shown when no vacancy matches', 'rows' => 2 ),
					),
				),

				'application' => array(
					'title'       => 'How to Apply',
					'description' => 'Used by every vacancy\'s "Apply via Email" button and its "Requirements" panel.',
					'fields'      => array(
						'email'          => array( 'type' => 'text', 'label' => 'Email for applications' ),
						'checklistTitle' => array( 'type' => 'text', 'label' => 'Checklist heading' ),
						'checklist'      => array( 'type' => 'lines', 'label' => 'General checklist', 'rows' => 5, 'help' => 'One per line. A vacancy with its own requirements shows those instead.' ),
						'instructions'   => array( 'type' => 'textarea', 'label' => 'Submission instructions', 'rows' => 3, 'help' => '{email} is replaced by the email address above.' ),
					),
				),

				'benefits'    => array(
					'title'       => 'Benefits',
					'description' => 'The perks and benefits cards.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Benefits',
							'item_label'  => 'Benefit',
							'title_field' => 'title',
							'fields'      => array(
								'title'       => array( 'type' => 'text', 'label' => 'Title' ),
								'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
							),
						),
					),
				),

				'staff'       => array(
					'title'       => 'Staff Voices',
					'anchor'      => 'staff-stories',
					'description' => 'Carousel of quotes from faculty and staff.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Quotes',
							'item_label'  => 'Quote',
							'title_field' => 'name',
							'fields'      => array(
								'quote'    => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 5 ),
								'name'     => array( 'type' => 'text', 'label' => 'Name' ),
								'role'     => array( 'type' => 'text', 'label' => 'Job title' ),
								'portrait' => $image( 'Photo', 'Square-ish photos work best. Initials show if empty.' ),
							),
						),
						'emptyState'  => array( 'type' => 'text', 'label' => 'Text shown when there are no quotes' ),
					),
				),

				'firstJob'    => array(
					'title'       => 'First Job Stories',
					'anchor'      => 'first-job-stories',
					'description' => 'Graduates describing how NAMI helped them land their first job.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'stories'     => array(
							'type'        => 'repeater',
							'label'       => 'Stories',
							'item_label'  => 'Story',
							'title_field' => 'name',
							'fields'      => array(
								'name'          => array( 'type' => 'text', 'label' => 'Name' ),
								'role'          => array( 'type' => 'text', 'label' => 'Job title' ),
								'company'       => array( 'type' => 'text', 'label' => 'Company' ),
								'degree'        => array( 'type' => 'text', 'label' => 'Degree' ),
								'graduatedYear' => array( 'type' => 'number', 'label' => 'Graduation year' ),
								'supportType'   => array( 'type' => 'text', 'label' => 'How NAMI helped (short tag)' ),
								'quote'         => array( 'type' => 'textarea', 'label' => 'Quote', 'rows' => 4 ),
								'portrait'      => $image( 'Photo', 'Initials show if empty.' ),
							),
						),
					),
				),

				'placement'   => array(
					'title'       => 'Industry Network',
					'anchor'      => 'career-placement',
					'description' => 'Heading and photo above the partner logos. The logos are shared with other pages and not edited here yet.',
					'fields'      => array(
						'label' => array( 'type' => 'text', 'label' => 'Small label' ),
						'title' => array( 'type' => 'text', 'label' => 'Title' ),
						'image' => $image( 'Photo', 'Remove the photo to hide this section.' ),
					),
				),

				'seo'         => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Careers page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Careers & Faculty Openings",
    "description": "Explore academic, research, and administrative career opportunities across NAMI International School, NAMI College, and Naaya Aayam Multi-Disciplinary Institute in Kathmandu."
  },
  "masthead": {
    "label": "CAREERS",
    "title": "Careers at NAMI.",
    "description": "Join an inspiring community of educators, scholars, and professionals dedicated to transformative teaching, research excellence, and world-class learning in Kathmandu.",
    "buttonLabel": "Explore open positions",
    "image": {
      "src": "/sections/nami/event-climate-panel.jpg",
      "alt": "NAMI faculty and scholars during an academic symposium in the NAMI conference auditorium.",
      "width": 800,
      "height": 533
    }
  },
  "vacancies": {
    "label": "Opportunities across our three academic wings.",
    "title": "Open Positions",
    "description": "We invite dedicated educators, researchers, and academic professionals to join our faculty and operational teams in Kathmandu.",
    "emptyState": "There are no vacancies matching your selected filters at the moment. Explore other departments or write directly to careers@nami.edu.np."
  },
  "application": {
    "email": "careers@nami.edu.np",
    "checklistTitle": "Application Checklist",
    "checklist": [
      "Updated Curriculum Vitae (CV) & Recent Photograph",
      "Copies of Academic Degrees & Transcripts",
      "Cover Letter / Statement of Teaching Philosophy",
      "Two Professional / Academic References"
    ],
    "instructions": "Send all application materials to {email} citing the position title in the subject line. Shortlisted candidates will be contacted within 5 working days."
  },
  "benefits": {
    "label": "Comprehensive support for our faculty and staff.",
    "title": "Perks & Benefits",
    "description": "We believe that high-quality education starts with taking care of our educators. We offer competitive remuneration and holistic staff support.",
    "items": [
      {
        "title": "Competitive Compensation",
        "description": "Above-market salary scales with structured annual increments, performance incentives, and statutory Provident Fund & Gratuity."
      },
      {
        "title": "Professional Development",
        "description": "Periodic teacher training workshops led directly by Cambridge International and University of Northampton faculty leads."
      },
      {
        "title": "Health & Accidental Coverage",
        "description": "Comprehensive group health insurance and accident protection plans for all permanent faculty and operational members."
      },
      {
        "title": "Tuition Concession for Children",
        "description": "Generous tuition fee waivers and scholarship support for dependent children attending NAMI International School or College."
      },
      {
        "title": "Transit & Cafeteria",
        "description": "Comfortable institutional transport routes covering Kathmandu, Lalitpur, and Bhaktapur, plus hygienic subsidized dining."
      },
      {
        "title": "Paid Sabbatical & Leave",
        "description": "Dedicated paid research leave, exam moderation leave, maternity/paternity support, and annual paid seasonal breaks."
      }
    ]
  },
  "staff": {
    "label": "What our educators and team say about working at NAMI.",
    "title": "Faculty & Staff Voices",
    "description": "Hear from lecturers, coordinators, and academic leaders about the collaborative culture, research support, and teaching freedom across our three wings.",
    "emptyState": "",
    "items": [
      {
        "quote": "Teaching at NAMI gives you the institutional backing and academic freedom to actually innovate in the classroom. The collaborative faculty community and research support make it one of the most fulfilling places to teach in Kathmandu.",
        "name": "Dr. Ramesh Adhikari",
        "role": "Senior Faculty & Research Lead, Computing",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "quote": "What stands out about working at NAMI is the genuine respect for educators' time and ideas. The continuous professional development and supportive management create an environment where teachers can truly thrive.",
        "name": "Bikash Maharjan",
        "role": "Department Coordinator, NAMI International School",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "quote": "The cross-disciplinary culture here encourages faculty to mentor students beyond just textbooks. The modern facilities, structured academic calendar, and supportive colleagues make NAMI an exemplary workplace.",
        "name": "Sunita Gautam",
        "role": "Senior Lecturer, Department of Business & Management",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "quote": "At NAMI, educator development is treated with the same seriousness as student achievement. We collaborate directly with Cambridge International and University of Northampton mentors to keep our academic standard world-class.",
        "name": "Philip Badikar Hilario",
        "role": "A Level Principal, NAMI College",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      }
    ]
  },
  "firstJob": {
    "label": "First Job Stories",
    "title": "How NAMI helped me land my first job.",
    "description": "From campus recruitment drives and mock technical interviews to capstone mentorship and industry internships, our graduates share how NAMI prepared them for their breakthrough career roles.",
    "stories": [
      {
        "name": "Smriti Shrestha",
        "company": "Leapfrog Technology",
        "role": "Associate Software Engineer",
        "degree": "BSc (Hons) Computing",
        "graduatedYear": 2024,
        "supportType": "Placement Cell & Mock Code Reviews",
        "quote": "NAMI's placement cell connected me with industry mentors and mock technical interviews during my final semester. That direct guidance and practical project reviews helped me land my first software engineering job before convocation.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "name": "Prashant KC",
        "company": "Nabil Bank",
        "role": "Management Trainee",
        "degree": "BBA (Hons)",
        "graduatedYear": 2023,
        "supportType": "Campus Recruitment & Case Competitions",
        "quote": "The corporate case competitions and presentation workshops at NAMI simulated real boardroom dynamics. When Nabil Bank conducted campus interviews, I felt thoroughly prepared to articulate my ideas and land the role.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "name": "Aayushma Basnet",
        "company": "WWF Nepal",
        "role": "Junior Environmental Analyst",
        "degree": "BSc (Hons) Environmental Science",
        "graduatedYear": 2024,
        "supportType": "Fieldwork Network & Research Mentorship",
        "quote": "Field research modules and industry internships arranged by NAMI gave me verifiable practical experience on my resume. My professor guided my application and helped me secure my dream first job in wildlife conservation.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "name": "Ronak Bastola",
        "company": "Cotiviti Nepal",
        "role": "Software Quality Engineer",
        "degree": "BSc (Hons) Computing (Software Eng.)",
        "graduatedYear": 2024,
        "supportType": "Industry Capstone & Career Placement",
        "quote": "The University of Northampton curriculum combined with NAMI's coding labs gave me real-world software architecture experience. My mentor's industry referrals helped me land my first software engineering position straight out of college.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "name": "Nitesh Shrestha",
        "company": "F1Soft International",
        "role": "Associate DevOps & Cloud Engineer",
        "degree": "BSc (Hons) Network Engineering",
        "graduatedYear": 2023,
        "supportType": "Lab Infrastructure & Industry Certifications",
        "quote": "Hands-on server labs and networking modules at NAMI gave me practical troubleshooting skills before I even graduated. The career center helped connect my capstone project directly to hiring managers at F1Soft.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      },
      {
        "name": "Kritika Thapa",
        "company": "Standard Chartered Bank Nepal",
        "role": "Retail Banking Associate",
        "degree": "BBA (Hons)",
        "graduatedYear": 2024,
        "supportType": "Corporate Internship & Alumni Network",
        "quote": "NAMI's alumni network and career counseling office helped me secure my 6-month corporate internship, which converted into a permanent full-time offer upon graduation.",
        "portrait": {
          "src": "/sections/nami/alumna-pragati-rai.jpg",
          "alt": "Portrait of Pragati Rai, NAMI A-Level alumna.",
          "width": 192,
          "height": 192
        }
      }
    ]
  },
  "placement": {
    "label": "The organisations and research bodies that collaborate with NAMI.",
    "title": "Industry & Academic Network",
    "image": {
      "src": "/sections/nami/event-climate-panel.jpg",
      "alt": "Faculty and guest scholars during an academic panel symposium in the NAMI conference auditorium.",
      "width": 800,
      "height": 533
    }
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);
