<?php
/**
 * NAMI CMS — Gallery
 *
 * Requires the "NAMI CMS — Core engine" snippet, version 1.2.0 or later
 * (collections). Adds a "Gallery" menu:
 *   - All Moments / Add New: each photo, video or quote card on /gallery.
 *   - Add Many Photos: pick several photos at once and file them together.
 *   - Page: …: the heading, the institution tabs and the bubbles under each tab.
 *
 * Field keys must match src/lib/cms/pages/gallery/types.ts in the Next.js project.
 * The JSON blocks at the bottom are generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

function nami_gallery_institutions() {
	return array(
		'all'              => 'All of NAMI (shows under every tab)',
		'primary'          => 'Primary',
		'higher-secondary' => '+2 Higher Secondary',
		'a-levels'         => 'A-Levels',
		'bachelors'        => 'Bachelors & Masters',
	);
}

function nami_gallery_categories() {
	return array(
		'academics'    => 'Academics',
		'campus-life'  => 'Campus Life',
		'events'       => 'Events',
		'sports'       => 'Sports',
		'achievements' => 'Achievements',
		'all'          => 'General',
	);
}

/** Bubble choices come from Gallery → Page: … so new bubbles appear here at once. */
function nami_gallery_bubble_options() {
	$options = array( '' => '— None —' );
	if ( ! function_exists( 'nami_cms_get_values' ) ) {
		return $options;
	}
	$values = nami_cms_get_values( 'gallery' );
	$groups = array(
		'primary'   => 'Primary',
		'plusTwo'   => '+2',
		'aLevels'   => 'A-Levels',
		'bachelors' => 'Bachelors',
	);
	foreach ( $groups as $section => $name ) {
		$bubbles = $values[ $section ]['bubbles'] ?? array();
		foreach ( is_array( $bubbles ) ? $bubbles : array() as $bubble ) {
			$key = trim( (string) ( $bubble['key'] ?? '' ) );
			if ( '' === $key || 'all' === $key ) {
				continue;
			}
			$label           = $name . ': ' . (string) ( $bubble['label'] ?? $key );
			$options[ $key ] = isset( $options[ $key ] ) ? $options[ $key ] . ' / ' . $label : $label;
		}
	}
	return $options;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$bubbles = function ( $tab ) {
			return array(
				'title'       => 'Bubbles: ' . $tab,
				'description' => 'The round buttons under the ' . $tab . ' tab. The bubble with key "all" shows every ' . $tab . ' moment; a bubble with key "others" shows the ' . $tab . ' moments that belong to no other bubble. Moments are linked to a bubble by its key.',
				'fields'      => array(
					'bubbles' => array(
						'type'        => 'repeater',
						'label'       => 'Bubbles',
						'item_label'  => 'Bubble',
						'title_field' => 'label',
						'fields'      => array(
							'key'        => array( 'type' => 'text', 'label' => 'Key', 'help' => 'Short lowercase name with hyphens, e.g. sports-club. Changing it unlinks the moments filed under it.' ),
							'label'      => array( 'type' => 'text', 'label' => 'Name' ),
							'shortLabel' => array( 'type' => 'text', 'label' => 'Short name (under the bubble)' ),
							'thumbnail'  => array( 'type' => 'image', 'label' => 'Picture in the bubble', 'help' => 'If empty, the icon below is shown.' ),
							'logo'       => array( 'type' => 'toggle', 'label' => 'Picture style', 'toggle_label' => 'It is a logo (show it whole on white instead of filling the circle)' ),
							'icon'       => array(
								'type'    => 'select',
								'label'   => 'Icon (when there is no picture)',
								'options' => array(
									'grid'        => 'Grid',
									'tech'        => 'Technology',
									'sports'      => 'Sports',
									'math'        => 'Maths',
									'arts'        => 'Arts',
									'culture'     => 'Culture',
									'trips'       => 'Trips',
									'science'     => 'Science',
									'social'      => 'Social',
									'events'      => 'Events',
									'business'    => 'Business',
									'convocation' => 'Convocation',
									'music'       => 'Music',
								),
							),
						),
					),
				),
			);
		};

		$tab = function ( $prefix, $name ) {
			return array(
				$prefix . 'Label'      => array( 'type' => 'text', 'label' => $name . ': tab name' ),
				$prefix . 'Badge'      => array( 'type' => 'text', 'label' => $name . ': short name' ),
				$prefix . 'PhotoLabel' => array( 'type' => 'text', 'label' => $name . ': label on full-screen photos' ),
			);
		};

		$pages['gallery'] = array(
			'title'          => 'Gallery page',
			'menu_parent'    => 'edit.php?post_type=nami_gallery',
			'submenu_prefix' => 'Page: ',
			'path'           => '/gallery',
			'sections'       => array(
				'heading'   => array(
					'title'       => 'Heading',
					'description' => 'The heading above the gallery and the button that loads more moments.',
					'fields'      => array(
						'label'     => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'     => array( 'type' => 'text', 'label' => 'Title' ),
						'moreLabel' => array( 'type' => 'text', 'label' => '"See more" button text' ),
					),
				),
				'tabs'      => array(
					'title'       => 'Institution Tabs',
					'description' => 'The names of the five tabs across the top of the gallery.',
					'fields'      => array_merge(
						$tab( 'all', 'All' ),
						$tab( 'primary', 'Primary' ),
						$tab( 'plusTwo', '+2' ),
						$tab( 'aLevels', 'A-Levels' ),
						$tab( 'bachelors', 'Bachelors' )
					),
				),
				'primary'   => $bubbles( 'Primary' ),
				'plusTwo'   => $bubbles( '+2' ),
				'aLevels'   => $bubbles( 'A-Levels' ),
				'bachelors' => $bubbles( 'Bachelors' ),
				'seo'       => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Gallery page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Gallery & Visual Archive | NAMI",
    "description": "Explore the photographic record of NAMI in Kathmandu — Primary, Higher Secondary, Cambridge A Levels, and University of Northampton Bachelor's & Master's degrees."
  },
  "heading": {
    "label": "Explore Our Moments",
    "title": "Our Gallery",
    "moreLabel": "See More Moments"
  },
  "tabs": {
    "allLabel": "All Institutions",
    "allBadge": "All",
    "allPhotoLabel": "NAMI",
    "primaryLabel": "Primary (Grades I–VII)",
    "primaryBadge": "Primary",
    "primaryPhotoLabel": "Primary",
    "plusTwoLabel": "+2 Higher Secondary",
    "plusTwoBadge": "+2",
    "plusTwoPhotoLabel": "Higher Secondary (+2)",
    "aLevelsLabel": "A-Levels",
    "aLevelsBadge": "A-Levels",
    "aLevelsPhotoLabel": "A-Levels",
    "bachelorsLabel": "Bachelors & Masters",
    "bachelorsBadge": "Degree",
    "bachelorsPhotoLabel": "Bachelors / Masters"
  },
  "primary": {
    "bubbles": [
      {
        "key": "all",
        "label": "All Primary Activities",
        "shortLabel": "All Primary",
        "icon": "grid",
        "thumbnail": {
          "src": "/sections/nami/level-school.jpg",
          "alt": "All Primary Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "tech-3di",
        "label": "3Di School New Zealand",
        "shortLabel": "3Di School",
        "icon": "tech",
        "thumbnail": {
          "src": "/logos/collaborators/3di.png",
          "alt": "3Di School New Zealand",
          "width": 0,
          "height": 0
        },
        "logo": true
      },
      {
        "key": "sports-playnepal",
        "label": "Play Nepal Sports",
        "shortLabel": "Play Nepal",
        "icon": "sports",
        "thumbnail": {
          "src": "/logos/collaborators/play-nepal.png",
          "alt": "Play Nepal Sports",
          "width": 0,
          "height": 0
        },
        "logo": true
      },
      {
        "key": "academics-math",
        "label": "UnMath Programme",
        "shortLabel": "UnMath",
        "icon": "math",
        "thumbnail": {
          "src": "/logos/collaborators/unmath.png",
          "alt": "UnMath Programme",
          "width": 0,
          "height": 0
        },
        "logo": true
      },
      {
        "key": "mero-coding",
        "label": "Mero Coding Hub",
        "shortLabel": "Mero Coding",
        "icon": "tech",
        "thumbnail": {
          "src": "/logos/collaborators/mero-coding.png",
          "alt": "Mero Coding Hub",
          "width": 0,
          "height": 0
        },
        "logo": true
      },
      {
        "key": "samatva-wellness",
        "label": "Samatva Wellness & Vaav",
        "shortLabel": "Samatva",
        "icon": "culture",
        "thumbnail": {
          "src": "/logos/collaborators/samatva-wellness.png",
          "alt": "Samatva Wellness & Vaav",
          "width": 0,
          "height": 0
        },
        "logo": true
      },
      {
        "key": "others",
        "label": "Other School Activities",
        "shortLabel": "Others",
        "icon": "arts",
        "thumbnail": {
          "src": "/gallery/Primary School/School Life/CLAYMATION.jpg",
          "alt": "Other School Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      }
    ]
  },
  "plusTwo": {
    "bubbles": [
      {
        "key": "all",
        "label": "All (+2) Activities",
        "shortLabel": "All (+2)",
        "icon": "grid",
        "thumbnail": {
          "src": "/sections/nami/level-plus-two.jpg",
          "alt": "All (+2) Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "sports-club",
        "label": "Sports Club",
        "shortLabel": "Sports Club",
        "icon": "sports",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/Sports/Basketball Tournament—2082.jpeg",
          "alt": "Sports Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "science-tech",
        "label": "Science & Tech Club",
        "shortLabel": "Science & Tech",
        "icon": "science",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/Academic/KIST FAIR- 2081.jpeg",
          "alt": "Science & Tech Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "social-service",
        "label": "Social Service Club",
        "shortLabel": "Social Service",
        "icon": "social",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/Events/Social Service Club.jpeg",
          "alt": "Social Service Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "event-management",
        "label": "Event Management Club",
        "shortLabel": "Events Club",
        "icon": "events",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/Events/HOLI.jpeg",
          "alt": "Event Management Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "art-literature",
        "label": "Art & Literature Club",
        "shortLabel": "Art & Lit",
        "icon": "arts",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/Events/intra-school art competition .jpeg",
          "alt": "Art & Literature Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "academic-tours",
        "label": "Academics & Tours",
        "shortLabel": "Study Tours",
        "icon": "math",
        "thumbnail": {
          "src": "/gallery/Higher Secondary/School Life/Educational Tour.jpeg",
          "alt": "Academics & Tours",
          "width": 0,
          "height": 0
        },
        "logo": false
      }
    ]
  },
  "aLevels": {
    "bubbles": [
      {
        "key": "all",
        "label": "All A-Levels Activities",
        "shortLabel": "All A-Levels",
        "icon": "grid",
        "thumbnail": {
          "src": "/sections/nami/level-a-level.jpg",
          "alt": "All A-Levels Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "sports",
        "label": "Sports Club",
        "shortLabel": "Sports Club",
        "icon": "sports",
        "thumbnail": {
          "src": "/gallery/A-levels/Sports/karate.jpeg",
          "alt": "Sports Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "social-services",
        "label": "Social Services Club",
        "shortLabel": "Social Services",
        "icon": "social",
        "thumbnail": {
          "src": "/sections/nami/hero-mustang.jpg",
          "alt": "Social Services Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "arts-crafts",
        "label": "Arts & Crafts Club",
        "shortLabel": "Arts & Crafts",
        "icon": "arts",
        "thumbnail": {
          "src": "/gallery/A-levels/Events/xyz.jpeg",
          "alt": "Arts & Crafts Club",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "academics",
        "label": "Cambridge Academics",
        "shortLabel": "Academics",
        "icon": "math",
        "thumbnail": {
          "src": "/gallery/A-levels/Academic/xyz1.jpeg",
          "alt": "Cambridge Academics",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "student-life",
        "label": "Student Life & Fests",
        "shortLabel": "Student Life",
        "icon": "events",
        "thumbnail": {
          "src": "/gallery/A-levels/Events/farewell.jpeg",
          "alt": "Student Life & Fests",
          "width": 0,
          "height": 0
        },
        "logo": false
      }
    ]
  },
  "bachelors": {
    "bubbles": [
      {
        "key": "all",
        "label": "All Degree Activities",
        "shortLabel": "All Degree",
        "icon": "grid",
        "thumbnail": {
          "src": "/sections/nami/level-bachelor-master.jpg",
          "alt": "All Degree Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "websurfer",
        "label": "WebSurfer Nepal",
        "shortLabel": "WebSurfer",
        "icon": "tech",
        "thumbnail": {
          "src": "/logos/mou/websurfer-logo-brighter1920x658-removebg-preview.png",
          "alt": "WebSurfer Nepal",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "startup-discovery",
        "label": "Startup Discovery Asia",
        "shortLabel": "Startup Asia",
        "icon": "business",
        "thumbnail": {
          "src": "/logos/mou/Startup_Discovery-removebg-preview.png",
          "alt": "Startup Discovery Asia",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "machan",
        "label": "Machan Wildlife Resort",
        "shortLabel": "Machan Resort",
        "icon": "science",
        "thumbnail": {
          "src": "/logos/mou/machian-removebg-preview.png",
          "alt": "Machan Wildlife Resort",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "suraj-interior",
        "label": "Suraj Interior & Design",
        "shortLabel": "Suraj Interior",
        "icon": "arts",
        "thumbnail": {
          "src": "/logos/mou/Suraj-removebg-preview.png",
          "alt": "Suraj Interior & Design",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "cross-web",
        "label": "Cross Web IT Solutions",
        "shortLabel": "Cross Web",
        "icon": "tech",
        "thumbnail": {
          "src": "/logos/mou/Cross_web-removebg-preview.png",
          "alt": "Cross Web IT Solutions",
          "width": 0,
          "height": 0
        },
        "logo": false
      },
      {
        "key": "others",
        "label": "Other Degree Activities",
        "shortLabel": "Others",
        "icon": "convocation",
        "thumbnail": {
          "src": "/gallery/Bachelors/Events/graduation.jpeg",
          "alt": "Other Degree Activities",
          "width": 0,
          "height": 0
        },
        "logo": false
      }
    ]
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);

add_filter(
	'nami_cms_collections',
	function ( $collections ) {
		$collections['gallery-items'] = array(
			'post_type'   => 'nami_gallery',
			'singular'    => 'Moment',
			'plural'      => 'Moments',
			'menu_name'   => 'Gallery',
			'icon'        => 'dashicons-format-gallery',
			'position'    => 3.8,
			'title_label' => 'Caption (shown on the photo and in full-screen view)',
			'description' => 'A photo, a video or a quote card on the Gallery page. To add many photos at once, use Gallery → Add Many Photos.',
			'columns'     => array( 'type', 'institution', 'bubble' ),
			'ready'       => false,
			'fields'      => array(
				'type'        => array(
					'type'    => 'select',
					'label'   => 'Kind',
					'options' => array(
						'image' => 'Photo',
						'video' => 'Video (shows the photo with a play button)',
						'quote' => 'Quote card',
					),
				),
				'institution' => array( 'type' => 'select', 'label' => 'Tab', 'options' => nami_gallery_institutions() ),
				'category'    => array( 'type' => 'select', 'label' => 'Category', 'options' => nami_gallery_categories() ),
				'bubble'      => array( 'type' => 'select', 'label' => 'Bubble', 'options' => nami_gallery_bubble_options(), 'help' => 'Pick a bubble of the same tab. Manage bubbles under Gallery → Page: Bubbles.' ),
				'image'       => array( 'type' => 'image', 'label' => 'Photo', 'help' => 'Needed for photos and videos. A moment without a photo is not shown.' ),
				'videoUrl'    => array( 'type' => 'video', 'label' => 'Video (for the Video kind)' ),
				'quoteText'   => array( 'type' => 'textarea', 'label' => 'Quote (for the Quote card kind)', 'rows' => 3 ),
				'quoteAuthor' => array( 'type' => 'text', 'label' => 'Quote by' ),
			),
			'import'      => json_decode(
				<<<'NAMI_IMPORT'
[
  {
    "title": "WebSurfer Industry AI & Computing Lab",
    "date": "2026-09-30",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "academics",
      "bubble": "websurfer",
      "image": {
        "src": "/gallery/Bachelors/Academic/ai.jpeg",
        "alt": "University students in interactive AI workshop and computing lab",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Campus Life & Student Celebrations",
    "date": "2026-09-29",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "campus-life",
      "bubble": "student-life",
      "image": {
        "src": "/gallery/A-levels/Events/xyz1.jpeg",
        "alt": "A-Levels students on campus during annual events",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Higher Secondary Holi Fest & Campus Celebrations",
    "date": "2026-09-28",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "event-management",
      "image": {
        "src": "/gallery/Higher Secondary/Events/HOLI.jpeg",
        "alt": "+2 cohort celebrating Spring Holi with vibrant organic colors on campus",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Primary Interactive Smart Classroom",
    "date": "2026-09-27",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "tech-3di",
      "image": {
        "src": "/sections/nami/level-school.jpg",
        "alt": "Primary school faculty teaching in interactive modern classroom",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Inter-House Basketball League",
    "date": "2026-09-26",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "sports",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/xyz.jpeg",
        "alt": "A-Levels students playing basketball in sports fixture",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Cross Web Data Innovation & Computing Laboratory",
    "date": "2026-09-25",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "academics",
      "bubble": "cross-web",
      "image": {
        "src": "/gallery/Bachelors/Academic/ai1.jpeg",
        "alt": "Students coding and working in university computing laboratory",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Cultural Fest & Stage Performances",
    "date": "2026-09-24",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "events",
      "bubble": "arts-crafts",
      "image": {
        "src": "/gallery/A-levels/Events/xyz.jpeg",
        "alt": "Students performing cultural and musical items on stage",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Inspirational Quote Card",
    "date": "2026-09-23",
    "fields": {
      "type": "quote",
      "institution": "all",
      "category": "all",
      "bubble": "",
      "image": {
        "src": "",
        "alt": "",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "The future belongs to those who believe in the beauty of their dreams.",
      "quoteAuthor": "Eleanor Roosevelt"
    }
  },
  {
    "title": "Primary Junior Explorers Walk",
    "date": "2026-09-22",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "others",
      "image": {
        "src": "/sections/nami/event-plantation-2022.jpg",
        "alt": "Students walking through university campus garden with books",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "University Convocation & Degree Award Ceremony",
    "date": "2026-09-21",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "achievements",
      "bubble": "others",
      "image": {
        "src": "/gallery/Bachelors/Events/graduation.jpeg",
        "alt": "Graduating class in formal convocation caps and gowns",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Annual Music Fest Live Performance",
    "date": "2026-09-20",
    "fields": {
      "type": "video",
      "institution": "bachelors",
      "category": "events",
      "bubble": "others",
      "image": {
        "src": "/sections/nami/event-elite-2023.jpg",
        "alt": "Student musician playing acoustic guitar and singing on stage",
        "width": 0,
        "height": 0
      },
      "videoUrl": "/videos/nami-video.mp4",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Graduating Class Farewell Gala",
    "date": "2026-09-19",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "events",
      "bubble": "student-life",
      "image": {
        "src": "/gallery/A-levels/Events/farewell.jpeg",
        "alt": "A-Levels farewell celebration and gathering",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "WebSurfer Telecom & High-Performance Computing Seminar",
    "date": "2026-09-18",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "academics",
      "bubble": "websurfer",
      "image": {
        "src": "/gallery/Bachelors/Academic/ai3.jpeg",
        "alt": "Students attending advanced machine learning and computing lecture",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Startup Discovery Asia Corporate Internship Induction",
    "date": "2026-09-17",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "academics",
      "bubble": "startup-discovery",
      "image": {
        "src": "/gallery/Bachelors/Academic/internship.jpeg",
        "alt": "Bachelors students during corporate internship onboarding",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Machan Eco-Tourism & Climate AI Symposium",
    "date": "2026-09-16",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "events",
      "bubble": "machan",
      "image": {
        "src": "/gallery/Bachelors/Events/ClimateAI.jpeg",
        "alt": "University symposium focusing on climate change and artificial intelligence",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Machan Wildlife Resort Sustainability Panel",
    "date": "2026-09-15",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "events",
      "bubble": "machan",
      "image": {
        "src": "/gallery/Bachelors/Events/ClimateAI1.jpeg",
        "alt": "Panel session with experts and students discussing climate solutions",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Startup Discovery Asia Venture Pitch Day",
    "date": "2026-09-14",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "achievements",
      "bubble": "startup-discovery",
      "image": {
        "src": "/gallery/Bachelors/Events/pitchday.jpeg",
        "alt": "Undergraduate student entrepreneurs pitching business ideas",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Cross Web Office Automation & Software Showcase",
    "date": "2026-09-13",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "events",
      "bubble": "cross-web",
      "image": {
        "src": "/gallery/Bachelors/Events/pitchday1.jpeg",
        "alt": "Students presenting technical project before panel of judges",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Suraj Interior Architecture & Space Design Study",
    "date": "2026-09-12",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "academics",
      "bubble": "suraj-interior",
      "image": {
        "src": "/gallery/Bachelors/College Life/tour.jpeg",
        "alt": "University design and engineering students during spatial architecture study",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Graduating Batch Convocation Celebration",
    "date": "2026-09-11",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "achievements",
      "bubble": "others",
      "image": {
        "src": "/gallery/Bachelors/Events/graduation1.jpeg",
        "alt": "Graduates celebrating convocation milestone",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Inter-University Esports League & Gaming Arena",
    "date": "2026-09-10",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "sports",
      "bubble": "others",
      "image": {
        "src": "/gallery/Bachelors/Sports/esport.jpeg",
        "alt": "Bachelors students competing in university esports tournament",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Campus Esports Championship Grand Finals",
    "date": "2026-09-09",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "sports",
      "bubble": "others",
      "image": {
        "src": "/gallery/Bachelors/Sports/esport1.jpeg",
        "alt": "Finals stage match of inter-college gaming cup",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "University Educational Excursion & Field Study",
    "date": "2026-09-08",
    "fields": {
      "type": "image",
      "institution": "bachelors",
      "category": "campus-life",
      "bubble": "others",
      "image": {
        "src": "/gallery/Bachelors/College Life/tour.jpeg",
        "alt": "Bachelors students group photograph during national field excursion",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Cambridge A-Levels Classroom & Academic Seminars",
    "date": "2026-09-07",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "academics",
      "bubble": "academics",
      "image": {
        "src": "/gallery/A-levels/Academic/xyz.jpeg",
        "alt": "A-Levels students engaged in academic seminar",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Science Laboratory & Research Practicals",
    "date": "2026-09-06",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "academics",
      "bubble": "academics",
      "image": {
        "src": "/gallery/A-levels/Academic/xyz1.jpeg",
        "alt": "A-Levels science practicals and laboratory session",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Cambridge Interactive Learning Sessions",
    "date": "2026-09-05",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "academics",
      "bubble": "academics",
      "image": {
        "src": "/gallery/A-levels/Academic/xyz2.jpeg",
        "alt": "Interactive study and group discussions",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Martial Arts & Karate Demonstration",
    "date": "2026-09-04",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "sports",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/karate.jpeg",
        "alt": "Students demonstrating martial arts in the dojo",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Sports Gala & Track Competitions",
    "date": "2026-09-03",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "sports",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/xyz1.jpeg",
        "alt": "Track and field sports meet in progress",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Futsal Championship Tournament",
    "date": "2026-09-02",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "sports",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/xyz2.jpeg",
        "alt": "Futsal match action on campus turf",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Indoor Games, Badminton & Table Tennis",
    "date": "2026-09-01",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "sports",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/xyz3.jpeg",
        "alt": "Indoor sports and recreational games",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Annual Sports Award & Medal Distribution",
    "date": "2026-08-31",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "achievements",
      "bubble": "sports",
      "image": {
        "src": "/gallery/A-levels/Sports/xyz4.jpeg",
        "alt": "Students receiving awards and medals",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Farewell Felicitations & Batch Celebration",
    "date": "2026-08-30",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "events",
      "bubble": "student-life",
      "image": {
        "src": "/gallery/A-levels/Events/farewell1.jpeg",
        "alt": "Students celebrating with teachers and classmates",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "A-Levels Orientation & Welcome Reception",
    "date": "2026-08-29",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "events",
      "bubble": "student-life",
      "image": {
        "src": "/gallery/A-levels/Events/xyz2.jpeg",
        "alt": "New batch welcome ceremonies and campus orientation",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Mustang Academic & Community Service Trip",
    "date": "2026-08-28",
    "fields": {
      "type": "image",
      "institution": "a-levels",
      "category": "events",
      "bubble": "social-services",
      "image": {
        "src": "/sections/nami/hero-mustang.jpg",
        "alt": "A-Levels students on community and ecological trip in Mustang",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Hotel Management Culinary & Table Service Practicals",
    "date": "2026-08-27",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "academics",
      "bubble": "academic-tours",
      "image": {
        "src": "/gallery/Higher Secondary/Academic/HotelManagementHandsOnlearning.jpeg",
        "alt": "+2 Hotel Management students demonstrating culinary and guest service skills",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Hospitality Industry Simulation Laboratory",
    "date": "2026-08-26",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "academics",
      "bubble": "academic-tours",
      "image": {
        "src": "/gallery/Higher Secondary/Academic/HotelManagementHandsOnlearning1.jpeg",
        "alt": "Hospitality students preparing dining presentation",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "KIST Science & Technology Innovation Fair 2081",
    "date": "2026-08-25",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "academics",
      "bubble": "science-tech",
      "image": {
        "src": "/gallery/Higher Secondary/Academic/KIST FAIR- 2081.jpeg",
        "alt": "+2 Science students showcasing science and engineering models at KIST Fair",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Robotics & Hardware Prototype Demonstration",
    "date": "2026-08-24",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "academics",
      "bubble": "science-tech",
      "image": {
        "src": "/gallery/Higher Secondary/Academic/KIST FAIR1- 2081.jpeg",
        "alt": "Students presenting engineering projects to visitors",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Zero Plastic 2040 Campus Sustainability Pledge",
    "date": "2026-08-23",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "event-management",
      "image": {
        "src": "/gallery/Higher Secondary/Events/Zero Plastic 2040.jpg",
        "alt": "+2 students and teachers taking the Zero Plastic 2040 pledge on campus",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Intra-School Visual Arts & Creative Painting Contest",
    "date": "2026-08-22",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "art-literature",
      "image": {
        "src": "/gallery/Higher Secondary/Events/intra-school art competition .jpeg",
        "alt": "+2 students creating paintings and sketches during art competition",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Fine Arts Exhibition & Gallery Presentation",
    "date": "2026-08-21",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "art-literature",
      "image": {
        "src": "/gallery/Higher Secondary/Events/intra-school art competition 1.jpeg",
        "alt": "Creative art showcase displayed along the campus corridor",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Youth Social Service Club Community Drive",
    "date": "2026-08-20",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "social-service",
      "image": {
        "src": "/gallery/Higher Secondary/Events/Social Service Club.jpeg",
        "alt": "+2 Social Service Club students leading community awareness drive",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Campus Blood Donation & Health Campaign",
    "date": "2026-08-19",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "events",
      "bubble": "social-service",
      "image": {
        "src": "/gallery/Higher Secondary/Events/Social Service Club1.jpeg",
        "alt": "Students organizing health camp and blood donation registration",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Basketball Tournament 2082 Championship Victory",
    "date": "2026-08-18",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "sports",
      "bubble": "sports-club",
      "image": {
        "src": "/gallery/Higher Secondary/Sports/Basketball Tournament—2082.jpeg",
        "alt": "Higher Secondary basketball team lifting championship trophy",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Inter-College Basketball Championship Match",
    "date": "2026-08-17",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "sports",
      "bubble": "sports-club",
      "image": {
        "src": "/gallery/Higher Secondary/Sports/Basketball Tournament—20821.jpeg",
        "alt": "+2 basketball match in progress with roaring crowds",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Annual +2 Futsal Championship League",
    "date": "2026-08-16",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "sports",
      "bubble": "sports-club",
      "image": {
        "src": "/gallery/Higher Secondary/Sports/futsal.jpeg",
        "alt": "Action photograph from the +2 futsal tournament finals",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Higher Secondary Educational & Cultural Excursion",
    "date": "2026-08-15",
    "fields": {
      "type": "image",
      "institution": "higher-secondary",
      "category": "campus-life",
      "bubble": "academic-tours",
      "image": {
        "src": "/gallery/Higher Secondary/School Life/Educational Tour.jpeg",
        "alt": "Group photograph of students during educational tour",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Math Olympiad & Mental Math Champions",
    "date": "2026-08-14",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "academics-math",
      "image": {
        "src": "/gallery/Primary School/Academic/Math Olympiad 2026.jpg",
        "alt": "Primary pupils celebrating Math Olympiad achievements",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Basantapur Heritage & History Excursion",
    "date": "2026-08-13",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "others",
      "image": {
        "src": "/gallery/Primary School/Academic/Basantapur Square academicvisit.jpg",
        "alt": "Primary school students visiting Basantapur Durbar Square",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Interactive Human Number Line Activity",
    "date": "2026-08-12",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "academics-math",
      "image": {
        "src": "/gallery/Primary School/Academic/Human Number Line Activity.jpg",
        "alt": "Pupils learning mathematics on the courtyard number line",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "World Day for Cultural Diversity Celebrations",
    "date": "2026-08-11",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "events",
      "bubble": "others",
      "image": {
        "src": "/gallery/Primary School/Cultural/World Day for Cultural Diversity 2026.jpg",
        "alt": "Primary school cultural diversity day performances and traditional attire",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "National Literacy & Book Reading Week",
    "date": "2026-08-10",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "events",
      "bubble": "others",
      "image": {
        "src": "/gallery/Primary School/Events/Literacy week.jpg",
        "alt": "Students engaging in library storytelling and reading activities",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Claymation & Creative Art Workshop",
    "date": "2026-08-09",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "others",
      "image": {
        "src": "/gallery/Primary School/School Life/CLAYMATION.jpg",
        "alt": "Primary pupils crafting stop-motion clay characters",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Field Trip to the National Museum of Nepal",
    "date": "2026-08-08",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "others",
      "image": {
        "src": "/gallery/Primary School/School Life/field trip to the National Museum of Nepal.jpg",
        "alt": "Primary children discovering historic artifacts at the national museum",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Play Nepal Inter-School Obstacle Course Challenge",
    "date": "2026-08-07",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "sports",
      "bubble": "sports-playnepal",
      "image": {
        "src": "/gallery/Primary School/Sports/Play Nepal IOCC 2026 Obstacle Challenge.jpg",
        "alt": "Primary pupils navigating athletic obstacle course challenges",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "International Open Friendship Taekwondo Championship",
    "date": "2026-08-06",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "sports",
      "bubble": "sports-playnepal",
      "image": {
        "src": "/gallery/Primary School/Sports/25th Anniversary of IOFTC & 15th International Open Friendship Taekwondo Championship 2025.jpeg",
        "alt": "Primary martial arts pupils with championship medals and certificates",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "3Di School Innovation & Science Exploration",
    "date": "2026-08-05",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "tech-3di",
      "image": {
        "src": "/gallery/Primary School/Academic/identifying living and non-living things.jpg",
        "alt": "Primary students working with 3Di science models and specimens",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Zero Waste & Ecological Stewardship Workshop",
    "date": "2026-08-04",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "tech-3di",
      "image": {
        "src": "/gallery/Primary School/School Life/Zero Waste Workshop.jpg",
        "alt": "Primary pupils learning zero-waste recycling and sustainability practices",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Mero Coding Robotics & Project Model Making",
    "date": "2026-08-03",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "mero-coding",
      "image": {
        "src": "/gallery/Primary School/School Life/project model-making.jpg",
        "alt": "Primary pupils building project models and exploring coding logic",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Mero Coding Digital Logic & Career Horizons",
    "date": "2026-08-02",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "academics",
      "bubble": "mero-coding",
      "image": {
        "src": "/gallery/Primary School/Academic/career path.jpg",
        "alt": "Primary students attending computational thinking and tech workshop",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Samatva Wellness Yoga & Mindfulness Practice",
    "date": "2026-08-01",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "samatva-wellness",
      "image": {
        "src": "/gallery/Primary School/School Life/yoga.jpg",
        "alt": "Primary children practicing mindful movement and yoga on campus",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  },
  {
    "title": "Samatva Oral Health & Hygiene Awareness Camp",
    "date": "2026-07-31",
    "fields": {
      "type": "image",
      "institution": "primary",
      "category": "campus-life",
      "bubble": "samatva-wellness",
      "image": {
        "src": "/gallery/Primary School/School Life/Oral Health Camp and Oral Hygiene Awareness Session.jpg",
        "alt": "Primary pupils in health and hygiene education workshop",
        "width": 0,
        "height": 0
      },
      "videoUrl": "",
      "quoteText": "",
      "quoteAuthor": ""
    }
  }
]
NAMI_IMPORT
				,
				true
			),
		);
		return $collections;
	}
);

/* ------------------------------------------------------------------
 * Gallery → Add Many Photos
 * ------------------------------------------------------------------ */

add_action(
	'admin_menu',
	function () {
		$hook = add_submenu_page(
			'edit.php?post_type=nami_gallery',
			'Add Many Photos',
			'Add Many Photos',
			'edit_pages',
			'nami-gallery-bulk',
			'nami_gallery_render_bulk'
		);
		add_action(
			'admin_enqueue_scripts',
			function ( $current ) use ( $hook ) {
				if ( $current === $hook ) {
					wp_enqueue_media();
				}
			}
		);
	},
	20
);

function nami_gallery_select( $name, array $options, $selected = '' ) {
	$html = sprintf( '<select name="%s" id="%s">', esc_attr( $name ), esc_attr( $name ) );
	foreach ( $options as $value => $label ) {
		$html .= sprintf( '<option value="%s"%s>%s</option>', esc_attr( $value ), selected( (string) $selected, (string) $value, false ), esc_html( $label ) );
	}
	return $html . '</select>';
}

function nami_gallery_render_bulk() {
	$added = isset( $_GET['nami_added'] ) ? absint( $_GET['nami_added'] ) : null;
	echo '<div class="wrap"><h1>Add Many Photos</h1>';
	if ( null !== $added ) {
		printf(
			'<div class="notice notice-success is-dismissible"><p>%s <a href="%s">See all moments</a></p></div>',
			esc_html( sprintf( '%d photo%s added to the gallery.', $added, 1 === $added ? '' : 's' ) ),
			esc_url( admin_url( 'edit.php?post_type=nami_gallery' ) )
		);
	}
	echo '<p style="max-width:720px">Choose or upload several photos, pick where they belong, and add them in one go. Each photo becomes its own moment; its caption is the photo\'s title in the Media Library (you can change it afterwards).</p>';
	echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">';
	echo '<input type="hidden" name="action" value="nami_gallery_bulk">';
	wp_nonce_field( 'nami_gallery_bulk' );
	echo '<input type="hidden" name="photos" id="nami-bulk-photos" value="[]">';
	echo '<table class="form-table" role="presentation"><tbody>';
	echo '<tr><th scope="row">Photos</th><td><p><button type="button" class="button button-primary" id="nami-bulk-pick">Choose / upload photos</button></p><div id="nami-bulk-preview" style="display:flex;flex-wrap:wrap;gap:8px;margin-top:8px"></div><p class="description" id="nami-bulk-count">No photos chosen yet.</p></td></tr>';
	echo '<tr><th scope="row"><label for="institution">Tab</label></th><td>' . nami_gallery_select( 'institution', nami_gallery_institutions(), 'all' ) . '</td></tr>'; // phpcs:ignore WordPress.Security.EscapeOutput
	echo '<tr><th scope="row"><label for="category">Category</label></th><td>' . nami_gallery_select( 'category', nami_gallery_categories(), 'events' ) . '</td></tr>'; // phpcs:ignore WordPress.Security.EscapeOutput
	echo '<tr><th scope="row"><label for="bubble">Bubble</label></th><td>' . nami_gallery_select( 'bubble', nami_gallery_bubble_options() ) . '</td></tr>'; // phpcs:ignore WordPress.Security.EscapeOutput
	echo '<tr><th scope="row"><label for="caption">Caption (optional)</label></th><td><input type="text" class="regular-text" name="caption" id="caption"><p class="description">Used for every photo instead of its Media Library title, e.g. "Sports Week 2026".</p></td></tr>';
	echo '</tbody></table>';
	submit_button( 'Add photos to the gallery' );
	echo '</form></div>';
	?>
	<script>
	(function () {
		var chosen = [];
		var input = document.getElementById('nami-bulk-photos');
		var preview = document.getElementById('nami-bulk-preview');
		var count = document.getElementById('nami-bulk-count');
		document.getElementById('nami-bulk-pick').addEventListener('click', function (event) {
			event.preventDefault();
			var frame = wp.media({ title: 'Choose photos', library: { type: 'image' }, button: { text: 'Use these photos' }, multiple: 'add' });
			frame.on('select', function () {
				chosen = frame.state().get('selection').toJSON().map(function (file) {
					return { id: file.id, url: file.url, alt: file.alt || '', title: file.title || '', width: file.width || 0, height: file.height || 0 };
				});
				input.value = JSON.stringify(chosen);
				preview.innerHTML = '';
				chosen.forEach(function (file) {
					var img = document.createElement('img');
					img.src = file.url;
					img.alt = '';
					img.style.cssText = 'width:96px;height:72px;object-fit:cover;border-radius:4px;border:1px solid #dcdcde';
					preview.appendChild(img);
				});
				count.textContent = chosen.length + ' photo' + (chosen.length === 1 ? '' : 's') + ' chosen.';
			});
			frame.open();
		});
	})();
	</script>
	<?php
}

add_action(
	'admin_post_nami_gallery_bulk',
	function () {
		check_admin_referer( 'nami_gallery_bulk' );
		if ( ! current_user_can( 'edit_pages' ) || ! function_exists( 'nami_cms_collections' ) ) {
			wp_die( 'You are not allowed to add photos.', 403 );
		}
		$config = nami_cms_collections()['gallery-items'] ?? null;
		if ( null === $config ) {
			wp_die( 'The gallery is not set up.', 500 );
		}

		$photos  = json_decode( wp_unslash( (string) ( $_POST['photos'] ?? '[]' ) ), true ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- each value sanitised below.
		$caption = sanitize_text_field( wp_unslash( $_POST['caption'] ?? '' ) );
		$shared  = array(
			'type'        => 'image',
			'institution' => wp_unslash( $_POST['institution'] ?? 'all' ),
			'category'    => wp_unslash( $_POST['category'] ?? 'all' ),
			'bubble'      => wp_unslash( $_POST['bubble'] ?? '' ),
		);
		$added   = 0;
		$GLOBALS['nami_cms_quiet'] = true;

		foreach ( is_array( $photos ) ? array_slice( $photos, 0, 200 ) : array() as $photo ) {
			if ( ! is_array( $photo ) || ! wp_attachment_is_image( absint( $photo['id'] ?? 0 ) ) ) {
				continue;
			}
			$id      = absint( $photo['id'] );
			$title   = '' !== $caption ? $caption : sanitize_text_field( (string) get_the_title( $id ) );
			$alt     = (string) get_post_meta( $id, '_wp_attachment_image_alt', true );
			$meta    = wp_get_attachment_metadata( $id );
			$post_id = wp_insert_post(
				array(
					'post_type'   => 'nami_gallery',
					'post_status' => 'publish',
					'post_title'  => '' !== $title ? $title : 'Photo',
				),
				true
			);
			if ( is_wp_error( $post_id ) ) {
				continue;
			}
			$fields = nami_cms_collection_clean(
				$config,
				array_merge(
					$shared,
					array(
						'image' => array(
							'src'    => wp_get_attachment_url( $id ),
							'alt'    => '' !== $alt ? $alt : $title,
							'width'  => $meta['width'] ?? 0,
							'height' => $meta['height'] ?? 0,
						),
					)
				)
			);
			update_post_meta( $post_id, '_nami_fields', wp_slash( $fields ) );
			++$added;
		}

		$GLOBALS['nami_cms_quiet'] = false;
		if ( $added > 0 ) {
			nami_cms_notify_site( 'gallery-items' );
		}
		wp_safe_redirect( admin_url( 'edit.php?post_type=nami_gallery&page=nami-gallery-bulk&nami_added=' . $added ) );
		exit;
	}
);
