<?php
/**
 * NAMI CMS — Documents & Publications
 *
 * Requires the "NAMI CMS — Core engine" snippet, version 1.2.0 or later
 * (collections). Adds a "Documents" menu:
 *   - All Documents / Add New: each downloadable file on /documents
 *     (forms, books, brochures …).
 *   - Page: …: the heading, the category tabs, the empty-search message and
 *     the "apply online" banner.
 *
 * Field keys must match src/lib/cms/pages/documents/types.ts in the Next.js project.
 * The JSON blocks at the bottom are generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

/** Category choices come from Documents → Page: Categories. */
function nami_documents_category_options() {
	$options = array();
	if ( function_exists( 'nami_cms_get_values' ) ) {
		$values = nami_cms_get_values( 'documents' );
		$items  = $values['categories']['items'] ?? array();
		foreach ( is_array( $items ) ? $items : array() as $item ) {
			$key = trim( (string) ( $item['key'] ?? '' ) );
			if ( '' !== $key ) {
				$options[ $key ] = (string) ( $item['label'] ?? $key );
			}
		}
	}
	return empty( $options ) ? array( '' => '— Add categories under Documents → Page: Categories —' ) : $options;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$pages['documents'] = array(
			'title'          => 'Documents page',
			'menu_parent'    => 'edit.php?post_type=nami_document',
			'submenu_prefix' => 'Page: ',
			'path'           => '/documents',
			'sections'       => array(
				'heading'    => array(
					'title'       => 'Heading',
					'description' => 'The top of the Documents page and the search box.',
					'fields'      => array(
						'label'             => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'             => array( 'type' => 'text', 'label' => 'Title' ),
						'description'       => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'searchPlaceholder' => array( 'type' => 'text', 'label' => 'Hint in the search box' ),
					),
				),
				'categories' => array(
					'title'       => 'Categories',
					'description' => 'The filter buttons above the documents. Each document is filed under one category by its key.',
					'fields'      => array(
						'allLabel' => array( 'type' => 'text', 'label' => 'Name of the "show everything" button' ),
						'items'    => array(
							'type'        => 'repeater',
							'label'       => 'Categories',
							'item_label'  => 'Category',
							'title_field' => 'label',
							'fields'      => array(
								'key'   => array( 'type' => 'text', 'label' => 'Key', 'help' => 'Short lowercase name with hyphens, e.g. admissions. Changing it unfiles the documents under it.' ),
								'label' => array( 'type' => 'text', 'label' => 'Button name' ),
							),
						),
					),
				),
				'empty'      => array(
					'title'       => 'No Results',
					'description' => 'Shown when a search finds nothing.',
					'fields'      => array(
						'title'      => array( 'type' => 'text', 'label' => 'Title' ),
						'text'       => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 2 ),
						'resetLabel' => array( 'type' => 'text', 'label' => 'Reset button text' ),
					),
				),
				'banner'     => array(
					'title'       => 'Apply Online Banner',
					'description' => 'The banner under the documents.',
					'fields'      => array(
						'title'  => array( 'type' => 'text', 'label' => 'Title', 'help' => 'Leave empty to hide the banner.' ),
						'text'   => array( 'type' => 'textarea', 'label' => 'Text', 'rows' => 2 ),
						'button' => array( 'type' => 'link', 'label' => 'Button' ),
					),
				),
				'seo'        => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Documents page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Documents & Publications",
    "description": "Download official NAMI publications, the institutional book and printable admission application forms for NAMI International School, NAMI College and Naaya Aayam Multi-Disciplinary Institute."
  },
  "heading": {
    "label": "Official Resources",
    "title": "Documents & Publications",
    "description": "Access and download official institutional publications, prospectus books, curriculum guidelines, and printable admission application forms across NAMI institutions.",
    "searchPlaceholder": "Search documents or forms..."
  },
  "categories": {
    "allLabel": "All Documents",
    "items": [
      {
        "key": "publications",
        "label": "Publications & Books"
      },
      {
        "key": "admissions",
        "label": "Admission Forms"
      }
    ]
  },
  "empty": {
    "title": "No documents found",
    "text": "No documents match your search criteria. Try a different search term or category.",
    "resetLabel": "Reset Filters"
  },
  "banner": {
    "title": "Prefer applying completely online?",
    "text": "You can fill out the dynamic digital inquiry and application form directly in your browser without printing.",
    "button": {
      "label": "Online Admissions Portal →",
      "href": "/admissions"
    }
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);

add_filter(
	'nami_cms_collections',
	function ( $collections ) {
		$collections['documents'] = array(
			'post_type'   => 'nami_document',
			'singular'    => 'Document',
			'plural'      => 'Documents',
			'icon'        => 'dashicons-media-document',
			'position'    => 3.85,
			'title_label' => 'Document title',
			'description' => 'A downloadable file on the Documents page. Upload the file with "Choose / upload file".',
			'columns'     => array( 'category', 'institution', 'fileSize' ),
			'ready'       => false,
			'fields'      => array(
				'file'        => array( 'type' => 'file', 'label' => 'File', 'help' => 'Upload a PDF (or Word file), or paste a link. A document without a file is not shown.' ),
				'category'    => array( 'type' => 'select', 'label' => 'Category', 'options' => nami_documents_category_options() ),
				'institution' => array(
					'type'    => 'select',
					'label'   => 'Institution (badge on the card)',
					'options' => array(
						'NAMI Group' => 'NAMI Group',
						'School'     => 'School',
						'College'    => 'College',
						'Institute'  => 'Institute',
					),
				),
				'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 4 ),
				'note'        => array( 'type' => 'text', 'label' => 'Small note at the bottom of the card', 'placeholder' => 'Academic Intake 2026' ),
				'fileSize'    => array( 'type' => 'text', 'label' => 'File size', 'help' => 'Leave empty: it is filled in automatically from the uploaded file when you save.' ),
				'featured'    => array( 'type' => 'toggle', 'label' => 'Highlight', 'toggle_label' => 'Give this card a red outline' ),
			),
			'import'      => json_decode(
				<<<'NAMI_IMPORT'
[
  {
    "title": "NAMI Institutional Book & Profile",
    "date": "2026-09-30",
    "fields": {
      "category": "publications",
      "institution": "NAMI Group",
      "description": "Comprehensive institutional profile of Naaya Aayam Multi-Disciplinary Institute, highlighting governance, academic credentials, UK degree partnerships, Cambridge affiliation, campus infrastructure, and founding philosophy.",
      "file": "/documents/Nami book.pdf",
      "fileSize": "4.15 MB",
      "note": "Official Edition",
      "featured": true
    }
  },
  {
    "title": "Bachelors & Masters Degree Application Form",
    "date": "2026-09-29",
    "fields": {
      "category": "admissions",
      "institution": "Institute",
      "description": "Official admission application form for University of Northampton (UK) undergraduate and postgraduate programmes at NAMI (BSc. Computing, Software Engineering, Network Engineering, Environmental Science, BBA, MBA).",
      "file": "/documents/Nami_applicationform_bachelors.pdf",
      "fileSize": "111 KB",
      "note": "Academic Intake 2026",
      "featured": true
    }
  },
  {
    "title": "Cambridge International A-Level Application Form",
    "date": "2026-09-28",
    "fields": {
      "category": "admissions",
      "institution": "College",
      "description": "Official admission form for Cambridge Assessment International Education (CAIE) AS and A Level programmes across Science, Business, and Humanities streams at NAMI College.",
      "file": "/documents/NAMI_College_A_Level_Application_Form.pdf",
      "fileSize": "255 KB",
      "note": "Academic Intake 2026",
      "featured": true
    }
  },
  {
    "title": "NAMI International School (+2 Higher Secondary) Application Form",
    "date": "2026-09-27",
    "fields": {
      "category": "admissions",
      "institution": "School",
      "description": "Official enrollment form for National Examinations Board (NEB) Grade XI & XII (+2 Science & Management) at NAMI International School.",
      "file": "/documents/Application_form_nami_international_school_plus_2.pdf",
      "fileSize": "3.03 MB",
      "note": "Academic Intake 2026",
      "featured": false
    }
  },
  {
    "title": "NAMI International School (Primary School) Admission Form",
    "date": "2026-09-26",
    "fields": {
      "category": "admissions",
      "institution": "School",
      "description": "Official enrollment and student record application form for primary learners (Grades I through VII) at NAMI International School.",
      "file": "/documents/Nami International School (Primary) Admission form.pdf",
      "fileSize": "135 KB",
      "note": "Academic Intake 2026",
      "featured": false
    }
  }
]
NAMI_IMPORT
				,
				true
			),
		);
		return $collections;
	}
);

// Fill in the file size from the upload when it was left empty. Runs after the
// core engine has saved the fields (priority 10) and before it refreshes the
// website (priority 99).
add_action(
	'save_post_nami_document',
	function ( $post_id ) {
		if ( wp_is_post_revision( $post_id ) ) {
			return;
		}
		$fields = get_post_meta( $post_id, '_nami_fields', true );
		if ( ! is_array( $fields ) || '' !== trim( (string) ( $fields['fileSize'] ?? '' ) ) ) {
			return;
		}
		$attachment = attachment_url_to_postid( (string) ( $fields['file'] ?? '' ) );
		$path       = $attachment ? get_attached_file( $attachment ) : '';
		if ( ! $path || ! file_exists( $path ) ) {
			return;
		}
		$fields['fileSize'] = size_format( filesize( $path ), 2 );
		update_post_meta( $post_id, '_nami_fields', wp_slash( $fields ) );
	},
	20
);
