<?php
/**
 * NAMI CMS — Contact page and Messages inbox
 *
 * Requires the "NAMI CMS — Core engine" snippet (it holds the shared secret,
 * Settings → NAMI CMS). Adds a "Contact" menu:
 *   - Messages: every message sent with the form on /contact (received from the
 *     Next.js route src/app/api/contact/route.ts, signed with the shared secret),
 *     with a status, internal notes and a "Reply by email" button.
 *   - Email Settings: who is emailed about each new message.
 *   - Page: …: the text of the Contact page.
 *
 * Emails use WordPress's own mail function; see the Applications snippet notes
 * about installing an SMTP plugin such as "WP Mail SMTP".
 *
 * Page field keys must match src/lib/cms/pages/contact/types.ts in the Next.js
 * project. The JSON block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) || defined( 'NAMI_CONTACT' ) ) {
	return;
}
define( 'NAMI_CONTACT', '1.0.0' );

const NAMI_MSG_TYPE = 'nami_message';
const NAMI_MSG_CAP  = 'edit_pages';

function nami_msg_statuses() {
	return array(
		'new'     => 'New',
		'replied' => 'Replied',
		'closed'  => 'Closed',
	);
}

function nami_msg_meta( $post_id, $key ) {
	return get_post_meta( $post_id, '_nami_' . $key, true );
}

function nami_msg_settings() {
	$saved = get_option( 'nami_msg_settings', array() );
	$saved = is_array( $saved ) ? $saved : array();
	return array_merge( array( 'to' => 'info@nami.edu.np' ), $saved );
}

function nami_msg_emails( $raw ) {
	$list = preg_split( '/[\s,;]+/', (string) $raw );
	return array_values( array_filter( array_map( 'sanitize_email', $list ), 'is_email' ) );
}

/* ------------------------------------------------------------------
 * Page text (Contact → Page: …)
 * ------------------------------------------------------------------ */

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$pages['contact'] = array(
			'title'          => 'Contact page',
			'menu_parent'    => 'edit.php?post_type=' . NAMI_MSG_TYPE,
			'submenu_prefix' => 'Page: ',
			'path'           => '/contact',
			'sections'       => array(
				'masthead'  => array(
					'title'       => 'Heading',
					'description' => 'The top of the Contact page. The email, phone numbers and social links come from Site Settings → Contact & Social Media.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'emailLabel'  => array( 'type' => 'text', 'label' => 'Label above the email' ),
						'phoneLabel'  => array( 'type' => 'text', 'label' => 'Label above the phone numbers' ),
						'socialLabel' => array( 'type' => 'text', 'label' => 'Label above the social icons' ),
					),
				),
				'form'      => array(
					'title'       => 'Message Form',
					'anchor'      => 'enquiry',
					'description' => 'The form visitors use to send a message. Messages arrive under Contact → Messages.',
					'fields'      => array(
						'label'            => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'            => array( 'type' => 'text', 'label' => 'Title' ),
						'description'      => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => '{email} is replaced by the main email address.' ),
						'nameLabel'        => array( 'type' => 'text', 'label' => 'Name box label' ),
						'emailLabel'       => array( 'type' => 'text', 'label' => 'Email box label' ),
						'phoneLabel'       => array( 'type' => 'text', 'label' => 'Phone box label' ),
						'topicLabel'       => array( 'type' => 'text', 'label' => 'Subject box label' ),
						'topicPlaceholder' => array( 'type' => 'text', 'label' => 'Subject box hint' ),
						'topicGeneral'     => array( 'type' => 'text', 'label' => 'First subject choice', 'help' => 'The institutions are listed after it automatically.' ),
						'topicOther'       => array( 'type' => 'text', 'label' => 'Last subject choice' ),
						'messageLabel'     => array( 'type' => 'text', 'label' => 'Message box label' ),
						'submitLabel'      => array( 'type' => 'text', 'label' => 'Send button text' ),
						'directPrompt'     => array( 'type' => 'text', 'label' => 'Text before the email link under the form' ),
						'successTitle'     => array( 'type' => 'text', 'label' => 'Thank-you title (after sending)' ),
						'successText'      => array( 'type' => 'textarea', 'label' => 'Thank-you text', 'rows' => 2 ),
					),
				),
				'locations' => array(
					'title'       => 'Locations',
					'anchor'      => 'locations',
					'description' => 'The heading above the campus maps. The campuses themselves are under Site Settings.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'hostsLabel'  => array( 'type' => 'text', 'label' => 'Label above "what is taught here"' ),
						'mapNote'     => array( 'type' => 'text', 'label' => 'Note under each map', 'help' => '{area} is replaced by the campus area.' ),
					),
				),
				'seo'       => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Contact page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Contact",
    "description": "Reach NAMI in Kathmandu — email, phone, school and college locations at Gokarneshwor-7 and New Baneshwor, and a message form for admissions and general enquiries."
  },
  "masthead": {
    "label": "Contact",
    "title": "Talk to NAMI.",
    "description": "Admissions, college visits, transcripts, or a question about a programme. Reach us directly, or send a message from this page.",
    "emailLabel": "Write to us",
    "phoneLabel": "Call us",
    "socialLabel": "Follow"
  },
  "form": {
    "label": "Tell us what you need.",
    "title": "Send a message",
    "description": "Fill this in and your message goes straight to our office, and we will get back to you. You can also write to {email}.",
    "nameLabel": "Full name",
    "emailLabel": "Email address",
    "phoneLabel": "Phone number",
    "topicLabel": "What is this about?",
    "messageLabel": "Your message",
    "topicPlaceholder": "Choose a subject",
    "topicGeneral": "General enquiry",
    "topicOther": "Something else",
    "submitLabel": "Send",
    "directPrompt": "Prefer to write it yourself?",
    "successTitle": "Thank you! Your message has been sent.",
    "successText": "We have received your inquiry and our team will get back to you shortly."
  },
  "locations": {
    "label": "Where to find us.",
    "title": "Locations",
    "description": "Each location carries a different part of the institute. The maps below are centred on the surrounding area rather than a door number.",
    "hostsLabel": "Taught here",
    "mapNote": "Map centred on the {area} area."
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);

/* ------------------------------------------------------------------
 * Messages
 * ------------------------------------------------------------------ */

add_action(
	'init',
	function () {
		register_post_type(
			NAMI_MSG_TYPE,
			array(
				'labels'          => array(
					'name'               => 'Messages',
					'singular_name'      => 'Message',
					'menu_name'          => 'Contact',
					'all_items'          => 'Messages',
					'edit_item'          => 'Message',
					'search_items'       => 'Search Messages',
					'not_found'          => 'No messages yet.',
					'not_found_in_trash' => 'No messages in the trash.',
				),
				'public'          => false,
				'show_ui'         => true,
				'show_in_menu'    => true,
				'show_in_rest'    => false,
				'menu_position'   => 3.02,
				'menu_icon'       => 'dashicons-email-alt',
				'supports'        => array( 'title' ),
				'capability_type' => 'page',
				'map_meta_cap'    => true,
				'capabilities'    => array( 'create_posts' => 'do_not_allow' ),
				'rewrite'         => false,
				'query_var'       => false,
			)
		);
	}
);

add_action(
	'rest_api_init',
	function () {
		register_rest_route(
			'nami/v1',
			'/messages',
			array(
				'methods'             => 'POST',
				'permission_callback' => function ( WP_REST_Request $request ) {
					if ( ! function_exists( 'nami_cms_settings' ) ) {
						return new WP_Error( 'nami_msg_core_missing', 'The NAMI CMS core snippet is not active.', array( 'status' => 503 ) );
					}
					$secret = (string) nami_cms_settings()['secret'];
					return '' !== $secret && hash_equals( $secret, (string) $request->get_header( 'x-nami-secret' ) );
				},
				'callback'            => 'nami_msg_receive',
			)
		);
	}
);

function nami_msg_receive( WP_REST_Request $request ) {
	$body    = $request->get_json_params();
	$body    = is_array( $body ) ? $body : array();
	$name    = mb_substr( sanitize_text_field( (string) ( $body['name'] ?? '' ) ), 0, 200 );
	$email   = sanitize_email( (string) ( $body['email'] ?? '' ) );
	$phone   = mb_substr( sanitize_text_field( (string) ( $body['phone'] ?? '' ) ), 0, 60 );
	$topic   = mb_substr( sanitize_text_field( (string) ( $body['topic'] ?? '' ) ), 0, 200 );
	$message = mb_substr( sanitize_textarea_field( (string) ( $body['message'] ?? '' ) ), 0, 5000 );
	if ( '' === $name || '' === $message ) {
		return new WP_Error( 'nami_msg_bad_body', 'Invalid message.', array( 'status' => 400 ) );
	}

	$post_id = wp_insert_post(
		array(
			'post_type'   => NAMI_MSG_TYPE,
			'post_status' => 'publish',
			'post_title'  => $name . ' — ' . $topic,
		),
		true
	);
	if ( is_wp_error( $post_id ) ) {
		return new WP_Error( 'nami_msg_store_failed', 'The message could not be stored.', array( 'status' => 500 ) );
	}
	foreach ( array( 'name' => $name, 'email' => $email, 'phone' => $phone, 'topic' => $topic, 'message' => $message, 'status' => 'new' ) as $key => $value ) {
		update_post_meta( $post_id, '_nami_' . $key, wp_slash( $value ) );
	}

	nami_msg_send_email( $post_id );
	return rest_ensure_response( array( 'ok' => true ) );
}

$GLOBALS['nami_msg_mail_error'] = '';
add_action(
	'wp_mail_failed',
	function ( $error ) {
		$GLOBALS['nami_msg_mail_error'] = $error instanceof WP_Error ? $error->get_error_message() : 'unknown error';
	}
);

function nami_msg_send_email( $post_id ) {
	$to = nami_msg_emails( nami_msg_settings()['to'] );
	if ( empty( $to ) ) {
		update_post_meta( $post_id, '_nami_mail_error', 'No recipient set under Contact → Email Settings.' );
		return;
	}
	$name    = (string) nami_msg_meta( $post_id, 'name' );
	$email   = (string) nami_msg_meta( $post_id, 'email' );
	$topic   = (string) nami_msg_meta( $post_id, 'topic' );
	$headers = array( 'Content-Type: text/html; charset=UTF-8' );
	if ( is_email( $email ) ) {
		$headers[] = 'Reply-To: ' . str_replace( array( "\r", "\n" ), '', $name ) . ' <' . $email . '>';
	}
	$body = sprintf(
		'<div style="font-family:Arial,sans-serif;font-size:14px;color:#212529"><p>A new message was sent from the website\'s Contact page.</p><p><strong>From:</strong> %s<br><strong>Email:</strong> %s<br><strong>Phone:</strong> %s<br><strong>Subject:</strong> %s</p><div style="white-space:pre-wrap;border-left:3px solid #bd1b21;padding:4px 12px;margin:12px 0">%s</div><p>Reply to this email to answer %s directly. <a href="%s">Open it in WordPress</a></p></div>',
		esc_html( $name ),
		esc_html( $email ),
		esc_html( (string) nami_msg_meta( $post_id, 'phone' ) ),
		esc_html( $topic ),
		esc_html( (string) nami_msg_meta( $post_id, 'message' ) ),
		esc_html( $name ),
		esc_url( admin_url( 'post.php?post=' . $post_id . '&action=edit' ) )
	);
	$GLOBALS['nami_msg_mail_error'] = '';
	if ( ! wp_mail( $to, 'Website message: ' . $topic . ' — ' . $name, $body, $headers ) ) {
		update_post_meta( $post_id, '_nami_mail_error', wp_slash( $GLOBALS['nami_msg_mail_error'] ?: 'not sent' ) );
	}
}

/* ------------------------------------------------------------------
 * List screen
 * ------------------------------------------------------------------ */

add_filter(
	'manage_' . NAMI_MSG_TYPE . '_posts_columns',
	function () {
		return array(
			'cb'       => '<input type="checkbox">',
			'title'    => 'From & subject',
			'contact'  => 'Contact',
			'excerpt'  => 'Message',
			'status'   => 'Status',
			'received' => 'Received',
		);
	}
);

add_action(
	'manage_' . NAMI_MSG_TYPE . '_posts_custom_column',
	function ( $column, $post_id ) {
		switch ( $column ) {
			case 'contact':
				$email = (string) nami_msg_meta( $post_id, 'email' );
				echo esc_html( (string) nami_msg_meta( $post_id, 'phone' ) );
				if ( '' !== $email ) {
					echo '<br><a href="mailto:' . esc_attr( $email ) . '">' . esc_html( $email ) . '</a>';
				}
				break;
			case 'excerpt':
				echo esc_html( wp_trim_words( (string) nami_msg_meta( $post_id, 'message' ), 18 ) );
				if ( '' !== (string) nami_msg_meta( $post_id, 'mail_error' ) ) {
					echo '<br><span style="color:#b32d2e">⚠ email alert not sent</span>';
				}
				break;
			case 'status':
				$status = (string) nami_msg_meta( $post_id, 'status' );
				printf( '<strong style="color:%s">%s</strong>', esc_attr( 'new' === $status ? '#bd1b21' : '#50575e' ), esc_html( nami_msg_statuses()[ $status ] ?? $status ) );
				break;
			case 'received':
				echo esc_html( get_the_date( 'j M Y, g:i a', $post_id ) );
				break;
		}
	},
	10,
	2
);

add_filter(
	'post_row_actions',
	function ( $actions, $post ) {
		if ( NAMI_MSG_TYPE !== $post->post_type ) {
			return $actions;
		}
		unset( $actions['inline hide-if-no-js'] );
		if ( isset( $actions['edit'] ) ) {
			$actions['edit'] = sprintf( '<a href="%s">Open</a>', esc_url( get_edit_post_link( $post->ID ) ) );
		}
		return $actions;
	},
	10,
	2
);

add_action(
	'restrict_manage_posts',
	function ( $post_type ) {
		if ( NAMI_MSG_TYPE !== $post_type ) {
			return;
		}
		$current = isset( $_GET['nami_status'] ) ? sanitize_key( wp_unslash( $_GET['nami_status'] ) ) : '';
		echo '<select name="nami_status"><option value="">All statuses</option>';
		foreach ( nami_msg_statuses() as $value => $label ) {
			printf( '<option value="%s"%s>%s</option>', esc_attr( $value ), selected( $current, $value, false ), esc_html( $label ) );
		}
		echo '</select>';
	}
);

add_action(
	'pre_get_posts',
	function ( $query ) {
		if ( ! is_admin() || ! $query->is_main_query() || NAMI_MSG_TYPE !== $query->get( 'post_type' ) ) {
			return;
		}
		$status = isset( $_GET['nami_status'] ) ? sanitize_key( wp_unslash( $_GET['nami_status'] ) ) : '';
		if ( isset( nami_msg_statuses()[ $status ] ) ) {
			$query->set( 'meta_query', array( array( 'key' => '_nami_status', 'value' => $status ) ) );
		}
	}
);

// Red bubble with the number of new messages next to the menu item.
add_action(
	'admin_menu',
	function () {
		global $menu;
		if ( ! current_user_can( NAMI_MSG_CAP ) || ! is_array( $menu ) ) {
			return;
		}
		$new = new WP_Query(
			array(
				'post_type'      => NAMI_MSG_TYPE,
				'post_status'    => 'publish',
				'meta_key'       => '_nami_status',
				'meta_value'     => 'new',
				'fields'         => 'ids',
				'posts_per_page' => 1,
			)
		);
		if ( $new->found_posts < 1 ) {
			return;
		}
		foreach ( $menu as $index => $item ) {
			if ( 'edit.php?post_type=' . NAMI_MSG_TYPE === ( $item[2] ?? '' ) ) {
				$menu[ $index ][0] .= sprintf( ' <span class="awaiting-mod"><span class="pending-count">%d</span></span>', (int) $new->found_posts );
			}
		}
	},
	99
);

/* ------------------------------------------------------------------
 * Message screen
 * ------------------------------------------------------------------ */

add_action(
	'add_meta_boxes_' . NAMI_MSG_TYPE,
	function () {
		remove_meta_box( 'slugdiv', NAMI_MSG_TYPE, 'normal' );
		add_meta_box(
			'nami_msg_body',
			'Message',
			function ( $post ) {
				$email = (string) nami_msg_meta( $post->ID, 'email' );
				printf(
					'<p><strong>From:</strong> %s<br><strong>Email:</strong> %s<br><strong>Phone:</strong> %s<br><strong>Subject:</strong> %s<br><strong>Received:</strong> %s</p>',
					esc_html( (string) nami_msg_meta( $post->ID, 'name' ) ),
					'' !== $email ? '<a href="mailto:' . esc_attr( $email ) . '">' . esc_html( $email ) . '</a>' : '—',
					esc_html( (string) nami_msg_meta( $post->ID, 'phone' ) ),
					esc_html( (string) nami_msg_meta( $post->ID, 'topic' ) ),
					esc_html( get_the_date( 'j M Y, g:i a', $post ) )
				);
				printf( '<div style="white-space:pre-wrap;font-size:14px;line-height:1.6;border-left:3px solid #bd1b21;padding:8px 14px;background:#f6f7f7">%s</div>', esc_html( (string) nami_msg_meta( $post->ID, 'message' ) ) );
				if ( is_email( $email ) ) {
					printf(
						'<p style="margin-top:14px"><a class="button button-primary" href="%s">Reply by email</a></p>',
						esc_url( 'mailto:' . $email . '?subject=' . rawurlencode( 'Re: ' . (string) nami_msg_meta( $post->ID, 'topic' ) ) )
					);
				}
			},
			NAMI_MSG_TYPE,
			'normal',
			'high'
		);
		add_meta_box(
			'nami_msg_manage',
			'Status & notes',
			function ( $post ) {
				wp_nonce_field( 'nami_msg_manage', 'nami_msg_manage_nonce' );
				$status = (string) nami_msg_meta( $post->ID, 'status' );
				echo '<p><label for="nami_msg_status"><strong>Status</strong></label><br><select id="nami_msg_status" name="nami_msg_status" style="width:100%">';
				foreach ( nami_msg_statuses() as $value => $label ) {
					printf( '<option value="%s"%s>%s</option>', esc_attr( $value ), selected( $status, $value, false ), esc_html( $label ) );
				}
				echo '</select></p>';
				printf( '<p><label for="nami_msg_notes"><strong>Internal notes</strong></label><textarea id="nami_msg_notes" name="nami_msg_notes" rows="6" style="width:100%%">%s</textarea></p>', esc_textarea( (string) nami_msg_meta( $post->ID, 'notes' ) ) );
				$error = (string) nami_msg_meta( $post->ID, 'mail_error' );
				if ( '' !== $error ) {
					printf( '<p style="color:#b32d2e"><strong>Email alert problem:</strong> %s</p>', esc_html( $error ) );
				}
				echo '<p class="description">Press "Update" to save the status and notes.</p>';
			},
			NAMI_MSG_TYPE,
			'side',
			'high'
		);
	}
);

add_action(
	'save_post_' . NAMI_MSG_TYPE,
	function ( $post_id ) {
		if ( ! isset( $_POST['nami_msg_manage_nonce'] ) || ! wp_verify_nonce( sanitize_key( wp_unslash( $_POST['nami_msg_manage_nonce'] ) ), 'nami_msg_manage' ) ) {
			return;
		}
		if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		$status = sanitize_key( wp_unslash( $_POST['nami_msg_status'] ?? '' ) );
		if ( isset( nami_msg_statuses()[ $status ] ) ) {
			update_post_meta( $post_id, '_nami_status', $status );
		}
		update_post_meta( $post_id, '_nami_notes', wp_slash( sanitize_textarea_field( wp_unslash( $_POST['nami_msg_notes'] ?? '' ) ) ) );
	}
);

/* ------------------------------------------------------------------
 * Contact → Email Settings
 * ------------------------------------------------------------------ */

add_action(
	'admin_menu',
	function () {
		add_submenu_page( 'edit.php?post_type=' . NAMI_MSG_TYPE, 'Message Email Settings', 'Email Settings', 'manage_options', 'nami-msg-settings', 'nami_msg_render_settings' );
	}
);

add_action(
	'admin_post_nami_msg_settings',
	function () {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( 'You are not allowed to change these settings.', 403 );
		}
		check_admin_referer( 'nami_msg_settings' );
		$to = implode( ', ', nami_msg_emails( wp_unslash( $_POST['to'] ?? '' ) ) );
		update_option( 'nami_msg_settings', array( 'to' => $to ), false );

		$status = 'saved';
		if ( ! empty( $_POST['send_test'] ) ) {
			$recipients                     = nami_msg_emails( $to );
			$GLOBALS['nami_msg_mail_error'] = '';
			$sent                           = ! empty( $recipients ) && wp_mail( $recipients, 'NAMI website: test email', 'This is a test from Contact → Email Settings. If you can read this, contact form alerts will arrive here.' );
			$status                         = $sent ? 'test_ok' : 'test_failed';
			if ( ! $sent ) {
				set_transient( 'nami_msg_test_error_' . get_current_user_id(), empty( $recipients ) ? 'no recipients set' : ( $GLOBALS['nami_msg_mail_error'] ?: 'wp_mail returned false' ), 120 );
			}
		}
		wp_safe_redirect( add_query_arg( array( 'post_type' => NAMI_MSG_TYPE, 'page' => 'nami-msg-settings', 'nami_status' => $status ), admin_url( 'edit.php' ) ) );
		exit;
	}
);

function nami_msg_render_settings() {
	$status = isset( $_GET['nami_status'] ) ? sanitize_key( $_GET['nami_status'] ) : '';
	echo '<div class="wrap"><h1>Message Email Settings</h1>';
	if ( 'saved' === $status ) {
		echo '<div class="notice notice-success is-dismissible"><p>Settings saved.</p></div>';
	} elseif ( 'test_ok' === $status ) {
		echo '<div class="notice notice-success is-dismissible"><p>Settings saved and a test email was sent. Check the inbox (and the spam folder).</p></div>';
	} elseif ( 'test_failed' === $status ) {
		$error = get_transient( 'nami_msg_test_error_' . get_current_user_id() );
		printf( '<div class="notice notice-error"><p>Settings saved, but the test email could not be sent (%s). Install and set up an SMTP plugin such as "WP Mail SMTP", then try again.</p></div>', esc_html( $error ? $error : 'unknown error' ) );
	}
	echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">';
	echo '<input type="hidden" name="action" value="nami_msg_settings">';
	wp_nonce_field( 'nami_msg_settings' );
	printf(
		'<table class="form-table" role="presentation"><tbody><tr><th scope="row"><label for="to">Email new messages to</label></th><td><input type="text" class="large-text" id="to" name="to" value="%s"><p class="description">Separate several addresses with commas. Replying to the alert email answers the sender directly.</p></td></tr></tbody></table>',
		esc_attr( nami_msg_settings()['to'] )
	);
	echo '<p class="submit"><button type="submit" class="button button-primary">Save settings</button> <button type="submit" name="send_test" value="1" class="button">Save and send test email</button></p>';
	echo '</form></div>';
}
