<?php
/**
 * NAMI CMS — Alumni
 *
 * Requires the "NAMI CMS — Core engine" snippet, version 1.2.0 or later
 * (collections). Adds an "Alumni" menu:
 *   - All Stories / Add New: each alumni spotlight on /alumni, with its full
 *     story, career milestones, interview and skills.
 *   - Stories sent by graduates through "Share Your Story" arrive here as
 *     DRAFTS (with their photo and contact details); edit and Publish them.
 *   - Page: …: the heading, wing tabs, numbers, employers and the banner.
 *
 * Field keys must match src/lib/cms/pages/alumni/types.ts in the Next.js project.
 * The JSON blocks at the bottom are generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) || defined( 'NAMI_ALUMNI' ) ) {
	return;
}
define( 'NAMI_ALUMNI', '1.0.0' );

function nami_alumni_wings() {
	return array(
		'undergraduate'    => 'Undergraduate',
		'graduate'         => 'Graduate (Masters)',
		'college'          => 'A-Levels',
		'higher-secondary' => 'Secondary School (+2)',
	);
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$image = function ( $label, $help = null ) {
			return array_filter( array( 'type' => 'image', 'label' => $label, 'help' => $help ) );
		};

		$pages['alumni'] = array(
			'title'          => 'Alumni page',
			'menu_parent'    => 'edit.php?post_type=nami_alumni',
			'submenu_prefix' => 'Page: ',
			'path'           => '/alumni',
			'sections'       => array(
				'masthead'  => array(
					'title'       => 'Heading',
					'description' => 'The top of the Alumni page.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title', 'placeholder' => '8,000+ Alumni' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text (jumps to the stories)' ),
						'image'       => $image( 'Photo' ),
					),
				),
				'stories'   => array(
					'title'       => 'Stories Heading',
					'anchor'      => 'alumni-stories',
					'description' => 'The heading above the alumni stories. Add the stories under Alumni → Add New.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3 ),
					),
				),
				'wings'     => array(
					'title'       => 'Wing Names',
					'description' => 'The filter buttons above the stories, and the wing name shown on each story card.',
					'fields'      => array(
						'allTab'            => array( 'type' => 'text', 'label' => '"Show everyone" button' ),
						'undergraduateTab'  => array( 'type' => 'text', 'label' => 'Undergraduate: button' ),
						'undergraduateCard' => array( 'type' => 'text', 'label' => 'Undergraduate: name on cards' ),
						'graduateTab'       => array( 'type' => 'text', 'label' => 'Graduate: button' ),
						'graduateCard'      => array( 'type' => 'text', 'label' => 'Graduate: name on cards' ),
						'collegeTab'        => array( 'type' => 'text', 'label' => 'A-Levels: button' ),
						'collegeCard'       => array( 'type' => 'text', 'label' => 'A-Levels: name on cards' ),
						'plusTwoTab'        => array( 'type' => 'text', 'label' => '+2: button' ),
						'plusTwoCard'       => array( 'type' => 'text', 'label' => '+2: name on cards' ),
					),
				),
				'metrics'   => array(
					'title'       => 'Numbers',
					'description' => 'The red band with the alumni numbers.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Numbers',
							'item_label'  => 'Number',
							'title_field' => 'label',
							'fields'      => array(
								'stat'   => array( 'type' => 'text', 'label' => 'Number', 'placeholder' => '8,000+' ),
								'label'  => array( 'type' => 'text', 'label' => 'What it counts' ),
								'detail' => array( 'type' => 'textarea', 'label' => 'Detail', 'rows' => 2 ),
							),
						),
					),
				),
				'employers' => array(
					'title'       => 'Employers',
					'anchor'      => 'employers',
					'description' => 'The two scrolling rows of organisations where alumni work.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						'items'       => array(
							'type'        => 'repeater',
							'label'       => 'Organisations',
							'item_label'  => 'Organisation',
							'title_field' => 'name',
							'fields'      => array(
								'name'   => array( 'type' => 'text', 'label' => 'Name' ),
								'sector' => array( 'type' => 'text', 'label' => 'Sector' ),
								'logo'   => $image( 'Logo (optional)', 'Without a logo, the name is shown.' ),
							),
						),
					),
				),
				'connect'   => array(
					'title'       => '"Share Your Story" Banner',
					'anchor'      => 'connect',
					'description' => 'The banner at the end of the page. Its button opens the form graduates use to send their story.',
					'fields'      => array(
						'label'       => array( 'type' => 'text', 'label' => 'Small label' ),
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
						'buttonLabel' => array( 'type' => 'text', 'label' => 'Button text' ),
						'email'       => array( 'type' => 'text', 'label' => 'Alumni office email', 'help' => 'New stories sent through the form are emailed here, and visitors see it if sending fails.' ),
					),
				),
				'seo'       => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Alumni page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'       => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Alumni Network & Career Spotlights | NAMI",
    "description": "Explore the achievements of over 8,000 NAMI graduates leading innovation across computing, environmental science, business, and research worldwide."
  },
  "masthead": {
    "label": "ALUMNI NETWORK",
    "title": "8,000+ Alumni",
    "description": "From Kathmandu to global institutions across 15+ countries, NAMI graduates are leading innovation in computing, sustainable development, business, and research.",
    "buttonLabel": "Explore Alumni Spotlights",
    "image": {
      "src": "/hero/alumni/alumni-hero.jpg",
      "alt": "NAMI Alumni network and graduation celebration.",
      "width": 1500,
      "height": 1000
    }
  },
  "stories": {
    "label": "ALUMNI VOICES",
    "title": "Where NAMI Graduates Go",
    "description": "From healthcare technology leaders in Kathmandu and network security engineers to venture-backed fintech entrepreneurs in New York, explore the career journeys of our graduates."
  },
  "wings": {
    "allTab": "All Alumni",
    "undergraduateTab": "Undergraduate Program",
    "undergraduateCard": "Undergraduate Programme",
    "graduateTab": "Graduate Program",
    "graduateCard": "Graduate Programme",
    "collegeTab": "A-Levels",
    "collegeCard": "A-Levels",
    "plusTwoTab": "Secondary School",
    "plusTwoCard": "Secondary School (+2)"
  },
  "metrics": {
    "label": "COMMUNITY & SCALE",
    "title": "A Legacy of Excellence Across Fourteen Years",
    "description": "Our alumni form a connected global community of researchers, technology leaders, entrepreneurs, and scholars.",
    "items": [
      {
        "stat": "8,000+",
        "label": "Total Alumni",
        "detail": "Graduates across all academic programmes since 2012."
      },
      {
        "stat": "5,000+",
        "label": "NEB 10+2 Alumni",
        "detail": "Science and Management graduates advancing into top institutions."
      },
      {
        "stat": "2,500+",
        "label": "UG & PG Degree Holders",
        "detail": "University of Northampton (UK) accredited Bachelor's and Master's degree holders."
      },
      {
        "stat": "500+",
        "label": "Cambridge A Level Scholars",
        "detail": "Studying in world-leading universities across the UK, US, and Australia."
      }
    ]
  },
  "employers": {
    "label": "CAREER NETWORK",
    "title": "Where Our Alumni Are",
    "description": "From global technology companies and leading commercial banks to international conservation bodies and research institutes, NAMI graduates are making an impact worldwide.",
    "items": [
      {
        "name": "Leapfrog Technology",
        "sector": "Software & AI Solutions",
        "logo": {
          "src": "/logos/careers/Leapfrog.png.webp",
          "alt": "Leapfrog Technology",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Khalti Digital Wallet",
        "sector": "Fintech & Payments",
        "logo": {
          "src": "/logos/careers/640px-Khalti_Digital_Wallet_Logo.png.jpg.webp",
          "alt": "Khalti Digital Wallet",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "eSewa",
        "sector": "Digital Payments",
        "logo": {
          "src": "/logos/careers/esewa.png.webp",
          "alt": "eSewa",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Fonepay",
        "sector": "Payment Network",
        "logo": {
          "src": "/logos/careers/fonepay-1.png.webp",
          "alt": "Fonepay",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "IME Pay",
        "sector": "Fintech & Digital Wallet",
        "logo": {
          "src": "/logos/careers/IME-Pay-Logo.png.webp",
          "alt": "IME Pay",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "CloudFactory",
        "sector": "Data & AI Solutions",
        "logo": {
          "src": "/logos/careers/cloud-factory.png.webp",
          "alt": "CloudFactory",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Pathao Nepal",
        "sector": "Consumer Tech & Mobility",
        "logo": {
          "src": "/logos/careers/Pathao-Logo_Horizontal_with_TagLine-e1706002895600.png.webp",
          "alt": "Pathao Nepal",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Genese Solutions",
        "sector": "Cloud & DevOps",
        "logo": {
          "src": "/logos/careers/genese.png.webp",
          "alt": "Genese Solutions",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Logpoint",
        "sector": "Cybersecurity & SIEM",
        "logo": {
          "src": "/logos/careers/logpoint.png.webp",
          "alt": "Logpoint",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Treeleaf Technologies",
        "sector": "AI & Embedded Systems",
        "logo": {
          "src": "/logos/careers/Treeleaf-final.jpeg.webp",
          "alt": "Treeleaf Technologies",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Yarsa Labs",
        "sector": "Software Engineering",
        "logo": {
          "src": "/logos/careers/yarsa-labs-full.png.webp",
          "alt": "Yarsa Labs",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Programiz",
        "sector": "EdTech & Learning Platforms",
        "logo": {
          "src": "/logos/careers/programiz.png.webp",
          "alt": "Programiz",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Ekbana Solutions",
        "sector": "Enterprise Software",
        "logo": {
          "src": "/logos/careers/ekbana.png.webp",
          "alt": "Ekbana Solutions",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Swift Technology",
        "sector": "Financial Technology",
        "logo": {
          "src": "/logos/careers/SWIFT-LOGO-WEBSITE-1.png.webp",
          "alt": "Swift Technology",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "DishHome",
        "sector": "Broadcasting & Telecom",
        "logo": {
          "src": "/logos/careers/DishHome_Logo.svg_.png.webp",
          "alt": "DishHome",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Karkhana",
        "sector": "Education & Innovation",
        "logo": {
          "src": "/logos/careers/karkhana.png.webp",
          "alt": "Karkhana",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Broadway Infosys",
        "sector": "Professional IT Training",
        "logo": {
          "src": "/logos/careers/broadway.png.webp",
          "alt": "Broadway Infosys",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Clock B Business Technology",
        "sector": "Business Strategy & Tech",
        "logo": {
          "src": "/logos/careers/clockb.png.webp",
          "alt": "Clock B Business Technology",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "InfoDevelopers",
        "sector": "Banking & Core Software",
        "logo": {
          "src": "/logos/careers/info-developers.png.webp",
          "alt": "InfoDevelopers",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Adex International",
        "sector": "Technology Consulting",
        "logo": {
          "src": "/logos/careers/Purple-Adex-Logo-1_1680601855.png.webp",
          "alt": "Adex International",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Dlytica",
        "sector": "Data Analytics & Cloud",
        "logo": {
          "src": "/logos/careers/Dlytica.png.webp",
          "alt": "Dlytica",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Intuji",
        "sector": "Digital Transformation",
        "logo": {
          "src": "/logos/careers/intuji.png.webp",
          "alt": "Intuji",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "LogicaBeans",
        "sector": "Enterprise Solutions",
        "logo": {
          "src": "/logos/careers/logicabeans-logo-software-company-2.png.webp",
          "alt": "LogicaBeans",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "LIS Nepal",
        "sector": "Analytics & Retail Solutions",
        "logo": {
          "src": "/logos/careers/lis-logo.png.webp",
          "alt": "LIS Nepal",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "TechKraft",
        "sector": "Product Development",
        "logo": {
          "src": "/logos/careers/techkraft.jpg.webp",
          "alt": "TechKraft",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Spiralogics",
        "sector": "Custom Healthcare Tech",
        "logo": {
          "src": "/logos/careers/spiralogics.png.webp",
          "alt": "Spiralogics",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Eminence Ways",
        "sector": "Information Security",
        "logo": {
          "src": "/logos/careers/eminence-ways.png.webp",
          "alt": "Eminence Ways",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Diyo AI",
        "sector": "Artificial Intelligence",
        "logo": {
          "src": "/logos/careers/Diyo-Ai.png.webp",
          "alt": "Diyo AI",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Code Himalaya",
        "sector": "Mobile & Web Apps",
        "logo": {
          "src": "/logos/careers/Code-Himalaya-e1709001522785.png.webp",
          "alt": "Code Himalaya",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Quickfox Consulting",
        "sector": "Management Consulting",
        "logo": {
          "src": "/logos/careers/37.-Quickfox-Consulting-e1715081130304.png.webp",
          "alt": "Quickfox Consulting",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Wise Yak",
        "sector": "HealthTech & AI",
        "logo": {
          "src": "/logos/careers/Wise-yak-logo.png.webp",
          "alt": "Wise Yak",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Waft Technology",
        "sector": "Cloud & Web Platforms",
        "logo": {
          "src": "/logos/careers/waft.png.webp",
          "alt": "Waft Technology",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Tuna Technology",
        "sector": "Software Solutions",
        "logo": {
          "src": "/logos/careers/tuna.png.webp",
          "alt": "Tuna Technology",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Slash Plus",
        "sector": "Product Design & Tech",
        "logo": {
          "src": "/logos/careers/Slashlogo-e1715081500251.png.webp",
          "alt": "Slash Plus",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Prixa",
        "sector": "Digital Health Solutions",
        "logo": {
          "src": "/logos/careers/prixa.png.webp",
          "alt": "Prixa",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Palm Mind",
        "sector": "Software & Technology",
        "logo": {
          "src": "/logos/careers/palm-mind.png.webp",
          "alt": "Palm Mind",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Dynamic Technosoft",
        "sector": "Enterprise ERP",
        "logo": {
          "src": "/logos/careers/dynamic_technosoft_logo.png.webp",
          "alt": "Dynamic Technosoft",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "ExtensoData",
        "sector": "Big Data & AI",
        "logo": {
          "src": "/logos/careers/extensodata_logo-1.jpg.webp",
          "alt": "ExtensoData",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "CodroidHub",
        "sector": "Mobile Development",
        "logo": {
          "src": "/logos/careers/codroidhub_logo.jpeg.webp",
          "alt": "CodroidHub",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "DataHub",
        "sector": "Cloud & Data Centers",
        "logo": {
          "src": "/logos/careers/datahub.png.webp",
          "alt": "DataHub",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Aqore",
        "sector": "Staffing Software",
        "logo": {
          "src": "/logos/careers/aqore-e1707312849329.jpg.webp",
          "alt": "Aqore",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Grit",
        "sector": "Creative & Digital Agency",
        "logo": {
          "src": "/logos/careers/grit1.png.webp",
          "alt": "Grit",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Sunya Ek",
        "sector": "Software Innovations",
        "logo": {
          "src": "/logos/careers/sunya-ek.png.webp",
          "alt": "Sunya Ek",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Inspiring Lab",
        "sector": "Research & Development",
        "logo": {
          "src": "/logos/careers/inspiring-lab.jpg.webp",
          "alt": "Inspiring Lab",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Cypher",
        "sector": "Security & Technology",
        "logo": {
          "src": "/logos/careers/cypher.jpg.webp",
          "alt": "Cypher",
          "width": 0,
          "height": 0
        }
      },
      {
        "name": "Agni Group (Mahindra)",
        "sector": "Automotive & Electric Mobility",
        "logo": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        }
      }
    ]
  },
  "connect": {
    "label": "STAY IN TOUCH",
    "title": "Are You a NAMI Graduate?",
    "description": "Reconnect with your batch, update your career milestones, submit an alumni spotlight, or join our student mentorship circle.",
    "buttonLabel": "Share Your Story",
    "email": "alumni@nami.edu.np"
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);

add_filter(
	'nami_cms_collections',
	function ( $collections ) {
		$collections['alumni-stories'] = array(
			'post_type'   => 'nami_alumni',
			'singular'    => 'Story',
			'plural'      => 'Stories',
			'menu_name'   => 'Alumni',
			'icon'        => 'dashicons-welcome-learn-more',
			'position'    => 3.9,
			'title_label' => 'Graduate\'s name',
			'description' => 'An alumni spotlight. The card shows the photo, role, wing and the first two highlights; "read the story" opens the rest.',
			'columns'     => array( 'wing', 'programme', 'company' ),
			'ready'       => false,
			'fields'      => array(
				'wing'           => array( 'type' => 'select', 'label' => 'Wing', 'options' => nami_alumni_wings() ),
				'photo'          => array( 'type' => 'image', 'label' => 'Photo', 'help' => 'A square portrait works best. A story without a photo is not shown.' ),
				'programme'      => array( 'type' => 'text', 'label' => 'Programme', 'placeholder' => 'BSc. (Hons) Computing' ),
				'graduationYear' => array( 'type' => 'text', 'label' => 'Graduation year / batch', 'placeholder' => 'Class of 2024' ),
				'currentRole'    => array( 'type' => 'text', 'label' => 'Current role' ),
				'company'        => array( 'type' => 'text', 'label' => 'Organisation' ),
				'location'       => array( 'type' => 'text', 'label' => 'Location', 'placeholder' => 'Kathmandu, Nepal' ),
				'highlights'     => array( 'type' => 'lines', 'label' => 'Highlights', 'rows' => 4, 'help' => 'One per line. The first two appear on the card.' ),
				'keyQuote'       => array( 'type' => 'textarea', 'label' => 'Highlighted quote', 'rows' => 3 ),
				'story'          => array( 'type' => 'paragraphs', 'label' => 'Full story', 'rows' => 14 ),
				'milestones'     => array(
					'type'        => 'repeater',
					'label'       => 'Career milestones',
					'item_label'  => 'Milestone',
					'title_field' => 'title',
					'fields'      => array(
						'year'         => array( 'type' => 'text', 'label' => 'When', 'placeholder' => '2024' ),
						'title'        => array( 'type' => 'text', 'label' => 'Title' ),
						'organization' => array( 'type' => 'text', 'label' => 'Organisation' ),
						'description'  => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
					),
				),
				'interview'      => array(
					'type'        => 'repeater',
					'label'       => 'Interview',
					'item_label'  => 'Question',
					'title_field' => 'question',
					'fields'      => array(
						'question' => array( 'type' => 'text', 'label' => 'Question' ),
						'answer'   => array( 'type' => 'textarea', 'label' => 'Answer', 'rows' => 4 ),
					),
				),
				'skills'         => array( 'type' => 'lines', 'label' => 'Skills gained', 'rows' => 5, 'help' => 'One per line.' ),
			),
			'import'      => json_decode(
				<<<'NAMI_IMPORT'
[
  {
    "title": "Reesav Rokka",
    "date": "2026-09-30",
    "fields": {
      "wing": "undergraduate",
      "photo": {
        "src": "/alumni/eesav rokka.png",
        "alt": "Reesav Rokka",
        "width": 0,
        "height": 0
      },
      "programme": "BSc. (Hons) Computing",
      "graduationYear": "Alumnus",
      "currentRole": "Senior IT Head",
      "company": "Gokarneshwor Municipal Hospital",
      "location": "Kathmandu, Nepal",
      "highlights": [
        "Senior IT Head managing hospital technology systems, digital workflows, and healthcare IT infrastructure.",
        "Introduced digital tools and systems that empower doctors, nurses, and staff to provide faster, better patient services."
      ],
      "keyQuote": "Presentations gave me confidence, group projects taught me collaboration, and practical assignments prepared me to solve real-world problems. What began with a desire to build an IT career became a role where technical skills improve hospital services and support the community.",
      "story": [
        "Reesav Rokka first learned about Naaya Aayam Multi-Disciplinary Institute (NAMI) through his friends and educational counselors. They spoke highly of its quality education, supportive environment, and practical approach to learning. At the time, Reesav wanted to build a career in Information Technology (IT), and he felt NAMI would give him the practical skills and foundation he needed rather than focusing only on textbook knowledge.",
        "During his time at NAMI, Reesav found the college welcoming and felt comfortable approaching teachers for guidance. His growth came not only from classroom lessons but also from projects, presentations, and group assignments. These experiences taught him problem-solving, communication, teamwork, leadership, and how to listen to others. He came to understand that technical knowledge alone was not enough for a successful career.",
        "After graduating, Reesav started working as an IT professional at Gokarneshwor Municipal Hospital. With experience and increasing responsibility, he became Senior IT Head. His role involves managing the hospital's technology systems, protecting information, managing software, supporting digital projects, and working with doctors, nurses, administrators, and other staff to solve practical problems through technology.",
        "He has also contributed to several improvements at the hospital, including introducing digital systems, strengthening its technology infrastructure, and developing tools that support healthcare professionals. What matters most to him is seeing how these technological improvements can help staff access information faster, work more accurately, and provide better services to patients.",
        "Looking back, Reesav sees a strong connection between his education and his career. Presentations gave me confidence, group projects taught me collaboration, and practical assignments prepared him to solve real-world problems. He believes students should use every classroom activity as preparation for their future, while also continuing to learn because technology constantly changes.",
        "His journey is ultimately about turning an interest in technology into meaningful work. What began with a desire to build an IT career became a role where his technical skills help improve hospital services and support the wider community."
      ],
      "milestones": [
        {
          "year": "Academic",
          "title": "BSc. (Hons) Computing & Practical Foundation",
          "organization": "NAMI / University of Northampton",
          "description": "Completed hands-on software development, systems engineering, collaborative projects, and communication-focused presentations."
        },
        {
          "year": "Career Start",
          "title": "IT Professional",
          "organization": "Gokarneshwor Municipal Hospital",
          "description": "Managed core hospital technology systems, ensured clinical data integrity, and supported digital tooling for healthcare workers."
        },
        {
          "year": "Present",
          "title": "Senior IT Head",
          "organization": "Gokarneshwor Municipal Hospital",
          "description": "Directs institutional technology infrastructure, digital systems, cybersecurity, and practical software tools supporting medical staff and patients."
        }
      ],
      "interview": [
        {
          "question": "How did your education at NAMI connect with your current healthcare leadership role?",
          "answer": "Presentations gave me confidence, group projects taught me collaboration, and practical assignments prepared me to solve real-world problems. Working with doctors, nurses, and administrators requires strong communication alongside technical expertise."
        },
        {
          "question": "What is most rewarding about your current work?",
          "answer": "Seeing how technological improvements help staff access information faster, work more accurately, and provide better services to patients. It is about turning an interest in technology into meaningful work that supports the wider community."
        },
        {
          "question": "What is your advice for current students?",
          "answer": "Use every classroom activity as preparation for your future, while also continuing to learn because technology constantly changes."
        }
      ],
      "skills": [
        "Healthcare IT Systems",
        "Infrastructure & Security",
        "Digital Transformation",
        "Team Leadership & Collaboration",
        "Problem-Solving & Communication"
      ]
    }
  },
  {
    "title": "Daniel Sapkota",
    "date": "2026-09-29",
    "fields": {
      "wing": "undergraduate",
      "photo": {
        "src": "/alumni/daniel sapkota.png",
        "alt": "Daniel Sapkota",
        "width": 0,
        "height": 0
      },
      "programme": "BSc. (Hons) Computing",
      "graduationYear": "Alumnus",
      "currentRole": "Co-founder",
      "company": "Lightcone",
      "location": "New York, USA",
      "highlights": [
        "Co-founder of Lightcone, a New York fintech startup that has raised USD 4 million in venture capital from US and European investors.",
        "Awarded a full scholarship and stipend to pursue a PhD in Computer Science at the University of Nevada, Las Vegas (UNLV)."
      ],
      "keyQuote": "Build something quickly, get users, learn from the process, iterate, innovate, and keep taking action.",
      "story": [
        "Daniel Sapkota is a Co-founder of Lightcone, a fintech startup based in New York, USA. His journey began at NAMI, where he developed an interest in technology and entrepreneurship.",
        "After graduating from NAMI, Daniel received a full scholarship and stipend to pursue a PhD in Computer Science at the University of Nevada, Las Vegas (UNLV). He later moved into the technology industry and co-founded Lightcone, a fintech startup that has raised USD 4 million in venture capital from investors in the United States and Europe.",
        "Daniel credits NAMI’s hands-on, industry-focused learning for helping him develop the confidence and initiative that have been important throughout his career. He particularly remembers how the curriculum encouraged him to act quickly and build things rather than only study theory. He also highlights the value of the US technology industry’s emphasis on agency.",
        "His advice to current students is straightforward: build something quickly, get users, learn from the process, iterate, innovate, and keep taking action.",
        "Daniel also remembers his teachers at NAMI fondly, especially Deepak Karna, whom he credits as his mentor. He describes himself as a student who was difficult to keep under control, but says he loved his teachers and values the mentorship he received.",
        "Overall, Daniel’s story shows a path from NAMI → PhD in Computer Science at UNLV → technology industry → fintech entrepreneurship in New York, eventually becoming a co-founder of a startup that attracted significant international venture investment."
      ],
      "milestones": [
        {
          "year": "Academic",
          "title": "BSc. Computing & Entrepreneurship Foundation",
          "organization": "NAMI / University of Northampton",
          "description": "Cultivated engineering discipline and startup initiative under the close mentorship of Deepak Karna and faculty."
        },
        {
          "year": "PhD Fellowship",
          "title": "PhD in Computer Science (Full Scholarship & Stipend)",
          "organization": "University of Nevada, Las Vegas (UNLV)",
          "description": "Awarded full scholarship and stipend for advanced computing doctoral studies and academic research in the United States."
        },
        {
          "year": "US Tech",
          "title": "Technology Industry & High-Agency Execution",
          "organization": "US Tech Ecosystem",
          "description": "Transitioned into the US tech industry, embracing rapid prototyping, user feedback, and high personal agency."
        },
        {
          "year": "Present",
          "title": "Co-founder",
          "organization": "Lightcone (New York, USA)",
          "description": "Co-founded fintech startup Lightcone, raising USD 4 Million in venture capital from prominent investors across the US and Europe."
        }
      ],
      "interview": [
        {
          "question": "How did NAMI's learning approach influence your entrepreneurial path?",
          "answer": "NAMI's hands-on, industry-focused learning helped me develop confidence and initiative. The curriculum encouraged me to act quickly and build things rather than only study theory, matching the emphasis on agency in the US tech ecosystem."
        },
        {
          "question": "What mentorship stood out during your time at NAMI?",
          "answer": "I remember my teachers at NAMI fondly, especially Deepak Karna, whom I credit as my mentor. I was a student who was difficult to keep under control, but I loved my teachers and value the mentorship and encouragement I received."
        },
        {
          "question": "What is your key advice to current students?",
          "answer": "Build something quickly, get users, learn from the process, iterate, innovate, and keep taking action."
        }
      ],
      "skills": [
        "Fintech Innovation",
        "Venture Capital & Fundraising",
        "Computer Science Research",
        "Rapid Product Iteration",
        "High-Agency Leadership"
      ]
    }
  },
  {
    "title": "Abhishek Gautam",
    "date": "2026-09-28",
    "fields": {
      "wing": "undergraduate",
      "photo": {
        "src": "/alumni/abhishek sharma.png",
        "alt": "Abhishek Gautam",
        "width": 0,
        "height": 0
      },
      "programme": "BSc. (Hons) Computing",
      "graduationYear": "Alumnus",
      "currentRole": "Network Security Engineer & Lecturer",
      "company": "DNS & KFA College",
      "location": "Kathmandu, Nepal",
      "highlights": [
        "Network Security Engineer at DNS designing, implementing, and managing network security solutions to keep client infrastructure secure and reliable.",
        "Part-time Lecturer at KFA College teaching Computer Networks, Data Communication, and Networking to BCS-IT students."
      ],
      "keyQuote": "Stay curious about emerging trends, seek guidance from seniors and industry professionals when choosing your specialization and keep an eye on global developments in IT.",
      "story": [
        "Abhishek first heard about NAMI while preparing for the IOE entrance exam in Kathmandu — a teacher at his training institute recommended the college, and after comparing curricula with other universities, he was drawn to NAMI's practical, industry-oriented approach.",
        "As a student, he found NAMI supportive and engaging, with hands-on learning at the core of the experience. He credits the approachable faculty, collaborative culture, and project-based coursework for building both his technical skills and his confidence for the professional world.",
        "Today, he works as a Network Security Engineer at DNS, where he designs, implements, and manages network security solutions to keep client infrastructure secure and reliable. Alongside that, he's a part-time Lecturer at KFA College, teaching Computer Networks, Data Communication, and Networking to BCS-IT students — a dual role he says lets him apply industry expertise while mentoring the next generation of IT professionals.",
        "He finds the most rewarding part of his work to be solving complex technical challenges and knowing his efforts help protect critical systems while enabling businesses to operate securely. He encourages current NAMI students to stay curious about emerging trends and keep building practical skills.",
        "His fondest NAMI memories are the last-minute assignment sessions with friends, the shared excitement of meeting deadlines, and the lasting friendships from his college years. His journey stands as a testament to how practical education, perseverance, and continuous growth can build a successful, impactful career."
      ],
      "milestones": [
        {
          "year": "Academic",
          "title": "BSc. Computing & Practical Foundation",
          "organization": "NAMI / University of Northampton",
          "description": "Built technical proficiency through hands-on lab learning, collaborative assignments, and industry-oriented coursework."
        },
        {
          "year": "Industry",
          "title": "Network Security Engineer",
          "organization": "DNS",
          "description": "Designs, implements, and manages network security solutions to protect critical systems and maintain reliable client infrastructure."
        },
        {
          "year": "Academia",
          "title": "Part-time Lecturer (BCS-IT)",
          "organization": "KFA College",
          "description": "Teaches Computer Networks, Data Communication, and Networking to BCS-IT students, mentoring emerging technology professionals."
        }
      ],
      "interview": [
        {
          "question": "How did you first discover NAMI and what drew you to it?",
          "answer": "While preparing for the IOE entrance exam in Kathmandu, a teacher at my training institute recommended NAMI. After comparing curricula with other universities, I was drawn to NAMI's practical, industry-oriented approach."
        },
        {
          "question": "What is most rewarding about your dual role in cybersecurity and academia?",
          "answer": "Solving complex technical challenges and knowing my efforts help protect critical systems while enabling businesses to operate securely. Alongside that, teaching lets me apply real-world industry expertise while mentoring the next generation of IT professionals."
        },
        {
          "question": "What is your advice for current NAMI students?",
          "answer": "Stay curious about emerging trends, seek guidance from seniors and industry professionals when choosing your specialization and keep an eye on global developments in IT."
        }
      ],
      "skills": [
        "Network Security & Defense",
        "Data Communication & Routing",
        "Infrastructure Resilience",
        "Higher Education Mentorship",
        "Complex Problem Solving"
      ]
    }
  },
  {
    "title": "Denish Tuladhar",
    "date": "2026-09-27",
    "fields": {
      "wing": "undergraduate",
      "photo": {
        "src": "/alumni/Denish.png",
        "alt": "Denish Tuladhar",
        "width": 0,
        "height": 0
      },
      "programme": "Bachelor of Business Administration (BBA)",
      "graduationYear": "Alumnus",
      "currentRole": "Marketing Executive",
      "company": "Agni Group (Mahindra BEV & SUV)",
      "location": "Kathmandu, Nepal",
      "highlights": [
        "Marketing Executive at Agni Group leading marketing strategies, product launches, and digital campaigns for Mahindra's BEV and SUV portfolio in Nepal.",
        "Awarded the Best Emerging Performer Award within just three months of joining Agni Group.",
        "Previously spearheaded healthcare marketing, branding, strategic partnerships, and event management at KIST Teaching Hospital."
      ],
      "keyQuote": "Receiving the Best Emerging Performer Award within just three months of joining Agni Group has been one of my proudest achievements. Looking back, NAMI was more than just a place where I earned my degree—it was where I built the foundation for the career I have today.",
      "story": [
        "Denish Tuladhar first heard about NAMI through a friend who spoke highly of its academic standards and its unique three-year Bachelor's degree programme. Motivated by NAMI's reputation for providing quality education within a shorter duration, it allowed him to balance both his studies and his professional ambitions in an environment that offered the flexibility and rigor he was looking for.",
        "His experience at NAMI was both enriching and transformative. The faculty members were approachable, knowledgeable, and always encouraged active participation. The learning environment emphasized teamwork, presentations, case studies, and real-world problem solving, which helped him build confidence, communication skills, and leadership abilities.",
        "The most valuable aspect of his education at NAMI was its emphasis on research-based assignments, practical learning, and professional development. The curriculum encouraged analytical thinking, project-based learning, and collaboration, preparing him to adapt quickly to workplace challenges throughout his career.",
        "After completing his studies, Denish began his career in healthcare marketing at KIST Teaching Hospital, where he worked on branding, digital marketing campaigns, strategic partnerships, and event management, giving him valuable exposure to integrated marketing and communication strategies.",
        "Currently, Denish is working at Agni Group as a Marketing Executive, specializing in Mahindra's BEV and SUV segment. In this role, he develops and executes marketing strategies including product launch planning, digital campaigns, event management, content creation, influencer collaborations, dealership marketing, and brand-building initiatives across Nepal.",
        "One of his proudest achievements has been receiving the Best Emerging Performer Award within just three months of joining Agni Group. He finds it immensely rewarding to contribute to Nepal's transition toward electric mobility and sustainable transportation."
      ],
      "milestones": [
        {
          "year": "Academic",
          "title": "Bachelor of Business Administration & Foundation",
          "organization": "NAMI / University of Northampton",
          "description": "Completed research-based coursework, analytical case studies, team presentations, and business management projects."
        },
        {
          "year": "Healthcare",
          "title": "Healthcare Marketing Specialist",
          "organization": "KIST Teaching Hospital",
          "description": "Managed branding, digital campaigns, strategic partnerships, and hospital-wide public relations and event execution."
        },
        {
          "year": "Automotive",
          "title": "Marketing Executive (Mahindra BEV & SUV)",
          "organization": "Agni Group",
          "description": "Leads product launches, digital campaigns, dealership marketing, content creation, and electric mobility brand strategies across Nepal."
        },
        {
          "year": "Honors",
          "title": "Best Emerging Performer Award",
          "organization": "Agni Group",
          "description": "Awarded top organizational honors within three months of joining for high-impact marketing execution and campaign leadership."
        }
      ],
      "interview": [
        {
          "question": "How did you first hear about NAMI, and what motivated you to choose NAMI for your studies?",
          "answer": "I first heard about NAMI through a friend who spoke highly of its academic standards and its unique three-year Bachelor's degree programme. What motivated me to choose NAMI was its reputation for providing quality education within a shorter duration. It allowed me to balance both my studies and my professional life, and NAMI offered the flexible environment I was looking for."
        },
        {
          "question": "How would you describe the overall learning environment and experience at NAMI during your time as a student?",
          "answer": "My experience at NAMI was both enriching and transformative. The faculty members were approachable, knowledgeable and always encouraged active participation. The learning environment emphasized teamwork, presentations, case studies and real-world problem solving, which helped me build confidence, communication skills and leadership abilities. Beyond academics, NAMI encouraged students to think critically and develop practical skills that prepared us for the professional world."
        },
        {
          "question": "Which aspects of your education at NAMI have been most valuable in shaping your academic and professional journey?",
          "answer": "The most valuable aspect of my education at NAMI was its emphasis on research-based assignments, practical learning and professional development. The curriculum encouraged analytical thinking, project-based learning and collaboration, preparing me to adapt quickly to workplace challenges. These experiences have helped me become more confident in problem-solving, strategic thinking and decision-making throughout my career."
        },
        {
          "question": "Could you share some key milestones or achievements in your career since graduating from NAMI?",
          "answer": "After completing my studies, I began my career in healthcare marketing at KIST Teaching Hospital, where I worked on branding, digital marketing campaigns, strategic partnerships and event management. This role gave me valuable exposure to integrated marketing and communication strategies. Currently, I am working at Agni Group as a Marketing Executive, specializing in Mahindra's BEV and SUV segment. One of my proudest achievements has been receiving the Best Emerging Performer Award within just three months of joining Agni Group."
        },
        {
          "question": "What does your current role involve, and what do you find most rewarding about your work?",
          "answer": "In my current role at Agni Group, I am responsible for developing and executing marketing strategies for Mahindra's BEV and SUV portfolio. My work includes product launch planning, digital campaigns, event management, content creation, influencer collaborations, dealership marketing and brand-building initiatives across Nepal. The most rewarding part of my work is contributing to Nepal's transition toward electric mobility. It is exciting to work with innovative vehicles and create marketing campaigns that influence customer perceptions while helping shape the future of sustainable transportation."
        },
        {
          "question": "What advice would you like to offer current NAMI students who aspire to build successful careers in their chosen fields?",
          "answer": "Never limit your learning to the classroom. Take every opportunity to participate in internships, workshops, competitions and networking events. Build strong communication skills, stay curious and continuously learn new technologies and industry trends. Don't wait for the perfect opportunity—gain real experience, sharpen your skills and then pursue the path you're truly passionate about. Success comes from being adaptable, disciplined, humble and willing to step outside your comfort zone."
        },
        {
          "question": "Is there a particular memory or experience from your time at NAMI that remains especially meaningful to you?",
          "answer": "One of my most memorable experiences at NAMI was spending late nights researching journals and preparing assignments with my classmates. Those moments taught me discipline, time management, teamwork and the ability to perform under pressure. The friendships I built, the guidance I received from the faculty and the confidence I developed during those years continue to influence both my personal and professional life."
        }
      ],
      "skills": [
        "EV & Automotive Marketing Strategy",
        "Product Launch & Campaign Execution",
        "Digital Marketing & Influencer Relations",
        "Brand Strategy & Strategic Partnerships",
        "Dealership & Integrated Event Marketing",
        "Analytical & Research-Based Decision Making"
      ]
    }
  },
  {
    "title": "Avni Adhikari",
    "date": "2026-09-26",
    "fields": {
      "wing": "higher-secondary",
      "photo": {
        "src": "/testimonials/plus-two/Avni Adhikari.png",
        "alt": "Avni Adhikari",
        "width": 0,
        "height": 0
      },
      "programme": "Secondary School (Science Stream)",
      "graduationYear": "Class of 2026",
      "currentRole": "President, Arts & Literature Club",
      "company": "NAMI International School",
      "location": "Kathmandu, Nepal",
      "highlights": [
        "Secondary School Science stream alumna (Class of 2026) with distinction across physics, chemistry, and biology labs.",
        "Former President of the Arts and Literature Club, leading student initiatives, literary activities, and cultural events.",
        "Demonstrated remarkable resilience, student leadership, and community spirit throughout her academic journey."
      ],
      "keyQuote": "NAMI will always be more than just the place where I completed my Plus Two. It is a chapter of my life filled with friendships, laughter, challenges, lessons, and so many memories that I will carry with me. And for all of it, I will always be grateful.",
      "story": [
        "When I first walked through the doors of NAMI International School, I never imagined how meaningful the next two years would become. Like any new beginning, my first day came with a mix of excitement and nervousness. I was stepping into a new environment, meeting new people, and starting a new chapter of my life. I had no idea then that this place would give me so many memories to look back on.",
        "Looking back, my +2 experience was about much more than just academics. It was about the friendships I made, the people I met, the challenges I faced, and all the small moments that made everyday college life special.",
        "Some of my favorite memories were the days when we got to take a break from our usual routine. Our trip to Sukute Beach is definitely one of the memories I will always remember. Spending the day with my friends, laughing, having fun, and just enjoying being together made it such a special day.",
        "Our Holi celebrations were another unforgettable part of my NAMI experience. The colors, music, laughter, and all the chaos made those moments so much fun. These are the kinds of memories that I know I will miss the most.",
        "Another important part of my NAMI experience was being the President of the Arts and Literature Club. Taking on that responsibility gave me the chance to meet and work with people I probably wouldn't have gotten to know otherwise. From planning activities to being involved in different events, it pushed me to be more confident and responsible. Looking back, I'm really glad I got the opportunity to be a part of the club in that way.",
        "And then there were our lab classes. Physics, Chemistry, and Biology labs were a whole different experience from sitting in a classroom and taking notes. From trying to get experiments right, working with our friends, making mistakes, and sometimes having absolutely no idea what was going on, the labs gave us some of the funniest and most memorable moments.",
        "Of course, these two years were not always easy. We went through something much bigger than academics when the GEN-Z protests affected our NAMI community, and our college was completely burned down. Seeing a place that held so many memories for us being destroyed was heartbreaking. But what I remember even more is how quickly everyone came together and moved forward. NAMI continued despite everything, and it showed me that a college is not just a building. It is the people, the memories, and the spirit that make it special.",
        "I also want to take a moment to thank all our teachers. Thank you for teaching me, guiding me, and being there for me throughout these two years. Beyond the lessons and exams, you have taught me things that I will carry with me throughout my life.",
        "When I look back at my time at NAMI now, I realize how much I changed and grew during these two years. I learned to face challenges, value the people around me, step out of my comfort zone, and appreciate the little moments that make life special.",
        "NAMI will always be more than just the place where I completed my Plus Two. It is a chapter of my life filled with friendships, laughter, challenges, lessons, and so many memories that I will carry with me. And for all of it, I will always be grateful."
      ],
      "milestones": [
        {
          "year": "2024–2026",
          "title": "Secondary School (+2 Science Stream)",
          "organization": "NAMI International School",
          "description": "Completed comprehensive physics, chemistry, and biology coursework alongside practical laboratory inquiry."
        },
        {
          "year": "Leadership",
          "title": "President, Arts & Literature Club",
          "organization": "NAMI International School",
          "description": "Spearheaded creative initiatives, student literary publications, multidisciplinary workshops, and campus festivals."
        },
        {
          "year": "Community",
          "title": "Student Solidarity & Campus Resilience",
          "organization": "NAMI Community",
          "description": "Fostered peer support, active participation, and community resilience during campus rebuilding."
        },
        {
          "year": "2026",
          "title": "Science Stream Alumna (Class of 2026)",
          "organization": "NAMI Alumni Network",
          "description": "Graduated with honors, advancing into higher education with strong foundational competencies in science and leadership."
        }
      ],
      "interview": [
        {
          "question": "How did your journey at NAMI begin?",
          "answer": "When I first walked through the doors of NAMI International School, I never imagined how meaningful the next two years would become. My first day came with a mix of excitement and nervousness. I was stepping into a new environment, meeting new people, and starting a new chapter of my life that gave me so many memories to look back on."
        },
        {
          "question": "What made your +2 experience special beyond regular academics?",
          "answer": "My +2 experience was about much more than just academics. It was about the friendships I made, the people I met, the challenges I faced, and all the small moments that made everyday college life special—from our memorable trip to Sukute Beach to our unforgettable Holi celebrations filled with colors, music, and laughter."
        },
        {
          "question": "What was your experience leading the Arts and Literature Club?",
          "answer": "Being the President of the Arts and Literature Club gave me the chance to meet and work with people I probably wouldn't have gotten to know otherwise. From planning activities to being involved in different events, it pushed me to be more confident and responsible. I'm really glad I got the opportunity to be a part of the club in that way."
        },
        {
          "question": "How were your laboratory classes in the Science stream?",
          "answer": "Physics, Chemistry, and Biology labs were a whole different experience from sitting in a classroom and taking notes. From trying to get experiments right, working with our friends, making mistakes, and sometimes having absolutely no idea what was going on, the labs gave us some of the funniest and most memorable moments."
        },
        {
          "question": "How did the community respond to unexpected challenges?",
          "answer": "When unexpected events affected our community, seeing a place with so many memories damaged was heartbreaking. But what I remember even more is how quickly everyone came together and moved forward. It showed me that a college is not just a building. It is the people, the memories, and the spirit that make it special."
        },
        {
          "question": "What message would you like to share with your teachers and mentors?",
          "answer": "Thank you for teaching me, guiding me, and being there for me throughout these two years. Beyond the lessons and exams, you have taught me things that I will carry with me throughout my life."
        },
        {
          "question": "How do you summarize your overall transformation at NAMI?",
          "answer": "I learned to face challenges, value the people around me, step out of my comfort zone, and appreciate the little moments that make life special. NAMI will always be more than just where I completed Plus Two—it is a chapter filled with friendships, laughter, lessons, and memories for which I will always be grateful."
        }
      ],
      "skills": [
        "Scientific Inquiry & Laboratory Research",
        "Student Leadership & Club Governance",
        "Arts & Literature Event Management",
        "Team Collaboration & Problem Solving",
        "Crisis Resilience & Community Solidarity",
        "Public Speaking & Expressive Communication"
      ]
    }
  },
  {
    "title": "Yunisha Basnet",
    "date": "2026-09-25",
    "fields": {
      "wing": "higher-secondary",
      "photo": {
        "src": "/testimonials/plus-two/Yunisha Shrestha.jpeg",
        "alt": "Yunisha Basnet",
        "width": 0,
        "height": 0
      },
      "programme": "Secondary School (Management Stream)",
      "graduationYear": "Class of 2026",
      "currentRole": "Management Graduate",
      "company": "NAMI International School",
      "location": "Kathmandu, Nepal",
      "highlights": [
        "Secondary School Management stream alumna (Class of 2026) recognized for active participation and academic dedication.",
        "Experienced comprehensive guidance and mentorship from friendly, understanding faculty members throughout her studies.",
        "Thrived in NAMI's peaceful, green campus environment, building lifelong friendships and collaborative learning habits."
      ],
      "keyQuote": "Overall, my time at NAMI was a beautiful combination of learning, growth, friendship, and unforgettable memories. I am truly grateful for the experiences, the teachers who guided me, and the wonderful people I met during my journey.",
      "story": [
        "My journey at NAMI has been a truly wonderful and memorable experience. From the very first day I joined NAMI until the end of my session, I genuinely enjoyed every moment. The faculty members were very supportive, friendly, and understanding. My teachers helped me a lot with my studies and were always there whenever I needed guidance or had difficulties understanding something. Their constant support and encouragement made my learning experience much easier and more enjoyable.",
        "Apart from academics, one of the best parts of my journey was the friends I made along the way. I met some really lovely people who made my time at NAMI even more special. We shared so many fun moments, helped each other, and created memories that I will always cherish.",
        "I was also really impressed by the facilities at NAMI. The campus environment was peaceful, beautiful, and surrounded by greenery, which made it a refreshing place to study and spend time with friends. Overall, my time at NAMI was a beautiful combination of learning, growth, friendship, and unforgettable memories. I am truly grateful for the experiences, the teachers who guided me, and the wonderful people I met during my journey."
      ],
      "milestones": [
        {
          "year": "2024–2026",
          "title": "Secondary School (+2 Management Stream)",
          "organization": "NAMI International School",
          "description": "Completed core business, management, accounting, and economics coursework with active classroom participation."
        },
        {
          "year": "Academic",
          "title": "Collaborative Learning & Mentorship",
          "organization": "NAMI Faculty & Student Body",
          "description": "Engaged in continuous academic mentorship, peer study circles, and experiential group assignments."
        },
        {
          "year": "2026",
          "title": "Management Stream Alumna (Class of 2026)",
          "organization": "NAMI Alumni Network",
          "description": "Graduated successfully, equipped with strong foundational skills in commerce, management, and leadership for undergraduate studies."
        }
      ],
      "interview": [
        {
          "question": "How would you describe your overall experience at NAMI?",
          "answer": "My journey at NAMI has been a truly wonderful and memorable experience. From the very first day I joined NAMI until the end of my session, I genuinely enjoyed every moment. The faculty members were very supportive, friendly, and understanding, always helping me whenever I needed guidance."
        },
        {
          "question": "How did the faculty and teaching approach support your learning?",
          "answer": "My teachers helped me a lot with my studies and were always there whenever I had difficulties understanding something. Their constant support and encouragement made my learning experience much easier and more enjoyable."
        },
        {
          "question": "What role did friendships and the campus environment play during your time at NAMI?",
          "answer": "I met really lovely people who made my time at NAMI even more special—we shared so many fun moments, helped each other, and created memories that I will always cherish. The campus environment was peaceful, beautiful, and surrounded by greenery, which made it a refreshing place to study."
        },
        {
          "question": "What is your key takeaway looking back at your +2 years?",
          "answer": "My time at NAMI was a beautiful combination of learning, growth, friendship, and unforgettable memories. I am truly grateful for the experiences, the teachers who guided me, and the wonderful people I met during my journey."
        }
      ],
      "skills": [
        "Business & Management Foundations",
        "Financial Accounting & Analysis",
        "Collaborative Peer Teamwork",
        "Effective Communication & Presentation",
        "Critical Thinking & Problem Solving",
        "Self-Management & Leadership"
      ]
    }
  }
]
NAMI_IMPORT
				,
				true
			),
		);
		return $collections;
	}
);

/* ------------------------------------------------------------------
 * Stories sent by graduates ("Share Your Story" on /alumni)
 * ------------------------------------------------------------------ */

add_action(
	'rest_api_init',
	function () {
		register_rest_route(
			'nami/v1',
			'/alumni-submissions',
			array(
				'methods'             => 'POST',
				'permission_callback' => function ( WP_REST_Request $request ) {
					if ( ! function_exists( 'nami_cms_settings' ) ) {
						return new WP_Error( 'nami_alumni_core_missing', 'The NAMI CMS core snippet is not active.', array( 'status' => 503 ) );
					}
					$secret = (string) nami_cms_settings()['secret'];
					return '' !== $secret && hash_equals( $secret, (string) $request->get_header( 'x-nami-secret' ) );
				},
				'callback'            => 'nami_alumni_receive',
			)
		);
	}
);

function nami_alumni_text( $body, $key, $max = 300 ) {
	return mb_substr( sanitize_text_field( (string) ( $body[ $key ] ?? '' ) ), 0, $max );
}

/** Saves the submitted photo in the Media Library; returns the image field value. */
function nami_alumni_save_photo( $photo, $name ) {
	$empty = array( 'src' => '', 'alt' => '', 'width' => 0, 'height' => 0 );
	if ( ! is_array( $photo ) ) {
		return $empty;
	}
	$bytes = base64_decode( (string) ( $photo['data'] ?? '' ), true );
	$info  = false !== $bytes ? getimagesizefromstring( $bytes ) : false;
	$types = array( 'image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp' );
	if ( false === $info || ! isset( $types[ $info['mime'] ] ) || strlen( $bytes ) > 4194304 ) {
		return $empty;
	}

	$filename = sanitize_file_name( 'alumni-' . sanitize_title( $name ) . '-' . wp_generate_password( 6, false ) . '.' . $types[ $info['mime'] ] );
	$upload   = wp_upload_bits( $filename, null, $bytes );
	if ( ! empty( $upload['error'] ) ) {
		return $empty;
	}
	$attachment = wp_insert_attachment(
		array(
			'post_mime_type' => $info['mime'],
			'post_title'     => $name,
			'post_status'    => 'inherit',
		),
		$upload['file']
	);
	if ( is_wp_error( $attachment ) || ! $attachment ) {
		return $empty;
	}
	require_once ABSPATH . 'wp-admin/includes/image.php';
	wp_update_attachment_metadata( $attachment, wp_generate_attachment_metadata( $attachment, $upload['file'] ) );
	update_post_meta( $attachment, '_wp_attachment_image_alt', $name );

	return array(
		'src'    => $upload['url'],
		'alt'    => $name,
		'width'  => (int) $info[0],
		'height' => (int) $info[1],
	);
}

function nami_alumni_receive( WP_REST_Request $request ) {
	$body = $request->get_json_params();
	$body = is_array( $body ) ? $body : array();
	$name = nami_alumni_text( $body, 'fullName', 200 );
	if ( '' === $name || ! function_exists( 'nami_cms_collections' ) ) {
		return new WP_Error( 'nami_alumni_bad_body', 'Invalid story.', array( 'status' => 400 ) );
	}
	$config = nami_cms_collections()['alumni-stories'] ?? null;
	if ( null === $config ) {
		return new WP_Error( 'nami_alumni_missing', 'The alumni list is not set up.', array( 'status' => 500 ) );
	}

	// The form's wing names → the website's wings.
	$wing_text = nami_alumni_text( $body, 'wing', 100 );
	$wing_map  = array(
		'Undergraduate Program' => 'undergraduate',
		'Graduate Program'      => 'graduate',
		'Cambridge A Levels'    => 'college',
		'Secondary School'      => 'higher-secondary',
		'School'                => 'higher-secondary',
	);
	$role      = nami_alumni_text( $body, 'currentRole' );
	$org       = nami_alumni_text( $body, 'currentOrg' );
	$headline  = nami_alumni_text( $body, 'storyHeadline' );
	$advice    = mb_substr( sanitize_textarea_field( (string) ( $body['advice'] ?? '' ) ), 0, 3000 );
	$story     = mb_substr( sanitize_textarea_field( (string) ( $body['experience'] ?? '' ) ), 0, 10000 );

	$GLOBALS['nami_cms_quiet'] = true; // A draft does not change the website.
	$post_id                   = wp_insert_post(
		array(
			'post_type'   => 'nami_alumni',
			'post_status' => 'draft',
			'post_title'  => $name,
		),
		true
	);
	$GLOBALS['nami_cms_quiet'] = false;
	if ( is_wp_error( $post_id ) ) {
		return new WP_Error( 'nami_alumni_store_failed', 'The story could not be stored.', array( 'status' => 500 ) );
	}

	$fields = nami_cms_collection_clean(
		$config,
		array(
			'wing'           => $wing_map[ $wing_text ] ?? 'undergraduate',
			'photo'          => nami_alumni_save_photo( $body['photo'] ?? null, $name ),
			'programme'      => nami_alumni_text( $body, 'program' ),
			'graduationYear' => nami_alumni_text( $body, 'graduationYear', 60 ),
			'currentRole'    => $role,
			'company'        => $org,
			'location'       => nami_alumni_text( $body, 'location' ),
			'highlights'     => $headline,
			'keyQuote'       => '',
			'story'          => $story,
			'milestones'     => array(),
			'interview'      => '' === $advice ? array() : array(
				array(
					'question' => 'What advice would you give to current and future students?',
					'answer'   => $advice,
				),
			),
			'skills'         => '',
		)
	);
	update_post_meta( $post_id, '_nami_fields', wp_slash( $fields ) );
	update_post_meta(
		$post_id,
		'_nami_submitter',
		wp_slash(
			array(
				'name'     => $name,
				'email'    => sanitize_email( (string) ( $body['email'] ?? '' ) ),
				'phone'    => nami_alumni_text( $body, 'phone', 60 ),
				'linkedin' => esc_url_raw( (string) ( $body['linkedin'] ?? '' ) ),
				'wing'     => $wing_text,
				'headline' => $headline,
				'received' => current_time( 'mysql' ),
			)
		)
	);

	nami_alumni_notify( $post_id );
	return rest_ensure_response( array( 'ok' => true ) );
}

function nami_alumni_notify( $post_id ) {
	$values = function_exists( 'nami_cms_get_values' ) ? nami_cms_get_values( 'alumni' ) : array();
	$to     = sanitize_email( (string) ( $values['connect']['email'] ?? '' ) );
	if ( ! is_email( $to ) ) {
		return;
	}
	$submitter = get_post_meta( $post_id, '_nami_submitter', true );
	$submitter = is_array( $submitter ) ? $submitter : array();
	$fields    = get_post_meta( $post_id, '_nami_fields', true );
	$fields    = is_array( $fields ) ? $fields : array();
	$headers   = array( 'Content-Type: text/html; charset=UTF-8' );
	if ( is_email( $submitter['email'] ?? '' ) ) {
		$headers[] = 'Reply-To: ' . str_replace( array( "\r", "\n" ), '', (string) $submitter['name'] ) . ' <' . $submitter['email'] . '>';
	}
	$answers = '';
	foreach ( (array) ( $fields['interview'] ?? array() ) as $entry ) {
		$answers .= '<p><strong>' . esc_html( $entry['question'] ?? '' ) . '</strong><br>' . nl2br( esc_html( $entry['answer'] ?? '' ) ) . '</p>';
	}
	$body = sprintf(
		'<div style="font-family:Arial,sans-serif;font-size:14px;color:#212529"><p>A graduate sent their story from the Alumni page. It is saved as a <strong>draft</strong>: edit it and press Publish to put it on the website.</p><p><strong>Name:</strong> %s<br><strong>Email:</strong> %s<br><strong>Phone:</strong> %s<br><strong>LinkedIn:</strong> %s<br><strong>Wing:</strong> %s<br><strong>Programme:</strong> %s (%s)<br><strong>Now:</strong> %s<br><strong>Location:</strong> %s</p><p><strong>Headline:</strong> %s</p><div style="white-space:pre-wrap;border-left:3px solid #bd1b21;padding:4px 12px">%s</div>%s<p><a href="%s">Open the draft in WordPress</a>%s</p></div>',
		esc_html( (string) ( $submitter['name'] ?? '' ) ),
		esc_html( (string) ( $submitter['email'] ?? '' ) ),
		esc_html( (string) ( $submitter['phone'] ?? '' ) ),
		esc_html( (string) ( $submitter['linkedin'] ?? '' ) ),
		esc_html( (string) ( $submitter['wing'] ?? '' ) ),
		esc_html( (string) ( $fields['programme'] ?? '' ) ),
		esc_html( (string) ( $fields['graduationYear'] ?? '' ) ),
		esc_html( trim( ( $fields['currentRole'] ?? '' ) . ', ' . ( $fields['company'] ?? '' ), ', ' ) ),
		esc_html( (string) ( $fields['location'] ?? '' ) ),
		esc_html( (string) ( $submitter['headline'] ?? '' ) ),
		esc_html( implode( "\n\n", (array) ( $fields['story'] ?? array() ) ) ),
		$answers,
		esc_url( admin_url( 'post.php?post=' . $post_id . '&action=edit' ) ),
		'' !== ( $fields['photo']['src'] ?? '' ) ? ' (their photo is attached to the draft)' : ''
	);
	wp_mail( $to, 'New alumni story: ' . (string) ( $submitter['name'] ?? '' ), $body, $headers );
}

// "Submitted by" box on stories that came from the form.
add_action(
	'add_meta_boxes_nami_alumni',
	function ( $post ) {
		$submitter = get_post_meta( $post->ID, '_nami_submitter', true );
		if ( ! is_array( $submitter ) || empty( $submitter['name'] ) ) {
			return;
		}
		add_meta_box(
			'nami_alumni_submitter',
			'Submitted by',
			function () use ( $submitter ) {
				$email = (string) ( $submitter['email'] ?? '' );
				printf(
					'<p><strong>%s</strong><br>%s<br>%s<br>%s</p><p class="description">Sent %s through "Share Your Story". Only staff see this box. They agreed to their story being shared.</p>',
					esc_html( (string) $submitter['name'] ),
					'' !== $email ? '<a href="mailto:' . esc_attr( $email ) . '">' . esc_html( $email ) . '</a>' : '',
					esc_html( (string) ( $submitter['phone'] ?? '' ) ),
					'' !== ( $submitter['linkedin'] ?? '' ) ? '<a href="' . esc_url( $submitter['linkedin'] ) . '" target="_blank" rel="noopener">LinkedIn ↗</a>' : '',
					esc_html( (string) ( $submitter['received'] ?? '' ) )
				);
			},
			'nami_alumni',
			'side',
			'high'
		);
	}
);

// Red bubble on the Alumni menu with the number of stories waiting for review.
add_action(
	'admin_menu',
	function () {
		global $menu;
		if ( ! current_user_can( 'edit_pages' ) || ! is_array( $menu ) ) {
			return;
		}
		$waiting = new WP_Query(
			array(
				'post_type'      => 'nami_alumni',
				'post_status'    => 'draft',
				'meta_key'       => '_nami_submitter',
				'fields'         => 'ids',
				'posts_per_page' => 1,
			)
		);
		if ( $waiting->found_posts < 1 ) {
			return;
		}
		foreach ( $menu as $index => $item ) {
			if ( 'edit.php?post_type=nami_alumni' === ( $item[2] ?? '' ) ) {
				$menu[ $index ][0] .= sprintf( ' <span class="awaiting-mod"><span class="pending-count">%d</span></span>', (int) $waiting->found_posts );
			}
		}
	},
	99
);
