<?php
/**
 * NAMI CMS — Student Life page
 *
 * Requires the "NAMI CMS — Core engine" snippet. Adds a "Student Life" menu
 * with one sub-menu per section of the /student-life page.
 *
 * Field keys must match src/lib/cms/pages/student-life/types.ts in the Next.js project.
 * The defaults block at the bottom is generated by `npm run cms:defaults`.
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

add_filter(
	'nami_cms_pages',
	function ( $pages ) {
		$pages['student-life'] = array(
			'title'      => 'Student Life',
			'menu_title' => 'Student Life',
			'icon'       => 'dashicons-groups',
			'position'   => 3.95,
			'path'       => '/student-life',
			'sections'   => array(
				'masthead' => array(
					'title'       => 'Heading',
					'description' => 'The top of the Student Life page.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 2 ),
					),
				),
				'pillars'  => array(
					'title'       => 'Sections',
					'description' => 'The numbered sections of the page (01, 02 …), in order. Use ↑ ↓ to reorder.',
					'fields'      => array(
						'items' => array(
							'type'        => 'repeater',
							'label'       => 'Sections',
							'item_label'  => 'Section',
							'title_field' => 'title',
							'fields'      => array(
								'title'      => array( 'type' => 'text', 'label' => 'Title' ),
								'lead'       => array( 'type' => 'textarea', 'label' => 'Intro (large text under the title)', 'rows' => 2 ),
								'paragraphs' => array( 'type' => 'paragraphs', 'label' => 'Text', 'rows' => 8 ),
								'highlights' => array( 'type' => 'lines', 'label' => 'Highlights', 'rows' => 6, 'help' => 'One per line. Shown as a list beside the text.' ),
								'image'      => array( 'type' => 'image', 'label' => 'Wide photo (optional)', 'help' => 'Shown across the full width under the section.' ),
							),
						),
					),
				),
				'seo'      => array(
					'title'       => 'Search & Sharing',
					'description' => 'How the Student Life page appears in Google results and when shared on social media.',
					'fields'      => array(
						'title'       => array( 'type' => 'text', 'label' => 'Page title' ),
						'description' => array( 'type' => 'textarea', 'label' => 'Description', 'rows' => 3, 'help' => 'About 150 characters.' ),
					),
				),
			),
			'defaults'   => json_decode(
				<<<'NAMI_JSON'
{
  "seo": {
    "title": "Student Life at NAMI",
    "description": "Discover the vibrant student life, sustainability initiatives, and community at NAMI."
  },
  "masthead": {
    "title": "Student Life",
    "description": "Beyond the classroom. A college that fosters innovation, leadership, and sustainability."
  },
  "pillars": {
    "items": [
      {
        "title": "Naaya Aayam Avinaya Prerana Kendra",
        "lead": "The innovation and incubation centre, built with Startup Discovery Asia.",
        "paragraphs": [
          "NAMI's Innovation and Incubation Centre is designed to transform ideas into impactful ventures. Established in collaboration with Startup Discovery Asia (SDA), a leading startup ecosystem enabler in South Asia, it gives aspiring entrepreneurs access to mentorship, networking, business development support and industry expertise.",
          "Whether the idea is a technology startup, a social enterprise, research-based innovation, a creative venture or a sustainable business, students get the guidance and resources to refine, test and scale it."
        ],
        "highlights": [
          "Entrepreneurial training and capacity-building workshops",
          "Mentorship from entrepreneurs, academics and industry experts",
          "Startup ideation, business model development and validation",
          "Networking events, innovation challenges and startup competitions",
          "Support for prototype development, market research and venture growth",
          "A collaborative workspace for creativity and teamwork"
        ],
        "image": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        }
      },
      {
        "title": "Service Learning",
        "lead": "Students design, launch and finish their own community projects.",
        "paragraphs": [
          "The goal of Service Learning at NAMI International School is to help each student find their own way to make a positive impact, instilling a love of service that lasts a lifetime.",
          "Students learn coordination, leadership and effective communication, run their initiatives under adult supervision, and document their progress through reflective essays, diaries and journals."
        ],
        "highlights": [
          "Student-led initiatives from design to delivery",
          "Coordination, leadership and communication skills",
          "Reflective essays, diaries and project journals"
        ],
        "image": {
          "src": "/sections/nami/campus-service-camp.jpg",
          "alt": "Pupils in red uniforms seated around a hilltop school ground in Sindhupalchowk, facing stacks of red relief bags laid out on benches at a NAMI service camp.",
          "width": 1190,
          "height": 793
        }
      },
      {
        "title": "Leadership & Career Counselling",
        "lead": "Structured career guidance, mentorship and leadership development.",
        "paragraphs": [
          "NAMI treats career counselling and leadership development as core student support: structured career guidance, skills assessment, mentorship and exposure to diverse academic and professional pathways, alongside training, workshops and experiential learning.",
          "A monthly motivational series, \"Motivational Stories by Inspirational Leaders of Change\", brings successful figures from different fields to students from secondary to Master's level. The NAMI Golden Z Club Orientation Programme develops leadership through global leadership values and women's empowerment initiatives, in interaction with experienced Zontians."
        ],
        "highlights": [
          "Skills assessment and one-to-one mentorship",
          "\"Motivational Stories by Inspirational Leaders of Change\"",
          "NAMI Golden Z Club"
        ],
        "image": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        }
      },
      {
        "title": "Industry Exposure",
        "lead": "Internships, mentorship, placements and collaborative research.",
        "paragraphs": [
          "NAMI has established partnerships with leading industry players across banking, technology, media, hospitality and capital markets. These collaborations give students internships, mentorship, job placements and collaborative research, closing the gap between academic learning and industry expectations."
        ],
        "highlights": [
          "Internships and job placements with partner organisations",
          "Mentorship from working professionals",
          "Collaborative research projects"
        ],
        "image": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        }
      },
      {
        "title": "Sustainability",
        "lead": "Our 5-year sustainability roadmap towards a green, zero-waste, and plastic-free campus aligned with the UN Sustainable Development Goals.",
        "paragraphs": [
          "Sustainability is a core institutional priority at NAMI. Under our 5-year sustainability roadmap, we are actively transforming our operations, academic framework, and campus infrastructure towards renewable energy, resource efficiency, structured waste segregation and recycling, reduced paper reliance, sustainable mobility, and transitioning to a fully plastic-free zone.",
          "These initiatives are aligned with the United Nations Sustainable Development Goals—particularly climate action, responsible consumption and production, and quality education—and are carried into teaching through interdisciplinary curricula, student-led green initiatives, applied research, and community engagement."
        ],
        "highlights": [
          "5-year strategic roadmap towards a fully plastic-free campus",
          "Structured waste segregation, recycling, and resource management",
          "Curriculum, applied research, and community action on environmental challenges"
        ],
        "image": {
          "src": "",
          "alt": "",
          "width": 0,
          "height": 0
        }
      }
    ]
  }
}
NAMI_JSON
				,
				true
			),
		);
		return $pages;
	}
);
